// ==========================================
// DATA SOALAN PENDIDIKAN MUZIK (4 Kategori Pertama)
// ==========================================
const pendidikanMuzikData = {
    "notasi_dan_balar": [
        {"q": "Lima garisan lurus dan empat ruang yang digunakan untuk menulis nota muzik dipanggil ___?", "a": "balar"},
        {"q": "Simbol muzik yang diletakkan pada awal balar untuk menentukan pic nota dipanggil ___?", "a": "klef trebel"},
        {"q": "Apakah nama lain bagi klef trebel?", "a": "klef g"},
        {"q": "Garisan menegak yang membahagikan balar kepada beberapa bahagian dipanggil garisan ___?", "a": "bar"},
        {"q": "Kawasan di antara dua garisan bar dipanggil ___?", "a": "bar"},
        {"q": "Dua garisan bar menegak di penghujung balar menandakan ___ lagu?", "a": "tamat"},
        {"q": "Nota yang ditulis pada garisan pertama balar dari bawah ialah nota ___?", "a": "e"},
        {"q": "Nota yang ditulis pada garisan kedua balar dari bawah ialah nota ___?", "a": "g"},
        {"q": "Nota yang ditulis pada garisan ketiga balar dari bawah ialah nota ___?", "a": "b"},
        {"q": "Nota yang ditulis pada garisan keempat balar dari bawah ialah nota ___?", "a": "d"},
        {"q": "Nota yang ditulis pada garisan kelima balar dari bawah ialah nota ___?", "a": "f"},
        {"q": "Nota yang berada di ruang pertama balar dari bawah ialah nota ___?", "a": "f"},
        {"q": "Nota yang berada di ruang kedua balar dari bawah ialah nota ___?", "a": "a"},
        {"q": "Nota yang berada di ruang ketiga balar dari bawah ialah nota ___?", "a": "c"},
        {"q": "Nota yang berada di ruang keempat balar dari bawah ialah nota ___?", "a": "e"},
        {"q": "Sebutkan perkataan bahasa Inggeris yang dibentuk oleh empat nota di dalam ruang balar?", "a": "face"},
        {"q": "Garisan pendek tambahan yang ditulis di bawah atau di atas balar dipanggil garisan ___?", "a": "bantu"},
        {"q": "Nota C tengah biasanya ditulis pada garisan ___?", "a": "bantu"},
        {"q": "Klef trebel mula dilukis dari garisan keberapa pada balar?", "a": "dua"},
        {"q": "Adakah kedudukan nota di atas balar menentukan tinggi atau rendah bunyi pic?", "a": "ya"},
        {"q": "Semakin tinggi kedudukan nota pada balar, semakin ___ pic tersebut.", "a": "tinggi"},
        {"q": "Semakin rendah kedudukan nota pada balar, semakin ___ pic tersebut.", "a": "rendah"},
        {"q": "Bahagian bulat pada nota muzik dipanggil ___ nota.", "a": "kepala"},
        {"q": "Tangkai pada nota muzik ditulis menghala ke atas jika nota berada di ___ garisan ketiga.", "a": "bawah"},
        {"q": "Tangkai pada nota muzik ditulis menghala ke bawah jika nota berada di ___ garisan ketiga.", "a": "atas"},
        {"q": "Adakah garisan bar berkembar digunakan untuk memisahkan bahagian lagu yang berbeza?", "a": "ya"},
        {"q": "Abjad pertama yang digunakan dalam menamakan nota muzik ialah ___?", "a": "a"},
        {"q": "Abjad terakhir yang digunakan dalam sistem nama nota muzik ialah ___?", "a": "g"},
        {"q": "Selepas nota G, abjad nama nota akan kembali semula kepada nota ___?", "a": "a"},
        {"q": "Berapakah jumlah garisan yang ada pada satu balar?", "a": "lima"},
        {"q": "Berapakah jumlah ruang yang ada pada satu balar?", "a": "empat"},
        {"q": "Sistem penulisan muzik menggunakan simbol dan tanda dipanggil ___ muzik.", "a": "notasi"},
        {"q": "Nota yang terletak betul-betul di bawah garisan pertama balar (tanpa garisan bantu) ialah nota ___?", "a": "d"},
        {"q": "Nota yang terletak betul-betul di atas garisan kelima balar ialah nota ___?", "a": "g"},
        {"q": "Adakah klef trebel penting untuk instrumen berpic tinggi seperti rekorder?", "a": "ya"},
        {"q": "Pengiraan garisan dan ruang pada balar mestilah bermula dari ___ ke atas.", "a": "bawah"},
        {"q": "Simbol klef trebel menyerupai bentuk huruf ___ yang diubah suai.", "a": "g"},
        {"q": "Garisan yang merentasi tengah-tengah kepala nota dipanggil nota pada ___?", "a": "garisan"},
        {"q": "Kepala nota yang berada di antara dua garisan dipanggil nota pada ___?", "a": "ruang"},
        {"q": "Jika nota F berada di ruang pertama, apakah nota yang berada di garisan kedua?", "a": "g"},
        {"q": "Jika nota B berada di garisan ketiga, apakah nota yang berada di ruang ketiga?", "a": "c"},
        {"q": "Sistem tujuh bunyi pic dalam muzik dipanggil tangga ___?", "a": "nada"},
        {"q": "Garisan penutup lagu terdiri daripada satu garisan nipis dan satu garisan ___?", "a": "tebal"},
        {"q": "Adakah kita boleh melukis klef trebel di tengah-tengah bar tanpa sebab?", "a": "tidak"},
        {"q": "Klef g merujuk kepada kedudukan pusat pusaran klef itu pada garisan ___?", "a": "dua"},
        {"q": "Jarak pic antara satu nota dengan nota yang sama di tingkat atas dipanggil satu ___?", "a": "oktaf"},
        {"q": "Notasi muzik ditulis dari arah ___ ke kanan.", "a": "kiri"},
        {"q": "Garisan tegak yang memotong balar dinamakan garisan ___?", "a": "bar"},
        {"q": "Nota A terletak pada ruang keberapa dalam balar?", "a": "dua"},
        {"q": "Adakah garisan bantu digunakan untuk nota yang terlalu tinggi atau terlalu rendah?", "a": "ya"}
    ],

    "klef_trebel": [
        {"q": "Simbol utama yang diletakkan pada awal setiap balar untuk menunjukkan pic tinggi dipanggil ___?", "a": "klef trebel"},
        {"q": "Apakah nama lain bagi klef trebel?", "a": "klef g"},
        {"q": "Mengapakah klef trebel dipanggil klef G?", "a": "kerana bermula di garisan g"},
        {"q": "Klef trebel digunakan untuk menulis nota bagi instrumen berpic ___?", "a": "tinggi"},
        {"q": "Berikan satu contoh alat tiup di sekolah yang menggunakan skor klef trebel?", "a": "rekorder"},
        {"q": "Adakah instrumen pianika membaca notasi dalam klef trebel?", "a": "ya"},
        {"q": "Pusaran bulatan dalam klef trebel mestilah menyentuh garisan keberapa dari bawah?", "a": "dua"},
        {"q": "Nota muzik yang terletak pada garisan kedua balar dalam klef trebel ialah nota ___?", "a": "g"},
        {"q": "Nota apakah yang terletak di ruang pertama balar?", "a": "f"},
        {"q": "Nota apakah yang terletak di garisan pertama balar?", "a": "e"},
        {"q": "Nota apakah yang terletak di ruang kedua balar?", "a": "a"},
        {"q": "Nota apakah yang terletak di garisan ketiga balar?", "a": "b"},
        {"q": "Nota apakah yang terletak di ruang ketiga balar?", "a": "c"},
        {"q": "Nota apakah yang terletak di garisan keempat balar?", "a": "d"},
        {"q": "Nota apakah yang terletak di ruang keempat balar?", "a": "e"},
        {"q": "Nota apakah yang terletak di garisan kelima balar?", "a": "f"},
        {"q": "Untuk menghafal nota pada ruang balar klef trebel, kita boleh mengingat perkataan ___?", "a": "face"},
        {"q": "Gabungan nota pada garisan balar dari bawah ke atas ialah E, G, B, D, dan ___?", "a": "f"},
        {"q": "Nota C tengah ditulis pada satu garisan pendek di bawah balar yang dipanggil garisan ___?", "a": "bantu"},
        {"q": "Nota yang terletak melekat di bawah garisan pertama balar (tanpa garisan bantu) ialah nota ___?", "a": "d"},
        {"q": "Nota yang terletak melekat di atas garisan kelima balar ialah nota ___?", "a": "g"},
        {"q": "Antara nota E (garisan 1) dan nota F (ruang 1), manakah yang mempunyai pic lebih tinggi?", "a": "f"},
        {"q": "Antara nota B (garisan 3) dan nota A (ruang 2), manakah yang mempunyai pic lebih rendah?", "a": "a"},
        {"q": "Apakah nota yang berada satu langkah di atas nota G (garisan 2)?", "a": "a"},
        {"q": "Apakah nota yang berada satu langkah di bawah nota G (garisan 2)?", "a": "f"},
        {"q": "Apakah nama nota yang berada di ruang ketiga balar?", "a": "c"},
        {"q": "Apakah nama nota yang berada di garisan keempat balar?", "a": "d"},
        {"q": "Adakah suara nyanyian kanak-kanak biasanya ditulis menggunakan skor klef trebel?", "a": "ya"},
        {"q": "Simbol klef trebel ditulis di sebelah ___ petunjuk meter masa.", "a": "kiri"},
        {"q": "Jika kepala nota ditulis lebih tinggi pada balar klef trebel, bunyinya akan menjadi lebih ___?", "a": "tinggi"},
        {"q": "Jika kepala nota ditulis lebih rendah pada balar klef trebel, bunyinya akan menjadi lebih ___?", "a": "rendah"},
        {"q": "Apakah nota sebelum nota C tengah jika kita bergerak ke bawah?", "a": "b"},
        {"q": "Garisan bantu digunakan apabila pic sesuatu nota berada di ___ had balar biasa.", "a": "luar"},
        {"q": "Rekorder soprano menggunakan sistem notasi klef ___?", "a": "trebel"},
        {"q": "Apakah nama abjad muzik selepas nota G?", "a": "a"},
        {"q": "Berapakah jumlah abjad yang digunakan dalam penamaan nota klef trebel?", "a": "tujuh"},
        {"q": "Abjad penamaan nota muzik bermula dari A hingga ___?", "a": "g"},
        {"q": "Jika anda meniup rekorder dengan menutup semua lubang, anda menghasilkan nota C ___?", "a": "tengah"},
        {"q": "Nota E berada di ruang keempat balar, manakala nota E yang satu lagi berada di garisan ___?", "a": "pertama"},
        {"q": "Nota F berada di garisan kelima balar, manakala nota F yang satu lagi berada di ruang ___?", "a": "pertama"},
        {"q": "Adakah klef trebel digunakan untuk alat muzik berpic sangat rendah seperti tuba atau gitar bes?", "a": "tidak"},
        {"q": "Alat muzik piano dimainkan dengan tangan kanan biasanya membaca nota dalam klef ___?", "a": "trebel"},
        {"q": "Apakah nota yang terletak di antara nota A (ruang 2) dan nota C (ruang 3)?", "a": "b"},
        {"q": "Apakah nota yang terletak di antara nota F (ruang 1) dan nota A (ruang 2)?", "a": "g"},
        {"q": "Di dalam klef trebel, nota C tengah mempunyai pic yang lebih ___ daripada nota C di ruang ketiga.", "a": "rendah"},
        {"q": "Di dalam klef trebel, nota D di garisan keempat mempunyai pic yang lebih ___ daripada nota D di bawah balar.", "a": "tinggi"},
        {"q": "Setiap garisan dan ruang pada balar klef trebel mewakili satu pic ___ yang tertentu.", "a": "nada"},
        {"q": "Bila melukis klef trebel, garisan menegak paling atas akan membentuk seolah-olah sebuah ___ kecil di puncaknya.", "a": "gelung"},
        {"q": "Adakah klef trebel wajib diletakkan pada permulaan setiap baris baru dalam skor muzik?", "a": "ya"},
        {"q": "Kedudukan pusat pusaran bawah klef trebel menentukan nama garisan tersebut sebagai garisan ___?", "a": "g"}
    ],

    "jenis_alat_muzik": [
        {"q": "Alat muzik yang dimainkan dengan cara memukul, mengetuk atau menggoncang dipanggil alat ___?", "a": "perkusi"},
        {"q": "Alat muzik yang dimainkan dengan cara meniup angin ke dalamnya dipanggil alat ___?", "a": "tiup"},
        {"q": "Alat muzik yang mempunyai tali dan dimainkan secara memetik atau menggesek dipanggil alat ___?", "a": "bertali"},
        {"q": "Kastenet, tamborin, dan loceng dikategorikan di bawah kumpulan alat ___?", "a": "perkusi"},
        {"q": "Rekorder dan pianika merupakan contoh alat muzik jenis ___?", "a": "tiup"},
        {"q": "Gitar, biola, dan ukulele dikategorikan di bawah kumpulan alat ___?", "a": "bertali"},
        {"q": "Alat perkusi terbahagi kepada dua jenis, iaitu perkusi berpic dan perkusi ___?", "a": "tidak berpic"},
        {"q": "Antara kastenet dan xilofon, manakah contoh alat perkusi berpic?", "a": "xilofon"},
        {"q": "Antara tamborin dan segi tiga, adakah kedua-duanya termasuk dalam perkusi tidak berpic?", "a": "ya"},
        {"q": "Alat perkusi yang boleh menghasilkan melodi atau pic Do-Re-Mi dipanggil perkusi ___?", "a": "berpic"},
        {"q": "Alat perkusi yang hanya menghasilkan satu bunyi atau rentak tanpa pic dipanggil perkusi ___?", "a": "tidak berpic"},
        {"q": "Bagaimanakah cara yang betul untuk memainkan alat kastenet?", "a": "ketuk atau pukul"},
        {"q": "Bagaimanakah cara yang betul untuk memainkan alat marakas?", "a": "goncang"},
        {"q": "Alat perkusi berbentuk tiga segi besi yang diketuk dengan pemukul besi dipanggil ___?", "a": "segi tiga"},
        {"q": "Alat muzik perkusi tradisional Melayu yang sering digunakan untuk mengiringi perarakan pengantin dipanggil ___?", "a": "kompang"},
        {"q": "Alat muzik tradisional Sarawak yang berbentuk seperti perahu dan mempunyai tali dipanggil ___?", "a": "sape"},
        {"q": "Alat muzik tiup yang diperbuat daripada plastik atau kayu dan dipelajari dalam subjek Muzik sekolah rendah ialah ___?", "a": "rekorder"},
        {"q": "Alat muzik tiup yang mempunyai papan kekunci seperti piano kecil dipanggil ___?", "a": "pianika"},
        {"q": "Bagaimanakah cara membunyikan alat muzik biola?", "a": "gesek"},
        {"q": "Bagaimanakah cara membunyikan alat muzik gitar atau ukulele?", "a": "petik"},
        {"q": "Alat muzik perkusi tradisional yang diperbuat daripada buluh dan berasal dari Indonesia dipanggil ___?", "a": "angklung"},
        {"q": "Adakah kompang merupakan jenis alat perkusi tidak berpic?", "a": "ya"},
        {"q": "Alat perkusi berpic yang mempunyai kepingan logam berpic tinggi dan diketuk dengan pemukul dipanggil ___?", "a": "metalofon"},
        {"q": "Alat perkusi berpic yang mempunyai kepingan kayu disusun mengikut saiz pic dipanggil ___?", "a": "xilofon"},
        {"q": "Alat muzik tiup tradisional masyarakat Orang Asli yang ditiup menggunakan hidung dipanggil seruling ___?", "a": "hidung"},
        {"q": "Alat muzik bertali terbesar yang dimainkan secara menggesek sambil duduk ialah ___?", "a": "selo"},
        {"q": "Alat muzik bertali tradisional yang popular dalam muzik Ghazal di Johor ialah ___?", "a": "gambus"},
        {"q": "Adakah alat muzik dram samping (snare drum) termasuk dalam kumpulan perkusi berpic?", "a": "tidak"},
        {"q": "Alat tiup barat yang diperbuat daripada gangsa atau loyang dan mempunyai tiga injap butang dipanggil ___?", "a": "trompet"},
        {"q": "Gendang mempunyai permukaan kulit yang menghasilkan bunyi apabila ___?", "a": "dipukul"},
        {"q": "Bagaimanakah cara membunyikan alat tiup harmonika?", "a": "tiup dan hisap"},
        {"q": "Alat perkusi kecil berbentuk bulat berkembar yang diletakkan pada jari dan diketuk ialah ___?", "a": "kastenet"},
        {"q": "Alat perkusi berupa gelung bertaring loceng kecil yang boleh dipukul atau digoncang ialah ___?", "a": "tamborin"},
        {"q": "Alat muzik tiup yang sangat besar, panjang, berpusing-pusing dan biasa dimainkan dalam pancaragam sekolah ialah ___?", "a": "tuba"},
        {"q": "Adakah piano dikategorikan sebagai alat muzik papan kekunci yang juga mempunyai tali di dalamnya?", "a": "ya"},
        {"q": "Apakah alat tiup kayu yang mempunyai lubang jari dan sering dimainkan secara melintang?", "a": "seruling"},
        {"q": "Alat perkusi tradisional Kelantan yang berbentuk seperti pasu besar dan dimainkan secara berpasangan dipanggil gendang ___?", "a": "rebana"},
        {"q": "Kumpulan alat muzik tiup yang diperbuat daripada logam loyang seperti trompet dan tuba dikenali sebagai alat tiup ___?", "a": "bas"},
        {"q": "Alat muzik bertali yang mempunyai empat tali besi, badannya lebih kecil daripada gitar dan popular di Hawaii ialah ___?", "a": "ukulele"},
        {"q": "Alat muzik tiup barat yang menggunakan satu kepingan reed pada pemipitnya dan berbentuk melengkung ialah ___?", "a": "saksofon"},
        {"q": "Adakah simbal menghasilkan bunyi berpic atau tidak berpic?", "a": "tidak berpic"},
        {"q": "Alat perkusi berbentuk silinder besar yang memberikan bunyi dentuman rendah yang dalam ialah dram ___?", "a": "besar"},
        {"q": "Apakah nama sepasang dram kecil tradisional dalam muzik mak yong yang dipukul menggunakan tangan?", "a": "gendang"},
        {"q": "Bagaimanakah cara memainkan alat gong tradisional?", "a": "ketuk dengan pemukul"},
        {"q": "Alat muzik bertali klasik Cina yang dipetik dan diletakkan secara melintang di atas meja dipanggil ___?", "a": "guzheng"},
        {"q": "Alat muzik bertali tradisional India yang mempunyai leher panjang dan banyak tali getaran dipanggil ___?", "a": "sitar"},
        {"q": "Adakah serunai sejenis alat muzik tiup tradisional yang digunakan dalam persembahan wayang kulit?", "a": "ya"},
        {"q": "Apakah bahan utama yang digunakan untuk membuat bilah alat muzik xilofon?", "a": "kayu"},
        {"q": "Apakah bahan utama yang digunakan untuk membuat bilah alat muzik metalofon?", "a": "logam"},
        {"q": "Menjaga kebersihan alat tiup seperti rekorder selepas digunakan adalah amalan yang sangat ___?", "a": "baik"}
    ],

"nilai_nota_ritma": [
        {"q": "Nota semibreif mempunyai nilai sebanyak ___ ketukan?", "a": "empat"},
        {"q": "Nota minim mempunyai nilai sebanyak ___ ketukan?", "a": "dua"},
        {"q": "Nota krocet mempunyai nilai sebanyak ___ ketukan?", "a": "satu"},
        {"q": "Nota kuaver mempunyai nilai sebanyak ___ ketukan?", "a": "setengah"},
        {"q": "Simbol bulatan bujur kosong tanpa tangkai ialah nota ___?", "a": "semibreif"},
        {"q": "Nota yang mempunyai kepala putih berserta tangkai dipanggil ___?", "a": "minim"},
        {"q": "Nota yang mempunyai kepala hitam berserta tangkai dipanggil ___?", "a": "krocet"},
        {"q": "Nota yang mempunyai kepala hitam, tangkai, dan satu bendera dipanggil ___?", "a": "kuaver"},
        {"q": "Apakah nama simbol yang digunakan untuk menandakan zon senyap dalam muzik?", "a": "tanda rehat"},
        {"q": "Tanda rehat yang berbentuk seperti topi terbalik di bawah garisan keempat bernilai empat ketukan ialah tanda rehat ___?", "a": "semibreif"},
        {"q": "Tanda rehat yang berbentuk seperti topi tegak di atas garisan ketiga bernilai dua ketukan ialah tanda rehat ___?", "a": "minim"},
        {"q": "Tanda rehat yang kelihatan seperti kilat bersambung bernilai satu ketukan ialah tanda rehat ___?", "a": "krocet"},
        {"q": "Tanda rehat yang mempunyai satu bendera kecil bernilai setengah ketukan ialah tanda rehat ___?", "a": "kuaver"},
        {"q": "Dua nota kuaver yang digabungkan tangkainya menggunakan garisan penghubung bernilai ___ ketukan?", "a": "satu"},
        {"q": "Meter 2/4 menunjukkan terdapat ___ ketukan dalam satu bar?", "a": "dua"},
        {"q": "Meter 3/4 menunjukkan terdapat ___ ketukan dalam satu bar?", "a": "tiga"},
        {"q": "Meter 4/4 menunjukkan terdapat ___ ketukan dalam satu bar?", "a": "empat"},
        {"q": "Nombor yang berada di sebelah atas dalam petunjuk meter menunjukkan ___ ketukan dalam satu bar.", "a": "bilangan"},
        {"q": "Nombor 4 di sebelah bawah dalam petunjuk meter menunjukkan jenis nota ___ bernilai satu ketukan.", "a": "krocet"},
        {"q": "Gabungan satu nota krocet dan satu nota krocet menghasilkan jumlah ___ ketukan?", "a": "dua"},
        {"q": "Gabungan satu nota minim dan satu nota krocet menghasilkan jumlah ___ ketukan?", "a": "tiga"},
        {"q": "Gabungan dua nota minim menghasilkan jumlah ___ ketukan?", "a": "empat"},
        {"q": "Empat nota krocet yang dihimpunkan dalam satu bar meter 4/4 memberikan jumlah ___ ketukan?", "a": "empat"},
        {"q": "Berapakah bilangan nota krocet yang diperlukan untuk menyamai nilai satu nota semibreif?", "a": "empat"},
        {"q": "Berapakah bilangan nota minim yang diperlukan untuk menyamai nilai satu nota semibreif?", "a": "dua"},
        {"q": "Berapakah bilangan nota kuaver yang diperlukan untuk menyamai nilai satu nota krocet?", "a": "dua"},
        {"q": "Berapakah bilangan nota kuaver yang diperlukan untuk menyamai nilai satu nota minim?", "a": "empat"},
        {"q": "Jika satu bar meter 2/4 mengandungi satu nota krocet, berapakah bilangan nota kuaver lagi yang diperlukan untuk memenuhkan bar tersebut?", "a": "dua"},
        {"q": "Adakah nilai tanda rehat krocet sama panjang dengan nilai nota krocet?", "a": "ya"},
        {"q": "Adakah nilai tanda rehat minim sama panjang dengan nilai nota minim?", "a": "ya"},
        {"q": "Simbol titik di sebelah nota muzik berfungsi menambah ___ daripada nilai asal nota tersebut.", "a": "separuh"},
        {"q": "Nota krocet bertitik (dotted crotchet) mempunyai nilai sebanyak 1 dan ___ ketukan?", "a": "setengah"},
        {"q": "Nota minim bertitik (dotted minim) mempunyai nilai sebanyak ___ ketukan?", "a": "tiga"},
        {"q": "Corak tiupan atau ketukan yang berulang-ulang mengikut pusingan meter dipanggil ___ ritma?", "a": "corak"},
        {"q": "Alat perkusi tidak berpic biasanya digunakan untuk mengekalkan ___ semasa menyanyi.", "a": "tempo"},
        {"q": "Kelajuan sesuatu pusingan atau ketukan muzik dipanggil ___?", "a": "tempo"},
        {"q": "Jika tempo lagu bertukar menjadi cepat, adakah nilai ketukan nota krocet mengecil menjadi setengah ketukan?", "a": "tidak"},
        {"q": "Sebutkan sebutan kodaly bagi nota krocet?", "a": "ta"},
        {"q": "Sebutkan sebutan kodaly bagi nota minim?", "a": "ta-ah"},
        {"q": "Sebutkan sebutan kodaly bagi sepasang nota kuaver berkembar?", "a": "ti-ti"},
        {"q": "Sebutkan sebutan kodaly bagi nota semibreif?", "a": "ta-ah-ah-ah"},
        {"q": "Sebutan kodaly 'sa' biasanya merujuk kepada tanda rehat bagi nota ___?", "a": "krocet"},
        {"q": "Garisan melengkung yang menghubungkan dua nota berpic sama untuk mencantumkan nilainya dipanggil garisan ___?", "a": "ikat"},
        {"q": "Adakah nota yang diikat dengan garisan pengikat perlu ditiup atau diketuk dua kali?", "a": "tidak"},
        {"q": "Petunjuk meter masa diletakkan di dalam balar selepas simbol ___?", "a": "klef trebel"},
        {"q": "Tanda bar berkembar yang mempunyai dua titik bertindih di tengahnya dinamakan tanda ___?", "a": "ulangan"},
        {"q": "Apabila menemui tanda ulangan (repeat sign), pemain muzik mestilah memainkan semula bahagian tersebut dari ___?", "a": "awal"},
        {"q": "Ketukan pertama dalam setiap bar meter biasanya mempunyai penekanan atau ___ yang lebih kuat.", "a": "aksen"},
        {"q": "Adakah tanda rehat semibreif digantung di bawah garisan keempat balar?", "a": "ya"},
        {"q": "Adakah tanda rehat minim didudukkan di atas garisan ketiga balar?", "a": "ya"}
    ],

    "solfa_dan_nyanyian": [
        {"q": "Sistem isyarat tangan yang digunakan untuk mewakili pic suara Do-Re-Mi dipanggil isyarat tangan ___?", "a": "curwen"},
        {"q": "Pic solfa yang paling rendah dalam susunan oktaf asas muzik sekolah rendah ialah ___?", "a": "do"},
        {"q": "Pic solfa yang berada satu anak tangga di atas pic Do ialah ___?", "a": "re"},
        {"q": "Pic solfa yang berada satu anak tangga di atas pic Re ialah ___?", "a": "mi"},
        {"q": "Pic solfa yang berada satu anak tangga di atas pic Mi ialah ___?", "a": "fa"},
        {"q": "Pic solfa yang berada satu anak tangga di atas pic Fa ialah ___?", "a": "so"},
        {"q": "Pic solfa yang berada satu anak tangga di atas pic So ialah ___?", "a": "la"},
        {"q": "Pic solfa yang berada satu anak tangga di atas pic La ialah ___?", "a": "ti"},
        {"q": "Susunan pic solfa dari rendah ke tinggi (Do ke Do atas) dinamakan susunan ___?", "a": "menaik"},
        {"q": "Susunan pic solfa dari tinggi ke rendah (Do atas ke Do bawah) dinamakan susunan ___?", "a": "menurun"},
        {"q": "Isyarat tangan Curwen untuk pic Do berbentuk tangan ___?", "a": "genggam"},
        {"q": "Isyarat tangan Curwen untuk pic Re berbentuk tangan condong menghala ke ___?", "a": "atas"},
        {"q": "Isyarat tangan Curwen untuk pic Mi berbentuk tangan mendatar dengan tapak tangan menghala ke ___?", "a": "bawah"},
        {"q": "Isyarat tangan Curwen untuk pic Fa berbentuk tangan genggam dengan ibu jari menghala ke ___?", "a": "bawah"},
        {"q": "Isyarat tangan Curwen untuk pic So berbentuk tapak tangan mendatar menghala ke ___?", "a": "dada"},
        {"q": "Isyarat tangan Curwen untuk pic La berbentuk pergelangan tangan yang terkulai lemah ke ___?", "a": "bawah"},
        {"q": "Isyarat tangan Curwen untuk pic Ti berbentuk jari telunjuk menunjuk condong ke ___?", "a": "atas"},
        {"q": "Proses menyanyikan pic menggunakan suku kata Do, Re, Mi dipanggil latihan ___?", "a": "solfa"},
        {"q": "Sebelum memulakan aktiviti nyanyian, kita perlu melakukan latihan ___ suara.", "a": "pemanasan"},
        {"q": "Postur menyanyi yang betul semasa berdiri memerlukan dada tegak dan kaki dibuka seluas ___?", "a": "bahu"},
        {"q": "Semasa menyanyi, kita hendaklah mengambil nafas menggunakan ruang ___ untuk menyimpan lebih banyak udara.", "a": "diafragma"},
        {"q": "Adakah kita dibenarkan mengangkat bahu ke atas semasa menarik nafas untuk menyanyi?", "a": "tidak"},
        {"q": "Keupayaan menyanyikan sesuatu nota atau lagu dengan pic yang tepat dan tidak sumbang dipanggil ___?", "a": "intonasi"},
        {"q": "Penyampaian sebutan seni kata lagu yang jelas, bersih, dan betul dipanggil ___?", "a": "artikulasi"},
        {"q": "Kekuatan atau kelembutan bunyi dalam nyanyian dipanggil ___?", "a": "dinamik"},
        {"q": "Simbol 'f' (forte) dalam skor lagu membawa maksud nyanyian dinyanyikan secara ___?", "a": "kuat"},
        {"q": "Simbol 'p' (piano) dalam skor lagu membawa maksud nyanyian dinyanyikan secara ___?", "a": "lembut"},
        {"q": "Nyanyian sekumpulan murid secara beramai-ramai menyampaikan sesebuah lagu dipanggil nyanyian ___?", "a": "koor"},
        {"q": "Lagu yang dinyanyikan secara kejar-mengejar di mana kumpulan kedua mula menyanyi lewat sedikit daripada kumpulan pertama dipanggil lagu ___?", "a": "pusingan"},
        {"q": "Apakah nama lain bagi lagu pusingan dalam istilah muzik barat?", "a": "canon"},
        {"q": "Nyanyian tanpa menggunakan sebarang iringan alat muzik dipanggil nyanyian ___?", "a": "akapela"},
        {"q": "Teknik menyanyi dengan memutuskan nota-nota muzik secara pendek dan tangkas dipanggil ___?", "a": "stakato"},
        {"q": "Teknik menyanyi dengan menyambungkan nota-nota muzik secara licin dan beralun dipanggil ___?", "a": "legato"},
        {"q": "Garisan melengkung di atas nota yang mengarahkan penyanyi menyanyi secara legato dipanggil garisan ___?", "a": "frasa"},
        {"q": "Seseorang yang memimpin, menjaga tempo, dan memberi isyarat dinamik kepada kumpulan koor dipanggil ___?", "a": "konduktor"},
        {"q": "Adakah membuka mulut dengan luas membantu menghasilkan intonasi suara yang lebih bulat dan jelas?", "a": "ya"},
        {"q": "Organ utama dalam badan manusia yang bergetar untuk menghasilkan suara ialah peti ___?", "a": "suara"},
        {"q": "Menyanyi sambil mengikut pergerakan kreatif dapat membantu murid merasai ___ lagu.", "a": "tempo"},
        {"q": "Warna ton suara manusia berbeza mengikut saiz fizikal dan jantina. Istilah warna ton ini dipanggil ___?", "a": "timbre"},
        {"q": "Suara tinggi bagi penyanyi wanita dewasa dalam klasifikasi muzik klasik dipanggil ___?", "a": "soprano"},
        {"q": "Suara rendah bagi penyanyi lelaki dewasa dalam klasifikasi muzik klasik dipanggil ___?", "a": "bas"},
        {"q": "Adakah menjerit dengan kuat semasa menyanyi boleh merosakkan pita suara?", "a": "ya"},
        {"q": "Latihan menyebut huruf vokal A, E, I, O, U dengan bentuk mulut yang betul membantu memantapkan ___?", "a": "artikulasi"},
        {"q": "Apabila dinamik lagu berubah dari 'p' menjadi 'f', nyanyian harus diubah daripada lembut menjadi ___?", "a": "kuat"},
        {"q": "Lagu Kebangsaan Malaysia yang dinyanyikan dengan penuh semangat dan tertib dipanggil ___?", "a": "negaraku"},
        {"q": "Semasa menyanyikan lagu Negaraku di perhimpunan, postur badan kita mestilah berdiri ___?", "a": "tegak"},
        {"q": "Pic solfa manakah yang kedudukannya berada paling atas sekali di antara Mi, So, dan La?", "a": "la"},
        {"q": "Pic solfa manakah yang kedudukannya berada paling bawah sekali di antara Fa, Re, dan So?", "a": "re"},
        {"q": "Latihan pernafasan dengan menahan nafas dan menghembus secara perlahan menggunakan bunyi 'sss' dinamakan latihan ___?", "a": "kawalan"},
        {"q": "Adakah mendengar melodi lagu berulang kali membantu penyanyi menghafal pic dengan baik?", "a": "ya"}
    ],

    "muzik_tradisional": [
        {"q": "Muzik tradisional Kelantan yang dinyanyikan secara berkumpulan dengan seorang juara dan barisan awak-awak dipanggil ___?", "a": "dikir barat"},
        {"q": "Alat muzik tiup utama yang mengandungi pipit dan menjadi ketua melodi dalam ensembel Wayang Kulit Kelantan ialah ___?", "a": "serunai"},
        {"q": "Ensembel muzik tradisional yang menggunakan set gong kecil disusun di atas rak kayu dan popular di Negeri Sembilan ialah ___?", "a": "caklempong"},
        {"q": "Ensembel muzik istana yang menggunakan instrumen saron, bonang, gambang, dan gong besar dipanggil ___?", "a": "gamelan"},
        {"q": "Muzik Gamelan Melayu sangat terkenal dan berkembang di istana negeri Terengganu dan ___?", "a": "pahang"},
        {"q": "Alat muzik utama dalam dikir barat yang berbentuk dram dua muka dan diletakkan di atas riba pemain dipanggil gendang ___?", "a": "anak"},
        {"q": "Gendang yang saiznya lebih besar daripada gendang anak dalam dikir barat dipanggil gendang ___?", "a": "ibu"},
        {"q": "Alat muzik logam bulat berkembar yang diketuk bersama dalam dikir barat untuk mengekalkan masa dipanggil ___?", "a": "tetawak"},
        {"q": "Ketua penyanyi yang memulakan nyanyian dan pantun dalam persembahan dikir barat dipanggil ___?", "a": "juara"},
        {"q": "Penyanyi kedua yang menyambung lirik juara dengan nada melodi yang lebih rancak dalam dikir barat dipanggil ___?", "a": "tukang karang"},
        {"q": "Kumpulan penari latar yang duduk bersila dan menyanyi beramai-ramai dalam dikir barat dipanggil ___?", "a": "awak-awak"},
        {"q": "Apakah aktiviti fizikal berirama yang dilakukan oleh awak-awak semasa persembahan dikir barat?", "a": "tepuk tangan"},
        {"q": "Alat muzik bertali tradisional kaum kenyah dan kayan di Sarawak yang dipahat daripada sebatang kayu dipanggil ___?", "a": "sape"},
        {"q": "Alat muzik tiup tradisional Sabah yang diperbuat daripada labu air kering dan batang buluh dipanggil ___?", "a": "sompoton"},
        {"q": "Alat muzik perkusi tradisional kaum Kadazandusun yang terdiri daripada set gong gantung dipanggil ___?", "a": "kulintangan"},
        {"q": "Alat muzik perkusi berbentuk bulat, mempunyai satu permukaan kulit dan dipalu semasa perarakan hari raya dipanggil ___?", "a": "kompang"},
        {"q": "Kompang biasanya diperbuat daripada kayu keras dan permukaannya menggunakan kulit ___ kering.", "a": "kambing"},
        {"q": "Alat muzik bertali tradisional India yang mempunyai leher panjang, popular dalam muzik klasikal ialah ___?", "a": "sitar"},
        {"q": "Sepasang dram tangan tradisional India yang terdiri daripada dram kecil (dayan) dan dram besar (bayan) dipanggil ___?", "a": "tabla"},
        {"q": "Alat muzik tiup tradisional Cina yang diperbuat daripada buluh dan ditiup secara melintang dipanggil ___?", "a": "dizi"},
        {"q": "Alat muzik bertali klasik Cina yang mempunyai dua tali dan digesek menggunakan penggesek di celah tali dipanggil ___?", "a": "erhu"},
        {"q": "Muzik tradisional masyarakat Johor yang mendapat pengaruh daripada muzik Timur Tengah dinamakan muzik ___?", "a": "ghazal"},
        {"q": "Alat muzik bertali utama yang tidak mempunyai tetali fret (fretless) dan berbentuk seperti buah pear dalam muzik Ghazal ialah ___?", "a": "gambus"},
        {"q": "Gong besar yang digantung dan dipukul bagi menandakan permulaan atau penutup pusingan melodi tradisional dipanggil ___?", "a": "tawak"},
        {"q": "Adakah alat muzik marakas termasuk dalam kumpulan alat muzik tradisional asli Malaysia?", "a": "tidak"},
        {"q": "Teater tradisional Melayu yang menggabungkan unsur lakonan, tarian, dan muzik yang berasal dari Kedah dipanggil ___?", "a": "mak yong"},
        {"q": "Alat muzik bertali tiga yang digesek untuk mengiringi nyanyian dalam teater Mak Yong dipanggil rebab ___?", "a": "tiga tali"},
        {"q": "Muzik tarian tradisional masyarakat Portugis di Melaka yang menggunakan biola, gitar, dan pandeiro dipanggil ___?", "a": "branyo"},
        {"q": "Gendang besar berkulit satu yang digantung di masjid atau surau lama untuk menandakan masuk waktu solat dipanggil ___?", "a": "beduk"},
        {"q": "Alat muzik caklempong yang memainkan melodi utama dalam persembahan dikategorikan sebagai caklempong ___?", "a": "gereteh"},
        {"q": "Alat muzik caklempong yang berfungsi sebagai pengawal tempo dan kord dipanggil caklempong ___?", "a": "tingkah"},
        {"q": "Apakah bahan utama yang digunakan untuk membuat mangkuk alat muzik caklempong?", "a": "gangsa"},
        {"q": "Adakah muzik gamelan asalnya dimainkan khas sebagai hiburan untuk golongan istana dan diraja sahaja?", "a": "ya"},
        {"q": "Alat muzik bertali tradisional Cina yang mempunyai empat tali dan dipetik dalam kedudukan menegak dipanggil ___?", "a": "pipa"},
        {"q": "Alat muzik perkusi tradisional Cina yang berupa dram besar berkulit lembu dan dipalu menggunakan dua kayu tebal dipanggil ___?", "a": "shigu"},
        {"q": "Tarian singa masyarakat Cina biasanya diringi oleh pukulan dram besar, simbal, dan ___ logam.", "a": "gong"},
        {"q": "Gendang dua muka tradisional India yang diikat pada pinggang dan dipalu dengan tangan atau ranting kayu dipanggil ___?", "a": "dholak"},
        {"q": "Seruling tradisional India yang diperbuat daripada sebatang buluh khas dipanggil ___?", "a": "bansuri"},
        {"q": "Apakah nama alat muzik jenis xilofon kayu yang terdapat di dalam set ensembel Gamelan Melayu?", "a": "gambang"},
        {"q": "Instrumen gamelan yang terdiri daripada kepingan logam diletakkan di atas kotak kayu dan dipukul dengan pemukul getah dipanggil ___?", "a": "saron"},
        {"q": "Adakah persembahan dikir barat menggunakan mikrofon untuk juara dan tukang karang?", "a": "ya"},
        {"q": "Muzik tradisional Sabah dan Sarawak banyak menggunakan alam semula jadi seperti bambu dan ___ sebagai bahan alat muzik.", "a": "kayu"},
        {"q": "Alat muzik sape pada asalnya dimainkan untuk tujuan ritual pembomohan, namun kini dimainkan sebagai muzik ___?", "a": "hiburan"},
        {"q": "Alat muzik perkusi tradisional bersaiz sangat kecil yang dipakai pada jari penari India dipanggil ___?", "a": "ghunghru"},
        {"q": "Adakah kita perlu menghormati dan memelihara muzik tradisional pelbagai kaum di Malaysia?", "a": "ya"},
        {"q": "Muzik tradisional menyumbang kepada pembentukan identiti dan warisan ___ negara.", "a": "budaya"},
        {"q": "Tarian zapin di Johor biasanya diiringi oleh petikan alat muzik ___ dan pukulan marwas.", "a": "gambus"},
        {"q": "Dram kecil bermuka dua yang dipukul secara laju untuk mengiringi tarian zapin dipanggil ___?", "a": "marwas"},
        {"q": "Adakah serunai dikategorikan sebagai alat perkusi tidak berpic?", "a": "tidak"},
        {"q": "Menonton persembahan muzik tradisional dapat memupuk rasa bangga terhadap warisan ___?", "a": "bangsa"}
    ],

"apresiasi_muzik": [
        {"q": "Perbuatan mendengar muzik dengan teliti serta memberikan penilaian atau penghargaan dipanggil ___ muzik?", "a": "apresiasi"},
        {"q": "Perubahan dinamik secara beransur-ansur daripada lembut kepada kuat dipanggil ___?", "a": "crescendo"},
        {"q": "Perubahan dinamik secara beransur-ansur daripada kuat kepada lembut dipanggil ___?", "a": "decrescendo"},
        {"q": "Istilah Itali yang digunakan untuk menunjukkan tempo lagu yang lambat dan tenang ialah ___?", "a": "andante"},
        {"q": "Istilah Itali yang digunakan untuk menunjukkan tempo lagu yang cepat dan rancak ialah ___?", "a": "allegro"},
        {"q": "Istilah Itali yang membawa maksud tempo lagu yang sangat lambat ialah ___?", "a": "adagio"},
        {"q": "Istilah Itali yang membawa maksud tempo lagu yang sangat cepat ialah ___?", "a": "vivace"},
        {"q": "Bentuk susunan sesebuah lagu yang mempunyai dua bahagian berbeza (A dan B) dinamakan bentuk ___?", "a": "biner"},
        {"q": "Bentuk susunan sesebuah lagu yang mempunyai tiga bahagian (A, B, dan A semula) dinamakan bentuk ___?", "a": "ternari"},
        {"q": "Ensembel muzik barat bersaiz besar yang menggabungkan keluarga alat bertali, tiup kayu, tiup logam, dan perkusi dipanggil ___?", "a": "orkestra"},
        {"q": "Dalam sesebuah orkestra barat, kumpulan alat muzik manakah yang mempunyai bilangan pemain paling banyak?", "a": "bertali"},
        {"q": "Komposer muzik klasik barat yang sangat terkenal dengan karya 'Symphony No. 5' walaupun mengalami masalah pendengaran ialah ___?", "a": "beethoven"},
        {"q": "Komposer genius zaman klasikal yang menggubah lagu buaian terkenal 'Twinkle Twinkle Little Star' ialah ___?", "a": "mozart"},
        {"q": "Komposer barat Zaman Barok yang terkenal dengan lagu 'Toccata and Fugue' menggunakan organ paip ialah ___?", "a": "bach"},
        {"q": "Lagu rakyat Pantai Timur yang dinyanyikan semasa bermain permainan layang-layang tradisional dipanggil ___?", "a": "wau bulan"},
        {"q": "Lagu rakyat yang menceritakan tentang seekor kambing dan bertanyakan di mana anak kambing saya dipanggil ___?", "a": "chan mali chan"},
        {"q": "Lagu tradisi negeri Johor yang sering dinyanyikan berpasangan dengan pantun nasihat dipanggil dondang ___?", "a": "sayang"},
        {"q": "Apakah genre muzik yang menggunakan instrumen elektrik seperti gitar elektrik, bes, dan dram dengan irama yang sangat bertenaga?", "a": "rok"},
        {"q": "Genre muzik moden yang menekankan lirik berima secara pantas mengikut rentak bit (beat) dipanggil muzik ___?", "a": "hip hop"},
        {"q": "Genre muzik yang berasal dari Amerika Syarikat dengan ciri improvisasi dan kord yang kompleks dipanggil muzik ___?", "a": "jaz"},
        {"q": "Adakah elemen melodi, ritma, harmoni, dan warna ton merupakan komponen utama dalam mengkaji apresiasi muzik?", "a": "ya"},
        {"q": "Kualiti bunyi atau keunikan suara yang membezakan antara rekorder dan pianika dipanggil warna ___?", "a": "ton"},
        {"q": "Gabungan dua atau lebih nota yang dibunyikan serentak untuk menghasilkan bunyi yang sedap dipanggil ___?", "a": "harmoni"},
        {"q": "Susunan pic secara mendatar yang membentuk sebuah melodi lagu dipanggil ___?", "a": "melodi"},
        {"q": "Rentak irama yang teratur dan berulang-ulang dalam sesebuah gubahan lagu dipanggil ___?", "a": "ritma"},
        {"q": "Dewan konsert muzik klasikal paling berprestij di Malaysia yang terletak di KLCC ialah Dewan Filharmonik ___?", "a": "petronas"},
        {"q": "Kumpulan pemuzik profesional yang menetap dan mengadakan konsert di Dewan Filharmonik Petronas dikenali sebagai ___?", "a": "mpo"},
        {"q": "Apakah singkatan bagi nama kumpulan musisi Malaysian Philharmonic Orchestra?", "a": "mpo"},
        {"q": "Adakah muzik pop biasanya mempunyai struktur lagu yang mudah diingati dan popular dalam kalangan masyarakat?", "a": "ya"},
        {"q": "Muzik tradisi ghazal di Johor mendapat pengaruh besar daripada kebudayaan negara ___?", "a": "arab"},
        {"q": "Muzik gamelan melayu yang kita dengar hari ini mempunyai pengaruh asal daripada pulau ___?", "a": "jawa"},
        {"q": "Alatan muzik dalam orkestra barat seperti flut dan klarinet dikelompokkan dalam keluarga alat tiup ___?", "a": "kayu"},
        {"q": "Alatan muzik dalam orkestra barat seperti trompet dan trombon dikelompokkan dalam keluarga alat tiup ___?", "a": "logam"},
        {"q": "Alat muzik perkusi berpic dalam orkestra yang berbentuk seperti kawah besar besi dipanggil ___?", "a": "timpani"},
        {"q": "Apakah nama alat bertali paling kecil dalam keluarga biola yang mempunyai pic tertinggi?", "a": "biola"},
        {"q": "Apakah nama instrumen bertali yang saiznya lebih besar daripada biola tetapi lebih kecil daripada selo?", "a": "viola"},
        {"q": "Menilai keindahan sesebuah lagu berdasarkan lirik dan melodi membantu mematangkan emosi dan ___ murid.", "a": "pemikiran"},
        {"q": "Muzik yang dicipta khas tanpa lirik suara dan hanya menggunakan alat muzik sahaja dipanggil muzik ___?", "a": "instrumental"},
        {"q": "Nyanyian solo bermaksud nyanyian yang disampaikan oleh ___ orang penyanyi sahaja?", "a": "seorang"},
        {"q": "Nyanyian duet bermaksud nyanyian yang disampaikan oleh ___ orang penyanyi?", "a": "dua"},
        {"q": "Nyanyian trio bermaksud nyanyian yang disampaikan oleh ___ orang penyanyi?", "a": "tiga"},
        {"q": "Nyanyian kuartet bermaksud nyanyian yang disampaikan oleh ___ orang penyanyi?", "a": "empat"},
        {"q": "Adakah rentak tarian inang mempunyai tempo yang lebih cepat berbanding rentak tarian joget?", "a": "tidak"},
        {"q": "Rentak tradisional Melayu yang sangat rancak dan biasa digunakan untuk mengiringi tarian perkahwinan ialah rentak ___?", "a": "joget"},
        {"q": "Rentak tradisional yang berirama perlahan, lembut, dan gemalai dipanggil rentak ___?", "a": "asli"},
        {"q": "Apakah nama alat muzik tiup utama dalam persembahan menora dan wayang kulit?", "a": "serunai"},
        {"q": "Simbol 'ff' (fortissimo) dalam apresiasi skor membawa maksud bunyi yang sangat ___?", "a": "kuat"},
        {"q": "Simbol 'pp' (pianissimo) dalam apresiasi skor membawa maksud bunyi yang sangat ___?", "a": "lembut"},
        {"q": "Seseorang yang mendengar muzik dengan penuh penghayatan untuk memahami mesej pencipta dipanggil penonton yang ___?", "a": "bijak"},
        {"q": "Adakah lagu kebangsaan sesebuah negara digubah untuk menaikkan semangat patriotik rakyat?", "a": "ya"}
    ],

    "etika_persembahan": [
        {"q": "Sikapan atau peraturan tingkah laku yang betul semasa mengadakan atau menonton konsert dipanggil ___ persembahan?", "a": "etika"},
        {"q": "Sebelum mengadakan persembahan, semua ahli kumpulan muzik mestilah menghadiri sesi ___ dengan disiplin.", "a": "latihan"},
        {"q": "Datang awal ke tempat perlawanan atau lokasi persembahan menunjukkan kita seorang yang menepati ___?", "a": "masa"},
        {"q": "Pakaian yang dipilih untuk persembahan di atas pentas sekolah mestilah kemas, sopan, dan ___?", "a": "sesuai"},
        {"q": "Semasa melangkah masuk ke atas pentas, kita hendaklah berjalan dengan postur badan yang ___ dan yakin.", "a": "tegak"},
        {"q": "Sebelum memulakan persembahan, para pemuzik atau penyanyi biasanya akan ___ hormat kepada penonton.", "a": "tunduk"},
        {"q": "Semasa rakan kumpulan sedang bermain di atas pentas, adakah kita dibenarkan berbual-bual dengan kuat?", "a": "tidak"},
        {"q": "Jika tersilap memainkan nota muzik semasa persembahan langsung, kita mestilah tetap ___ bermain sehingga tamat.", "a": "meneruskan"},
        {"q": "Sikap mengkritik atau mentertawakan rakan yang tersilap di atas pentas merupakan perbuatan yang ___?", "a": "buruk"},
        {"q": "Selepas tamat sesebuah persembahan, penonton memberikan penghargaan dengan cara ___?", "a": "tepuk tangan"},
        {"q": "Bilakah waktu yang paling tepat untuk penonton memberikan tepukan tangan semasa konsert klasikal?", "a": "selepas lagu tamat"},
        {"q": "Adakah penonton dibenarkan membuat bising atau menjerit semasa muzik sedang dimainkan dalam dewan tertutup?", "a": "tidak"},
        {"q": "Sebelum memasuki dewan konsert formal, kita mestilah memastikan telefon bimbit diletakkan dalam mod ___?", "a": "senyap"},
        {"q": "Menonton persembahan muzik dengan tenang tanpa mengganggu orang di sebelah menunjukkan etika penonton yang ___?", "a": "berbudaya"},
        {"q": "Adakah kita dibenarkan membawa makanan dan minuman manis ke dalam dewan konsert bertaraf antarabangsa?", "a": "tidak"},
        {"q": "Mengambil gambar menggunakan lampu denyar (flash) semasa persembahan silau boleh ___ tumpuan pemuzik.", "a": "mengganggu"},
        {"q": "Kawasan di belakang pentas yang digunakan oleh pemuzik untuk bersiap dan menunggu giliran dipanggil ___?", "a": "backstage"},
        {"q": "Di kawasan belakang pentas (backstage), pemuzik mestilah menjaga ketenteraman dan tidak ___?", "a": "bising"},
        {"q": "Sekiranya kita menjadi penonton, adakah kita perlu hadir lebih awal sebelum tirai panggung dibuka?", "a": "ya"},
        {"q": "Membaca brosur atau atur cara program sebelum konsert bermula membantu penonton ___ jalan cerita persembahan.", "a": "memahami"},
        {"q": "Sentiasa menjaga kebersihan ruang tempat duduk penonton selepas konsert tamat adalah amalan yang ___?", "a": "terpuji"},
        {"q": "Pemain muzik yang menghormati arahan dan isyarat tangan konduktor orkestra menunjukkan semangat ___ yang tinggi.", "a": "kerjasama"},
        {"q": "Perasaan gemetar atau takut yang dialami oleh seseorang sebelum membuat persembahan di atas pentas dipanggil ___ pentas?", "a": "demam"},
        {"q": "Cara terbaik untuk mengatasi masalah demam pentas ialah dengan melakukan latihan ___ nafas secara teratur.", "a": "kawalan"},
        {"q": "Adakah etika berpakaian ke dewan konsert formal membenarkan penonton memakai selipar dan seluar pendek?", "a": "tidak"},
        {"q": "Semasa persembahan koor, mengekalkan hubungan mata (eye contact) dengan konduktor adalah etika penyanyi yang ___?", "a": "wajib"},
        {"q": "Memastikan semua peralatan muzik dikembalikan ke tempat asal selepas persembahan selesai merupakan tanggungjawab ___?", "a": "bersama"},
        {"q": "Menyanyi dengan mengikut kemampuan suara sendiri tanpa menjerit berlebihan bertujuan menjaga keharmonian ___ kumpulan.", "a": "imbangan"},
        {"q": "Adakah penonton dibenarkan keluar masuk dewan sesuka hati ketika lagu sedang dipersembahkan?", "a": "tidak"},
        {"q": "Etika penonton semasa persembahan artis jalanan (busking) ialah memberikan sumbangan ikhlas ke dalam ___ disediakan.", "a": "tabung"},
        {"q": "Mengucapkan terima kasih kepada krew pentas yang membantu menyediakan mikrofon menunjukkan sikap yang ___?", "a": "bersopan"},
        {"q": "Sekiranya berlaku kerosakan alat muzik rakan sebelum persembahan, etika yang baik ialah cuba ___ alat jika mampu.", "a": "meminjamkan"},
        {"q": "Menepati masa dalam setiap jadual latihan muzik melatih diri kita menjadi murid yang ___?", "a": "berdisiplin"},
        {"q": "Berdiri tegak dan menyanyikan lagu sekolah dengan penuh hormat merupakan etika perhimpunan yang ___?", "a": "betul"},
        {"q": "Adakah amalan berbual menggunakan telefon bimbit semasa konsert sedang berlangsung melanggar etika penonton?", "a": "ya"},
        {"q": "Mengambil berat keselamatan fizikal alat muzik yang dipinjam daripada pihak sekolah merupakan etika penggunaan yang ___?", "a": "amanah"},
        {"q": "Apabila persembahan tamat, sorakan penghargaan tinggi yang biasa disorakkan oleh penonton dipanggil ___?", "a": "bravo"},
        {"q": "Perkataan 'bravo' disorakkan oleh penonton untuk menyatakan rasa ___ atas persembahan yang sangat cemerlang.", "a": "kagum"},
        {"q": "Adakah sah dari segi etika jika kita meniru atau menciplak karya muzik orang lain tanpa kebenaran?", "a": "tidak"},
        {"q": "Amalan menciplak hasil kerja seni orang lain dan mengaku sebagai hak sendiri dipanggil ___?", "a": "plagiat"},
        {"q": "Menghargai sumbangan guru muzik dengan memberikan tumpuan penuh semasa kelas merupakan etika seorang ___?", "a": "murid"},
        {"q": "Bersikap sabar dan tenang ketika menunggu giliran membuat persembahan di atas pentas adalah sikap yang ___?", "a": "matang"},
        {"q": "Pemuzik profesional sentiasa memastikan alat muzik mereka dilaras atau di___ picnya sebelum konsert bermula.", "a": "tala"},
        {"q": "Proses menala (tuning) alat muzik bertali sangat penting supaya bunyi yang dihasilkan tidak ___?", "a": "sumbang"},
        {"q": "Adakah etika menonton membolehkan kita meletakkan kaki di atas kerusi hadapan di dalam panggung?", "a": "tidak"},
        {"q": "Apabila persembahan tamat, etika melangkah keluar dari dewan perlulah dilakukan secara tertib tanpa ___?", "a": "berebut"},
        {"q": "Menhargai perbezaan bakat dan kebolehan muzik rakan-rakan sekelas akan mewujudkan suasana belajar yang ___?", "a": "harmoni"},
        {"q": "Adakah murid dibenarkan menyentuh alat muzik khas milik guru tanpa mendapat keizinan terlebih dahulu?", "a": "tidak"},
        {"q": "Sentiasa tersenyum dan memberikan tenaga positif di atas pentas dapat menarik minat ___?", "a": "penonton"},
        {"q": "Menjaga nama baik sekolah semasa menyertai pertandingan muzik di luar adalah etika kumpulan yang ___?", "a": "utama"}
    ],

    "kerjaya_muzik": [
        {"q": "Seseorang yang bekerja mencipta melodi, lirik, dan menggubah sesebuah lagu dipanggil ___?", "a": "komposer"},
        {"q": "Seseorang yang kerjayanya menyanyikan lagu secara profesional di atas pentas atau di dalam studio dipanggil ___?", "a": "penyanyi"},
        {"q": "Seseorang yang memimpin, menjaga tempo, dan menyelaras permainan sebuah orkestra atau kumpulan koor dipanggil ___?", "a": "konduktor"},
        {"q": "Kerjaya mengajar subjek Pendidikan Muzik di sekolah rendah atau sekolah menengah dipanggil ___ muzik?", "a": "guru"},
        {"q": "Seseorang yang pakar dalam mengawal sistem bunyi, mikrofon, dan adunan muzik semasa konsert dipanggil jurutera ___?", "a": "bunyi"},
        {"q": "Seseorang yang mengajar murid bermain alat muzik secara individu di pusat tuisyen swasta dipanggil ___ muzik?", "a": "tutor"},
        {"q": "Kerjaya menyanyi atau bermain muzik di studio rakaman untuk menghasilkan album dipanggil pemuzik ___?", "a": "rakaman"},
        {"q": "Seseorang yang menulis nota muzik dan mengubah suai susunan lagu untuk dimainkan oleh pelbagai alat muzik dipanggil ___?", "a": "pengubah"},
        {"q": "Apakah nama kerjaya bagi seseorang yang mahir membaiki dan menala pic piano yang rosak?", "a": "penala piano"},
        {"q": "Kerjaya menghiburkan orang ramai dengan memutarkan lagu di stesen radio dipanggil penyiar atau ___?", "a": "dj"},
        {"q": "Seseorang yang mencipta skor muzik latar belakang untuk sesebuah filem atau drama tv dipanggil komposer skor ___?", "a": "filem"},
        {"q": "Kerjaya menggunakan muzik sebagai medium rawatan untuk membantu memulihkan kesihatan minda dan fizikal pesakit dipanggil pakar ___ muzik?", "a": "terapi"},
        {"q": "Adakah seorang pakar terapi muzik boleh bekerja di hospital atau pusat pemulihan khas?", "a": "ya"},
        {"q": "Seseorang yang mahir dalam membuat dan membina alat muzik tradisional seperti sape atau kompang dipanggil ___ alat muzik?", "a": "pembuat"},
        {"q": "Kerjaya membuat ulasan, kritikan, dan artikel tentang album atau konsert muzik di surat khabar dipanggil ___ muzik?", "a": "pengkritik"},
        {"q": "Seseorang yang menguruskan jadual, kontrak, dan kebajikan artis atau kumpulan muzik dipanggil ___ artis?", "a": "pengurus"},
        {"q": "Pemuzik kreatif yang membuat persembahan secara santai di jalanan atau kawasan awam untuk mencari rezeki dipanggil ___?", "a": "busker"},
        {"q": "Aktiviti membuat persembahan muzik di kawasan terbuka jalanan dipanggil aktiviti ___?", "a": "busking"},
        {"q": "Seseorang yang pakar dalam menulis lirik atau seni kata lagu yang indah dan bermakna dipanggil penulis ___?", "a": "lirik"},
        {"q": "Tempat khas yang dilengkapi peralatan kalis bunyi untuk merakam suara dan alat muzik dipanggil studio ___?", "a": "rakaman"},
        {"q": "Seseorang yang memiliki dan menguruskan perniagaan menjual pelbagai alat muzik dipanggil ___ kedai muzik?", "a": "pemilik"},
        {"q": "Adakah bidang kerjaya muzik memerlukan minat, bakat, dan latihan berterusan yang tinggi?", "a": "ya"},
        {"q": "Seseorang pemuzik yang bermain alat muzik tiup loyang dalam pasukan tentera atau polis dipanggil pemuzik pancaragam ___?", "a": "tentera"},
        {"q": "Kumpulan pemuzik yang bermain di majlis-majlis rasmi istana diraja dipanggil ensembel ___?", "a": "nobat"},
        {"q": "Adakah menjadi seorang konduktor orkestra memerlukan pengetahuan teori muzik yang sangat mendalam?", "a": "ya"},
        {"q": "Seseorang yang bertanggungjawab memilih lagu dan menyusun giliran persembahan di majlis keramaian dipanggil ___?", "a": "dj"},
        {"q": "Kerjaya menyanyi di dalam kumpulan koor profesional teater mega dipanggil penyanyi ___?", "a": "koor"},
        {"q": "Seseorang yang mereka bentuk reka letak dan akustik dewan konsert supaya gema bunyinya cantik dipanggil jurutera ___?", "a": "akustik"},
        {"q": "Pembuat alat muzik bertali klasikal seperti biola dan selo dikenali dengan istilah khusus iaitu ___?", "a": "luthier"},
        {"q": "Seseorang yang menari sambil menyanyi dalam sesebuah teater dipanggil pelakon teater ___?", "a": "muzikal"},
        {"q": "Adakah kemajuan teknologi hari ini membolehkan seseorang membina kerjaya sebagai komposer muzik digital di rumah?", "a": "ya"},
        {"q": "Seseorang yang bekerja mempromosikan album dan tiket konsert artis kepada orang ramai dipanggil pegawai ___?", "a": "pemasaran"},
        {"q": "Pemuzik yang mahir bermain pelbagai jenis alat muzik perkusi dalam sesebuah ensembel dipanggil pemain ___?", "a": "perkusi"},
        {"q": "Kerjaya menulis buku teks atau buku rujukan berkaitan teori muzik sekolah dipanggil penulis ___?", "a": "buku"},
        {"q": "Seseorang yang pakar dalam mengkaji sejarah perkembangan muzik dan budaya masyarakat dipanggil ahli ___ muzik?", "a": "sejarah"},
        {"q": "Adakah menjadi seorang penyanyi terkenal memerlukan disiplin yang tinggi dalam menjaga kesihatan suara?", "a": "ya"},
        {"q": "Mengelakkan makanan berminyak dan ais adalah antara amalan penting bagi menjaga aset kerjaya seorang ___?", "a": "nyanyian"},
        {"q": "Seseorang yang kerjayanya bermain dram untuk pelbagai artis berbeza tanpa terikat dengan mana-mana kumpulan dipanggil pemain dram ___?", "a": "bebas"},
        {"q": "Istilah bagi pemuzik yang bekerja secara kontrak bebas tanpa kumpulan tetap ialah pemuzik ___?", "a": "freelance"},
        {"q": "Seseorang yang bekerja di syarikat rakaman untuk menapis dan mencari bakat baru nyanyian dipanggil ejen ___?", "a": "bakat"},
        {"q": "Kerjaya menghasilkan kesan bunyi khas (sound effects) untuk permainan video atau animasi dipanggil pereka ___?", "a": "bunyi"},
        {"q": "Adakah pemain rekorder profesional boleh membina kerjaya dengan mengadakan konsert solo di seluruh dunia?", "a": "ya"},
        {"q": "Seseorang yang mahir bermain alat muzik piano untuk mengiringi penyanyi lain semasa ujibakat dipanggil ___ piano?", "a": "pengiring"},
        {"q": "Pemuzik yang menganggotai kumpulan pancaragam sekolah menyertai latihan demi melatih ___ masa depan.", "a": "kerjaya"},
        {"q": "Kerjaya peguam yang pakar dalam menguruskan kes hak cipta lagu dan cetak rompak dipanggil peguam undang-undang ___?", "a": "hiburan"},
        {"q": "Seseorang yang menghasilkan kandungan video ulasan lagu di platform media sosial dipanggil ___ kandungan muzik?", "a": "pencipta"},
        {"q": "Mengajar kelas muzik secara dalam talian (online) merupakan inovasi kerjaya alaf baharu bagi seorang ___ muzik.", "a": "guru"},
        {"q": "Seseorang yang menyanyi khas untuk iklan radio atau televisyen dipanggil penyanyi ___?", "a": "jingle"},
        {"q": "Seseorang yang bertanggungjawab menjaga dan menyusun susunan mikrofon di atas pentas konsert sebelum artis bermula dipanggil krew ___?", "a": "pentas"},
        {"q": "Adakah industri muzik menyumbang kepada pertumbuhan ekonomi dan sektor kreativiti sesebuah negara?", "a": "ya"}
    ]
};