// ==========================================
// 1. SCIENCE QUESTION DATA (16 Categories)
// ==========================================
const scienceData = {
"scientific_skills": [
        {"q": "Using senses to gather information about objects or phenomena is known as ___?", "a": "observing"},
        {"q": "The tool used to measure the length of a book is a ___?", "a": "ruler"},
        {"q": "The sense used to smell a flower is the sense of ___?", "a": "smell"},
        {"q": "The sense used to taste an orange is the sense of ___?", "a": "taste"},
        {"q": "The sense used to hear a bell is the sense of ___?", "a": "hearing"},
        {"q": "The sense used to see the color of a leaf is the sense of ___?", "a": "sight"},
        {"q": "The sense used to feel if an object is hot is the sense of ___?", "a": "touch"},
        {"q": "Giving an early explanation for an observation is making an ___?", "a": "inference"},
        {"q": "Making an expectation about what will happen next is called ___?", "a": "predicting"},
        {"q": "Grouping objects based on similar characteristics is known as ___?", "a": "classifying"},
        {"q": "The standard metric unit for measuring temperature is degree ___?", "a": "celsius"},
        {"q": "A scientific tool used to measure temperature accurately is a ___?", "a": "thermometer"},
        {"q": "A tool used to measure time accurately in a race is a ___?", "a": "stopwatch"},
        {"q": "The standard unit for a very short duration of time is the ___?", "a": "second"},
        {"q": "A tool used to measure the mass of an object is a weighing ___?", "a": "scale"},
        {"q": "The standard unit for heavy mass is the ___?", "a": "kilogram"},
        {"q": "A tool used to measure the volume of a liquid is a measuring ___?", "a": "cylinder"},
        {"q": "The standard unit for liquid volume in small amounts is the ___?", "a": "millilitre"},
        {"q": "The variable that is intentionally changed in an experiment is the ___ variable?", "a": "manipulated"},
        {"q": "The variable that is observed or measured in an experiment is the ___ variable?", "a": "responding"},
        {"q": "The variable that is kept the same throughout the experiment is the ___ variable?", "a": "constant"},
        {"q": "A testable statement about the relationship between variables is a ___?", "a": "hypothesis"},
        {"q": "The tool used to see very tiny objects like bacteria is a ___?", "a": "microscope"},
        {"q": "The tool used to see very distant objects in space is a ___?", "a": "telescope"},
        {"q": "Recording and sharing data in tables or charts is known as ___?", "a": "communicating"},
        {"q": "One way to communicate scientific data visually is by using a ___?", "a": "graph"},
        {"q": "The tool used to clean a test tube is called a test tube ___?", "a": "brush"},
        {"q": "Where should liquid chemical waste safely be disposed of in the lab?", "a": "sink"},
        {"q": "Where should solid waste be disposed of in the lab?", "a": "dustbin"},
        {"q": "What formation must students form before entering the science room?", "a": "line"},
        {"q": "What activity is strictly forbidden in the science room?", "a": "eating"},
        {"q": "Who should you report an accident to immediately?", "a": "teacher"},
        {"q": "A tool used to put out small fires is a fire ___?", "a": "extinguisher"},
        {"q": "Representing a specimen accurately through art is a scientific ___?", "a": "drawing"},
        {"q": "The standard unit for measuring area is the ___ centimetre?", "a": "square"},
        {"q": "The correct eye level when reading a liquid scale must match the ___?", "a": "meniscus"},
        {"q": "Using a hand lens makes a specimen look ___?", "a": "bigger"},
        {"q": "Live specimens should be safely returned to their natural ___?", "a": "habitat"},
        {"q": "The skill of handling science equipment correctly is known as ___ skills?", "a": "manipulative"},
        {"q": "Arranging data from the smallest value to the largest is known as ___ order?", "a": "ascending"},
        {"q": "The main purpose of an experiment is to test a ___?", "a": "hypothesis"},
        {"q": "A summary of the results at the end of an experiment is called a ___?", "a": "conclusion"},
        {"q": "The tool used to measure the girth of a tree is a measuring ___?", "a": "tape"},
        {"q": "The unit for measuring a very short length is the ___?", "a": "millimetre"},
        {"q": "Anything that can be measured and changed in an experiment is a ___?", "a": "variable"},
        {"q": "Measuring the change in litmus paper color uses the skill of ___?", "a": "observing"},
        {"q": "The trait of a scientist who always wants to find out more is ___?", "a": "curiosity"},
        {"q": "A science room must have good airflow or ___?", "a": "ventilation"},
        {"q": "The first step in a scientific investigation is ___ the problem?", "a": "identifying"},
        {"q": "An ancient tool used to measure time using falling sand is the ___?", "a": "hourglass"}
    ],
    "human_life_processes": [
        {"q": "The main organ used for breathing is the ___?", "a": "lungs"},
        {"q": "The gas we inhale during breathing is ___?", "a": "oxygen"},
        {"q": "The gas we exhale during breathing is carbon ___?", "a": "dioxide"},
        {"q": "The path of air during inhalation ends at the ___?", "a": "lungs"},
        {"q": "The path of air during exhalation ends at the ___?", "a": "nose"},
        {"q": "The small air sacs in the lungs for gas exchange are the ___?", "a": "alveoli"},
        {"q": "Chest movement during inhalation goes upwards and ___?", "a": "outwards"},
        {"q": "Chest movement during exhalation goes downwards and ___?", "a": "inwards"},
        {"q": "The breathing rate when we are sleeping is ___?", "a": "low"},
        {"q": "The breathing rate when we are running is ___?", "a": "high"},
        {"q": "The process of removing waste from the body is ___?", "a": "excretion"},
        {"q": "The process of removing undigested food from the body is ___?", "a": "defecation"},
        {"q": "The organ that excretes urine is the ___?", "a": "kidneys"},
        {"q": "The organ that excretes sweat is the ___?", "a": "skin"},
        {"q": "The organ that excretes carbon dioxide is the ___?", "a": "lungs"},
        {"q": "The liquid waste product of the kidneys is ___?", "a": "urine"},
        {"q": "The waste product released through the skin is ___?", "a": "sweat"},
        {"q": "Besides carbon dioxide, the lungs also excrete water ___?", "a": "vapor"},
        {"q": "Excretion is important to humans to ensure we stay ___?", "a": "healthy"},
        {"q": "The body's reaction to a change in its surroundings is a response to ___?", "a": "stimuli"},
        {"q": "Closing your eyes when bright light shines is a response to ___?", "a": "light"},
        {"q": "Shivering when it is very cold is a response to ___?", "a": "temperature"},
        {"q": "Pulling your hand away from a hot stove is a response to ___?", "a": "heat"},
        {"q": "The sense organ used for hearing sound stimuli is the ___?", "a": "ears"},
        {"q": "The sense organ used for tasting food is the ___?", "a": "tongue"},
        {"q": "The sense organ used for smelling is the ___?", "a": "nose"},
        {"q": "The sense organ used for touch and temperature is the ___?", "a": "skin"},
        {"q": "Humans reproduce to ensure species survival by giving ___?", "a": "birth"},
        {"q": "Passing characteristics from parents to offspring is called ___?", "a": "inheritance"},
        {"q": "An example of a physical trait inherited from parents is the type of ___?", "a": "hair"},
        {"q": "Another example of an inherited characteristic is the color of our ___?", "a": "skin"},
        {"q": "The inherited colored part of the eye is called the ___?", "a": "iris"},
        {"q": "A harmful and addictive substance found in cigarettes is ___?", "a": "nicotine"},
        {"q": "A bad habit that seriously damages the lungs is ___?", "a": "smoking"},
        {"q": "A substance that slows down response to stimuli when consumed is ___?", "a": "alcohol"},
        {"q": "Substances that cause hallucinations and loss of coordination are ___?", "a": "drugs"},
        {"q": "The muscle that helps in the breathing process is the ___?", "a": "diaphragm"},
        {"q": "The bones that protect the heart and lungs form the rib ___?", "a": "cage"},
        {"q": "Difficulty in passing out feces is called ___?", "a": "constipation"},
        {"q": "To prevent constipation, we must eat enough ___?", "a": "fiber"},
        {"q": "The gas required by body cells to stay alive is ___?", "a": "oxygen"},
        {"q": "The temporary storage organ for urine in the body is the ___?", "a": "bladder"},
        {"q": "Undigested food waste is known as ___?", "a": "feces"},
        {"q": "Is height an inherited characteristic?", "a": "yes"},
        {"q": "Can a scar from an injury be inherited?", "a": "no"},
        {"q": "The human life cycle begins from a ___?", "a": "baby"},
        {"q": "Jumping when hearing a loud thunder is a response to ___?", "a": "sound"},
        {"q": "Breathing rate is measured as breaths per ___?", "a": "minute"},
        {"q": "The windpipe that connects the nose to the lungs is the ___?", "a": "trachea"},
        {"q": "The process of making new individuals is ___?", "a": "reproduction"}
    ],

"animal_classification": [
        {"q": "Animals with a backbone are called ___?", "a": "vertebrates"},
        {"q": "Animals without a backbone are called ___?", "a": "invertebrates"},
        {"q": "The breathing organ of a fish is the ___?", "a": "gills"},
        {"q": "The breathing organ of a grasshopper is the ___?", "a": "spiracles"},
        {"q": "A worm breathes through its moist ___?", "a": "skin"},
        {"q": "The breathing organ of a cat is the ___?", "a": "lungs"},
        {"q": "Animals that live both on land and in water are ___?", "a": "amphibians"},
        {"q": "A frog in water breathes through its moist ___?", "a": "skin"},
        {"q": "A frog on land breathes using its ___?", "a": "lungs"},
        {"q": "Animals that eat only plants are called ___?", "a": "herbivores"},
        {"q": "Animals that eat only other animals are called ___?", "a": "carnivores"},
        {"q": "Animals that eat both plants and animals are called ___?", "a": "omnivores"},
        {"q": "Is a cow a herbivore, carnivore, or omnivore?", "a": "herbivore"},
        {"q": "Is a tiger a herbivore, carnivore, or omnivore?", "a": "carnivore"},
        {"q": "Is a chicken a herbivore, carnivore, or omnivore?", "a": "omnivore"},
        {"q": "Animals that give birth to their young are ___?", "a": "mammals"},
        {"q": "Animals that lay eggs and have feathers are ___?", "a": "birds"},
        {"q": "Animals with dry scales that lay eggs are ___?", "a": "reptiles"},
        {"q": "A whale breathes through its ___?", "a": "lungs"},
        {"q": "A dolphin is classified as a ___?", "a": "mammal"},
        {"q": "A platypus is a unique mammal because it lays ___?", "a": "eggs"},
        {"q": "Insects have how many legs?", "a": "six"},
        {"q": "A spider is an invertebrate because it has no ___?", "a": "backbone"},
        {"q": "Which group of vertebrates are warm-blooded and have fur?", "a": "mammals"},
        {"q": "The breathing organ of a shrimp is the ___?", "a": "gills"},
        {"q": "A butterfly breathes through its ___?", "a": "spiracles"},
        {"q": "An example of a reptile that lives in water is a ___?", "a": "turtle"},
        {"q": "Birds breathe using their ___?", "a": "lungs"},
        {"q": "Is a crocodile a vertebrate or invertebrate?", "a": "vertebrate"},
        {"q": "A penguin is classified as a ___?", "a": "bird"},
        {"q": "The hard outer covering of an insect is an ___?", "a": "exoskeleton"},
        {"q": "An animal that produces milk for its young is a ___?", "a": "mammal"},
        {"q": "Salamanders and newts are examples of ___?", "a": "amphibians"},
        {"q": "A snail is an example of an ___?", "a": "invertebrate"},
        {"q": "Does a snake have a backbone?", "a": "yes"},
        {"q": "Animals that hunt other animals for food are ___?", "a": "predators"},
        {"q": "Animals that are hunted and eaten are ___?", "a": "prey"},
        {"q": "A bat is the only mammal that can ___?", "a": "fly"},
        {"q": "Is an eagle a carnivore?", "a": "yes"},
        {"q": "Do all mammals live on land?", "a": "no"},
        {"q": "Is a shark a mammal or a fish?", "a": "fish"},
        {"q": "Invertebrates like crabs have a hard ___?", "a": "shell"},
        {"q": "Which organ do tadpoles use to breathe?", "a": "gills"},
        {"q": "A lizard is classified as a ___?", "a": "reptile"},
        {"q": "The group of animals that feed their young with milk are ___?", "a": "mammals"},
        {"q": "Are most insects vertebrates or invertebrates?", "a": "invertebrates"},
        {"q": "A dragonfly is an example of an ___?", "a": "insect"},
        {"q": "The breathing organ of a caterpillar is the ___?", "a": "spiracles"},
        {"q": "Is a bear an omnivore?", "a": "yes"},
        {"q": "An animal with a streamlined body for swimming is a ___?", "a": "fish"}
    ],
    "plant_processes": [
        {"q": "The process by which plants make their own food is ___?", "a": "photosynthesis"},
        {"q": "The green pigment found in leaves is called ___?", "a": "chlorophyll"},
        {"q": "The gas absorbed by plants for photosynthesis is carbon ___?", "a": "dioxide"},
        {"q": "The gas released by plants during photosynthesis is ___?", "a": "oxygen"},
        {"q": "The main source of energy for photosynthesis is ___?", "a": "sunlight"},
        {"q": "What do plants absorb from the soil for photosynthesis?", "a": "water"},
        {"q": "The food produced by photosynthesis is stored as ___?", "a": "starch"},
        {"q": "Which part of the plant usually carries out photosynthesis?", "a": "leaves"},
        {"q": "Plant shoots grow towards which stimulus?", "a": "light"},
        {"q": "Plant roots grow towards which stimulus?", "a": "water"},
        {"q": "Plant roots also respond to the downward pull of ___?", "a": "gravity"},
        {"q": "Mimosa pudica (touch-me-not) leaves fold inward when ___?", "a": "touched"},
        {"q": "Venus flytrap leaves snap shut in response to ___?", "a": "touch"},
        {"q": "A potato plant usually stores starch in its underground ___?", "a": "stem"},
        {"q": "Tiny pores on the surface of leaves are called ___?", "a": "stomata"},
        {"q": "How do non-flowering plants like ferns reproduce?", "a": "spores"},
        {"q": "How do banana plants reproduce?", "a": "suckers"},
        {"q": "Hibiscus plants usually reproduce through stem ___?", "a": "cuttings"},
        {"q": "How do mushrooms reproduce?", "a": "spores"},
        {"q": "Onions typically reproduce using underground ___?", "a": "stems"},
        {"q": "The scattering of seeds away from the parent plant is called ___?", "a": "dispersal"},
        {"q": "Seeds dispersed by wind are usually light and have ___?", "a": "wings"},
        {"q": "An example of a seed dispersed by wind is the ___?", "a": "dandelion"},
        {"q": "Seeds dispersed by water have a husk that is ___?", "a": "spongy"},
        {"q": "An example of a fruit dispersed by water is the ___?", "a": "coconut"},
        {"q": "Fruits dispersed by animals are usually brightly colored and ___?", "a": "fleshy"},
        {"q": "Seeds dispersed by an explosive mechanism will naturally ___?", "a": "burst"},
        {"q": "A seed dispersed by an explosive mechanism is the rubber ___?", "a": "seed"},
        {"q": "Seeds must be dispersed far away to avoid ___?", "a": "competition"},
        {"q": "A cactus stores water in the desert using its fleshy ___?", "a": "stem"},
        {"q": "Some plants shed their leaves in the dry season to prevent water ___?", "a": "loss"},
        {"q": "A plant that sheds its leaves during dry seasons is the rubber ___?", "a": "tree"},
        {"q": "Needle-like leaves help pine trees prevent water ___?", "a": "loss"},
        {"q": "What protects a rose plant from enemies?", "a": "thorns"},
        {"q": "What liquid protects a papaya tree from insects?", "a": "latex"},
        {"q": "Bamboo protects itself from enemies using fine ___?", "a": "hairs"},
        {"q": "Fine hairs on bamboo stems can cause ___?", "a": "itchiness"},
        {"q": "A rafflesia flower protects itself from herbivores by releasing a bad ___?", "a": "smell"},
        {"q": "Some plants like the pong-pong tree protect themselves by being ___?", "a": "poisonous"},
        {"q": "Does a mushroom make its own food?", "a": "no"},
        {"q": "Do all plants produce flowers?", "a": "no"},
        {"q": "What part of the plant holds it firmly in the ground?", "a": "roots"},
        {"q": "The tube that transports water from roots to leaves is the ___?", "a": "xylem"},
        {"q": "The tube that transports food from leaves to other parts is the ___?", "a": "phloem"},
        {"q": "A lotus floats on water because its stem contains air ___?", "a": "spaces"},
        {"q": "Morning glory plants get enough sunlight using their climbing ___?", "a": "stems"},
        {"q": "A pineapple plant protects itself from being eaten using its sharp ___?", "a": "leaves"},
        {"q": "Plants are known as what in a food chain?", "a": "producers"},
        {"q": "Does a plant need oxygen to survive?", "a": "yes"},
        {"q": "What do seeds need to germinate? Water, air, and ___?", "a": "warmth"}
    ],

"energy_forms": [
        {"q": "What is the primary source of energy on Earth?", "a": "Sun"},
        {"q": "Energy possessed by a moving object is called ___ energy?", "a": "kinetic"},
        {"q": "Energy stored in food, wood, or batteries is called ___ energy?", "a": "chemical"},
        {"q": "Energy that we can see is called ___ energy?", "a": "light"},
        {"q": "Energy produced by vibrating objects is called ___ energy?", "a": "sound"},
        {"q": "Energy that makes us feel warm is called ___ energy?", "a": "heat"},
        {"q": "Energy stored in a stretched rubber band or lifted object is ___ energy?", "a": "potential"},
        {"q": "Energy flowing through electrical wires is called ___ energy?", "a": "electrical"},
        {"q": "Energy generated from the splitting of atoms is ___ energy?", "a": "nuclear"},
        {"q": "Is energy from the Sun renewable or nonrenewable?", "a": "renewable"},
        {"q": "Are fossil fuels renewable or nonrenewable?", "a": "nonrenewable"},
        {"q": "An example of a fossil fuel extracted from the ground is ___?", "a": "petroleum"},
        {"q": "Energy source from plant and animal waste is called ___?", "a": "biomass"},
        {"q": "Electricity generated from moving water is called ___?", "a": "hydroelectric"},
        {"q": "Principle: Energy cannot be created or ___?", "a": "destroyed"},
        {"q": "In a battery, chemical energy changes to ___ energy?", "a": "electrical"},
        {"q": "In a light bulb, electrical energy changes to light and ___ energy?", "a": "heat"},
        {"q": "In a radio, electrical energy changes to ___ energy?", "a": "sound"},
        {"q": "A solar panel changes solar energy to ___ energy?", "a": "electrical"},
        {"q": "When you rub your hands together, kinetic energy changes to ___ energy?", "a": "heat"},
        {"q": "A television converts electrical energy into sound and ___ energy?", "a": "light"},
        {"q": "An electric iron converts electrical energy into ___ energy?", "a": "heat"},
        {"q": "A falling apple changes potential energy into ___ energy?", "a": "kinetic"},
        {"q": "During photosynthesis, solar energy changes into ___ energy?", "a": "chemical"},
        {"q": "Energy that can be replenished constantly is called ___ energy?", "a": "renewable"},
        {"q": "Energy that will run out and cannot be replaced quickly is ___ energy?", "a": "nonrenewable"},
        {"q": "Wind turbines use what type of energy source?", "a": "wind"},
        {"q": "Is coal a renewable energy source?", "a": "no"},
        {"q": "Is ocean wave a renewable energy source?", "a": "yes"},
        {"q": "Energy obtained from hot rocks deep underground is ___ energy?", "a": "geothermal"},
        {"q": "Switching off lights when leaving a room helps to ___ energy?", "a": "save"},
        {"q": "Carpooling helps to save fuel, specifically ___ fuels?", "a": "fossil"},
        {"q": "Food provides humans with ___ energy?", "a": "chemical"},
        {"q": "When a bow is pulled back, it gains ___ energy?", "a": "potential"},
        {"q": "The faster a car moves, the more ___ energy it has.", "a": "kinetic"},
        {"q": "A ringing school bell produces ___ energy?", "a": "sound"},
        {"q": "A lit candle converts chemical energy into light and ___ energy?", "a": "heat"},
        {"q": "A moving bicycle has ___ energy?", "a": "kinetic"},
        {"q": "A laptop runs on ___ energy?", "a": "electrical"},
        {"q": "The energy stored in fossil fuels originally came from the ___?", "a": "Sun"},
        {"q": "Riding a bicycle instead of driving helps save ___?", "a": "fuel"},
        {"q": "Solar panels are usually placed on the ___?", "a": "roof"},
        {"q": "Do plants use kinetic energy to make food?", "a": "no"},
        {"q": "The main form of energy you get from sitting near a campfire is ___ energy?", "a": "heat"},
        {"q": "A book resting high up on a shelf has ___ energy?", "a": "potential"},
        {"q": "A washing machine converts electrical energy mainly into ___ energy?", "a": "kinetic"},
        {"q": "An electric toaster converts electrical energy into ___ energy?", "a": "heat"},
        {"q": "Are natural gas reserves limitless?", "a": "no"},
        {"q": "Using energy wisely ensures we have enough for the ___?", "a": "future"},
        {"q": "Batteries store energy in the form of ___ energy?", "a": "chemical"}
    ],
    "light_properties": [
        {"q": "Light travels in a ___ line.", "a": "straight"},
        {"q": "The bouncing of light off a surface is called ___?", "a": "reflection"},
        {"q": "The bending of light as it moves between different materials is called ___?", "a": "refraction"},
        {"q": "An object that allows all light to pass through it is ___?", "a": "transparent"},
        {"q": "An object that allows only some light to pass through it is ___?", "a": "translucent"},
        {"q": "An object that does not allow any light to pass through it is ___?", "a": "opaque"},
        {"q": "Is clear glass transparent, translucent, or opaque?", "a": "transparent"},
        {"q": "Is wood transparent, translucent, or opaque?", "a": "opaque"},
        {"q": "Is frosted glass transparent, translucent, or opaque?", "a": "translucent"},
        {"q": "A dark area formed when light is blocked by an object is a ___?", "a": "shadow"},
        {"q": "If an object is moved closer to the light source, the shadow becomes ___?", "a": "bigger"},
        {"q": "If the screen is moved further from the object, the shadow becomes ___?", "a": "bigger"},
        {"q": "Shadows are formed because light travels in a ___ line?", "a": "straight"},
        {"q": "A tool that uses reflection to see behind or around corners is a ___?", "a": "periscope"},
        {"q": "A surface that reflects light well is usually smooth and ___?", "a": "shiny"},
        {"q": "An example of an object that reflects light is a ___?", "a": "mirror"},
        {"q": "A pencil looks bent in a glass of water due to ___?", "a": "refraction"},
        {"q": "The size of a pool looks shallower than it is due to ___?", "a": "refraction"},
        {"q": "A tool used to see tiny objects by refracting light is a ___?", "a": "microscope"},
        {"q": "A tool used to see distant stars through refraction or reflection is a ___?", "a": "telescope"},
        {"q": "A glass object that separates white light into seven colors is a ___?", "a": "prism"},
        {"q": "The seven colors of light are seen in a ___?", "a": "rainbow"},
        {"q": "The first color in a rainbow is ___?", "a": "red"},
        {"q": "A mirror with a flat surface is called a ___ mirror?", "a": "plane"},
        {"q": "A mirror that curves outwards is a ___ mirror?", "a": "convex"},
        {"q": "A mirror that curves inwards is a ___ mirror?", "a": "concave"},
        {"q": "Side mirrors of a car are usually ___ mirrors?", "a": "convex"},
        {"q": "Security mirrors in shops are usually ___ mirrors?", "a": "convex"},
        {"q": "Dentists use a ___ mirror to see teeth clearly?", "a": "concave"},
        {"q": "Does a shadow have colors?", "a": "no"},
        {"q": "When light hits a mirror, it is ___?", "a": "reflected"},
        {"q": "What happens to light when it enters a prism?", "a": "refraction"},
        {"q": "Can light pass through a brick wall?", "a": "no"},
        {"q": "Is water a transparent material?", "a": "yes"},
        {"q": "Is a shadow always the same shape as the object?", "a": "yes"},
        {"q": "What is the natural source of light for Earth?", "a": "sun"},
        {"q": "Lenses in spectacles work based on light ___?", "a": "refraction"},
        {"q": "A magnifying glass uses which property of light?", "a": "refraction"},
        {"q": "Light travels faster in air than in ___?", "a": "water"},
        {"q": "A periscope contains two ___?", "a": "mirrors"},
        {"q": "Can we see objects in a completely dark room?", "a": "no"},
        {"q": "To see an object, light must be ___ into our eyes.", "a": "reflected"},
        {"q": "Does air allow light to pass through?", "a": "yes"},
        {"q": "A shadow is shortest when the sun is ___?", "a": "overhead"},
        {"q": "Shadows are longest during sunrise and ___?", "a": "sunset"},
        {"q": "The image in a plane mirror is always the same ___ as the object.", "a": "size"},
        {"q": "Is clear plastic a transparent material?", "a": "yes"},
        {"q": "Refraction happens because the ___ of light changes.", "a": "speed"},
        {"q": "A rainbow is formed when sunlight is refracted by ___?", "a": "raindrops"},
        {"q": "Can a shadow be formed by a transparent object?", "a": "no"}
    ],

"electricity_basics": [
        {"q": "What provides electrical energy in a simple circuit?", "a": "battery"},
        {"q": "What component converts electrical energy into light energy in a circuit?", "a": "bulb"},
        {"q": "The component used to connect all parts of a circuit is the ___?", "a": "wire"},
        {"q": "The component used to complete or break a circuit is the ___?", "a": "switch"},
        {"q": "A circuit where electricity can flow fully is called a ___ circuit?", "a": "closed"},
        {"q": "A circuit where the path of electricity is broken is called an ___ circuit?", "a": "open"},
        {"q": "If the switch is open, will the bulb light up?", "a": "no"},
        {"q": "If the switch is closed, will the bulb light up?", "a": "yes"},
        {"q": "A circuit with only one path for electricity to flow is a ___ circuit?", "a": "series"},
        {"q": "A circuit with more than one path for electricity to flow is a ___ circuit?", "a": "parallel"},
        {"q": "In which circuit do bulbs share the exact same path?", "a": "series"},
        {"q": "In which circuit is each bulb on a different branch?", "a": "parallel"},
        {"q": "Adding more dry cells in a series circuit makes the bulb ___?", "a": "brighter"},
        {"q": "Adding more bulbs in a series circuit makes the bulbs ___?", "a": "dimmer"},
        {"q": "Which type of circuit is typically used in most houses?", "a": "parallel"},
        {"q": "If one bulb blows in a series circuit, do the others stay lit?", "a": "no"},
        {"q": "If one bulb blows in a parallel circuit, do the others stay lit?", "a": "yes"},
        {"q": "The positive and negative symbols on a dry cell represent its ___?", "a": "terminals"},
        {"q": "Materials that allow electricity to flow through them are called ___?", "a": "conductors"},
        {"q": "Materials that do not allow electricity to flow through them are called ___?", "a": "insulators"},
        {"q": "Is a metal spoon a conductor or an insulator?", "a": "conductor"},
        {"q": "Is a plastic ruler a conductor or an insulator?", "a": "insulator"},
        {"q": "Is a copper wire an insulator?", "a": "no"},
        {"q": "Is rubber considered an insulator?", "a": "yes"},
        {"q": "Wires are covered with plastic to provide ___?", "a": "insulation"},
        {"q": "What hazard might you experience if you touch a switch with wet hands?", "a": "shock"},
        {"q": "Is water a conductor of electricity?", "a": "yes"},
        {"q": "A safety device that breaks the circuit when current is too high is a ___?", "a": "fuse"},
        {"q": "Which component is represented by a long and short line in a diagram?", "a": "cell"},
        {"q": "The continuous flow of electricity is also known as electrical ___?", "a": "current"},
        {"q": "Do identical bulbs in a parallel circuit share the same brightness?", "a": "yes"},
        {"q": "Can a dry cell store energy forever?", "a": "no"},
        {"q": "What form of energy is stored inside a dry cell?", "a": "chemical"},
        {"q": "Using many appliances on one socket can cause an electrical ___?", "a": "overload"},
        {"q": "Objects in our homes that use electricity to work are called ___?", "a": "appliances"},
        {"q": "Is a rubber eraser a conductor?", "a": "no"},
        {"q": "Is a metal safety pin a conductor?", "a": "yes"},
        {"q": "A drawing that uses symbols to show a circuit is a circuit ___?", "a": "diagram"},
        {"q": "If the wires are not connected to the terminals, will the bulb light?", "a": "no"},
        {"q": "What happens to the brightness of bulbs in parallel if one is removed?", "a": "unchanged"},
        {"q": "Does adding a second cell to a single-bulb circuit make it brighter?", "a": "yes"},
        {"q": "Is a glass rod a conductor?", "a": "no"},
        {"q": "Does a bulb light up if it is physically 'blown'?", "a": "no"},
        {"q": "The thin wire inside a bulb that glows is called the ___?", "a": "filament"},
        {"q": "When electricity flows through a bulb, it produces light and ___?", "a": "heat"},
        {"q": "Should we put metal objects into an electrical socket?", "a": "no"},
        {"q": "Should we repair electrical items while they are still plugged in?", "a": "no"},
        {"q": "A heavy-duty car battery is also known as an ___?", "a": "accumulator"},
        {"q": "Electricity from a wall socket originally comes from a power ___?", "a": "station"},
        {"q": "To save electricity, we should use energy-efficient ___?", "a": "appliances"}
    ],
    "heat_and_temperature": [
        {"q": "A form of energy that flows from hot to cold is ___?", "a": "heat"},
        {"q": "The degree of hotness or coldness of an object is its ___?", "a": "temperature"},
        {"q": "The standard metric unit for temperature is degrees ___?", "a": "Celsius"},
        {"q": "A tool used to directly measure temperature is a ___?", "a": "thermometer"},
        {"q": "What happens to the temperature of water when it is heated?", "a": "increases"},
        {"q": "What happens to the temperature of water when it is cooled?", "a": "decreases"},
        {"q": "At what degree Celsius does water boil?", "a": "100"},
        {"q": "At what degree Celsius does ice melt?", "a": "0"},
        {"q": "When an object gains heat, its physical size will ___?", "a": "expand"},
        {"q": "When an object loses heat, its physical size will ___?", "a": "contract"},
        {"q": "Gaps are left between railway tracks to allow for thermal ___?", "a": "expansion"},
        {"q": "Electric wires are hung loosely to prevent snapping during thermal ___?", "a": "contraction"},
        {"q": "What happens to the liquid level in a thermometer when it gets hot?", "a": "rises"},
        {"q": "What happens to the liquid level in a thermometer when it gets cold?", "a": "drops"},
        {"q": "The silvery liquid used in a traditional thermometer is ___?", "a": "mercury"},
        {"q": "A balloon expands in hot water because the air inside experiences ___?", "a": "expansion"},
        {"q": "A metal ball cannot pass through a ring after heating because it ___?", "a": "expanded"},
        {"q": "To open a tight metal bottle cap, we should soak it in hot ___?", "a": "water"},
        {"q": "The main source of heat for the Earth is the ___?", "a": "Sun"},
        {"q": "When we rub our palms, they feel warm because of ___?", "a": "friction"},
        {"q": "Does a large bucket of water hold more heat than a cup at the same temperature?", "a": "yes"},
        {"q": "Are 'Heat' and 'Temperature' exactly the same scientific concept?", "a": "no"},
        {"q": "Water changes into steam at what temperature in Celsius?", "a": "100"},
        {"q": "Materials that allow heat to flow through them easily are called ___?", "a": "conductors"},
        {"q": "Materials that do not allow heat to flow through them easily are called ___?", "a": "insulators"},
        {"q": "Is aluminum considered a good heat conductor?", "a": "yes"},
        {"q": "Is wood considered a good heat insulator?", "a": "yes"},
        {"q": "Cooking pot handles are usually made of plastic to provide ___?", "a": "insulation"},
        {"q": "What happens to the mass of a metal bar after it expands?", "a": "unchanged"},
        {"q": "Thermal expansion refers to an increase in physical ___?", "a": "size"},
        {"q": "Thermal contraction refers to a decrease in physical ___?", "a": "size"},
        {"q": "The normal temperature of a healthy human body is around 37 degrees ___?", "a": "Celsius"},
        {"q": "Can heat travel through a total vacuum?", "a": "yes"},
        {"q": "Heat always travels from a higher temperature to a ___ temperature?", "a": "lower"},
        {"q": "A thermometer should be read at eye level with the ___?", "a": "meniscus"},
        {"q": "When water vapor loses heat and turns into liquid, it ___?", "a": "condenses"},
        {"q": "When liquid water loses a lot of heat and turns solid, it ___?", "a": "freezes"},
        {"q": "A clinical thermometer is specifically used to measure body ___?", "a": "temperature"},
        {"q": "What fabric item protects us from the cold by trapping body heat?", "a": "blanket"},
        {"q": "Must ice gain or lose heat in order to melt?", "a": "gain"},
        {"q": "Concrete bridges have expansion joints to prevent severe ___?", "a": "cracking"},
        {"q": "If we put an inflated balloon in the freezer, its size will ___?", "a": "shrink"},
        {"q": "The process of a solid completely changing into a liquid is called ___?", "a": "melting"},
        {"q": "The process of a liquid slowly changing into a gas is called ___?", "a": "evaporation"},
        {"q": "Is standard air a good conductor of heat?", "a": "no"},
        {"q": "Between 40 degrees and 80 degrees, the hotter one is ___?", "a": "80"},
        {"q": "When hot steam touches a cold surface, it turns back into ___?", "a": "water"},
        {"q": "The transfer of heat through a circulating liquid or gas is called ___?", "a": "convection"},
        {"q": "The transfer of heat through direct contact in a solid is called ___?", "a": "conduction"},
        {"q": "The transfer of heat through empty space via electromagnetic waves is called ___?", "a": "radiation"}
    ],

"states_of_matter": [
        {"q": "Anything that has mass and occupies space is called ___?", "a": "matter"},
        {"q": "The three states of matter are solid, liquid, and ___?", "a": "gas"},
        {"q": "Does a solid have a fixed shape?", "a": "yes"},
        {"q": "Does a solid have a fixed volume?", "a": "yes"},
        {"q": "Does a liquid have a fixed shape?", "a": "no"},
        {"q": "Does a liquid have a fixed volume?", "a": "yes"},
        {"q": "Does a gas have a fixed shape?", "a": "no"},
        {"q": "Does a gas have a fixed volume?", "a": "no"},
        {"q": "Which state of matter can be compressed easily?", "a": "gas"},
        {"q": "The process of a liquid turning into a solid is ___?", "a": "freezing"},
        {"q": "The process of a solid turning into a liquid is ___?", "a": "melting"},
        {"q": "The process of a liquid turning into a gas at its boiling point is ___?", "a": "boiling"},
        {"q": "The process of a liquid turning into a gas below its boiling point is ___?", "a": "evaporation"},
        {"q": "The process of a gas turning into a liquid is ___?", "a": "condensation"},
        {"q": "At what degree Celsius does water freeze?", "a": "0"},
        {"q": "At what degree Celsius does water boil?", "a": "100"},
        {"q": "Cloud formation is a result of which process?", "a": "condensation"},
        {"q": "Rain is part of the natural ___ cycle?", "a": "water"},
        {"q": "Small droplets of water on the outside of a cold glass are caused by ___?", "a": "condensation"},
        {"q": "Drying clothes under the sun involves the process of ___?", "a": "evaporation"},
        {"q": "Is a stone a solid, liquid, or gas?", "a": "solid"},
        {"q": "Is oxygen a solid, liquid, or gas?", "a": "gas"},
        {"q": "Is cooking oil a solid, liquid, or gas?", "a": "liquid"},
        {"q": "When ice melts, its particle arrangement becomes less ___?", "a": "orderly"},
        {"q": "In which state are particles packed very closely together?", "a": "solid"},
        {"q": "In which state can particles move freely and far apart?", "a": "gas"},
        {"q": "The constant movement of water between Earth and sky is the water ___?", "a": "cycle"},
        {"q": "What provides energy for the water cycle?", "a": "Sun"},
        {"q": "Does air have mass?", "a": "yes"},
        {"q": "Does air occupy space?", "a": "yes"},
        {"q": "Ice is the ___ state of water?", "a": "solid"},
        {"q": "Steam is the ___ state of water?", "a": "gas"},
        {"q": "When water evaporates, it turns into water ___?", "a": "vapor"},
        {"q": "The process that happens when we see morning dew on leaves is ___?", "a": "condensation"},
        {"q": "A liquid takes the shape of its container because it has no fixed ___?", "a": "shape"},
        {"q": "Can a solid flow like a liquid?", "a": "no"},
        {"q": "What happens to the volume of gas if it is put in a larger container?", "a": "increases"},
        {"q": "Is smoke an example of a gas?", "a": "yes"},
        {"q": "Is honey a liquid?", "a": "yes"},
        {"q": "Particles in a liquid can ___ over each other.", "a": "slide"},
        {"q": "To change a liquid to a gas, must it gain or lose heat?", "a": "gain"},
        {"q": "To change a liquid to a solid, must it gain or lose heat?", "a": "lose"},
        {"q": "Is a sponge a solid?", "a": "yes"},
        {"q": "The bubbles in boiling water are filled with water ___?", "a": "vapor"},
        {"q": "Does evaporation only happen at 100°C?", "a": "no"},
        {"q": "A state of matter that has no fixed shape and no fixed volume is ___?", "a": "gas"},
        {"q": "What is the result of water vapor losing heat high in the sky?", "a": "clouds"},
        {"q": "Can we see water vapor?", "a": "no"},
        {"q": "Is fine sand a solid or liquid?", "a": "solid"},
        {"q": "Water is the only substance found naturally in all three ___?", "a": "states"}
    ],
    "food_chains": [
        {"q": "An organism that makes its own food using sunlight is a ___?", "a": "producer"},
        {"q": "Animals that eat plants or other animals are called ___?", "a": "consumers"},
        {"q": "A diagram showing 'who eats whom' is a food ___?", "a": "chain"},
        {"q": "The main source of energy for all food chains is the ___?", "a": "Sun"},
        {"q": "An animal that hunts and eats other animals is a ___?", "a": "predator"},
        {"q": "An animal that is hunted and eaten by another animal is ___?", "a": "prey"},
        {"q": "In a food chain, the arrows represent the flow of ___?", "a": "energy"},
        {"q": "Plants are producers because they perform ___?", "a": "photosynthesis"},
        {"q": "An animal that eats only producers (plants) is a ___?", "a": "herbivore"},
        {"q": "An animal that eats only other consumers (meat) is a ___?", "a": "carnivore"},
        {"q": "An animal that eats both plants and animals is an ___?", "a": "omnivore"},
        {"q": "Several food chains linked together form a food ___?", "a": "web"},
        {"q": "A consumer that eats only plants is a ___ consumer.", "a": "primary"},
        {"q": "An animal that eats a primary consumer is a ___ consumer.", "a": "secondary"},
        {"q": "An animal at the top of a food chain is an ___ predator.", "a": "apex"},
        {"q": "What happens to the number of prey if predators increase?", "a": "decreases"},
        {"q": "What happens to the number of predators if prey disappears?", "a": "decreases"},
        {"q": "Organisms that break down dead plants and animals are ___?", "a": "decomposers"},
        {"q": "An example of a producer in a pond is ___?", "a": "algae"},
        {"q": "An example of a producer on land is ___?", "a": "grass"},
        {"q": "A hawk eating a snake is an example of a ___?", "a": "predator"},
        {"q": "In the chain Grass -> Grasshopper -> Bird, what type of consumer is the bird?", "a": "secondary"},
        {"q": "In the chain Leaf -> Caterpillar -> Bird, the leaf is a ___?", "a": "producer"},
        {"q": "Can a food chain start with an animal?", "a": "no"},
        {"q": "Energy ___ as it moves up the food chain.", "a": "decreases"},
        {"q": "A habitat with many linked food chains is very ___?", "a": "stable"},
        {"q": "If all plants in a habitat die, the animals will eventually ___?", "a": "die"},
        {"q": "Is a mushroom a producer?", "a": "no"},
        {"q": "Is a tiger a primary consumer?", "a": "no"},
        {"q": "A cow eating grass is a ___ consumer.", "a": "primary"},
        {"q": "Does a food web show more realistic eating habits than a chain?", "a": "yes"},
        {"q": "Which organism has the most energy in a food chain?", "a": "producer"},
        {"q": "In a food chain, the least energy is held by the apex ___?", "a": "predator"},
        {"q": "An eagle is a predator, its prey could be a ___?", "a": "snake"},
        {"q": "Small animals in the sea that eat algae are primary ___?", "a": "consumers"},
        {"q": "Can an animal be both a predator and a prey?", "a": "yes"},
        {"q": "Humans are usually classified as ___ in a food web.", "a": "omnivores"},
        {"q": "If frogs are removed, what happens to the insect population?", "a": "increases"},
        {"q": "Paddy plant -> Rat -> Snake. Who is the secondary consumer?", "a": "snake"},
        {"q": "Is a cat a predator to a mouse?", "a": "yes"},
        {"q": "Plankton -> Small fish -> Big fish. Who is the producer?", "a": "plankton"},
        {"q": "Most food chains have no more than ___ steps.", "a": "five"},
        {"q": "Energy is lost in the form of ___ at each level.", "a": "heat"},
        {"q": "A scavenger eats ___ animals.", "a": "dead"},
        {"q": "Is a vulture a scavenger?", "a": "yes"},
        {"q": "Is a spider a predator?", "a": "yes"},
        {"q": "A caterpillar is a ___ to a bird.", "a": "prey"},
        {"q": "Fungi and bacteria are examples of ___?", "a": "decomposers"},
        {"q": "Does a food chain work without sunlight?", "a": "no"},
        {"q": "The position of an organism in a food chain is its ___ level.", "a": "trophic"}
    ],

"materials_properties": [
        {"q": "Materials like wood and cotton come from ___?", "a": "plants"},
        {"q": "Materials like silk and wool come from ___?", "a": "animals"},
        {"q": "Materials like metal and glass come from ___?", "a": "rocks"},
        {"q": "Materials like plastic and synthetic cloth come from ___?", "a": "petroleum"},
        {"q": "A material that can be stretched and returns to its original shape is ___?", "a": "elastic"},
        {"q": "Is a rubber band elastic or non-elastic?", "a": "elastic"},
        {"q": "Materials that allow water to pass through or be soaked up are ___?", "a": "absorbent"},
        {"q": "Materials that do not soak up water are called ___?", "a": "waterproof"},
        {"q": "Is a raincoat made of absorbent or waterproof material?", "a": "waterproof"},
        {"q": "A material that allows light to pass through clearly is ___?", "a": "transparent"},
        {"q": "Is a metal spoon transparent?", "a": "no"},
        {"q": "Materials that allow electricity to flow through are electrical ___?", "a": "conductors"},
        {"q": "Most objects made of ___ are good electrical conductors.", "a": "metal"},
        {"q": "Materials that do not allow heat to flow through easily are ___?", "a": "insulators"},
        {"q": "Why is a cooking pot made of metal? Because it is a heat ___.", "a": "conductor"},
        {"q": "Why is a towel made of cotton? Because it ___ water.", "a": "absorbs"},
        {"q": "An object that stays on the surface of water is said to ___?", "a": "float"},
        {"q": "An object that goes to the bottom of water is said to ___?", "a": "sink"},
        {"q": "Is a heavy coin likely to float or sink?", "a": "sink"},
        {"q": "Is a dry leaf likely to float or sink?", "a": "float"},
        {"q": "Leather comes from the skin of ___?", "a": "animals"},
        {"q": "What is the basic source material of a plastic bottle?", "a": "petroleum"},
        {"q": "Is glass considered a natural or artificial material?", "a": "artificial"},
        {"q": "The ability of a material to support a heavy load without breaking is its ___?", "a": "strength"},
        {"q": "Is a paper bag stronger than a plastic bag when wet?", "a": "no"},
        {"q": "Objects made of iron will ___ when exposed to water and air.", "a": "rust"},
        {"q": "To prevent rusting, we can ___ the metal surface.", "a": "paint"},
        {"q": "Is gold a metal that rusts easily?", "a": "no"},
        {"q": "A magnet can easily attract objects made of ___?", "a": "iron"},
        {"q": "Is aluminum attracted to a magnet?", "a": "no"},
        {"q": "Which material is primarily used to make car tires?", "a": "rubber"},
        {"q": "Ceramics are generally made from baked ___?", "a": "clay"},
        {"q": "Is a glazed ceramic vase waterproof?", "a": "yes"},
        {"q": "Is a kitchen sponge an absorbent material?", "a": "yes"},
        {"q": "Are most plastics good heat insulators?", "a": "yes"},
        {"q": "Electrical wires are covered in plastic because it is an ___?", "a": "insulator"},
        {"q": "Which material is best for making the surface of a mirror?", "a": "glass"},
        {"q": "Is cotton considered a natural fiber?", "a": "yes"},
        {"q": "Is nylon considered a synthetic fiber?", "a": "yes"},
        {"q": "Synthetic materials are mostly made from ___?", "a": "petroleum"},
        {"q": "A window pane is made of glass because it is ___?", "a": "transparent"},
        {"q": "Is a wooden bridge a good electrical conductor?", "a": "no"},
        {"q": "Wool is used to make sweaters because it traps ___?", "a": "heat"},
        {"q": "Which is more elastic: a steel wire or ___?", "a": "rubber"},
        {"q": "An umbrella must be made of ___ material.", "a": "waterproof"},
        {"q": "Do all metals sink in water?", "a": "no"},
        {"q": "Copper is used in wires because it is a good ___?", "a": "conductor"},
        {"q": "Can a material be both waterproof and transparent?", "a": "yes"},
        {"q": "Is paper made from animals?", "a": "no"},
        {"q": "What stretchy material is best for a swimming cap?", "a": "latex"}
    ],
    "solar_system": [
        {"q": "The center of the solar system is the ___?", "a": "Sun"},
        {"q": "How many planets are there in our solar system?", "a": "eight"},
        {"q": "The closest planet to the Sun is ___?", "a": "Mercury"},
        {"q": "The largest planet in the solar system is ___?", "a": "Jupiter"},
        {"q": "The 'Red Planet' is known as ___?", "a": "Mars"},
        {"q": "The planet famous for its beautiful rings is ___?", "a": "Saturn"},
        {"q": "The coldest and furthest planet from the Sun is ___?", "a": "Neptune"},
        {"q": "The third planet from the Sun is ___?", "a": "Earth"},
        {"q": "The hottest planet in the solar system is ___?", "a": "Venus"},
        {"q": "Small rocky objects that orbit the Sun, mostly between Mars and Jupiter?", "a": "asteroids"},
        {"q": "A 'dirty snowball' made of ice and dust that orbits the Sun is a ___?", "a": "comet"},
        {"q": "Natural satellites that orbit planets are called ___?", "a": "moons"},
        {"q": "A path followed by a planet around the Sun is an ___?", "a": "orbit"},
        {"q": "The spinning of the Earth on its axis is called ___?", "a": "rotation"},
        {"q": "The movement of the Earth around the Sun is called ___?", "a": "revolution"},
        {"q": "How many hours does it take for Earth to complete one rotation?", "a": "24"},
        {"q": "How many days does it take for Earth to complete one revolution roughly?", "a": "365"},
        {"q": "The Earth rotates from west to ___.", "a": "east"},
        {"q": "The Sun appears to rise in the ___?", "a": "east"},
        {"q": "The Sun appears to set in the ___?", "a": "west"},
        {"q": "The rotation of the Earth causes day and ___?", "a": "night"},
        {"q": "The imaginary line through the center of the Earth is the ___?", "a": "axis"},
        {"q": "Does the Sun move around the Earth?", "a": "no"},
        {"q": "The moon reflects light from the ___?", "a": "Sun"},
        {"q": "How many days does it take for the Moon to orbit the Earth roughly?", "a": "27"},
        {"q": "The different shapes of the Moon seen from Earth are called ___?", "a": "phases"},
        {"q": "The phase when the Moon is not visible at all is the ___ moon.", "a": "new"},
        {"q": "The phase when the Moon looks like a complete circle is the ___ moon.", "a": "full"},
        {"q": "Which planet is known as Earth's twin?", "a": "Venus"},
        {"q": "Is Pluto still classified as a major planet?", "a": "no"},
        {"q": "What is Pluto classified as now? A ___ planet.", "a": "dwarf"},
        {"q": "Gravity on the Moon is ___ than on Earth.", "a": "weaker"},
        {"q": "Does the Moon have its own light?", "a": "no"},
        {"q": "The force that keeps planets in their orbits is ___?", "a": "gravity"},
        {"q": "Which planet rotates on its side?", "a": "Uranus"},
        {"q": "The belt between Mars and Jupiter is the ___ belt.", "a": "asteroid"},
        {"q": "A meteor that hits the Earth's surface is a ___?", "a": "meteorite"},
        {"q": "A 'shooting star' is actually a ___?", "a": "meteor"},
        {"q": "Which planet has the most visible rings?", "a": "Saturn"},
        {"q": "Is the Sun a planet or a star?", "a": "star"},
        {"q": "The shape of a planet's orbit is an ___?", "a": "ellipse"},
        {"q": "Does Venus have any moons?", "a": "no"},
        {"q": "Does Mercury have an atmosphere?", "a": "no"},
        {"q": "Which planet is known for the Great Red Spot?", "a": "Jupiter"},
        {"q": "The only planet currently known to support life is ___?", "a": "Earth"},
        {"q": "Why is Mars red? Because of iron ___ in the soil.", "a": "oxide"},
        {"q": "A collection of billions of stars and solar systems is a ___?", "a": "galaxy"},
        {"q": "What is the name of our galaxy? The Milky ___.", "a": "Way"},
        {"q": "Is the Earth's axis straight or tilted?", "a": "tilted"},
        {"q": "Tides on Earth are caused by the pull of the ___?", "a": "Moon"}
    ],
    "machines_simple": [
        {"q": "A tool that makes work easier and faster is a ___?", "a": "machine"},
        {"q": "A simple machine with a slanted surface to move loads up is a ___?", "a": "ramp"},
        {"q": "A simple machine with a grooved wheel and a rope is a ___?", "a": "pulley"},
        {"q": "A simple machine consisting of a rigid bar that turns on a fixed point is a ___?", "a": "lever"},
        {"q": "The fixed point on which a lever turns is called the ___?", "a": "fulcrum"},
        {"q": "The force applied to a lever to move a load is called the ___?", "a": "effort"},
        {"q": "The object being moved by a lever is called the ___?", "a": "load"},
        {"q": "A simple machine made of a wheel attached to a central shaft is a wheel and ___?", "a": "axle"},
        {"q": "A simple machine that is thick at one end and tapers to a thin edge is a ___?", "a": "wedge"},
        {"q": "An inclined plane wrapped around a cylinder or cone is a ___?", "a": "screw"},
        {"q": "A wheel with teeth around its rim is a ___?", "a": "gear"},
        {"q": "A pair of scissors is an example of which simple machine?", "a": "lever"},
        {"q": "A staircase is an example of an inclined ___?", "a": "plane"},
        {"q": "An axe is an example of which simple machine?", "a": "wedge"},
        {"q": "A flagpole uses which simple machine to raise the flag?", "a": "pulley"},
        {"q": "A doorknob is an example of a wheel and ___?", "a": "axle"},
        {"q": "A bottle cap is an example of which simple machine?", "a": "screw"},
        {"q": "What type of simple machine is a playground slide? An inclined ___.", "a": "plane"},
        {"q": "Which simple machine is used to cut or split objects?", "a": "wedge"},
        {"q": "Which simple machine is used to hold objects firmly together?", "a": "screw"},
        {"q": "A see-saw is an example of a first-class ___?", "a": "lever"},
        {"q": "A wheelbarrow is an example of a second-class ___?", "a": "lever"},
        {"q": "A fishing rod is an example of a third-class ___?", "a": "lever"},
        {"q": "Two gears working together can change the ___ of motion.", "a": "direction"},
        {"q": "A combination of two or more simple machines is a ___ machine.", "a": "complex"},
        {"q": "Is a bicycle an example of a complex machine?", "a": "yes"},
        {"q": "Simple machines help us by reducing the ___ needed to do work.", "a": "effort"},
        {"q": "Is a knife essentially a wedge?", "a": "yes"},
        {"q": "Is a ramp an inclined plane?", "a": "yes"},
        {"q": "A crane uses a system of ___ to lift heavy loads.", "a": "pulleys"},
        {"q": "In a wheel and axle, the larger circular part is the ___?", "a": "wheel"},
        {"q": "The rod that goes through the center of a wheel is the ___?", "a": "axle"},
        {"q": "Which machine uses a spiral thread?", "a": "screw"},
        {"q": "When two gears mesh, they turn in ___ directions.", "a": "opposite"},
        {"q": "A nutcracker is an example of a ___?", "a": "lever"},
        {"q": "The longer the inclined plane, the ___ effort is needed.", "a": "less"},
        {"q": "Is a mechanical pencil sharpener a complex machine?", "a": "yes"},
        {"q": "A machine built to last without harming the environment is ___?", "a": "sustainable"},
        {"q": "Maintenance like ___ prevents metal machines from rusting.", "a": "oiling"},
        {"q": "A sweeping broom is a type of ___?", "a": "lever"},
        {"q": "Tweezers are a type of ___?", "a": "lever"},
        {"q": "The part of a screw that winds around its body is the ___?", "a": "thread"},
        {"q": "Can a pulley change the direction of an applied force?", "a": "yes"},
        {"q": "Is a hammer used to pull nails a simple machine?", "a": "yes"},
        {"q": "Is a manual hand drill considered a complex machine?", "a": "yes"},
        {"q": "The specific place where the effort is applied is the effort ___?", "a": "point"},
        {"q": "Does a simple machine create new energy?", "a": "no"},
        {"q": "Which is easier: lifting a heavy load straight up or using a ___?", "a": "ramp"},
        {"q": "A ladder leaning against a wall is an example of an inclined ___?", "a": "plane"},
        {"q": "Keeping machines clean helps them to last ___?", "a": "longer"}
    ],
    "microorganisms": [
        {"q": "Very tiny living things that cannot be seen with the naked eye are ___?", "a": "microorganisms"},
        {"q": "The tool used to see microorganisms clearly is a ___?", "a": "microscope"},
        {"q": "A type of microorganism used to make bread rise is ___?", "a": "yeast"},
        {"q": "Mushrooms and molds belong to which biological group?", "a": "fungi"},
        {"q": "A type of microorganism often found in yogurt is ___?", "a": "bacteria"},
        {"q": "The smallest type of microorganism is a ___?", "a": "virus"},
        {"q": "Microorganisms breathe, move and ___?", "a": "grow"},
        {"q": "Dough rising is proof that yeast is ___?", "a": "breathing"},
        {"q": "What do fungi produce to reproduce?", "a": "spores"},
        {"q": "Food turns moldy because of the growth of ___?", "a": "fungi"},
        {"q": "Diseases caused by microorganisms are called ___ diseases.", "a": "infectious"},
        {"q": "Is a mushroom technically a type of fungi?", "a": "yes"},
        {"q": "Can some bacteria be useful to humans?", "a": "yes"},
        {"q": "Tooth decay is primarily caused by ___?", "a": "bacteria"},
        {"q": "A medicine used specifically to kill bacteria is an ___?", "a": "antibiotic"},
        {"q": "What do we wear on our face to prevent spreading viruses through coughing?", "a": "mask"},
        {"q": "Washing hands with soap helps to physically remove ___?", "a": "microorganisms"},
        {"q": "Which microorganism causes the common flu?", "a": "virus"},
        {"q": "An example of a single-celled microorganism found in pond water is ___?", "a": "protozoa"},
        {"q": "Microorganisms need air, food, and ___ to grow.", "a": "water"},
        {"q": "What temperature condition is best for typical microorganism growth? ___ temperature.", "a": "room"},
        {"q": "Can certain microorganisms live in very cold places?", "a": "yes"},
        {"q": "Is Amoeba a type of protozoa?", "a": "yes"},
        {"q": "The fuzzy green spots on old bread are usually ___?", "a": "fungi"},
        {"q": "Does extreme heat kill most microorganisms?", "a": "yes"},
        {"q": "Vaccinations help our body fight against ___?", "a": "viruses"},
        {"q": "Are all microorganisms harmful?", "a": "no"},
        {"q": "What is the common term for harmful microorganisms that cause illness?", "a": "germs"},
        {"q": "Which process is used to make tap water safe from germs?", "a": "chlorination"},
        {"q": "Is Penicillium a type of useful fungi?", "a": "yes"},
        {"q": "Microorganisms that live in water and can make their own food are ___?", "a": "algae"},
        {"q": "The study of microorganisms is called ___?", "a": "microbiology"},
        {"q": "Can we see a single bacterium with our bare eyes?", "a": "no"},
        {"q": "Does freezing kill all microorganisms?", "a": "no"},
        {"q": "Microorganisms grow much faster in ___ conditions.", "a": "damp"},
        {"q": "The process where yeast makes bread rise is called ___?", "a": "fermentation"},
        {"q": "Is COVID-19 caused by a bacteria or a virus?", "a": "virus"},
        {"q": "Are microorganisms used in making soil compost?", "a": "yes"},
        {"q": "Spoiled food usually has a very bad ___?", "a": "smell"},
        {"q": "The process where microorganisms break down dead things is ___?", "a": "decomposition"},
        {"q": "Does stomach acid help kill some germs?", "a": "yes"},
        {"q": "Microorganisms breathe in order to produce ___?", "a": "energy"},
        {"q": "A microscopic type of algae often found in oceans is ___?", "a": "phytoplankton"},
        {"q": "Can viruses reproduce outside a living host cell?", "a": "no"},
        {"q": "Using a separate cutting board for meat prevents cross-___?", "a": "contamination"},
        {"q": "Is yeast a multicellular or unicellular organism?", "a": "unicellular"},
        {"q": "Is Paramecium a type of protozoa?", "a": "yes"},
        {"q": "Which sense helps you safely identify rotten food from a distance?", "a": "smell"},
        {"q": "Microorganisms are found virtually ___?", "a": "everywhere"},
        {"q": "A visible group of bacteria growing together is called a ___?", "a": "colony"}
    ],
    "food_preservation": [
        {"q": "The process of treating food to stop it from spoiling is ___?", "a": "preservation"},
        {"q": "Heating liquid to a high temperature to kill germs is ___?", "a": "boiling"},
        {"q": "Preserving food by removing all its water is ___?", "a": "drying"},
        {"q": "Using salt to preserve food like fish is ___?", "a": "salting"},
        {"q": "Preserving food in a vinegar or sugar solution is ___?", "a": "pickling"},
        {"q": "The process of heating liquid then cooling it quickly is ___?", "a": "pasteurization"},
        {"q": "Storing food in airtight metallic containers is ___?", "a": "canning"},
        {"q": "Storing food in air-tight plastic bags with no air is ___ packing?", "a": "vacuum"},
        {"q": "Keeping food at very low temperatures (below 0°C) is ___?", "a": "freezing"},
        {"q": "Keeping food in the refrigerator (above 0°C) is ___?", "a": "cooling"},
        {"q": "Coating food with melted wax to prevent air contact is ___?", "a": "waxing"},
        {"q": "Exposing food to wood smoke for preservation is ___?", "a": "smoking"},
        {"q": "Salt and sugar act as natural ___ in food preservation.", "a": "preservatives"},
        {"q": "Which method is best for preserving fresh milk?", "a": "pasteurization"},
        {"q": "Which method is commonly used to make salted fish?", "a": "salting"},
        {"q": "Drying food can be done using the oven or ___?", "a": "sunlight"},
        {"q": "What is the main biological cause of food spoilage?", "a": "microorganisms"},
        {"q": "Spoiled food often changes in color, smell, and ___?", "a": "taste"},
        {"q": "Why does vacuum packing prevent spoilage? It removes the ___.", "a": "air"},
        {"q": "Canned food can last for a long ___?", "a": "time"},
        {"q": "Pasteurization is named after scientist Louis ___?", "a": "Pasteur"},
        {"q": "Honey is a natural preservative because it lacks ___?", "a": "water"},
        {"q": "Does freezing kill microorganisms or just stop them?", "a": "stop"},
        {"q": "Which ingredient is heavily boiled with fruit to make jams?", "a": "sugar"},
        {"q": "The acid in vinegar helps to prevent the growth of ___.", "a": "bacteria"},
        {"q": "Is canned food completely safe to eat if the can is heavily dented?", "a": "no"},
        {"q": "Preserved food is much easier to ___ to other places.", "a": "transport"},
        {"q": "Food preservation helps to avoid food ___?", "a": "wastage"},
        {"q": "Which method is commonly used for chili or dried shrimp?", "a": "drying"},
        {"q": "Waxing is usually done on which type of food?", "a": "fruits"},
        {"q": "High acidity in pickling prevents the growth of ___?", "a": "microorganisms"},
        {"q": "What happens to the taste of food after pickling in vinegar? It becomes ___.", "a": "sour"},
        {"q": "Smoking food removes water and adds ___?", "a": "flavor"},
        {"q": "Should we check the expiry ___ before buying food?", "a": "date"},
        {"q": "Does boiling water kill most living microorganisms?", "a": "yes"},
        {"q": "Which preservation method places food in a sealed tin?", "a": "canning"},
        {"q": "Salt is used to preserve eggs because it draws out ___?", "a": "water"},
        {"q": "Keeping food in a cool place slows down its ___?", "a": "spoilage"},
        {"q": "What is used to coat some apples to keep them shiny and fresh?", "a": "wax"},
        {"q": "Preserved food can be eaten out of its natural ___?", "a": "season"},
        {"q": "Is pickling considered a modern or traditional method?", "a": "traditional"},
        {"q": "Does drying fundamentally change the texture of food?", "a": "yes"},
        {"q": "Pasteurization is mainly used for milk and fruit ___?", "a": "juice"},
        {"q": "Can vacuum packing be used effectively for nuts?", "a": "yes"},
        {"q": "Microorganisms cannot grow well without sufficient ___?", "a": "moisture"},
        {"q": "A bulging can is a strong sign that the food inside is ___?", "a": "spoiled"},
        {"q": "Is standard refrigeration a permanent preservation method?", "a": "no"},
        {"q": "Ultra-High Temperature (UHT) is a form of ___?", "a": "pasteurization"},
        {"q": "Why do we preserve food for emergencies? To increase its shelf ___.", "a": "life"},
        {"q": "The main goal of preservation is to create an ___ environment for germs.", "a": "unsuitable"}
    ],
    "preservation_conservation": [
        {"q": "Protecting the environment and living things from being destroyed is ___?", "a": "preservation"},
        {"q": "Using natural resources wisely to avoid wastage is ___?", "a": "conservation"},
        {"q": "Animals that no longer exist on Earth are ___?", "a": "extinct"},
        {"q": "An example of a famous extinct giant reptile is a ___?", "a": "dinosaur"},
        {"q": "An example of an extinct flightless bird from Mauritius is the ___?", "a": "dodo"},
        {"q": "Animals or plants facing the severe threat of extinction are ___?", "a": "endangered"},
        {"q": "An example of an endangered ape in Malaysia is the ___?", "a": "orangutan"},
        {"q": "Is the Malayan Tiger currently an endangered species?", "a": "yes"},
        {"q": "The main cause of animal extinction today is human ___?", "a": "activities"},
        {"q": "Illegal hunting and capturing of wild animals is called ___?", "a": "poaching"},
        {"q": "Cutting down forests on a massive scale is called ___?", "a": "deforestation"},
        {"q": "The place where an animal or plant naturally lives is its ___?", "a": "habitat"},
        {"q": "Reforestation means ___ trees in a depleted forest.", "a": "replanting"},
        {"q": "Setting up a National Park is a strict effort for nature ___?", "a": "preservation"},
        {"q": "Reducing, reusing, and recycling are essential parts of resource ___?", "a": "conservation"},
        {"q": "Is the giant Rafflesia flower considered endangered?", "a": "yes"},
        {"q": "Is the leatherback sea turtle endangered?", "a": "yes"},
        {"q": "Poachers illegally hunt elephants to take their ___?", "a": "tusks"},
        {"q": "Poachers illegally hunt tigers primarily for their ___?", "a": "skin"},
        {"q": "Poachers illegally hunt rhinoceros primarily for their ___?", "a": "horns"},
        {"q": "What happens to animals when their habitat is completely destroyed? They ___.", "a": "die"},
        {"q": "Severe water pollution can kill ___ life.", "a": "aquatic"},
        {"q": "Is the Woolly Mammoth an extinct animal?", "a": "yes"},
        {"q": "Creating a forest reserve is a crucial way to protect ___?", "a": "biodiversity"},
        {"q": "The set of rules that protects wildlife in Malaysia is a ___.", "a": "law"},
        {"q": "Education helps people understand the ___ of protecting nature.", "a": "importance"},
        {"q": "Is the Giant Panda still considered an endangered species?", "a": "yes"},
        {"q": "An area protected specifically to save turtles is a turtle ___?", "a": "sanctuary"},
        {"q": "Massive oil spills in the ocean cause severe water ___?", "a": "pollution"},
        {"q": "Global warming is worsened by too much carbon ___ gas.", "a": "dioxide"},
        {"q": "Can biological extinction ever be naturally reversed?", "a": "no"},
        {"q": "Sustainable logging practices help to maintain healthy ___?", "a": "forests"},
        {"q": "The gradual removal of the top layer of soil is soil ___?", "a": "erosion"},
        {"q": "Mangrove forests protect the coastline from harsh ___?", "a": "erosion"},
        {"q": "Recycling paper helps to save living ___?", "a": "trees"},
        {"q": "What is the current conservation status of the Javan Rhino?", "a": "endangered"},
        {"q": "Is hunting for sport allowed in strictly protected areas?", "a": "no"},
        {"q": "A place where animals are bred to increase their population is a breeding ___?", "a": "center"},
        {"q": "Is the Quagga (a zebra subspecies) an extinct animal?", "a": "yes"},
        {"q": "Using solar energy is an excellent way of ___ energy.", "a": "conserving"},
        {"q": "Is heavy air pollution a direct threat to living things?", "a": "yes"},
        {"q": "Should we buy luxury products made from endangered animals?", "a": "no"},
        {"q": "The delicate balance of nature and living things is the ___?", "a": "ecosystem"},
        {"q": "Which global organization works to protect nature? (Abbreviation)", "a": "WWF"},
        {"q": "Is the Dugong (sea cow) an endangered marine animal?", "a": "yes"},
        {"q": "Planting trees in urban areas is known as urban ___?", "a": "forestry"},
        {"q": "Actively saving water at home is an act of ___?", "a": "conservation"},
        {"q": "The main reason for the extinction of the Dodo was ___?", "a": "overhunting"},
        {"q": "Is the Tasmanian Tiger officially classified as extinct?", "a": "yes"},
        {"q": "We must protect nature and wildlife for our ___ generations.", "a": "future"}
    ]
};
