// ==========================================
// DATA SOALAN PENDIDIKAN SENI VISUAL (4 Kategori Pertama)
// ==========================================
const psvData = {
"unsur_seni": [
        {"q": "Titik yang bergerak akan menghasilkan ___?", "options": ["rupa", "jalinan", "garisan", "bentuk"], "a": 2},
        {"q": "Garisan yang bertitik-titik dipanggil garisan ___?", "options": ["lurus", "putus", "beralun", "melengkung"], "a": 1},
        {"q": "Garisan yang kelihatan seperti ombak ialah garisan ___?", "options": ["tegak", "putus", "beralun", "siku-siku"], "a": 2},
        {"q": "Pertemuan hujung garisan akan membentuk ___?", "options": ["bentuk", "rupa", "jalinan", "ruang"], "a": 1},
        {"q": "Rupa bebas tanpa sudut tetap dinamakan rupa ___?", "options": ["geometri", "abstrak", "organik", "negatif"], "a": 2},
        {"q": "Rupa yang bersudut dan bersistem dipanggil rupa ___?", "options": ["geometri", "organik", "positif", "maya"], "a": 0},
        {"q": "Rupa hanya mempunyai ukuran sifat dua ___?", "options": ["arah", "sisi", "sudut", "dimensi"], "a": 3},
        {"q": "Rupa yang ditambah isi padunya dinamakan ___?", "options": ["jalinan", "bentuk", "ruang", "ton"], "a": 1},
        {"q": "Bentuk yang boleh disentuh secara fizikal ialah bentuk ___?", "options": ["ilusi", "maya", "konkrit", "nyata"], "a": 2},
        {"q": "Bentuk nipis di dalam gambar lukisan dipanggil bentuk ___?", "options": ["konkrit", "ilusi", "nyata", "padat"], "a": 1},
        {"q": "Kesan rasa pada permukaan sesuatu objek dinamakan ___?", "options": ["jalinan", "ton", "warna", "rupa"], "a": 0},
        {"q": "Jalinan yang boleh disentuh dan dirasa kasar ialah jalinan ___?", "options": ["tampak", "sentuh", "ilusi", "nyata"], "a": 1},
        {"q": "Jalinan pada corak cetakan baju yang rata ialah jalinan ___?", "options": ["sentuh", "fizikal", "kasar", "tampak"], "a": 3},
        {"q": "Kawasan kosong di sekeliling objek dinamakan ___?", "options": ["bentuk", "ruang", "latar", "tapak"], "a": 1},
        {"q": "Ruang sebenar pada karya tiga dimensi ialah ruang ___?", "options": ["ilusi", "dalaman", "nyata", "tampak"], "a": 2},
        {"q": "Ruang dalam lukisan pemandangan di kertas ialah ruang ___?", "options": ["nyata", "fizikal", "ilusi", "terbuka"], "a": 2},
        {"q": "Merah, biru dan kuning diklasifikasikan sebagai warna ___?", "options": ["sekunder", "tertiar", "asas", "neutral"], "a": 2},
        {"q": "Warna sekunder hasil campuran merah dan kuning ialah ___?", "options": ["hijau", "jingga", "ungu", "coklat"], "a": 1},
        {"q": "Campuran warna biru dan kuning akan menghasilkan warna ___?", "options": ["hijau", "jingga", "ungu", "merah jambu"], "a": 0},
        {"q": "Campuran warna merah dan biru akan menghasilkan warna ___?", "options": ["hijau", "coklat", "jingga", "ungu"], "a": 3},
        {"q": "Warna tertiar terhasil daripada campuran warna asas dan ___?", "options": ["sekunder", "neutral", "asas", "harmoni"], "a": 0},
        {"q": "Warna yang memberi rasa ceria dan bertenaga ialah warna ___?", "options": ["sejuk", "panas", "neutral", "gelap"], "a": 1},
        {"q": "Warna yang memberi rasa tenang dan damai ialah warna ___?", "options": ["panas", "terang", "sejuk", "garang"], "a": 2},
        {"q": "Warna hitam dan putih dikategorikan sebagai warna ___?", "options": ["asas", "neutral", "sekunder", "tertiar"], "a": 1},
        {"q": "Kesan gelap atau terang pada sesuatu warna dinamakan ___?", "options": ["ton", "krom", "shade", "tint"], "a": 0},
        {"q": "Campuran warna putih pada warna asal akan menghasilkan ___?", "options": ["shade", "ton", "tint", "krom"], "a": 2},
        {"q": "Campuran warna hitam pada warna asal akan menghasilkan ___?", "options": ["tint", "shade", "ton", "kecerahan"], "a": 1},
        {"q": "Rupa bentuk objek sebenar di atas permukaan dipanggil rupa ___?", "options": ["negatif", "positif", "geometri", "organik"], "a": 1},
        {"q": "Rupa kosong di luar kawasan objek dipanggil rupa ___?", "options": ["positif", "abstrak", "negatif", "bebas"], "a": 2},
        {"q": "Garisan yang dilukis secara tebal memberi kesan yang ___?", "options": ["ringan", "lembut", "berat", "laju"], "a": 2},
        {"q": "Sehelai daun bunga nipis mempunyai rupa jenis ___?", "options": ["geometri", "organik", "mekanikal", "simetri"], "a": 1},
        {"q": "Permukaan batu jalanan mempunyai jalinan jenis ___?", "options": ["tampak", "sentuh", "ilusi", "lukis"], "a": 1},
        {"q": "Warna laut yang kebiruan menggambarkan suasana yang ___?", "options": ["panas", "ceria", "sejuk", "gementar"], "a": 2},
        {"q": "Warna api yang merah terang menggambarkan kumpulan warna ___?", "options": ["panas", "sejuk", "neutral", "lembut"], "a": 0},
        {"q": "Pasu bunga pasu bunga sebenar di taman ialah bentuk ___?", "options": ["ilusi", "konkrit", "maya", "lukisan"], "a": 1},
        {"q": "Bentuk awan di dalam sekeping lukisan ialah bentuk ___?", "options": ["konkrit", "nyata", "fizikal", "ilusi"], "a": 3},
        {"q": "Garisan lurus tegak yang berdiri memberi kesan ___?", "options": ["lemah", "teguh", "beralun", "goyang"], "a": 1},
        {"q": "Permukaan cermin tingkap kaca mempunyai jalinan yang ___?", "options": ["kasar", "tajam", "licin", "berbulu"], "a": 2},
        {"q": "Permukaan luar kulit durian mempunyai jalinan yang ___?", "options": ["licin", "kasar", "lembut", "rata"], "a": 1},
        {"q": "Objek di bahagian hadapan lukisan mestilah dilukis lebih ___?", "options": ["kecil", "kabur", "besar", "tinggi"], "a": 2},
        {"q": "Objek di bahagian belakang lukisan mestilah dilukis lebih ___?", "options": ["besar", "kecil", "jelas", "lebar"], "a": 1},
        {"q": "Warna merah diklasifikasikan ke dalam kategori warna ___?", "options": ["asas", "sekunder", "tertiar", "neutral"], "a": 0},
        {"q": "Warna hijau diklasifikasikan ke dalam kategori warna ___?", "options": ["asas", "sekunder", "tertiar", "neutral"], "a": 1},
        {"q": "Kawasan lantai yang menempatkan pameran arca ialah ruang ___?", "options": ["ilusi", "nyata", "lukisan", "minda"], "a": 1},
        {"q": "Unsur seni paling asas sebelum mula menjadi garisan ialah ___?", "options": ["rupa", "warna", "titik", "jalinan"], "a": 2},
        {"q": "Roda tayar basikal yang bulat mempunyai asas rupa ___?", "options": ["organik", "geometri", "bebas", "abstrak"], "a": 1},
        {"q": "Jalinan bunga tayar basikal yang tebal ialah jalinan ___?", "options": ["tampak", "sentuh", "ilusi", "warna"], "a": 1},
        {"q": "Jarak kekosongan di antara dua batang pokok dinamakan ___?", "options": ["bentuk", "jalinan", "garisan", "ruang"], "a": 3},
        {"q": "Cahaya matahari di dalam lukisan lazimnya diwarnakan ___?", "options": ["biru", "kuning", "ungu", "hitam"], "a": 1},
        {"q": "Unsur seni yang memanjang dan mempunyai arah haluan ialah ___?", "options": ["rupa", "bentuk", "garisan", "ruang"], "a": 2}
    ],

    "prinsip_rekaan": [
        {"q": "Susunan unsur yang sama berat di kiri dan kanan dinamakan ___?", "options": ["kontra", "imbangan", "harmoni", "kesatuan"], "a": 1},
        {"q": "Imbangan yang sama tepat di kiri dan kanan ialah imbangan ___?", "options": ["asimetri", "simetri", "berpusat", "sisi"], "a": 1},
        {"q": "Imbangan yang tidak sama rupa tetapi kekal stabil ialah imbangan ___?", "options": ["simetri", "asimetri", "sepadan", "tepat"], "a": 1},
        {"q": "Unsur sangat berbeza yang diletakkan bersama dipanggil ___?", "options": ["harmoni", "kesatuan", "kontra", "penegasan"], "a": 2},
        {"q": "Tulisan hitam berlawanan dengan kertas putih mewujudkan kesan ___?", "options": ["harmoni", "ritma", "imbangan", "kontra"], "a": 3},
        {"q": "Bahagian paling menonjol di dalam sesebuah karya dinamakan ___?", "options": ["kepelbagaian", "penegasan", "harmoni", "imbangan"], "a": 1},
        {"q": "Fungsi utama prinsip penegasan adalah untuk menarik ___?", "options": ["perhatian", "minat", "simpati", "kemarahan"], "a": 0},
        {"q": "Unsur yang berulang-ulang mewujudkan ritma dan ___?", "options": ["kekakuan", "ketenangan", "pergerakan", "kesatuan"], "a": 2},
        {"q": "Susunan unsur yang sangat teratur dan tenang dipanggil ___?", "options": ["kontra", "kepelbagaian", "harmoni", "penegasan"], "a": 2},
        {"q": "Penggunaan pelbagai unsur warna dan bentuk berbeza dipanggil ___?", "options": ["kesatuan", "kepelbagaian", "harmoni", "imbangan"], "a": 1},
        {"q": "Gabungan semua elemen membentuk tema yang lengkap dinamakan ___?", "options": ["kontra", "kesatuan", "ritma", "penegasan"], "a": 1},
        {"q": "Corak garisan ombak yang dilukis berulang menghasilkan kesan ___?", "options": ["imbangan", "kesatuan", "kontra", "ritma"], "a": 3},
        {"q": "Rupa kepak rama-rama menunjukkan ciri imbangan ___?", "options": ["simetri", "asimetri", "kepelbagaian", "kontra"], "a": 0},
        {"q": "Objek gergasi di tengah objek kerdil menghasilkan kesan ___?", "options": ["harmoni", "kesatuan", "penegasan", "imbangan"], "a": 2},
        {"q": "Warna yang bersebelahan dalam carta roda warna ialah warna ___?", "options": ["penggenap", "kontra", "harmoni", "neutral"], "a": 2},
        {"q": "Warna yang bertentangan dalam carta roda warna dipanggil warna ___?", "options": ["asas", "sekunder", "harmoni", "penggenap"], "a": 3},
        {"q": "Warna penggenap sangat sesuai untuk menghasilkan kesan visual ___?", "options": ["harmoni", "kesatuan", "kontra", "imbangan"], "a": 2},
        {"q": "Kekemasan anyaman tikar yang sekata menunjukkan gaya ___?", "options": ["harmoni", "kontra", "kepelbagaian", "penegasan"], "a": 0},
        {"q": "Karya yang serabut dan bercelaru telah hilang sifat ___?", "options": ["kepelbagaian", "kesatuan", "kontra", "penegasan"], "a": 1},
        {"q": "Titik hujan lebat yang dilukis miring menunjukkan kesan ___?", "options": ["imbangan", "kekakuan", "harmoni", "pergerakan"], "a": 3},
        {"q": "Poster yang baik mesti ada tulisan tajuk bersaiz besar sebagai ___?", "options": ["harmoni", "penegasan", "kesatuan", "imbangan"], "a": 1},
        {"q": "Arca ukiran kayu yang boleh berdiri tegak mempunyai prinsip ___?", "options": ["imbangan", "kontra", "ritma", "pergerakan"], "a": 0},
        {"q": "Penggunaan garisan tebal dan garisan nipis secara serentak mewujudkan ___?", "options": ["kesatuan", "harmoni", "kepelbagaian", "imbangan"], "a": 2},
        {"q": "Corak kotak hitam putih pada lantai papan dam mempunyai prinsip ___?", "options": ["kontra", "kepelbagaian", "harmoni", "penegasan"], "a": 2},
        {"q": "Anatomi muka manusia merupakan contoh ciptaan imbangan ___?", "options": ["simetri", "asimetri", "kontra", "kepelbagaian"], "a": 0},
        {"q": "Lukisan dahan pokok yang ditiup angin kencang menunjukkan kesan ___?", "options": ["kekakuan", "harmoni", "kesatuan", "pergerakan"], "a": 3},
        {"q": "Gubahan alam menggunakan warna biru dan hijau memberi kesan ___?", "options": ["harmoni", "kontra", "penegasan", "kepelbagaian"], "a": 0},
        {"q": "Rupa bulat merah diletakkan di celah segi tiga biru mewujudkan prinsip ___?", "options": ["harmoni", "kesatuan", "kontra", "imbangan"], "a": 2},
        {"q": "Prinsip kesatuan menjadikan keseluruhan karya kelihatan lebih ___?", "options": ["selerak", "bercelaru", "kemas", "bosan"], "a": 2},
        {"q": "Susunan dahan pokok hutan yang tidak sekata ialah imbangan ___?", "options": ["simetri", "asimetri", "berpusat", "sekata"], "a": 1},
        {"q": "Susunan garisan panjang yang melingkar mencipta kesan ___?", "options": ["imbangan", "kontra", "ritma", "kesatuan"], "a": 2},
        {"q": "Pembuatan wau bulan tradisional mempunyai rekaan yang sangat ___?", "options": ["simetri", "asimetri", "bebas", "bercelaru"], "a": 0},
        {"q": "Fokus sasaran mata apabila memandang ke arah lukisan dikenali sebagai ___?", "options": ["harmoni", "penegasan", "kesatuan", "kepelbagaian"], "a": 1},
        {"q": "Perbezaan kerdil dan gergasi yang amat ketara menghasilkan prinsip ___?", "options": ["kesatuan", "harmoni", "imbangan", "kontra"], "a": 3},
        {"q": "Tembikar pasu labu sayong mempunyai bentuk rupa yang ___?", "options": ["simetri", "asimetri", "abstrak", "bebas"], "a": 0},
        {"q": "Karya lukisan tanpa sebarang kepelbagaian akan kelihatan sangat ___?", "options": ["menarik", "bosan", "ceria", "harmoni"], "a": 1},
        {"q": "Prinsip kesatuan akan menyatukan semua corak menjadi satu ___?", "options": ["warna", "rupa", "tema", "garisan"], "a": 2},
        {"q": "Warna daun hijau dicampur kuning merupakan gabungan yang ___?", "options": ["harmoni", "kontra", "penegasan", "neutral"], "a": 0},
        {"q": "Kepelbagaian corak yang terlampau banyak akan nampak berserabut dan ___?", "options": ["cantik", "kemas", "menarik", "kaku"], "a": 3},
        {"q": "Jalinan kapas lembut bersebelahan jalinan batu kasar mewujudkan ___?", "options": ["harmoni", "kesatuan", "kontra", "imbangan"], "a": 2},
        {"q": "Arah laluan mata melihat ke dalam lukisan dipanggil ___?", "options": ["imbangan", "pergerakan", "harmoni", "penegasan"], "a": 1},
        {"q": "Titik penegasan utama pada sesebuah lukisan potret manusia biasanya ialah ___?", "options": ["baju", "latar", "wajah", "tangan"], "a": 2},
        {"q": "Pengulangan rupa kotak segi empat yang banyak secara berderet menghasilkan ___?", "options": ["kontra", "ritma", "kesatuan", "imbangan"], "a": 1},
        {"q": "Warna harmoni di suasana taman mewujudkan perasaan yang ___?", "options": ["gelisah", "marah", "takut", "tenang"], "a": 3},
        {"q": "Kepelbagaian ton warna akan menambah kecantikan dan nilai ___?", "options": ["estetik", "komersial", "ekonomi", "sejarah"], "a": 0},
        {"q": "Reka bentuk ikon logo syarikat mesti mempunyai daya ___?", "options": ["saing", "tahan", "tarikan", "upaya"], "a": 2},
        {"q": "Penegasan tulisan teks pada kain rentang membantu penyampaian ___?", "options": ["mesej", "lukisan", "bahan", "media"], "a": 0},
        {"q": "Keseimbangan karya wujud dari segi pandangan visual dan berat ___?", "options": ["minda", "fizikal", "dalaman", "ilusi"], "a": 1},
        {"q": "Kontra tona warna yang paling menonjol dan kuat ialah warna hitam dan ___?", "options": ["biru", "merah", "kuning", "putih"], "a": 3},
        {"q": "Secara umumnya, prinsip rekaan bertugas mengawal dan menyusun semua unsur ___?", "options": ["seni", "sains", "bahan", "media"], "a": 0}
    ],

    "media_bahan": [
        {"q": "Bahan dan alat yang digunakan oleh pelukis dipanggil ___?", "options": ["teknik", "media", "karya", "gaya"], "a": 1},
        {"q": "Pensel, krayon, dan serbuk arang tergolong dalam media ___?", "options": ["basah", "kering", "cecair", "lekit"], "a": 1},
        {"q": "Cat poster, cat air, dan akrilik cair tergolong dalam media ___?", "options": ["basah", "kering", "pepejal", "serbuk"], "a": 0},
        {"q": "Media lukisan hitam pekat yang diperbuat dari kayu terbakar ialah ___?", "options": ["pensel", "krayon", "arang", "pen"], "a": 2},
        {"q": "Sebilangan media basah perlu dicairkan menggunakan air atau ___?", "options": ["minyak", "gam", "lilin", "dakwat"], "a": 0},
        {"q": "Alat sapuan berbulu yang digunakan untuk mewarna cat air ialah ___?", "options": ["pena", "berus", "pisau", "span"], "a": 1},
        {"q": "Bekas lekuk plastik yang digunakan untuk membancuh cat dipanggil ___?", "options": ["kanvas", "palet", "baldi", "cawan"], "a": 1},
        {"q": "Pastel warna dan krayon memiliki sifat kalis air kerana ia ___?", "options": ["kering", "berminyak", "keras", "cair"], "a": 1},
        {"q": "Teknik mencantum dan menampal cebisan kertas berwarna dinamakan ___?", "options": ["montaj", "kolaj", "capan", "resis"], "a": 1},
        {"q": "Teknik menolak sapuan cat air menggunakan contengan lilin ialah ___?", "options": ["resis", "kolaj", "gosokan", "percikan"], "a": 0},
        {"q": "Teknik capan blok lino getah yang disapu dakwat basah dipanggil ___?", "options": ["lukisan", "catan", "cetakan", "montaj"], "a": 2},
        {"q": "Semburan warna cecair secara rawak menggunakan berus gigi dipanggil ___?", "options": ["capan", "percikan", "gosokan", "resis"], "a": 1},
        {"q": "Memindahkan corak syiling ke atas kertas menggunakan krayon dipanggil ___?", "options": ["gosokan", "capan", "stensil", "titikan"], "a": 0},
        {"q": "Guntingan imej gambar dari surat khabar yang ditampal bersusun dipanggil ___?", "options": ["kolaj", "montaj", "mozaik", "resis"], "a": 1},
        {"q": "Media kayu berteras grafit yang paling asas untuk murid melakar ialah ___?", "options": ["pen", "arang", "pensel", "krayon"], "a": 2},
        {"q": "Teknik menghasilkan imej muka dari bintik susunan mata pen dipanggil ___?", "options": ["garisan", "titikan", "gosokan", "resis"], "a": 1},
        {"q": "Bahan cecair lekit yang digunakan untuk melekatkan perca kertas kolaj ialah ___?", "options": ["air", "minyak", "gam", "lilin"], "a": 2},
        {"q": "Alat kayu tajam digunakan untuk menggores sisa krayon gelap dinamakan ___?", "options": ["pembaris", "pisau", "lidi", "gunting"], "a": 2},
        {"q": "Teknik mengapungkan cat nipis di atas baldi air lalu dicetak dipanggil ___?", "options": ["pualaman", "cetakan", "resis", "capan"], "a": 0},
        {"q": "Mewarna kain t-shirt putih menggunakan teknik balutan ikat dan ___?", "options": ["guntingan", "celupan", "tampalan", "semburan"], "a": 1},
        {"q": "Kertas tebal yang dilubangkan sebagai acuan semburan cat dipanggil ___?", "options": ["stensil", "blok", "kanvas", "palet"], "a": 0},
        {"q": "Media cat sekolah yang pekat dan sangat terang warnanya ialah cat ___?", "options": ["air", "minyak", "poster", "akrilik"], "a": 2},
        {"q": "Alat keluli berpemegang yang digunakan untuk memotong kertas nipis ialah ___?", "options": ["pisau", "gunting", "pembaris", "gergaji"], "a": 1},
        {"q": "Tanah liat lembut yang mudah dibentuk amat sesuai untuk aktiviti ___?", "options": ["catan", "lukisan", "arca", "cetakan"], "a": 2},
        {"q": "Menampal cebisan kertas pada rangka belon belon dikenali sebagai papier ___?", "options": ["mace", "colle", "art", "craft"], "a": 0},
        {"q": "Media warna mainan lembut seperti doh untuk aktiviti memodel dipanggil ___?", "options": ["plastisin", "tanah liat", "lilin", "gipsum"], "a": 0},
        {"q": "Membersihkan palet bancuhan yang kotor sangat memerlukan basuhan ___?", "options": ["minyak", "air", "turpentin", "alkohol"], "a": 1},
        {"q": "Cat basah moden kalis air yang sangat pantas untuk kering dipanggil cat ___?", "options": ["air", "poster", "minyak", "akrilik"], "a": 3},
        {"q": "Teknik menyapu warna tanpa menggunakan campuran air dikenali sebagai teknik ___?", "options": ["basah", "lembap", "kering", "legap"], "a": 2},
        {"q": "Catan kertas lembab disapu dengan warna berus basah dipanggil basah atas ___?", "options": ["kering", "basah", "lembap", "rata"], "a": 1},
        {"q": "Jalinan tulang daun yang gugur sangat sesuai dirakam menggunakan teknik ___?", "options": ["capan", "gosokan", "resis", "kolaj"], "a": 1},
        {"q": "Alat penggelek silinder untuk meratakan dakwat ke atas lino dipanggil ___?", "options": ["berus", "roller", "spatula", "pisau"], "a": 1},
        {"q": "Sapuan media cat air tebal mestilah menggunakan kertas ___?", "options": ["akhbar", "minyak", "lukisan", "tisu"], "a": 2},
        {"q": "Batang lidi buluh yang diraut halus sering digunakan merangka rangka ___?", "options": ["gasing", "wau", "tembikar", "bakul"], "a": 1},
        {"q": "Barangan kotak kadbod terpakai sangat sesuai dipotong dan dijadikan bahan binaan ___?", "options": ["komersial", "kitar", "buangan", "hiasan"], "a": 1},
        {"q": "Penutup botol buangan yang dicelup warna boleh dicap sebagai bahan ___?", "options": ["resis", "kolaj", "capan", "gosokan"], "a": 2},
        {"q": "Serbuk arang yang digosok dengan jari memberikan kesan kelabu yang ___?", "options": ["cerah", "gelap", "putih", "berwarna"], "a": 1},
        {"q": "Ketulan span mandian berlubang sering digunakan guru dalam resis teknik ___?", "options": ["gosokan", "kolaj", "montaj", "capan"], "a": 3},
        {"q": "Untuk melukis secara kekal di atas kain kanvas, media paling sesuai ialah cat ___?", "options": ["air", "poster", "minyak", "krayon"], "a": 2},
        {"q": "Garisan warna lilin krayon secara magisnya akan sentiasa menolak cat ___?", "options": ["minyak", "air", "akrilik", "poster"], "a": 1},
        {"q": "Semburan teknik percikan yang halus memerlukan alat berus gigi dan ___?", "options": ["sikat", "gunting", "pembaris", "pisau"], "a": 0},
        {"q": "Sapuan cat pekat dan tebal yang menutupi keseluruhan lapisan bawah dipanggil ___?", "options": ["lut sinar", "lut cahaya", "legap", "cair"], "a": 2},
        {"q": "Cecair khas pelarut untuk membersih atau mencairkan cat minyak dipanggil ___?", "options": ["air", "minyak tanah", "turpentin", "alkohol"], "a": 2},
        {"q": "Palet plastik yang kotor wajib dicuci selepas selesai guna agar ia sentiasa ___?", "options": ["kotor", "bersih", "basah", "rosak"], "a": 1},
        {"q": "Kesilapan melakar menggunakan sebatang pensel dengan mudahnya boleh dipadam guna ___?", "options": ["pembaris", "pemadam", "kertas", "air"], "a": 1},
        {"q": "Lukisan yang menggunakan media cecair basah perlukan sedikit masa untuk ___?", "options": ["kering", "cair", "hilang", "keras"], "a": 0},
        {"q": "Kertas majalah dan kertas warna merupakan ramuan utama untuk menghasilkan gubahan ___?", "options": ["capan", "resis", "kolaj", "montaj"], "a": 2},
        {"q": "Pisau pemotong besi yang tajam digunakan untuk memotong kadbod tebal secara ___?", "options": ["lurus", "melengkung", "beralun", "rawak"], "a": 0},
        {"q": "Peraturan utama ketika menggunakan gunting di dalam kelas ialah aspek keselamatan mesti ___?", "options": ["diabai", "dijaga", "dilupa", "dilihat"], "a": 1},
        {"q": "Penggunaan alat dan media lukisan yang tepat akan menjadikan karya lebih ___?", "options": ["buruk", "bosan", "cantik", "kaku"], "a": 2}
    ],
    
"lukisan_dan_catan": [
        {"q": "Proses menggambar menggunakan alatan media kering dinamakan ___?", "options": ["catan", "cetakan", "lukisan", "arca"], "a": 2},
        {"q": "Proses menghasilkan gambar berwarna menggunakan media basah dinamakan ___?", "a": "catan"},
        {"q": "Teknik menggunakan garisan bersilang rapat dipanggil silang ___?", "options": ["sengit", "pangkah", "lurus", "titik"], "a": 1},
        {"q": "Teknik bauran dilakukan dengan cara ___ kesan pensel agar nampak lembut?", "a": "gosok"},
        {"q": "Gred pensel yang cerah dan sesuai untuk lakaran asas awal ialah ___?", "options": ["2b", "hb", "4b", "6b"], "a": 1},
        {"q": "Pensel siri B seperti 4B mempunyai mata grafit yang lebih tebal dan ___?", "a": "gelap"},
        {"q": "Cat air (watercolour) mempunyai sifat jernih yang dipanggil lut ___?", "options": ["legap", "sinar", "cahaya", "kabur"], "a": 1},
        {"q": "Cat poster mempunyai sifat tebal, pekat dan tidak telus cahaya iaitu ___?", "a": "legap"},
        {"q": "Warna basah yang disapu atas kertas basah dipanggil basah atas ___?", "options": ["kering", "lembap", "basah", "legap"], "a": 2},
        {"q": "Berus yang dicelup sedikit warna dan disapu atas kertas kering dipanggil ___ atas kering?", "a": "kering"},
        {"q": "Kesan pantulan cahaya paling terang pada sesuatu objek dinamakan ___?", "options": ["bayang", "gelap", "kilauan", "ton"], "a": 2},
        {"q": "Objek yang menghalang arah laluan cahaya akan menghasilkan bayang-___?", "a": "bayang"},
        {"q": "Objek jarak dekat perlu dilukis dengan saiz yang lebih ___?", "options": ["besar", "kecil", "kabur", "sama"], "a": 0},
        {"q": "Objek jarak jauh perlu dilukis dengan saiz yang lebih ___?", "a": "kecil"},
        {"q": "Lukisan benda kaku yang tersusun seperti raga buah dipanggil alam ___?", "options": ["benda", "semula jadi", "fantasi", "maya"], "a": 0},
        {"q": "Cat minyak sangat lambat kering dan memerlukan pelarut khas seperti ___?", "a": "turpentin"},
        {"q": "Teknik lukisan berbentuk bintik-bintik menggunakan mata pen dinamakan ___?", "options": ["garisan", "titikan", "gosokan", "lorekan"], "a": 1},
        {"q": "Berus cat jenis bulat runcing amat sesuai untuk melukis garisan yang ___?", "a": "halus"},
        {"q": "Berus cat jenis rata (flat) sesuai menyapu warna di kawasan kertas yang ___?", "options": ["sempit", "luas", "kasar", "tebal"], "a": 1},
        {"q": "Garisan panduan berpetak untuk membesarkan lukisan asal dipanggil garisan ___?", "a": "grid"},
        {"q": "Lukisan yang memaparkan gambaran wajah figura manusia dipanggil lukisan ___?", "options": ["benda", "pemandangan", "potret", "abstrak"], "a": 2},
        {"q": "Karya yang memaparkan keindahan alam semula jadi dinamakan catan ___?", "a": "pemandangan"},
        {"q": "Titik di mana semua garisan pandangan mengecil dan hilang dipanggil titik ___?", "options": ["pusat", "lenyap", "mula", "akhir"], "a": 1},
        {"q": "Berus lukisan yang kotor cat poster perlu dicuci bersih menggunakan ___?", "a": "air"},
        {"q": "Warna cat air akan hilang kesan lut sinarnya jika dicampurkan terlalu banyak cat ___?", "options": ["hitam", "kuning", "putih", "biru"], "a": 2},
        {"q": "Palet perlulah dibasuh dengan segera sebelum sisa cat basah menjadi ___?", "a": "keras"},
        {"q": "Mewarna langit awan sangat serasi menggunakan teknik basah atas ___?", "options": ["kering", "basah", "lembap", "rata"], "a": 1},
        {"q": "Kesan terang dan gelap kawasan bayang pada objek mewujudkan nilai ___?", "a": "ton"},
        {"q": "Garisan berlingkar bebas untuk menghasilkan ton gelap lukisan dipanggil ___?", "options": ["titikan", "contengan", "lorekan", "silang pangkah"], "a": 1},
        {"q": "Campuran cat kuning dan biru pada lukisan pokok menghasilkan warna ___?", "a": "hijau"},
        {"q": "Kertas untuk catan air mesti mempunyai tekstur yang lebih padat dan ___?", "options": ["kasar", "tebal", "nipis", "keras"], "a": 1},
        {"q": "Kesilapan bentuk semasa membuat lakaran pensel boleh dihilangkan guna ___?", "a": "pemadam"},
        {"q": "Arah sinaran cahaya akan menentukan di mana letaknya bayang-bayang ___?", "options": ["kekal", "maya", "gugur", "nyata"], "a": 2},
        {"q": "Susunan kedudukan barangan di dalam sesebuah karya lukisan dikenali sebagai ___?", "a": "komposisi"},
        {"q": "Sedikit warna hitam dicampur pada cat asli untuk mewarnakan bahagian yang ___?", "options": ["terang", "gelap", "pudar", "jelas"], "a": 1},
        {"q": "Pecahan ruang dalam lukisan ada latar depan, latar tengah, dan latar ___?", "a": "belakang"},
        {"q": "Pen teknikal berdakwat hitam sangat popular digunakan dalam penghasilan seni ___?", "options": ["catan", "cetakan", "lukisan", "kolaj"], "a": 2},
        {"q": "Sentiasa tukar air basuhan berus di dalam cawan supaya catan tidak menjadi ___?", "a": "kotor"},
        {"q": "Untuk mengekalkan kilauan pantulan, biarkan kawasan kertas tersebut kekal berwarna ___?", "options": ["kuning", "hitam", "putih", "biru"], "a": 2},
        {"q": "Memegang pen dengan tegak pada kertas akan menghasilkan lukisan garisan yang ___?", "a": "tajam"},
        {"q": "Jarak ilusi mendalam yang dicipta dalam seni gambar 2D dinamakan ___?", "options": ["ruang", "ton", "perspektif", "imbangan"], "a": 2},
        {"q": "Media arang menghasilkan kesan lukisan yang sangat pekat, berdebu, dan ___?", "a": "hitam"},
        {"q": "Berus basah yang ditinggalkan terendam menghala ke bawah lantai akan cepat ___?", "options": ["kering", "patah", "rosak", "bersih"], "a": 2},
        {"q": "Lukisan jenis moden yang tidak mempunyai rupa objek yang jelas dipanggil seni ___?", "a": "abstrak"},
        {"q": "Alat pelindung yang dipakai pada baju semasa mencatan dipanggil ___?", "options": ["topi", "tuala", "apron", "sarung tangan"], "a": 2},
        {"q": "Cat akrilik jauh lebih cepat mengering berbanding media cat ___?", "a": "minyak"},
        {"q": "Penggunaan kumpulan warna sejuk banyak menghasilkan suasana catan yang rasa ___?", "options": ["panas", "marah", "tenang", "ceria"], "a": 2},
        {"q": "Mengekalkan lorekan ton pensel yang sekata memerlukan tahap kawalan ___ tangan yang baik.", "a": "tekanan"},
        {"q": "Lukisan cantik yang siap dibingkaikan kebiasaannya akan dipamerkan di ___ seni.", "options": ["muzium", "kedai", "galeri", "rumah"], "a": 2},
        {"q": "Aktiviti menghasilkan karya catan amat melatih kesabaran jiwa dan tahap ___ fikiran.", "a": "fokus"}
    ],

    "gosokan_dan_cetakan": [
        {"q": "Memindahkan jalinan sentuh duit syiling menggunakan krayon dipanggil teknik ___?", "options": ["gosokan", "capan", "cetakan", "lakaran"], "a": 0},
        {"q": "Dua jenis alat media yang paling lazim untuk membuat gosokan ialah krayon dan ___?", "a": "pensel"},
        {"q": "Daun kering amat sesuai untuk bahan gosokan kerana garisan uratnya agak ___?", "options": ["licin", "kasar", "lembut", "lurus"], "a": 1},
        {"q": "Gosokan di atas cermin kaca gagal terjadi kerana permukaan cermin berjalinan ___?", "a": "licin"},
        {"q": "Teknik mengecap blok berdakwat atau berwarna ke atas kertas dipanggil ___?", "options": ["cetakan", "gosokan", "catan", "kolaj"], "a": 0},
        {"q": "Teknik cetakan membolehkan karya imej yang sama dihasilkan berulang kali dengan ___?", "a": "pantas"},
        {"q": "Alat penggelek silinder untuk meratakan dakwat ke atas lino dinamakan ___?", "options": ["berus", "span", "roller", "pisau"], "a": 2},
        {"q": "Belahan kentang yang dikorek dan ditebuk coraknya boleh dijadikan sebuah ___ cetakan.", "a": "blok"},
        {"q": "Cetakan paling pantas tanpa memerlukan alatan tambahan ialah cetakan cap ___?", "options": ["kaki", "tangan", "jari", "siku"], "a": 2},
        {"q": "Cetakan stensil menapis warna cat menyembur melalui kertas tebal yang telah ___?", "a": "ditebuk"},
        {"q": "Cetakan getah lino memerlukan alat ukir besi (carving tool) yang mata ukirnya amat ___?", "options": ["tumpul", "tajam", "tebal", "kasar"], "a": 1},
        {"q": "Cetakan menggunakan kepingan blok kayu adalah contoh teknik cetak yang paling ___?", "a": "tua"},
        {"q": "Dakwat cetakan pada blok wajib disapu rata agar corak yang terhasil sangat ___?", "options": ["jelas", "kabur", "pudar", "gelap"], "a": 0},
        {"q": "Cetakan menggunakan bingkai saring sutera sangat dikomersialkan untuk mencetak ___?", "a": "baju"},
        {"q": "Warna cat perlu diasingkan pada palet supaya hasil capan cetakan tidak nampak ___?", "options": ["terang", "comot", "jelas", "cantik"], "a": 1},
        {"q": "Cetakan kolagraf menggabungkan pelbagai bahan yang dibina menggunakan teknik ___?", "a": "tampalan"},
        {"q": "Proses pergerakan menekan blok berwarna ke atas kain atau kertas dinamakan ___?", "options": ["gosokan", "capan", "lakaran", "lorekan"], "a": 1},
        {"q": "Untuk memastikan hasil cetakan melekat elok, tekanan tangan dari atas mestilah ___?", "a": "kuat"},
        {"q": "Cetakan timbul (relief) mengambil dakwat hanya pada bahagian permukaan yang ___?", "options": ["rendah", "dalam", "tinggi", "rata"], "a": 2},
        {"q": "Cetakan benam (intaglio) meresapkan dakwat masuk di bahagian celah garisan yang ___?", "a": "dalam"},
        {"q": "Keratan rentas batang pisang basah boleh dicap sebagai unsur jalinan bahan ___?", "options": ["sintetik", "buatan", "alam", "mesin"], "a": 2},
        {"q": "Warna cat basah jangan digaul terlalu cair agar rupa cetakan imejnya tidak ___?", "a": "kembang"},
        {"q": "Gosokan krayon berlainan warna berlapis-lapis akan mencipta gaya visual yang ___?", "options": ["membosankan", "cantik", "kotor", "gelap"], "a": 1},
        {"q": "Hati-hati! Tekanan tangan yang terlalu melampau masa menggosok akan menyebabkan kertas ___?", "a": "koyak"},
        {"q": "Bagi hasil capan seragam, kertas mestilah diletakkan di atas lantai atau meja yang ___?", "options": ["kasar", "condong", "rata", "bergerak"], "a": 2},
        {"q": "Huruf abjad 'B' yang diukir pada blok lino wajib diukir secara ___ agar cetakannya betul.", "a": "terbalik"},
        {"q": "Cetakan menggunakan hirisan buah bendi mudah basi kerana ia terbuat daripada sayur ___?", "options": ["tahan lama", "plastik", "segar", "kering"], "a": 2},
        {"q": "Kesan corak jalinan pada tapak kasut sukan sangat ideal dirakam melalui teknik ___?", "a": "gosokan"},
        {"q": "Penyapuan sekatan lilin cair pada kain skrin sutera dinamakan cetakan ___ sutera.", "options": ["benam", "saring", "timbul", "lino"], "a": 1},
        {"q": "Gosokan ringkas yang menggunakan satu tona warna krayon pekat sahaja dinamakan ___?", "a": "monokrom"},
        {"q": "Cetakan seni asli terhad bertandatangan pelukis asalnya biasanya dijual dengan harga ___?", "options": ["rendah", "tinggi", "murah", "biasa"], "a": 1},
        {"q": "Murid dilarang bergurau semasa memegang pengukir lino demi mematuhi langkah ___?", "a": "keselamatan"},
        {"q": "Sisa tikar getah bermotif ialah contoh bahan kreatif sekolah yang sesuai menggantikan blok ___?", "options": ["kayu", "batu", "lino", "kaca"], "a": 2},
        {"q": "Cetakan pualaman terhasil daripada teknik memindahkan cat minyak di atas permukaan ___?", "a": "air"},
        {"q": "Gosokan bertujuan merakam jalinan manakala teknik cetakan berfungsi membanyakkan ___?", "options": ["asal", "salinan", "harga", "bahan"], "a": 1},
        {"q": "Corak motif bunga berulang di atas sehelai langsir rumah dihasilkan melalui proses mesin ___?", "a": "cetak"},
        {"q": "Pelepah betik yang dipotong secara serong akan tercetak memaparkan bentuk ___?", "options": ["bulat", "bujur", "segi empat", "segi tiga"], "a": 1},
        {"q": "Berus span bulat diguna untuk mengecap warna melalui lubang motif potongan ___?", "a": "stensil"},
        {"q": "Semasa menggosok krayon, dua-dua belah kertas dan bahan bawahnya mesti dipegang ___?", "options": ["longgar", "kemas", "jauh", "condong"], "a": 1},
        {"q": "Blok lino yang tamat digunakan wajib dibasuh sebersihnya dari sebarang sisa pewarna ___?", "a": "dakwat"},
        {"q": "Capan kotak berulang dengan jarak susunan tersusun membentuk prinsip seni ___?", "options": ["ritma", "kontra", "penegasan", "kesatuan"], "a": 0},
        {"q": "Sebaiknya hampar surat khabar dahulu di meja agar permukaan meja tidak dihinggapi ___?", "a": "warna"},
        {"q": "Penggelek roller dakwat disapu-sapu pada cermin kaca leper dahulu agar pusingan teksturnya ___?", "options": ["kasar", "tebal", "rata", "kembang"], "a": 2},
        {"q": "Ketika melakukan capan blok, kawal tangan elakkan blok bergoyang agar hasilnya tidak ___?", "a": "senget"},
        {"q": "Cetakan yang dihasilkan kilang mesin jauh lebih terperinci dan tampak lebih ___?", "options": ["tradisional", "moden", "kasar", "kabur"], "a": 1},
        {"q": "Media ubi kentang sangat digemari kerana tekstur isinya lembut dan amat mudah di___?", "a": "ukir"},
        {"q": "Jalinan tampak pada catan kertas dinding adalah mustahil untuk dirakam menggunakan ___?", "options": ["capan", "lukisan", "gosokan", "fotografi"], "a": 2},
        {"q": "Cat akrilik pekat tanpa air akan menempel dan kering di atas kertas lukisan dengan agak ___?", "a": "cepat"},
        {"q": "Melakukan ukiran cetakan tradisional sangat mendidik jiwa menanam sifat sabar dan ketelitian ___?", "options": ["kerja", "main", "bercakap", "melihat"], "a": 0},
        {"q": "Peliharalah pengetahuan seni visual cetakan agar kita menghargai keindahan gubahan ___?", "a": "grafik"}
    ],

    "kolaj_dan_montaj": [
        {"q": "Teknik menghasilkan gambar dengan susunan menampal cebisan kertas dinamakan ___?", "options": ["montaj", "kolaj", "mozek", "capan"], "a": 1},
        {"q": "Kolaj selalunya menggunakan guntingan bahan buangan seperti helaian majalah dan kertas ___?", "a": "warna"},
        {"q": "Bahan gam cair sangat diperlukan untuk membolehkan perca bahan kolaj terus ___?", "options": ["kering", "melekat", "tercabut", "basah"], "a": 1},
        {"q": "Guntingan pelbagai gambar figura manusia di akhbar disusun menjadi komposisi dipanggil ___?", "a": "montaj"},
        {"q": "Montaj menyusun pelbagai gambar potong yang sudah mempunyai ___ penceritaan tersendiri.", "options": ["warna", "imej", "ton", "jalinan"], "a": 1},
        {"q": "Alat keluli dua bilah berpemegang yang tajam untuk mengerat kertas tebal ialah ___?", "a": "gunting"},
        {"q": "Berhati-hati pegang gunting semasa memotong agar jari tidak berdarah demi menjaga ___?", "options": ["kebersihan", "kecantikan", "keselamatan", "kepantasan"], "a": 2},
        {"q": "Cebisan perca kertas krep kolaj lazimnya akan dikoyak atau digunting menjadi saiz yang ___?", "a": "kecil"},
        {"q": "Susunan himpunan montaj kereta dan tayar boleh diangkat mewakili tema kenderaan atau ___?", "options": ["sukan", "pengangkutan", "alam", "bangunan"], "a": 1},
        {"q": "Untuk menghasilkan kolaj berasaskan alam semula jadi, gunakan bahan seperti daun dan ___?", "a": "ranting"},
        {"q": "Gambar ruang udara atau tanah lapang sesuai dijadikan sebagai kawasan latar belakang yang ___?", "options": ["kecil", "terhad", "besar", "sempit"], "a": 2},
        {"q": "Kolaj bijirin makanan mampu direka kreatif menggunakan bahan dapur kacang dan ___?", "a": "beras"},
        {"q": "Aktiviti memilih imej montaj yang tepat dari majalah amat melatih sel-sel rangsangan ___?", "options": ["mata", "tangan", "minda", "otot"], "a": 2},
        {"q": "Gaya kolaj mozek lebih mementingkan potongan cebisan kecil kertas berwarna berbentuk ___?", "a": "petak"},
        {"q": "Susunan cebisan perca kolaj yang dirempitkan rapat menampakkan nilai ton yang sangat ___?", "options": ["lemah", "pudar", "padat", "longgar"], "a": 2},
        {"q": "Sapuan cecair gam di belakang gambar tidak patut dicalit berlebihan agar kertas nipis tidak ___?", "a": "koyak"},
        {"q": "Menghasilkan sebuah poster kempen kemerdekaan di sekolah amat cocok menggunakan teknik ___?", "options": ["catan", "montaj", "kolaj", "gosokan"], "a": 1},
        {"q": "Tampalan himpunan serpihan perca kain kapas bermotif batik juga diiktiraf sebagai kraf ___?", "a": "kolaj"},
        {"q": "Kerja guntingan memotong lengkuk gambar susuk manusia memerlukan daya penglihatan yang ___?", "options": ["tajam", "teliti", "cepat", "kasar"], "a": 1},
        {"q": "Objek watak utama montaj mestilah sentiasa diletakkan dan ditampal di bahagian paling ___?", "a": "atas"},
        {"q": "Cecair pelekat likat warna putih yang amat kukuh bagi meresap cantuman kayu dikenali gam ___?", "options": ["kertas", "uhu", "pva", "cecair"], "a": 2},
        {"q": "Gambar potong majalah yang bercetak tajam rona warnanya mempunyai tahap resolusi yang ___?", "a": "tinggi"},
        {"q": "Kolaj dari serpihan kecil kulit cangkerang telur ayam mewujudkan kesan deria jalinan ___?", "options": ["tampak", "sentuh", "ilusi", "maya"], "a": 1},
        {"q": "Sebelum memulakan gam cebisan demi cebisan, murid dinasihat melukis asas garisan ___?", "a": "panduan"},
        {"q": "Sesuatu tema sukan dalam gubahan montaj perlu diselitkan dengan gambar kelengkapan atlet yang ___?", "options": ["biasa", "kasar", "sesuai", "berlawanan"], "a": 2},
        {"q": "Pembaris keluli besi boleh digunakan sebagai alat bantu mengoyak hujung kertas secara ___?", "a": "lurus"},
        {"q": "Penampalan gambar singa dan gajah digabungkan cantik membentuk diorama alam habitat ___?", "options": ["bandar", "liar", "air", "udara"], "a": 1},
        {"q": "Teknik kolaj gumpalan kertas tisu merah bulat boleh ditampal rimbun menjadi sejambak ___?", "a": "bunga"},
        {"q": "Lebihan cebisan keratan majalah kitar semula di atas meja dilarang dibuang sepah ke luar ___?", "options": ["tingkap", "meja", "tong", "bilik"], "a": 2},
        {"q": "Untuk penjimatan kos pameran, karya montaj disalin fotostat agar menjadi salinan rona ___?", "a": "hitam"},
        {"q": "Gambar objek potong saiz besar di latar hadapan berbanding belakang wujudkan ilusi ___?", "options": ["ruang", "bentuk", "jalinan", "rupa"], "a": 0},
        {"q": "Gunakan berus cat leper bersih bagi memastikan pelekat rata tersapu pada ruang kertas yang ___?", "a": "luas"},
        {"q": "Kerja merenyuk dan kolaj berpasangan sangat menitikberatkan sifat permuafakatan dan rasa ___?", "options": ["bekerjasama", "dengki", "mementingkan diri", "kekerasan"], "a": 0},
        {"q": "Gubahan reka montaj poster iklan lazimnya menyertakan potongan imej seni corak muka ___?", "a": "huruf"},
        {"q": "Di alam milenial, montaj digital suntingan boleh direka pantas dengan klik fungsi aplikasi ___?", "options": ["mesin", "komputer", "kamera", "telefon"], "a": 1},
        {"q": "Sekiranya teringin menambah rona, biji kolaj beras putih boleh diwarnakan dengan campuran cat ___?", "a": "air"},
        {"q": "Koyakan carik jari kertas akhbar tanpa gunting memberikan hasil bentuk lilit garisan sisi yang ___?", "options": ["lurus", "kemas", "kasar", "licin"], "a": 2},
        {"q": "Pecahan keras cengkerang siput laut ditebuk gam menjadi kolaj mengeluarkan keritik bunyi apabila di___?", "a": "sentuh"},
        {"q": "Bagi memastikan kepingan pasir dan batu serbuk pantas gamnya perlu disapu lapisan gam agak ___?", "options": ["nipis", "tebal", "cair", "sedikit"], "a": 1},
        {"q": "Penghasilan karya montaj kreatif sama sekali tidak menguji daya kemahiran bakat pelukis ___?", "a": "tangan"},
        {"q": "Ruang latar belakang kolaj kosong akan disumbat rapat menggunakan sisa warna agar nampak ___?", "options": ["kosong", "besar", "penuh", "tebal"], "a": 2},
        {"q": "Awas jari yang basah berlumur gam lekit! Lap bersih pelekat meleleh dengan helaian helai ___?", "a": "tisu"},
        {"q": "Berhemah memilih potongan majalah gambar; gambar jelek seram buangan sangat berimej ___?", "options": ["positif", "negatif", "cantik", "baik"], "a": 1},
        {"q": "Jika merancang rupa bentuk objek bayang redup gelita, gunakan keratan potongan ton warna ___?", "a": "gelap"},
        {"q": "Binaan kreatif poster Malaysia merdeka sentiasa dihiasi kibaran panji megah bendera Jalur ___?", "options": ["putih", "hitam", "gemilang", "merah"], "a": 2},
        {"q": "Paparan kolaj yang direndam cuaca di luar dewan hujan lama-kelamaan basah akan mereput ___?", "a": "rosak"},
        {"q": "Kolaj keping tisu kuning diletak bertindan ke atas tisu merah mewujudkan efek campuran warna ___?", "options": ["lama", "asal", "baru", "pudar"], "a": 2},
        {"q": "Rutin teliti cermat memetik perca susun gam halus banyak merangsang otot pergerakan motor ___?", "a": "halus"},
        {"q": "Sesebuah karya seni montaj akan dikira johan dari sudut kecekapan guntingan dan kejelasan ___?", "options": ["gam", "kertas", "tema", "meja"], "a": 2},
        {"q": "Mencintai kraf kolaj sisa majalah mendidik anak menjaga tonggak ekosistem keseimbangan alam ___?", "a": "sekitar"}
    ],
    
"kraf_tradisional": [
        {"q": "Kraf anyaman tikar biasanya menggunakan daun ___?", "a": "mengkuang"},
        {"q": "Kraf melukis corak menggunakan lilin cair di atas kain dipanggil ___?", "a": "batik"},
        {"q": "Alat menakung lilin cair dalam pembuatan batik dinamakan ___?", "a": "canting"},
        {"q": "Seni membentuk tanah liat menjadi pasu dipanggil kraf ___?", "a": "tembikar"},
        {"q": "Tembikar sayong yang terkenal di Perak dipanggil ___ sayong?", "a": "labu"},
        {"q": "Proses membentuk corak pada permukaan kayu dinamakan ukiran ___?", "a": "kayu"},
        {"q": "Mainan tradisional yang berputar ligat di atas tanah lilitan tali ialah ___?", "a": "gasing"},
        {"q": "Permainan layang-layang tradisional Melayu di Kelantan dipanggil ___?", "a": "wau"},
        {"q": "Wau yang mempunyai rupa bentuk seperti bulan sabit ialah wau ___?", "a": "bulan"},
        {"q": "Kraf anyaman bakul tradisional banyak menggunakan bilah pokok ___?", "a": "buluh"},
        {"q": "Kain songket ditenun menggunakan benang kapas dan benang ___?", "a": "emas"},
        {"q": "Seni melipat kertas warisan Jepun dinamakan ___?", "a": "origami"},
        {"q": "Kraf kelarai merupakan corak pelbagai motif dalam seni ___?", "a": "anyaman"},
        {"q": "Motif pucuk rebung amat popular diukir pada ukiran dan ___?", "a": "tekstil"},
        {"q": "Tepian anyaman tikar dimatikan dengan lipatan agar tidak ___?", "a": "lerai"},
        {"q": "Warna asli daun mengkuang yang telah dikeringkan ialah kuning ___?", "a": "pucat"},
        {"q": "Pewarna kain batik dimatikan warnanya dengan serbuk silikat agar tidak ___?", "a": "luntur"},
        {"q": "Pembuatan tembikar tradisional dibakar di dalam ___ untuk mengeras?", "a": "tanur"},
        {"q": "Ukiran kayu berlubang yang tembus ke belakang dipanggil ukiran ___?", "a": "tebuk"},
        {"q": "Bahan utama pembuatan gasing tradisional biasanya ialah teras ___?", "a": "kayu"},
        {"q": "Tali gasing tradisional lazimnya dipintal dari sabut ___?", "a": "kelapa"},
        {"q": "Wau puyuh mendapat namanya daripada rupa bentuk seekor ___?", "a": "burung"},
        {"q": "Batik blok menggunakan cap logam yang dicelup ke dalam ___ cair?", "a": "lilin"},
        {"q": "Tembikar terenang sangat popular dihasilkan oleh masyarakat negeri ___?", "a": "pahang"},
        {"q": "Anyaman tikar Sarawak banyak menggunakan corak berwarna hitam dan ___?", "a": "merah"},
        {"q": "Senjata tradisional Melayu yang berluk dan berseni dipanggil ___?", "a": "keris"},
        {"q": "Sarung keris tradisional biasanya diukir indah menggunakan bahan ___?", "a": "kayu"},
        {"q": "Motif bunga mawar dalam kraf dinamakan motif ___?", "a": "flora"},
        {"q": "Motif ayam dan itik dalam kraf tangan dinamakan motif ___?", "a": "fauna"},
        {"q": "Proses anyaman katis tikar biasanya bermula dari bahagian ___?", "a": "tengah"},
        {"q": "Motif awan larat mempunyai rekaan garisan yang sentiasa ___?", "a": "bersambung"},
        {"q": "Tikar mengkuang dijemur di bawah cahaya matahari agar cepat ___?", "a": "kering"},
        {"q": "Seni tekat benang emas tradisional sangat popular di istana negeri ___?", "a": "perak"},
        {"q": "Alat bingkai penegang kain untuk tekat dipanggil pemidang ___?", "a": "kayu"},
        {"q": "Alat peraut buluh rangka wau dinamakan pisau ___?", "a": "raut"},
        {"q": "Benang sutera lembut digunakan untuk menenun kain ___?", "a": "sutera"},
        {"q": "Corak batik pelangi dihasilkan melalui teknik ikat dan ___?", "a": "celup"},
        {"q": "Hasil kraf raga rotan asalnya dicipta untuk tujuan membawa ___?", "a": "barang"},
        {"q": "Orang Asli mahir membuat kraf sumpitan untuk tujuan alat ___?", "a": "memburu"},
        {"q": "Tembikar labu sayong asli dibakar sehingga bertukar warna ___?", "a": "hitam"},
        {"q": "Anyaman tudung saji digunakan di dapur untuk menutup ___?", "a": "makanan"},
        {"q": "Bakul sia tradisional kaum Cina diperbuat dari buluh dan dicat ___?", "a": "merah"},
        {"q": "Kain pua kumbu merupakan tenunan tradisional masyarakat Iban di ___?", "a": "sarawak"},
        {"q": "Manik pelbagai warna dirangkai menjadi hiasan kraf kolar ___?", "a": "leher"},
        {"q": "Pembuatan ukiran kayu perlukan alat pengetuk yang bernama ___?", "a": "gandin"},
        {"q": "Seni khat kaligrafi pada kayu ukiran masjid berteraskan tulisan ___?", "a": "jawi"},
        {"q": "Alat tenun tradisional Melayu yang digerakkan guna kaki dipanggil kek ___?", "a": "tenun"},
        {"q": "Wau jala budi mempunyai corak ekor seperti hujung daun ___?", "a": "budi"},
        {"q": "Anyaman raga daun nipah sangat ringan tetapi sangat ___ dibawa?", "a": "kukuh"},
        {"q": "Industri seni kraf tangan banyak menjana sumber pendapatan ekonomi ___?", "a": "rakyat"}
    ],

    "apresiasi_seni": [
        {"q": "Proses menilai dan menghargai keindahan karya seni dinamakan ___?", "a": "apresiasi"},
        {"q": "Apresiasi membolehkan kita memahami maksud tersirat atau ___ pelukis?", "a": "mesej"},
        {"q": "Kita menghayati lukisan karya seni dengan menggunakan deria ___?", "a": "mata"},
        {"q": "Lukisan pemandangan yang cantik akan menimbulkan rasa ___ di hati?", "a": "gembira"},
        {"q": "Apresiasi seni dapat menajamkan minda dan daya ___ murid?", "a": "fikir"},
        {"q": "Warna merah terang pada lukisan lazimnya melambangkan rasa ___?", "a": "marah"},
        {"q": "Warna biru pada lukisan laut membawa perwakilan emosi yang ___?", "a": "tenang"},
        {"q": "Warna kuning dan jingga sering dikaitkan dengan simbol ___?", "a": "ceria"},
        {"q": "Menceritakan kelebihan lukisan rakan merupakan satu bentuk ___?", "a": "pujian"},
        {"q": "Mengkritik karya rakan mestilah sentiasa menggunakan bahasa yang ___?", "a": "sopan"},
        {"q": "Karya seni yang baik dinilai dari segi kekemasan dan tahap ___?", "a": "kreativiti"},
        {"q": "Setiap pelukis bebas mengekspresikan idea minda melalui karya ___?", "a": "seni"},
        {"q": "Memahami bahasa seni visual dapat meningkatkan tahap ___ murid?", "a": "kefahaman"},
        {"q": "Karya seni kraf tempatan sangat menonjolkan ciri budaya ___?", "a": "tradisional"},
        {"q": "Meniru seratus peratus lukisan orang lain dipanggil perbuatan ___?", "a": "plagiat"},
        {"q": "Apresiasi yang jujur melatih kita bersikap lebih ikhlas dan ___?", "a": "amanah"},
        {"q": "Mentertawakan lukisan yang kurang cantik adalah satu sikap yang ___?", "a": "buruk"},
        {"q": "Pelukis cat air tersohor Malaysia, Abdullah Ariff, suka melukis alam ___?", "a": "semulajadi"},
        {"q": "Tokoh seni kartun Malaysia, Datuk Lat, terkenal dengan siri Kampung ___?", "a": "boy"},
        {"q": "Karya seni arca sentiasa dinilai berdasarkan bentuk fizikal yang ___?", "a": "konkrit"},
        {"q": "Semasa sesi apresiasi diadakan, murid akan tampil bercakap di hadapan ___?", "a": "kelas"},
        {"q": "Penerangan karya haruslah disampaikan dengan nada suara yang ___?", "a": "jelas"},
        {"q": "Penonton sesi apresiasi amat digalakkan untuk menyoal soalan yang ___?", "a": "bernas"},
        {"q": "Menilai fungsi garisan lukisan bermaksud kita mengkaji unsur ___?", "a": "seni"},
        {"q": "Penggunaan bahan kitar semula dipuji kerana ia sangat mesra ___?", "a": "alam"},
        {"q": "Apresiasi membantu murid mengenali kekuatan dan ___ karya lukisannya?", "a": "kelemahan"},
        {"q": "Jika lukisan kotor dan renyuk, nilai estetikanya akan menjadi ___?", "a": "rendah"},
        {"q": "Nilai estetika bermaksud memfokuskan kepada nilai ___ pada karya?", "a": "kecantikan"},
        {"q": "Seni lukisan potret dinilai pada tahap ketepatan rupa ___?", "a": "wajah"},
        {"q": "Karya catan abstrak dinilai melalui corak permainan emosi dan ___?", "a": "warna"},
        {"q": "Karya seni kraf ukiran kayu sangat bernilai dan berharga ___?", "a": "tinggi"},
        {"q": "Guru PSV akan memberi markah tambahan berdasarkan tahap ___ murid?", "a": "usaha"},
        {"q": "Perasaan sedih pelukis mudah digambarkan melalui penggunaan warna ___?", "a": "gelap"},
        {"q": "Setiap teguran kritikan seni perlulah bersifat ___ dan membina?", "a": "positif"},
        {"q": "Karya catan memaparkan kehalusan sapuan berus cat ___?", "a": "air"},
        {"q": "Bersyukur dengan kurniaan bakat seni merupakan nilai murni yang ___?", "a": "terpuji"},
        {"q": "Sesi perbincangan apresiasi memupuk semangat ___ berpasukan?", "a": "kerja"},
        {"q": "Pelukis di luar sana bebas mencari ilham di luar kawasan ___?", "a": "rumah"},
        {"q": "Menghayati flora dan fauna mendekatkan rasa takjub kita kepada ___?", "a": "tuhan"},
        {"q": "Penilaian pada aspek imbangan merujuk kepada keseimbangan ___?", "a": "visual"},
        {"q": "Apresiasi cetakan timbul lino melihat ketepatan pemotongan ___?", "a": "blok"},
        {"q": "Keindahan anyaman tikar dinilai pada kelikatan dan ___ coraknya?", "a": "kekemasan"},
        {"q": "Karya seni montaj digital dinilai pada kemahiran menggunakan ___?", "a": "komputer"},
        {"q": "Menghargai seni warisan tangan membolehkan kita mempertahankan identiti ___?", "a": "bangsa"},
        {"q": "Pengumpul seni tegar sanggup membeli karya asli dengan harga ___?", "a": "mahal"},
        {"q": "Sebuah lukisan yang baik sudah cukup bercerita tanpa menggunakan ___?", "a": "perkataan"},
        {"q": "Menjaga karya peribadi daripada koyak menunjukkan sifat menghargai ___?", "a": "harta"},
        {"q": "Karya seni hebat yang dipamerkan wajar ditonton dengan rasa ___?", "a": "kagum"},
        {"q": "Budaya menghargai peninggalan seni perlu dipupuk sejak dari alam ___?", "a": "kecil"},
        {"q": "Penikmat karya seni akan sentiasa menyokong industri kreatif ___?", "a": "tempatan"}
    ],

    "pameran_seni": [
        {"q": "Acara rasmi mempamerkan hasil karya seni murid dinamakan ___?", "a": "pameran"},
        {"q": "Lokasi kawasan luas yang sering digunakan untuk pameran sekolah ialah ___?", "a": "dewan"},
        {"q": "Karya lukisan kertas perlu dibingkaikan agar kelihatan lebih ___?", "a": "kemas"},
        {"q": "Bingkai kadbod keras sementara untuk lukisan dikenali sebagai bingkai ___?", "a": "lekap"},
        {"q": "Susunan meja pameran mestilah teratur untuk melancarkan ___ pengunjung?", "a": "laluan"},
        {"q": "Karya arca konkrit yang berat wajib diletakkan di atas ___ pameran?", "a": "meja"},
        {"q": "Hasil catan kertas yang ringan boleh ditampal gantung pada ___?", "a": "dinding"},
        {"q": "Tanda kad nama pelukis yang dilekatkan pada penjuru karya dipanggil ___?", "a": "label"},
        {"q": "Fail buku himpunan hasil kerja seni murid sepanjang tahun dinamakan ___?", "a": "portfolio"},
        {"q": "Pameran memberi peluang kepada ibu bapa melihat bakat ___ mereka?", "a": "anak"},
        {"q": "Jawatankuasa jawatan pameran perlu dibentuk untuk mengagihkan ___ kerja?", "a": "tugas"},
        {"q": "Pengawas pameran bertugas menjaga keselamatan karya agar tidak ___?", "a": "rosak"},
        {"q": "Semua pengunjung dilarang sama sekali menyentuh atau ___ karya lukisan?", "a": "pegang"},
        {"q": "Buku pelawat meja depan disediakan untuk tetamu menulis ___ dan ulasan?", "a": "nama"},
        {"q": "Poster saiz besar pameran direka dan ditampal untuk tujuan hebahan ___?", "a": "promosi"},
        {"q": "Ruang pameran mesti dipastikan sentiasa berkeadaan bersih dan ___?", "a": "terang"},
        {"q": "Lampu sorot kuning digunakan untuk menyuluh cahaya tepat ke arah ___?", "a": "lukisan"},
        {"q": "Menghias sudut pameran menjadi lebih cantik menggunakan kain alas ___?", "a": "meja"},
        {"q": "Murid saling bekerjasama menghias dewan menonjolkan semangat ___?", "a": "pasukan"},
        {"q": "Acara Hari Terbuka sekolah amat sesuai diselitkan dengan program ___ seni?", "a": "pameran"},
        {"q": "Sesebuah pameran dikira sangat berjaya jika mendapat jumlah pengunjung yang ___?", "a": "ramai"},
        {"q": "Murid penghasil karya lukisan terbaik boleh dianugerahkan dengan sijil dan ___?", "a": "hadiah"},
        {"q": "Guru PSV sentiasa bertindak sebagai fasilitator atau ___ pameran?", "a": "pembimbing"},
        {"q": "Menyusun karya mengikut saiz kumpulan dan tema mewujudkan susunan yang ___?", "a": "teratur"},
        {"q": "Kad kertas jemputan pameran biasanya diedarkan rasmi kepada para ___?", "a": "tetamu"},
        {"q": "Pameran arca 3D arca stabail memerlukan ruang lantai pameran yang ___?", "a": "luas"},
        {"q": "Alunan bunyi muzik instrumental lembut dipasang untuk menenangkan emosi ___?", "a": "pengunjung"},
        {"q": "Label penerangan karya mesti mempunyai tajuk, media, dan nama ___?", "a": "pelukis"},
        {"q": "Tiket kertas masuk ke pameran hasil seni sekolah biasanya diberikan secara ___?", "a": "percuma"},
        {"q": "Karya kolaj bijian makanan perlu ditutup bungkus agar tidak dimakan ___?", "a": "serangga"},
        {"q": "Karya arca seramik mudah pecah perlu dijauhkan letaknya dari hujung ___ meja?", "a": "tepi"},
        {"q": "Pusat Galeri Seni Negara merupakan tempat pameran rasmi bertaraf ___?", "a": "antarabangsa"},
        {"q": "Menyertai pertandingan dan pameran dapat membina rasa keyakinan ___ murid?", "a": "diri"},
        {"q": "Setiap kelas subjek PSV perlu menghantar sekurang-kurangnya satu ___ seni?", "a": "karya"},
        {"q": "Hasil kraf wau bulan gergasi amat cantik jika diikat gantung di kawasan ___ dewan?", "a": "siling"},
        {"q": "Hasil ukiran topeng kertas boleh dipamerkan dengan cara diletakkan secara ___ di dinding?", "a": "gantung"},
        {"q": "Sesi perasmian pameran biasanya akan disempurnakan oleh tuan pengetua atau ___ besar?", "a": "guru"},
        {"q": "Aktiviti memotong rentang reben dilakukan semasa majlis perasmian ___ pameran?", "a": "pembukaan"},
        {"q": "Sudut pameran interaktif khas membenarkan pengunjung mencuba sendiri menggunakan alat ___?", "a": "seni"},
        {"q": "Karya kolaj montaj kertas ringan perlu disusun rapat agar tidak diterbangkan ___?", "a": "angin"},
        {"q": "Ahli jawatankuasa biro kebersihan wajib memastikan tetamu membuang sampah ke dalam ___?", "a": "tong"},
        {"q": "Pengunjung dilarang keras membawa minuman masuk agar karya lukisan tidak terkena ___?", "a": "kotoran"},
        {"q": "Karya seni basah catan hanya boleh dipamerkan setelah ia betul-betul ___?", "a": "kering"},
        {"q": "Cenderamata kraftangan buatan murid boleh dijual untuk mengumpul bajet ___ tabung seni?", "a": "dana"},
        {"q": "Semasa pameran berakhir, kesemua karya dinding perlu ditanggalkan dengan sangat ___?", "a": "cermat"},
        {"q": "Pengalaman berharga mengurus pameran menjadikan minda murid lebih proaktif dan ___?", "a": "kreatif"},
        {"q": "Pusat galeri seni muzium awam biasanya membenarkan kemasukan lawatan pada setiap ___?", "a": "hari"},
        {"q": "Membawa ahli keluarga rakan melawat galeri dapat mengisi masa cuti dengan amalan yang ___?", "a": "berfaedah"},
        {"q": "Pameran galeri seni memartabatkan martabat karya anak bangsa ke tahap yang lebih ___?", "a": "tinggi"},
        {"q": "Sambutan kemeriahan pameran seni wajar dijadikan sebuah memori indah manis di sekolah ___?", "a": "rendah"}
    ]
};
