// ==========================================
// DATA SOALAN SEJARAH (4 Kategori Pertama)
// ==========================================
const sejarahData = {
    "pengenalan_ilmu_sejarah": [
        {"q": "Apakah maksud sejarah mengikut istilah bahasa Arab 'syajaratun'?", "a": "pohon atau pokok"},
        {"q": "Sejarah membicarakan tentang tindakan manusia dan sebab-sebab mereka melakukannya. Siapakah sejarawan yang menyatakan pandangan ini?", "a": "herodotus"},
        {"q": "Ibn Khaldun menyatakan bahawa sejarah membicarakan tentang masyarakat manusia atau ___ manusia.", "a": "peradaban"},
        {"q": "Sejarawan tempatan Profesor Emeritus Tan Sri Dr. Khoo Kay Kim menyatakan sejarah merujuk kepada apa-apa yang pernah ___.", "a": "berlaku"},
        {"q": "Apakah nama sejarawan tempatan yang menulis buku 'An Introduction to Malaysian Historiography'?", "a": "mohd yusof ibrahim"},
        {"q": "Sumber sejarah terbahagi kepada dua kategori, iaitu sumber primer dan sumber ___.", "a": "sekunder"},
        {"q": "Apakah nama lain bagi sumber primer?", "a": "sumber pertama"},
        {"q": "Adakah sumber primer bahan yang belum diolah, dicetak, dan bersifat asli?", "a": "ya"},
        {"q": "Sebutkan satu contoh bahan sejarah yang dikategorikan sebagai sumber primer.", "a": "artifak atau manuskrip atau fosil"},
        {"q": "Apakah yang dimaksudkan dengan artifak?", "a": "tinggalan ciptaan manusia yang dibuat daripada batu, kaca, atau logam"},
        {"q": "Adakah kapak batu, tembikar, dan mata wang purba dikira sebagai artifak?", "a": "ya"},
        {"q": "Tinggalan haiwan atau tumbuhan yang telah membatu dinamakan ___.", "a": "fosil"},
        {"q": "Dokumen rasmi yang ditulis tangan dan belum dicetak dinamakan ___.", "a": "manuskrip"},
        {"q": "Sumber sekunder ialah bahan yang dikaji melalui pembacaan bahan ___.", "a": "tulis atau cetak"},
        {"q": "Sebutkan satu contoh bahan sejarah yang dikategorikan sebagai sumber sekunder.", "a": "buku atau majalah atau akhbar atau risalah"},
        {"q": "Adakah ensiklopedia dan buku teks sejarah dikategorikan sebagai sumber sekunder?", "a": "ya"},
        {"q": "Terdapat tiga kaedah penyelidikan sejarah, iaitu kaedah lisan, kaedah bertulis, dan kaedah ___.", "a": "arkeologi"},
        {"q": "Kaedah mendapatkan maklumat sejarah melalui proses bual bicarakan atau temu bual dinamakan kaedah ___.", "a": "lisan"},
        {"q": "Orang yang ditemu bual dalam kaedah lisan untuk memberikan maklumat sejarah dikenali sebagai ___.", "a": "orang sumber"},
        {"q": "Apakah langkah pertama dalam melakukan penyelidikan sejarah menggunakan kaedah lisan?", "a": "menentukan tokoh atau orang sumber"},
        {"q": "Kaedah mendapatkan maklumat daripada bahan bertulis atau lakaran pada dinding gua, batu, kayu, atau kertas dinamakan kaedah ___.", "a": "bertulis"},
        {"q": "Kaedah mendapatkan maklumat sejarah daripada tinggalan sejarah yang ditemukan melalui proses gali cari dinamakan kaedah ___.", "a": "arkeologi"},
        {"q": "Apakah nama proses gali cari yang dilakukan untuk mencari artifak di tapak arkeologi?", "a": "ekskavasi"},
        {"q": "Adakah proses menyelidiki artifak purba yang karam di dasar laut dinamakan arkeologi bawah air?", "a": "ya"},
        {"q": "Ruang masa sejarah diukur mengikut konsep dekad, abad, dan ___.", "a": "alaf"},
        {"q": "Satu dekad bersamaan dengan tempoh masa selama ___ tahun.", "a": "sepuluh"},
        {"q": "Satu abad bersamaan dengan tempoh masa selama ___ tahun.", "a": "seratus"},
        {"q": "Satu alaf bersamaan dengan tempoh masa selama ___ tahun.", "a": "seribu"},
        {"q": "Zaman sebelum kelahiran Nabi Isa AS dinamakan Zaman Sebelum ___.", "a": "masehi"},
        {"q": "Singkatan bagi Sebelum Masehi ditulis sebagai ___.", "a": "sm"},
        {"q": "Zaman selepas kelahiran Nabi Isa AS dinamakan Zaman ___.", "a": "masehi"},
        {"q": "Singkatan bagi Masehi ditulis dengan huruf ___.", "a": "m"},
        {"q": "Mengkaji sejarah membantu kita mengambil iktibar dan ___ daripada peristiwa masa lalu.", "a": "pengajaran"},
        {"q": "Adakah sejarah bersifat rekaan atau dongeng semata-mata?", "a": "tidak"},
        {"q": "Peristiwa sejarah mestilah dibuktikan dengan penemuan ___ yang sahih.", "a": "bukti atau sumber"},
        {"q": "Apakah nama bangunan di Kuala Lumpur yang menyimpan pelbagai dokumen rasmi dan khazanah sejarah bertulis negara?", "a": "arkib negara"},
        {"q": "Tempat untuk menyimpan dan memamerkan artifak serta khazanah sejarah purba untuk tatapan awam dinamakan ___.", "a": "muzium"},
        {"q": "Mengkaji sejarah dapat memupuk semangat ___ dan cinta akan tanah air.", "a": "patriotisme"},
        {"q": "Adakah susunan peristiwa sejarah mengikut urutan masa berlakunya dinamakan kronologi?", "a": "ya"},
        {"q": "Mengapakah kita perlu menghormati dan memelihara bangunan bersejarah di negara kita?", "a": "sebagai warisan dan bukti sejarah negara"},
        {"q": "Apakah peristiwa bersejarah negara yang berlaku pada 31 Ogos 1957?", "a": "kemerdekaan tanah melayu"},
        {"q": "Adakah penubuhan Malaysia pada 16 September 1963 dikira sebagai peristiwa sejarah?", "a": "ya"},
        {"q": "Mengkaji sejarah mengajar kita supaya tidak mengulangi ___ yang sama di masa depan.", "a": "kesilapan"},
        {"q": "Garis masa digunakan untuk melihat perkembangan sesuatu peristiwa sejarah secara ___.", "a": "tersusun"},
        {"q": "Apakah maksud 'non-artifak' dalam ilmu arkeologi?", "a": "tinggalan asal seperti dinding gua, parit, atau kubur yang tidak boleh dialihkan"},
        {"q": "Adakah tapak arkeologi Lembah Lenggong di Perak diiktiraf sebagai Tapak Warisan Dunia UNESCO?", "a": "ya"},
        {"q": "Penyelidikan sejarah memerlukan sikap yang jujur, teliti, dan ___.", "a": "objektif"},
        {"q": "Sejarah mengajar kita mengenali asal usul jati diri ___.", "a": "bangsa dan negara"},
        {"q": "Adakah rakaman video peristiwa pengisytiharan kemerdekaan negara dikategorikan sebagai sumber primer?", "a": "ya"},
        {"q": "Memahami sejarah membantu melahirkan generasi yang menghargai ___ keamanan negara.", "a": "erti"}
    ],

    "sejarah_diri_dan_keluarga": [
        {"q": "Maklumat lengkap tentang diri seseorang seperti nama, tarikh lahir, dan nama ibu bapa terkandung di dalam ___ diri.", "a": "biodata"},
        {"q": "Apakah dokumen rasmi yang dikeluarkan oleh Jabatan Pendaftaran Negara semasa seseorang bayi dilahirkan?", "a": "sijil kelahiran"},
        {"q": "Apakah nama lain bagi sijil kelahiran dalam bahasa harian?", "a": "surat beranak"},
        {"q": "Apabila berumur 12 tahun, setiap warganegara Malaysia wajib memohon kad pengenalan yang dinamakan ___.", "a": "mykad"},
        {"q": "Adakah nombor kad pengenalan setiap individu di Malaysia adalah sama?", "a": "tidak"},
        {"q": "Salasilah keluarga merujuk kepada susunan ___ sesebuah keluarga daripada nenek moyang hingga generasi sekarang.", "a": "asal usul"},
        {"q": "Keluarga asas terdiri daripada bapa, ibu, dan ___.", "a": "anak-anak"},
        {"q": "Adakah datuk, nenek, bapa saudara, dan emak saudara termasuk dalam ahli keluarga kembangan?", "a": "ya"},
        {"q": "Panggilan hormat bagi bapa kepada bapa atau ibu kita ialah ___.", "a": "datuk"},
        {"q": "Panggilan hormat bagi ibu kepada bapa atau ibu kita ialah ___.", "a": "nenek"},
        {"q": "Adakah panggilan 'Pak Long' atau 'Acha' merupakan contoh panggilan hormat ahli keluarga mengikut budaya kaum?", "a": "ya"},
        {"q": "Setiap ahli keluarga mempunyai peranan dan ___ masing-masing untuk menjaga keharmonian rumah tangga.", "a": "tanggungjawab"},
        {"q": "Siapakah yang bertanggungjawab menjadi ketua keluarga dan mencari nafkah sara hidup?", "a": "bapa"},
        {"q": "Apakah peranan utama seorang anak terhadap kedua-dua ibu bapa mereka?", "a": "menghormati dan membantu mereka"},
        {"q": "Adakah perbuatan meraikan hari ulang tahun perkahwinan ibu bapa merupakan amalan yang baik?", "a": "ya"},
        {"q": "Peristiwa penting yang membawa kesan mendalam dan sentiasa diingati oleh ahli keluarga dinamakan peristiwa ___ keluarga.", "a": "bersejarah"},
        {"q": "Sebutkan satu contoh peristiwa bersejarah yang menggembirakan sesebuah keluarga.", "a": "kelahiran adik baharu atau hari konvokesyen abang"},
        {"q": "Adakah peristiwa berpindah ke rumah baharu dikategorikan sebagai peristiwa bersejarah keluarga?", "a": "ya"},
        {"q": "Mengetahui sejarah diri dan keluarga membantu kita membina jati diri yang ___.", "a": "kuat"},
        {"q": "Apakah faedah utama mengamalkan budaya makan malam bersama-sama ahli keluarga?", "a": "mengeratkan hubungan kasih sayang"},
        {"q": "Adakah kita patut berasa bangga dengan asal usul susur galur keluarga kita?", "a": "ya"},
        {"q": "Peta alir susunan keluarga dari atas ke bawah dinamakan ___ keluarga.", "a": "pohon"},
        {"q": "Adakah abang kandung dan adik kandung dikategorikan sebagai adik-beradik?" , "a": "ya"},
        {"q": "Siapakah panggilan hormat bagi adik lelaki kepada bapa atau ibu kita mengikut budaya Melayu?", "a": "pak cik atau pak su"},
        {"q": "Sikap saling menghormati antara ahli keluarga dapat menghalang berlakunya ___.", "a": "pergaduhan"},
        {"q": "Apakah dokumen penting yang digunakan oleh ahli keluarga untuk melancong ke luar negara?", "a": "pasport"},
        {"q": "Adakah album gambar lama keluarga boleh dijadikan sebagai sumber sejarah keluarga?", "a": "ya"},
        {"q": "Sijil penghargaan persekolahan yang kita perolehi dikategorikan sebagai sumber ___ diri.", "a": "primer"},
        {"q": "Nama penuh kita mestilah ditulis mengikut nama yang tertera di dalam ___.", "a": "sijil kelahiran"},
        {"q": "Adakah wajar kita merahsiakan masalah besar daripada pengetahuan ibu bapa?", "a": "tidak"},
        {"q": "Sentiasa meminta ___ daripada ibu bapa sebelum keluar dari rumah menunjukkan adab yang tinggi.", "a": "keizinan atau restu"},
        {"q": "Apakah peranan ibu di rumah selain menguruskan kebajikan anak-anak?", "a": "mendidik dan memberikan kasih sayang"},
        {"q": "Adakah amalan menziarahi rumah datuk dan nenek di kampung semasa cuti sekolah digalakkan?", "a": "ya"},
        {"q": "Melalui sejarah keluarga, kita dapat mengekalkan ___ dan adat resam turun-temurun.", "a": "tradisi"},
        {"q": "Anak yang baik sentiasa sentiasa ___ kesejahteraan ibu bapa mereka selepas sembahyang.", "a": "mendoakan"},
        {"q": "Adakah perkahwinan ibu bapa dikira sebagai titik permulaan pembentukan keluarga asas?", "a": "ya"},
        {"q": "Apakah panggilan hormat bagi bapa saudara bagi masyarakat India?", "a": "mama atau periapa"},
        {"q": "Apakah panggilan hormat bagi nenek bagi masyarakat Cina?", "a": "po po"},
        {"q": "Sikap bertolak ansur antara adik-beradik melahirkan suasana rumah tangga yang ___.", "a": "bahagia"},
        {"q": "Adakah barang peninggalan nenek seperti acuan kuih tradisional dikira sebagai warisan keluarga?", "a": "ya"},
        {"q": "Mendengar nasihat dan cerita pengalaman hidup orang tua memberi kita ___ berguna.", "a": "pengajaran"},
        {"q": "Setiap anak berhak mendapat nama panggilan yang ___ dan mengandungi maksud yang baik.", "a": "sopan"},
        {"q": "Adakah anak angkat yang dipelihara dengan sah mempunyai hak kasih sayang yang sama dalam keluarga?", "a": "ya"},
        {"q": "Menjaga nama baik keluarga bermaksud kita tidak melakukan perkara yang ___ undang-undang.", "a": "melanggar"},
        {"q": "Kejayaan anak dalam pelajaran menjadi salah satu kebanggaan terbesar bagi kedua-dua ___.", "a": "ibu bapa"},
        {"q": "Adakah kita patut membantu menjaga adik semasa ibu sedang sibuk memasak?", "a": "ya"},
        {"q": "Rumahku, Syurgaku melambangkan keadaan rumah yang penuh dengan ___.", "a": "kedamaian dan kasih sayang"},
        {"q": "Hubungan darah yang menghubungkan kita dengan ahli keluarga yang lain dipanggil hubungan ___.", "a": "persaudaraan"},
        {"q": "Janganlah kita menjadi anak yang derhaka, sebaliknya jadilah anak yang ___.", "a": "berbakti"},
        {"q": "Keluarga yang bahagia menjadi asas kepada pembentukan masyarakat yang ___.", "a": "cemerlang"}
    ],

    "sejarah_sekolah": [
        {"q": "Setiap sekolah mempunyai nama yang tersendiri bagi memudahkan masyarakat ___ lokasinya.", "a": "mengenali"},
        {"q": "Adakah nama sekolah boleh diambil sempena nama tokoh pejuang, nama tempat, atau nama pengasasnya?", "a": "ya"},
        {"q": "Apakah nama dokumen atau pelan tersusun yang menunjukkan arah kedudukan bangunan di sekolah?", "a": "pelan sekolah"},
        {"q": "Lambang rasmi sekolah yang mengandungi moto, warna identiti, dan simbol khas dinamakan ___ sekolah.", "a": "lencana"},
        {"q": "Apakah yang dimaksudkan dengan 'moto' sekolah yang tertera pada lencana?", "a": "kata-kata azam atau slogan pembakar semangat murid"},
        {"q": "Setiap murid wajib berdiri tegak semasa menyanyikan lagu ___ sekolah dalam perhimpunan rasmi.", "a": "rasmi"},
        {"q": "Siapakah pemimpin tertinggi yang bertanggungjawab mentadbir sesebuah sekolah rendah?", "a": "guru besar"},
        {"q": "Adakah Persatuan Ibu Bapa dan Guru (PIBG) membantu sekolah dalam meningkatkan kecemerlangan murid?", "a": "ya"},
        {"q": "Sejarah penubuhan sekolah biasanya boleh dirujuk di dalam buku ___ sekolah atau majalah sekolah.", "a": "profil"},
        {"q": "Kita mestilah sentiasa menjaga nama baik sekolah dengan mematuhi segala ___ sekolah.", "a": "peraturan atau disiplin"},
        {"q": "Adakah perbuatan menconteng dinding bangunan sekolah melambangkan rasa sayang akan sekolah?", "a": "tidak"},
        {"q": "Kawasan geografi tempat kita membina rumah dan hidup bermasyarakat dinamakan kawasan ___.", "a": "tempat tinggal"},
        {"q": "Setiap kawasan tempat tinggal mempunyai alamat lengkap yang mengandungi poskod dan nama ___.", "a": "negeri"},
        {"q": "Adakah asal usul nama sesuatu tempat selalunya dikaitkan dengan nama tumbuhan, haiwan, tokoh, atau peristiwa?", "a": "ya"},
        {"q": "Sebutkan satu contoh nama tempat di Malaysia yang diambil sempena nama tumbuhan atau buah-buahan.", "a": "melaka atau pulau pinang"},
        {"q": "Apakah nama bandar diraja bagi negeri Selangor?", "a": "klang"},
        {"q": "Bentuk muka bumi kawasan tempat tinggal terbahagi kepada beberapa jenis seperti tanah pamah, pinggir laut, dan tanah ___.", "a": "tinggi"},
        {"q": "Kawasan tempat tinggal yang terletak di bandar biasanya mempunyai kepadatan penduduk yang ___.", "a": "tinggi"},
        {"q": "Adakah kemudahan awam seperti balai raya, taman permainan, dan klinik disediakan di kawasan kejiranan?", "a": "ya"},
        {"q": "Siapakah orang yang tinggal berhampiran atau bersebelahan dengan rumah kita?", "a": "jiran"},
        {"q": "Amalan bergotong-royong membersihkan kawasan perumahan dapat mengelakkan pembiakan nyamuk ___.", "a": "aedes"},
        {"q": "Adakah kita patut mengenali latar belakang sejarah tokoh tempatan yang berjasa di kawasan tempat tinggal kita?", "a": "ya"},
        {"q": "Pihak yang bertanggungjawab menjaga kebersihan dan pembangunan bandar di kawasan tempat tinggal dinamakan pihak berkuasa ___.", "a": "tempatan"},
        {"q": "Apakah singkatan bagi Pihak Berkuasa Tempatan?", "a": "pbt"},
        {"q": "Sebutkan satu contoh Pihak Berkuasa Tempatan yang menguruskan bandar raya besar.", "a": "majlis bandaraya"},
        {"q": "Adakah bangunan sekolah pertama kita boleh dianggap sebagai sebahagian daripada sejarah hidup kita?", "a": "ya"},
        {"q": "Lagu rasmi sekolah sentiasa menyeru murid supaya belajar bersungguh-sungguh demi masa ___.", "a": "depan"},
        {"q": "Warna-warna yang dipilih pada bendera sekolah mempunyai ___ yang tersendiri.", "a": "maksud"},
        {"q": "Adakah wajar kita membuat bising semasa guru besar sedang menyampaikan ucapan di perhimpunan?", "a": "tidak"},
        {"q": "Setiap sekolah mempunyai ___ laku atau kod etika disiplin yang mesti dipatuhi oleh semua murid.", "a": "tingkah"},
        {"q": "Kemudahan pusat sumber atau perpustakaan sekolah disediakan untuk membantu murid meningkatkan budaya ___.", "a": "membaca"},
        {"q": "Adakah sejarah tempat tinggal membantu kita menghargai warisan budaya komuniti setempat?", "a": "ya"},
        {"q": "Kawasan kampung tradisional biasanya mempunyai bentuk muka bumi tanah pamah yang sesuai untuk aktiviti ___.", "a": "pertanian"},
        {"q": "Apakah fungsi utama balai raya di sesebuah kawasan kampung atau taman perumahan?", "a": "tempat bermesyuarat atau aktiviti komuniti"},
        {"q": "Adakah kita patut menghormati jiran yang sedang mengadakan majlis keagamaan di rumah mereka?", "a": "ya"},
        {"q": "Sikap mesra dan suka bertegur sapa dengan jiran melahirkan suasana kejiranan yang ___.", "a": "harmoni"},
        {"q": "Apakah nama agensi keselamatan tempatan yang boleh dihubungi jika berlaku kecurian di kawasan perumahan?", "a": "polis"},
        {"q": "Adakah amalan merosakkan papan tanda nama jalan di kawasan tempat tinggal dikira sebagai kesalahan vandalism?", "a": "ya"},
        {"q": "Menjaga keselamatan kawasan tempat tinggal secara sukarela pada waktu malam dinamakan skim rukun ___.", "a": "tetangga"},
        {"q": "Kita mestilah menjaga kebersihan parit dan longkang di sekitar rumah bagi mengelakkan masalah banjir ___.", "a": "kilat"},
        {"q": "Adakah kedai runcit di kawasan perumahan memudahkan penduduk membeli barang keperluan harian?", "a": "ya"},
        {"q": "Identiti sekolah dicerminkan melalui pencapaian murid dalam bidang akademik dan ___.", "a": "kokurikulum"},
        {"q": "Guru-guru di sekolah bertindak sebagai ___ kedua kepada kita semasa di sekolah.", "a": "ibu bapa"},
        {"q": "Adakah sejarah perkembangan tempat tinggal dari sebuah kampung kecil menjadi bandar dinamakan pembandaran?", "a": "ya"},
        {"q": "Kita mestilah menggunakan kemudahan taman permainan dengan cermat supaya tidak ___.", "a": "rosak"},
        {"q": "Sebutkan kepentingan mengetahui arah mata angin di kawasan tempat tinggal.", "a": "untuk mengetahui kedudukan sesuatu tempat"},
        {"q": "Adakah wajar kita membuang sampah sarat ke dalam sungai yang mengalir di kawasan perumahan?", "a": "tidak"},
        {"q": "Sekolahku, ___.", "a": "syurgaku"},
        {"q": "Maju sekolah, majulah ___.", "a": "murid"},
        {"q": "Sentiasa sayangi sekolah dan tempat tinggal kerana di situlah tempat kita menuntut ilmu dan ___.", "a": "membesar"}
    ],

    "zaman_air_batu": [
        {"q": "Apakah nama zaman di mana permukaan bumi dilitupi oleh lapisan air batu yang tebal?", "a": "zaman air batu"},
        {"q": "Zaman Air Batu berlaku dalam tempoh masa yang sangat lama akibat penurunan ___ bumi.", "a": "suhu"},
        {"q": "Zaman Air Batu terbahagi kepada dua epok penting, iaitu Epok Pleistosen dan Epok ___.", "a": "holosen"},
        {"q": "Epok manakah yang merujuk kepada fasa akhir Zaman Air Batu di mana suhu bumi mula meningkat?", "a": "epok holosen"},
        {"q": "Proses pencairan air batu akibat peningkatan suhu bumi dinamakan proses ___.", "a": "penggelasieran"},
        {"q": "Apakah kesan utama proses penggelasieran terhadap bentuk fizikal bumi?", "a": "pembentukan tasik dan kenaikan aras laut"},
        {"q": "Adakah daratan yang menghubungkan pulau-pulau di Kepulauan Melayu pada Zaman Air Batu dinamakan Pentas Sunda?", "a": "ya"},
        {"q": "Pencairan air batu menyebabkan sebahagian Pentas Sunda ___ dan membentuk laut serta selat.", "a": "tenggelam"},
        {"q": "Sebutkan satu jenis haiwan purba yang hidup pada Zaman Air Batu dan telah pupus.", "a": "mamot atau harimau bertaring lengkung"},
        {"q": "Zaman Prasejarah ialah zaman di mana manusia belum mengenali sistem ___.", "a": "tulisan"},
        {"q": "Zaman Prasejarah terbahagi kepada empat tahap urutan masa, iaitu Paleolitik, Mesolitik, Neolitik, dan Zaman ___.", "a": "logam"},
        {"q": "Apakah Zaman Prasejarah yang paling awal sekali?", "a": "paleolitik"},
        {"q": "Manusia Zaman Paleolitik hidup secara ___ iaitu berpindah-randah dari satu tempat ke tempat lain.", "a": "nomad"},
        {"q": "Di manakah tempat tinggal utama bagi manusia Zaman Paleolitik dan Mesolitik?", "a": "gua atau kawasan sekitar tasik atau sungai"},
        {"q": "Apakah jenis alatan yang digunakan oleh manusia Zaman Paleolitik untuk memburu haiwan?", "a": "alat batu yang ringkas dan kasar"},
        {"q": "Adakah manusia Zaman Paleolitik sudah tahu cara menggunakan api untuk memanaskan badan?", "a": "ya"},
        {"q": "Zaman Prasejarah kedua yang menunjukkan penambahbaikan kecil pada alat batu dinamakan Zaman ___.", "a": "mesolitik"},
        {"q": "Zaman Prasejarah di mana manusia mula hidup menetap dan menjalankan aktiviti pertanian dinamakan Zaman ___.", "a": "neolitik"},
        {"q": "Adakah manusia Zaman Neolitik masih hidup berpindah-randah secara nomad?", "a": "tidak"},
        {"q": "Manusia Zaman Neolitik mencipta peralatan batu yang lebih licin, halus, dan mempunyai ___.", "a": "fungsi khusus"},
        {"q": "Apakah aktiviti ekonomi utama yang dijalankan oleh masyarakat Zaman Neolitik?", "a": "bercocok tanam dan menternak binatang"},
        {"q": "Tembikar tanah seperti periuk digunakan oleh manusia Zaman Neolitik untuk menyimpan ___.", "a": "makanan atau air"},
        {"q": "Zaman Prasejarah yang paling maju di mana manusia menggunakan gangsa dan besi dinamakan Zaman ___.", "a": "logam"},
        {"q": "Apakah dua jenis logam utama yang digunakan untuk membuat kapak dan mata lembing pada Zaman Logam?", "a": "gangsa dan besi"},
        {"q": "Adakah manusia Zaman Logam sudah menjalankan aktiviti perdagangan secara sistem barter?", "a": "ya"},
        {"q": "Apakah yang dimaksudkan dengan sistem barter?", "a": "sistem pertukaran barang tanpa menggunakan wang"},
        {"q": "Sebutkan satu lokasi tapak prasejarah Zaman Paleolitik yang terkenal di Malaysia.", "a": "lembah lenggong di perak atau gua niah di sarawak"},
        {"q": "Apakah nama penemuan rangka manusia Zaman Paleolitik yang paling lengkap di Lembah Lenggong, Perak?", "a": "orang perak atau perak man"},
        {"q": "Adakah lukisan dinding gua purba merupakan salah satu bukti peninggalan manusia Zaman Prasejarah?", "a": "ya"},
        {"q": "Lukisan di dinding Gua Niah, Sarawak biasanya menggambarkan aktiviti memburu dan upacara ___.", "a": "pengebumian"},
        {"q": "Masyarakat Zaman Logam mengebumikan mayat menggunakan kepingan batu yang dinamakan kubur kepingan ___.", "a": "batu"},
        {"q": "Peningkatan suhu bumi pada Epok Holosen menyebabkan manusia mula ___ ke kawasan yang lebih sesuai.", "a": "berhijrah"},
        {"q": "Adakah evolusi bentuk fizikal bumi mempengaruhi cara hidup dan penempatan manusia purba?", "a": "ya"},
        {"q": "Manusia Zaman Neolitik mula membentuk sistem sosial yang ringkas seperti penempatan sebuah ___.", "a": "kampung"},
        {"q": "Siapakah yang mengetuai sesebuah organisasi kampung pada Zaman Neolitik?", "a": "ketua kampung"},
        {"q": "Alatan batu berbentuk beliung pada Zaman Neolitik digunakan untuk aktiviti ___.", "a": "menggali tanah atau pertanian"},
        {"q": "Adakah penemuan gendang gangsa di Dong Son, Vietnam menjadi bukti wujudnya perdagangan Zaman Logam di Asia Tenggara?", "a": "ya"},
        {"q": "Manusia purba memburu haiwan untuk mendapatkan daging sebagai makanan dan ___ sebagai pakaian.", "a": "kulit haiwan"},
        {"q": "Adakah penempatan manusia purba kebanyakannya terletak berhampiran dengan sungai untuk mendapatkan sumber air?", "a": "ya"},
        {"q": "Zaman Logam memperlihatkan manusia sudah mula membina rumah daripada ___.", "a": "kayu"},
        {"q": "Kewujudan Zaman Prasejarah di Malaysia membuktikan negara kita mempunyai warisan sejarah yang sangat ___.", "a": "tua atau purba"},
        {"q": "Adakah manusia Zaman Paleolitik mengumpulkan hasil hutan seperti buah-buahan dan pucuk paku?", "a": "ya"},
        {"q": "Alatan memancing purba yang diperbuat daripada tulang haiwan dinamakan ___ gasing.", "a": "mata kail"},
        {"q": "Mengkaji Zaman Air Batu menyedarkan kita tentang kepentingan menjaga bumi daripada masalah pemanasan ___.", "a": "global"},
        {"q": "Adakah pemeliharaan alam sekitar dapat mengelakkan pencairan air batu kutub yang keterlaluan?", "a": "ya"},
        {"q": "Sebutkan lautan terbesar di dunia yang terbentuk akibat perubahan Zaman Air Batu.", "a": "lautan pasifik"},
        {"q": "Arkeologi membantu merungkai misteri kehidupan manusia prasejarah melalui peninggalan ___.", "a": "kebendaan"},
        {"q": "Manusia Zaman Logam mempunyai kepercayaan dan melakukan upacara ___ terhadap kuasa alam.", "a": "penyembahan"},
        {"q": "Sejarah perkembangan bumi dan manusia prasejarah mengajar kita erti ___ kehidupan.", "a": "kelangsungan"},
        {"q": "Hargai khazanah prasejarah negara sebagai bukti tamadun awal ___.", "a": "kita"}
    ],
"kerajaan_melayu_awal": [
        {"q": "Kerajaan Melayu Awal muncul di kawasan Kepulauan Melayu dan kebanyakannya terletak di pinggir ___.", "a": "sungai atau laut"},
        {"q": "Sebutkan sebuah kerajaan Melayu awal yang terletak di utara Semenanjung Melayu yang terkenal dengan perdagangan tawas.", "a": "kedah tua"},
        {"q": "Apakah nama kerajaan Melayu awal yang terletak di lembah Sungai Bujang, Perak?", "a": "gangga nagara"},
        {"q": "Adakah kerajaan Chih Tu merupakan sebuah kerajaan Melayu awal yang pernah wujud di Kelantan?", "a": "ya"},
        {"q": "Apakah nama kerajaan Melayu awal yang terletak di Sarawak dan terkenal dengan penemuan acuan besi purba?", "a": "santubong"},
        {"q": "Kerajaan Temasik merupakan nama asal bagi negara ___ pada hari ini.", "a": "singapura"},
        {"q": "Adakah kerajaan Funan dikategorikan sebagai kerajaan Melayu awal yang paling tua di Asia Tenggara?", "a": "ya"},
        {"q": "Apakah nama kerajaan Melayu awal di Sumatera yang terkenal sebagai pusat penyebaran agama Buddha dan pusat perdagangan laut yang kuat?", "a": "srivijaya"},
        {"q": "Kerajaan Melayu awal menjalankan kegiatan ekonomi berasaskan laut yang dipanggil perdagangan ___.", "a": "maritim"},
        {"q": "Lokasi pelabuhan yang strategik membolehkan pelabuhan kerajaan Melayu awal menjadi tempat persinggahan ___ dari luar.", "a": "pedagang"},
        {"q": "Adakah hasil hutan seperti damar, rotan, dan sarang burung merupakan barang dagangan utama kerajaan Melayu awal?", "a": "ya"},
        {"q": "Apakah jenis galian atau hasil bumi berharga yang menjadi tarikan pedagang asing ke Gangga Nagara?", "a": "bijih timah atau emas"},
        {"q": "Sebutkan satu kuasa besar dunia purba yang sering datang berdagang ke pelabuhan Kedah Tua.", "a": "india atau china"},
        {"q": "Adakah penemuan candi purba di Lembah Bujang membuktikan pengaruh agama Hindu-Buddha dalam kerajaan Kedah Tua?", "a": "ya"},
        {"q": "Kerajaan Majapahit berpusat di pulau ___.", "a": "jawa"},
        {"q": "Apakah gelaran bagi pemimpin tertinggi yang mengetuai sebuah kerajaan Melayu awal?", "a": "raja atau datu"},
        {"q": "Adakah laut di sekitar Kepulauan Melayu terlindung daripada tiupan angin monsun yang kencang?", "a": "ya"},
        {"q": "Angin monsun apakah yang digunakan oleh pedagang India untuk belayar ke Kepulauan Melayu?", "a": "angin monsun barat daya"},
        {"q": "Apakah komoditi atau barang berharga yang dicari oleh pedagang barat di Kepulauan Melayu sehinggakan wilayah ini digelar Kepulauan Rempah?", "a": "rempah-ratus"},
        {"q": "Adakah kerajaan Beruas di Perak muncul selepas kejatuhan kerajaan Gangga Nagara?", "a": "ya"},
        {"q": "Sebutkan barang dagangan bernilai dari Chih Tu yang bermaksud 'Tanah Merah'.", "a": "emas dan hasil hutan"},
        {"q": "Kerajaan Melayu awal yang terkenal dengan aktiviti pertanian padi sawah di lembah sungai yang subur ialah ___.", "a": "funan atau angkor"},
        {"q": "Adakah sistem tulisan dan kalendar mula diperkenalkan di pelabuhan hasil interaksi dengan pedagang luar?", "a": "ya"},
        {"q": "Mata wang purba yang digunakan dalam urusan perdagangan awal diperbuat daripada logam seperti ___.", "a": "emas atau perak atau timah"},
        {"q": "Apakah nama selat yang menjadi laluan perdagangan laut paling sibuk di dunia dan dikuasai oleh Srivijaya?", "a": "selat melaka"},
        {"q": "Adakah kerajaan Mataram merupakan sebuah kerajaan awal yang terkenal dengan pembinaan Candi Borobudur?", "a": "ya"},
        {"q": "Kemunculan pelabuhan pembekal bermula apabila penduduk setempat mengumpulkan hasil hutan untuk ___ kepada pedagang luar.", "a": "dijual atau ditukar"},
        {"q": "Pelabuhan yang dilengkapi dengan kemudahan gudang penyimpanan barang dan tempat tinggal pedagang dinamakan pelabuhan ___.", "a": "entrepot"},
        {"q": "Adakah penemuan manik kaca kuno di tapak sejarah menjadi bukti kewujudan hubungan perdagangan antarabangsa?", "a": "ya"},
        {"q": "Hubungan diplomatik antara kerajaan Melayu awal dengan China bertujuan untuk mendapatkan ___.", "a": "perlindungan keselamatan"},
        {"q": "Kerajaan Melayu awal yang terletak di Pahang kuno dinamakan kerajaan ___.", "a": "pan pan"},
        {"q": "Adakah aktiviti memungut hasil laut seperti sirip hiu dan mutiara dijalankan oleh penduduk kerajaan maritim?", "a": "ya"},
        {"q": "Sistem pemerintahan beraja menuntut rakyat memberikan kesetiaan yang sepenuhnya kepada ___.", "a": "pemerintah atau raja"},
        {"q": "Apakah fungsi utama sistem parit dan tali air yang dibina oleh kerajaan Angkor?", "a": "untuk mengairi kawasan tanaman padi"},
        {"q": "Adakah wujud pengkhususan pekerjaan seperti tukang kayu, penenun kain, dan pembuat senjata dalam masyarakat kerajaan awal?", "a": "ya"},
        {"q": "Seni bina kapal layar yang kukuh membolehkan pelaut Melayu belayar hingga ke pesisir pantai ___.", "a": "afrika atau madagaskar"},
        {"q": "Kerajaan Melayu awal runtuh atau merosot akibat serangan daripada kuasa luar atau kemunculan pelabuhan ___ baharu.", "a": "pesaing"},
        {"q": "Adakah kedaulatan sesebuah kerajaan awal diukur berdasarkan keluasan wilayah pengaruh dan jumlah rakyatnya?", "a": "ya"},
        {"q": "Pedagang Arab menggelar pelabuhan Kedah Tua dengan nama ___.", "a": "kalah-bar"},
        {"q": "Apakah kepentingan utama sungai kepada petempatan awal selain sebagai sumber air?", "a": "jalan pengangkutan dan perhubungan"},
        {"q": "Adakah penemuan batu bersurat purba membantu sejarawan mengenal pasti nama raja yang memerintah sesebuah kerajaan?", "a": "ya"},
        {"q": "Masyarakat kerajaan Melayu awal mengamalkan sistem ___ dalam menguruskan pembahagian air pertanian.", "a": "gotong-royong atau muafakat"},
        {"q": "Apakah kegunaan utama tawas yang diperdagangkan di Kedah Tua pada zaman purba?", "a": "untuk membersihkan air atau industri tekstil"},
        {"q": "Adakah barang tembikar dari zaman Dinasti Tang di China pernah ditemukan di tapak arkeologi Lembah Bujang?", "a": "ya"},
        {"q": "Kemahiran memproses bijih besi menunjukkan masyarakat Santubong telah mempunyai teknologi yang ___.", "a": "tinggi atau maju"},
        {"q": "Sikap keterbukaan menerima kehadiran pedagang luar menjadikan pelabuhan awal berkembang ___.", "a": "pesat"},
        {"q": "Adakah kita perlu berasa bangga dengan kehebatan tamadun kerajaan Melayu awal di tanah air kita?", "a": "ya"},
        {"q": "Warisan sistem beraja daripada kerajaan awal kekal ___ dalam sistem pentadbiran negara kita hari ini.", "a": "diamalkan"},
        {"q": "Kerajaan awal makmur, rakyat ___.", "a": "sejahtera"},
        {"q": "Mengkaji kerajaan Melayu awal menyedarkan kita tentang pentingnya menjaga keamanan wilayah ___ kita.", "a": "perairan"}
    ],

    "tokoh_terbilang": [
        {"q": "Siapakah tokoh yang telah mengasaskan Kesultanan Melayu Melaka pada sekitar tahun 1400?", "a": "parameswara"},
        {"q": "Parameswara memilih nama 'Melaka' sempena nama ___ tempat baginda bersandar semasa melihat peristiwa anjing pemburu ditendang oleh pelanduk.", "a": "pokok"},
        {"q": "Adakah keberanian seekor pelanduk putih menendang anjing pemburu menjadi pencetus idea pembukaan Melaka?", "a": "ya"},
        {"q": "Apakah jawatan tertinggi dalam sistem pemerintahan Melaka yang bertindak sebagai penasihat Sultan dan ketua hakim?", "a": "bendahara"},
        {"q": "Siapakah nama Bendahara Melaka yang paling terkenal dan digelar sebagai arkitek keagungan Melaka?", "a": "tun perak"},
        {"q": "Tun Perak telah berkhidmat dengan cekap di bawah pemerintahan berapa orang Sultan Melaka?", "a": "empat"},
        {"q": "Adakah Tun Perak menggunakan strategi meletakkan obor pada pokok bakau untuk menewaskan serangan tentera Siam?", "a": "ya"},
        {"q": "Apakah jawatan dalam Kesultanan Melayu Melaka yang bertanggungjawab menjaga keamanan kota dan keselamatan Sultan?", "a": "temenggung"},
        {"q": "Jawatan yang bertindak sebagai ketua angkatan laut dan pengawal keselamatan perairan Melaka dinamakan ___.", "a": "laksamana"},
        {"q": "Siapakah nama Laksamana Melaka yang paling gagah, setia, dan terkenal dengan hulu keris berluk 13?", "a": "hang tuah"},
        {"q": "Adakah Hang Tuah menguasai banyak bahasa asing yang memudahkannya bertindak sebagai utusan diplomatik Melaka?", "a": "ya"},
        {"q": "Sultan Melaka yang terkenal dengan usaha memperluaskan empayar wilayah Melaka melalui kaedah penaklukan dan perkahwinan ialah Sultan ___.", "a": "manzur shah"},
        {"q": "Apakah nama undang-undang bertulis Melaka yang mengandungi peraturan pelayaran dan urusan perdagangan di pelabuhan?", "a": "undang-undang laut melaka"},
        {"q": "Adakah Hukum Kanun Melaka mengandungi 44 fasal yang berkaitan dengan tanggungjawab pemerintah dan hukuman jenayah?", "a": "ya"},
        {"q": "Sistem pentadbiran yang tersusun di Melaka yang melibatkan pembahagian tugas empat pembesar utama dinamakan Sistem Pembesar ___ Lipat.", "a": "empat"},
        {"q": "Siapakah pembesar yang bertanggungjawab memungut cukai di pelabuhan dan menjaga khazanah perbendaharaan negara?", "a": "penghulu bendahari"},
        {"q": "Adakah jawatan Syahbandar diwujudkan untuk menguruskan hal-ehwal kebajikan pedagang dan perjalanan di pelabuhan?", "a": "ya"},
        {"q": "Apakah agama rasmi Kesultanan Melayu Melaka selepas pengislaman Sultan Megat Iskandar Shah?", "a": "islam"},
        {"q": "Melaka dikenali sebagai pelabuhan ___ kerana menjadi pusat pengumpulan barang dari timur dan barat.", "a": "entrepot"},
        {"q": "Adakah kedudukan Melaka yang terletak di laluan Selat Melaka terlindung daripada tiupan Angin Monsun Timur Laut?", "a": "ya"},
        {"q": "Sebutkan sebuah negara luar yang menjalinkan hubungan diplomatik awal dengan Melaka melalui utusan Laksamana Yin Ching.", "a": "china atau dinasti ming"},
        {"q": "Apakah nama puteri dari China yang dikabarkan berkahwin dengan Sultan Mansur Shah sebagai tanda hubungan akrab?", "a": "puteri hang li po"},
        {"q": "Adakah Melaka menggunakan bahasa Melayu sebagai bahasa perantaraan utama atau 'lingua franca'?", "a": "ya"},
        {"q": "Sultan manakah yang mangkur semasa Melaka berada di puncak keagungan empayarnya?", "a": "sultan alauddin riayat shah"},
        {"q": "Sultan Alauddin Riayat Shah terkenal sebagai seorang pemerintah yang prihatin kerana baginda sering ___ pada waktu malam untuk menjaga keselamatan rakyat.", "a": "meronda"},
        {"q": "Apakah gelaran yang diberikan kepada Hang Tuah dan rakan-rakannya yang berlima?", "a": "lima bersaudara"},
        {"q": "Sebutkan nama empat orang sahabat setia Laksamana Hang Tuah.", "a": "hang jebat, hang kasturi, hang lekir, hang lekiu"},
        {"q": "Adakah peristiwa pertarungan antara Hang Tuah dan Hang Jebat berlaku akibat isu pelanggaran konsep kesetiaan terhadap Sultan?", "a": "ya"},
        {"q": "Kata-kata keramat 'Takkan Melayu Hilang di Dunia' sering dikaitkan dengan tokoh ___.", "a": "hang tuah"},
        {"q": "Apakah faktor dalaman utama yang menyebabkan kejatuhan Kesultanan Melayu Melaka pada tahun 1511?", "a": "perpecahan rakyat atau rasuah atau kelemahan pemimpin"},
        {"q": "Siapakah nama Sultan terakhir yang memerintah Melaka sebelum kota tersebut jatuh ke tangan Portugis?", "a": "sultan mahmud shah"},
        {"q": "Adakah Portugis menyerang Melaka pada tahun 1511 di bawah pimpinan Alfonso de Albuquerque?", "a": "ya"},
        {"q": "Senjata moden apakah yang digunakan oleh tentera Portugis untuk menewaskan pertahanan Melaka?", "a": "meriam atau senapang"},
        {"q": "Walaupun Melaka telah jatuh, warisan sistem pemerintahan dan budayanya diteruskan oleh kerajaan ___.", "a": "johor riau"},
        {"q": "Adakah gajah digunakan oleh Sultan Melaka sebagai kenderaan perang semasa menentang Portugis?", "a": "ya"},
        {"q": "Pusat penyebaran agama Islam yang utama di Asia Tenggara pada abad ke-15 terletak di ___.", "a": "melaka"},
        {"q": "Apakah nama kitab sejarah bertulis yang menceritakan salasilah raja-raja dan keagungan Kesultanan Melayu Melaka?", "a": "sulalatus salatin atau sejarah melayu"},
        {"q": "Adakah pedagang asing yang datang ke Melaka diwajibkan membayar cukai rasmi yang dinamakan panduan?", "a": "ya"},
        {"q": "Golongan yang menduduki lapisan paling bawah dalam struktur masyarakat Kesultanan Melayu Melaka ialah ___.", "a": "hamba"},
        {"q": "Konsep 'daulat' merujuk kepada ___ tertinggi seseorang Sultan yang suci dan wajib dihormati.", "a": "kekuasaan"},
        {"q": "Adakah perbuatan derhaka atau menentang perintah Sultan dipercayai akan terkena tulah atau bencana?", "a": "ya"},
        {"q": "Kebijaksanaan Tun Perak ketara apabila baginda berjaya menjalinkan hubungan baik dengan negeri-negeri ___ Melaka.", "a": "naungan atau jajahan"},
        {"q": "Apakah nama tempat kediaman rasmi Sultan Melaka yang diperbuat daripada kayu tanpa menggunakan paku besi?", "a": "istana kesultanan melaka"},
        {"q": "Adakah pedagang dari wilayah Gujerat, India memainkan peranan penting dalam menyebarkan Islam di Melaka?", "a": "ya"},
        {"q": "Kemakmuran ekonomi Melaka disokong oleh penggunaan sistem mata wang tempatan yang diperbuat daripada ___.", "a": "timah"},
        {"q": "Sikap pahlawan yang sedia berkorban demi mempertahankan tanah air mestilah ___ oleh murid hari ini.", "a": "dicontohi"},
        {"q": "Adakah kita wajar menghargai peranan tokoh terbilang dalam membina asas kegemilangan tamadun negara?", "a": "ya"},
        {"q": "Melaka kota bersejarah, tempat lahirnya ___ bangsa.", "a": "warisan atau kedaulatan"},
        {"q": "Pembesar berwibawa, empayar ___.", "a": "gemilang"},
        {"q": "Jadikan pengajaran daripada kejatuhan Melaka supaya kita sentiasa menjaga ___ kaum.", "a": "perpaduan"}
    ],

    "warisan_negara": [
        {"q": "Apakah nama institusi pemerintahan tertinggi negara yang menjadi lambang kedaulatan sejak zaman kerajaan Melayu awal?", "a": "institusi raja"},
        {"q": "Sistem beraja di Malaysia pada hari ini dilaksanakan mengikut konsep Raja Perlembagaan dan Demokrasi ___.", "a": "berparlimen"},
        {"q": "Apakah gelaran rasmi bagi Ketua Utama Negara Malaysia yang dipilih daripada kalangan sembilan orang Raja Melayu?", "a": "yang di-pertuan agong"},
        {"q": "Sebutkan singkatan gelaran bagi Yang di-Pertuan Agong.", "a": "ydpa"},
        {"q": "Yang di-Pertuan Agong dipilih untuk memegang jawatan Ketua Utama Negara selama tempoh ___ tahun.", "a": "lima"},
        {"q": "Adakah pemilihan Yang di-Pertuan Agong dibuat secara bergilir-gilir oleh Majlis Raja-Raja?", "a": "ya"},
        {"q": "Berapakah jumlah negeri di Malaysia yang mempunyai raja atau sultan pada hari ini?", "a": "sembilan"},
        {"q": "Sebutkan tiga buah negeri di Malaysia yang tidak mempunyai sultan atau raja.", "a": "melaka, pulau pinang, sabah, sarawak"},
        {"q": "Apakah gelaran bagi ketua negeri bagi negeri-negeri yang tidak mempunyai sultan?", "a": "yang di-pertua negeri"},
        {"q": "Adakah negeri Perlis menggunakan gelaran 'Raja' bagi pemerintah tertingginya?", "a": "ya"},
        {"q": "Apakah gelaran bagi pemerintah tertinggi bagi negeri Negeri Sembilan?", "a": "yang di-pertuan besar"},
        {"q": "Konsep 'Daulat' melambangkan kekuasaan, kesucian, dan ___ seseorang raja untuk memerintah.", "a": "kedaulatan"},
        {"q": "Adakah perbuatan mengingkari arahan atau menderhaka kepada raja dipanggil sebagai durhaka?", "a": "ya"},
        {"q": "Apakah warna diraja yang digunakan khusus untuk pakaian, payung, dan hiasan istana?", "a": "kuning"},
        {"q": "Tempat kediaman rasmi bagi Yang di-Pertuan Agong dinamakan ___ Negara.", "a": "istana"},
        {"q": "Apakah nama persidangan rasmi yang dianggotai oleh semua sembilan Raja Melayu dan empat Yang di-Pertua Negeri?", "a": "majlis raja-raja"},
        {"q": "Adakah Yang di-Pertuan Agong bertindak sebagai Ketua Agama Islam bagi negeri baginda sendiri serta negeri-negeri tanpa raja?", "a": "ya"},
        {"q": "Alat kebesaran diraja yang berupa sejenis senjata bermata tajam dan menjadi lambang kekuasaan sultan dinamakan ___ diraja.", "a": "keris"},
        {"q": "Apakah nama tengkolok atau hiasan kepala diraja yang dipakai oleh Yang di-Pertuan Agong semasa istiadat rasmi?", "a": "tengkolok diraja atau dendam tak sudah"},
        {"q": "Adakah kalung diraja merupakan salah satu hiasan pakaian rasmi bagi Raja Permaisuri Agong?", "a": "ya"},
        {"q": "Alat kebesaran diraja yang berbentuk sepasang tongkat perak besar dan kecil dinamakan Cogan Alam dan Cogan ___.", "a": "agama"},
        {"q": "Bahasa khusus yang digunakan apabila bertutur dengan kerabat diraja dinamakan bahasa ___.", "a": "istana atau dalam"},
        {"q": "Apakah perkataan bahasa istana yang digunakan untuk menggantikan perkataan 'makan'?", "a": "santap"},
        {"q": "Apakah perkataan bahasa istana yang digunakan untuk menggantikan perkataan 'tidur'?", "a": "beradu"},
        {"q": "Adakah perkataan 'gering' dalam bahasa istana membawa maksud sakit?", "a": "ya"},
        {"q": "Perkataan 'titah' bermaksud kata-kata atau perintah yang dikeluarkan oleh ___.", "a": "raja atau sultan"},
        {"q": "Sebutkan perkataan bahasa istana yang bermaksud 'mati'.", "a": "mangkat"},
        {"q": "Adakah rakyat jelata wajib menggunakan bahasa istana semasa berurusan dengan raja di dalam balairung seri?", "a": "ya"},
        {"q": "Institusi raja bertindak sebagai payung perlindungan bagi memastikan keadilan dan ___ rakyat terpelihara.", "a": "kebajikan"},
        {"q": "Sikap taat setia kepada raja dan negara merupakan prinsip ke-___ dalam Rukun Negara.", "a": "dua"},
        {"q": "Adakah institusi raja penting sebagai simbol perpaduan rakyat Malaysia yang berbilang kaum?", "a": "ya"},
        {"q": "Siri istiadat rasmi melantik sultan baharu untuk menaiki takhta kerajaan dinamakan istiadat ___.", "a": "pertabalan"},
        {"q": "Pihak yang bertanggungjawab menguruskan upacara adat istiadat dan perjalanan harian di istana dipanggil Datuk ___.", "a": "pengelola bijaya diraja"},
        {"q": "Adakah institusi raja di Malaysia dilindungi oleh Perlembagaan Persekutuan?", "a": "ya"},
        {"q": "Setiap undang-undang yang diluluskan oleh Parlimen mestilah mendapat ___ daripada Yang di-Pertuan Agong.", "a": "perkenan atau kelulusan"},
        {"q": "Apakah kepentingan utama mengekalkan institusi raja di tanah air kita?", "a": "menjaga kestabilan politik dan warisan sejarah negara"},
        {"q": "Adakah wajar kita membuat hantaran yang menghina institusi diraja di media sosial?", "a": "tidak"},
        {"q": "Tindakan menghina sultan boleh dikenakan hukuman di bawah undang-undang negara kerana melanggar etika ___.", "a": "kesetiaan"},
        {"q": "Payung kuning diraja melambangkan kedaulatan raja yang ___.", "a": "tinggi atau agung"},
        {"q": "Apakah nama sejenis senjata seperti tombak berbilang mata yang digunakan dalam istiadat kebesaran diraja?", "a": "lembing atau tombak berbendera"},
        {"q": "Adakah jata negara Malaysia mempunyai simbol mahkota diraja?", "a": "tidak"},
        {"q": "Majlis mengangkat sumpah jawatan Perdana Menteri dilakukan di hadapan ___.", "a": "yang di-pertuan agong"},
        {"q": "Institusi raja merupakan warisan sejarah yang unik dan tiada galang ___.", "a": "gantinya"},
        {"q": "Adakah Yang di-Pertuan Agong merupakan Pemerintah Tertinggi Angkatan Tentera Malaysia?", "a": "ya"},
        {"q": "Sikap menghormati lambang-lambang kebesaran diraja membuktikan kita warganegara yang ___.", "a": "patriotik"},
        {"q": "Sultan adil raja disembah, raja zalim raja ___.", "a": "disanggah"},
        {"q": "Daulat ___.", "a": "tuanku"},
        {"q": "Raja dan rakyat berpisah ___.", "a": "tiada"},
        {"q": "Satia kepada raja, amanah kepada ___.", "a": "negara"},
        {"q": "Mengekalkan warisan institusi raja menjamin kelangsungan identiti ___ bangsa." , "a": "melayu atau malaysia"}
    ],

    "sejarah_kemerdekaan_1957": [
        {"q": "Siapakah tokoh yang mengetuai gerakan politik dan diplomasi sehingga berjaya memerdekakan Persekutuan Tanah Melayu?", "a": "tunku abdul rahman"},
        {"q": "Tunku Abdul Rahman mendapat gelaran agung sebagai Bapa ___.", "a": "kemerdekaan"},
        {"q": "Apakah nama parti gabungan tiga kaum utama yang memenangi Pilihan Raya Majlis Perundangan Persekutuan 1955?", "a": "parti perikatan"},
        {"q": "Tiga parti komponen di bawah Parti Perikatan ialah UMNO, MCA, dan ___.", "a": "mic"},
        {"q": "Siapakah nama pemimpin kaum Cina yang bekerjasama dengan Tunku Abdul Rahman dalam menuntut kemerdekaan?", "a": "tan cheng lock"},
        {"q": "Siapakah nama pemimpin kaum India yang mengetuai MIC semasa proses tuntutan kemerdekaan negara?", "a": "tun v.t. sambanthan"},
        {"q": "Adakah rundingan rasmi menuntut kemerdekaan antara rombongan Tanah Melayu dengan pihak British diadakan di bandar London?", "a": "ya"},
        {"q": "Apakah nama perjanjian bersejarah yang ditandatangani di London pada 8 Februari 1956 yang menetapkan tarikh kemerdekaan Tanah Melayu?", "a": "perjanjian kemerdekaan tanah melayu"},
        {"q": "Rombongan kemerdekaan ke London dibiayai menggunakan hasil sumbangan wang dan barang kemas daripada ___.", "a": "rakyat tempatan"},
        {"q": "Adakah pengorbanan wanita Melayu menyerahkan gelang emas untuk tambang rombongan ke London melambangkan semangat patriotisme tinggi?", "a": "ya"},
        {"q": "Sekembalinya dari London, Tunku Abdul Rahman mengumumkan tarikh kemerdekaan negara buat pertama kali di Padang Banda Hilir, ___.", "a": "melaka"},
        {"q": "Apakah nama suruhanjaya bebas yang dibentuk untuk menggubal Perlembagaan Persekutuan Tanah Melayu yang merdeka?", "a": "suruhanjaya reid"},
        {"q": "Kemerdekaan Persekutuan Tanah Melayu diisytiharkan secara rasmi pada tarikh ___.", "a": "31 ogos 1957"},
        {"q": "Upacara penurunan bendera British, Union Jack dilakukan pada tengah malam 30 Ogos 1957 di Padang ___.", "a": "kelab selangor atau dataran merdeka"},
        {"q": "Bendera Union Jack diturunkan dan diganti dengan pengibaran bendera Persekutuan ___ buat kali pertama.", "a": "tanah melayu"},
        {"q": "Di manakah lokasi stadium bersejarah tempat berlangsungnya upacara pengisytiharan kemerdekaan pada pagi 31 Ogos 1957?", "a": "stadium merdeka"},
        {"q": "Berapakah bilangan laungan kata 'Merdeka!' yang diucapkan oleh Tunku Abdul Rahman di Stadium Merdeka?", "a": "tujuh"},
        {"q": "Semasa laungan kemerdekaan, Tunku Abdul Rahman mengangkat tangan ___ ke udara.", "a": "kanan"},
        {"q": "Adakah dokumen rasmi Pemasyahiran Kemerdekaan ditulis dalam dua versi tulisan, iaitu tulisan Jawi dan Inggeris?", "a": "ya"},
        {"q": "Lagu kebangsaan '___' berkumandang buat kali pertama secara rasmi pada pagi hari kemerdekaan.", "a": "negaraku"},
        {"q": "Siapakah nama Yang di-Pertuan Agong yang pertama bagi Persekutuan Tanah Melayu yang merdeka?", "a": "tuanku abdul rahman"},
        {"q": "Tuanku Abdul Rahman ibni Almarhum Tuanku Muhammad merupakan Sultan bagi negeri ___.", "a": "negeri sembilan"},
        {"q": "Adakah muafakat dan toleransi antara kaum menjadi kunci utama kejayaan diplomasi kemerdekaan?", "a": "ya"},
        {"q": "Siapakah nama tokoh intelek Melayu yang menjadi srikandi wanita menentang Malayan Union dan mengasaskan pergerakan wanita UMNO?", "a": "ibu zain atau tun fatimah hashim"},
        {"q": "Setiap warganegara wajib ___ jasa-jasa para pemimpin pembina negara terdahulu.", "a": "menghargai"},
        {"q": "Adakah mengekalkan kemerdekaan negara adalah tugas yang lebih mencabar daripada menuntut kemerdekaan?", "a": "ya"},
        {"q": "Sikap bersatu padu antarabangsa dipamerkan apabila Tanah Melayu diterima menjadi ahli pertubuhan Komanwel dan ___.", "a": "pbb"},
        {"q": "Apakah peranan utama generasi muda hari ini dalam mengisi kemerdekaan negara?", "a": "belajar rajin dan menjaga perpaduan kaum"},
        {"q": "Adakah amalan mengibarkan Jalur Gemilang di rumah semasa Bulan Kemerdekaan dikira amalan patriotik?", "a": "ya"},
        {"q": "Semaikan rasa syukur kerana kita hidup di bumi merdeka yang aman tanpa bunyi letupan ___.", "a": "bom atau perang"},
        {"q": "Pemasyhuran kemerdekaan membuktikan masalah politik boleh diselesaikan melalui meja ___ tanpa pertumpahan darah.", "a": "rundingan"},
        {"q": "Adakah konsep 'Raja Perlembagaan' mula dikuatkuasakan secara rasmi selepas tahun 1957?", "a": "ya"},
        {"q": "Rakyat yang merdeka mempunyai ___ untuk memilih kerajaan sendiri melalui proses pilihan raya.", "a": "hak"},
        {"q": "Apakah warna asal pakaian rasmi musytari yang dipakai oleh Tunku Abdul Rahman semasa hari kemerdekaan?", "a": "putih"},
        {"q": "Adakah reka bentuk Stadium Merdeka diilhamkan sendiri oleh Tunku Abdul Rahman?", "a": "ya"},
        {"q": "Sikap toleransi kaum membolehkan syarat kerakyatan jus soli diterima secara ___ demi perpaduan.", "a": "muafakat"},
        {"q": "Kemerdekaan negara membawa maksud kita bebas membuat keputusan acuan ___ tanpa telunjuk asing.", "a": "sendiri"},
        {"q": "Apakah nama anugerah tertinggi negara yang diberikan kepada tokoh yang banyak berjasa dalam proses kemerdekaan?", "a": "tun"},
        {"q": "Adakah perbuatan memijak bendera negara sendiri mencerminkan jiwa seorang yang merdeka?", "a": "tidak"},
        {"q": "Jiwa yang merdeka ialah jiwa yang bebas daripada belenggu minda ___.", "a": "penjajah atau negatif"},
        {"q": "Sebutkan nama dokumen undang-undang tertinggi negara yang digubal pasca kemerdekaan.", "a": "perlembagaan persekutuan"},
        {"q": "Adakah kedudukan istimewa orang Melayu dan hak kaum lain dilindungi secara adil di dalam Perlembagaan?", "a": "ya"},
        {"q": "Hari Kebangsaan di Malaysia disambut pada tarikh yang sama dengan tarikh kemerdekaan iaitu ___ Ogos.", "a": "31"},
        {"q": "Sikap menghargai keamanan mengelakkan berlakunya perpecahan yang boleh ___ kemerdekaan.", "a": "menggugat"},
        {"q": "Satu hati, satu suara, kita laungkan ___.", "a": "merdeka"},
        {"q": "Merdeka bukan sekadar bebas fizikal, tetapi juga bebas ___.", "a": "minda"},
        {"q": "Tunku memimpin jalan diplomasi, rakyat menyokong penuh ___.", "a": "sehati"},
        {"q": "Tanah airku berdaulat, maruah bangsa ___.", "a": "hebat"},
        {"q": "Kekalkan kemerdekaan, bina masa depan yang ___.", "a": "gemilang"},
        {"q": "Merdeka! Merdeka! ___!", "a": "merdeka"}
    ],

    "pembentukan_malaysia_1963": [
        {"q": "Siapakah nama Perdana Menteri Persekutuan Tanah Melayu yang mencadangkan idea pembentukan Malaysia pada 27 Mei 1961?", "a": "tunku abdul rahman"},
        {"q": "Tunku Abdul Rahman mengumumkan cadangan pembentukan Malaysia di dalam majlis persidangan Persatuan Wartawan Luar Negeri Asia Tenggara di ___.", "a": "singapura"},
        {"q": "Apakah nama gagasan negara baharu yang dicadangkan menggabungkan Persekutuan Tanah Melayu, Singapura, Sarawak, Sabah, dan Brunei?", "a": "malaysia"},
        {"q": "Sebutkan satu sebab utama pembentukan Malaysia dilaksanakan.", "a": "menyekat ancaman komunis atau mengimbangi komposisi penduduk"},
        {"q": "Adakah usaha mempercepatkan proses kemerdekaan bagi Sabah dan Sarawak juga merupakan faktor penubuhan Malaysia?", "a": "ya"},
        {"q": "Apakah nama jawatankuasa awal yang ditubuhkan untuk mengadakan kempen penerangan dan mengumpul pandangan rakyat tentang Malaysia?", "a": "jppk atau jawatankuasa perundingan perpaduan malaysia"},
        {"q": "Siapakah nama tokoh pemimpin dari Sarawak yang mempengerusikan JPPK?", "a": "donald stephens atau tan sri datus dawat"},
        {"q": "Apakah nama suruhanjaya bebas yang dibentuk pada tahun 1962 untuk meninjau pandangan rakyat Sabah dan Sarawak?", "a": "suruhanjaya cobbold"},
        {"q": "Suruhanjaya Cobbold dipengerusikan oleh seorang tokoh British yang bernama Lord ___.", "a": "cobbold"},
        {"q": "Adakah hasil laporan Suruhanjaya Cobbold mendapati majoriti dua pertiga rakyat Sabah dan Sarawak bersetuju menyertai Malaysia?", "a": "ya"},
        {"q": "Apakah nama jawatankuasa yang dibentuk selepas itu untuk merangka syarat-syarat kemasukan Sabah dan Sarawak ke dalam Malaysia?", "a": "jak atau jawatankuasa antar kerajaan"},
        {"q": "Sabah mengemukakan dokumen tuntutan khas yang mengandungi berapa perkara sebagai syarat perlindungan hak mereka?", "a": "dua puluh"},
        {"q": "Sarawak mengemukakan dokumen perlindungan hak yang mengandungi ___ perkara.", "a": "lapan belas"},
        {"q": "Adakah tuntutan hak tersebut merangkumi perkara berkaitan kebebasan beragama, bahasa, dan kawalan imigresen?", "a": "ya"},
        {"q": "Siapakah nama tokoh pemimpin utama dari Sarawak yang menyokong kuat pembentukan Malaysia dan dilantik menjadi Ketua Menteri Sarawak yang pertama?", "a": "tan sri stephen kalong ningkan"},
        {"q": "Siapakah nama tokoh pejuang dari kaum Melanau yang turut menyokong pembentukan Malaysia dan menjadi Yang di-Pertua Negeri Sarawak yang pertama?", "a": "tun abang haji openg"},
        {"q": "Siapakah nama pemimpin utama Sabah dari pertubuhan UNKO yang menyokong penubuhan Malaysia dan menjadi Ketua Menteri Sabah yang pertama?", "a": "tun fuad stephens"},
        {"q": "Siapakah nama tokoh pemimpin Sabah daripada USNO yang dilantik menjadi Yang di-Pertua Negeri Sabah yang pertama?", "a": "tun mustapha datu harun"},
        {"q": "Adakah referendum atau proses pemungutan suara rakyat diadakan di Singapura untuk meninjau persetujuan penduduknya?", "a": "ya"},
        {"q": "Siapakah nama Ketua Menteri Singapura yang mengetuai usaha membawa Singapura menyertai Malaysia?", "a": "lee kuan yew"},
        {"q": "Negara jiran manakah yang melancarkan dasar konfrontasi menentang pembentukan Malaysia dengan slogan 'Ganyang Malaysia'?", "a": "indonesia"},
        {"q": "Siapakah nama Presiden Indonesia yang memimpin gerakan konfrontasi tersebut?", "a": "presiden soekarno"},
        {"q": "Adakah negara Filipina turut menentang penubuhan Malaysia kerana membuat tuntutan rasmi atas wilayah Sabah?", "a": "ya"},
        {"q": "Apakah nama pertubuhan antarabangsa yang diminta oleh Malaysia untuk membuat pengesahan semula pandangan rakyat Sabah dan Sarawak?", "a": "pbb atau pertubuhan bangsa-bangsa bersatu"},
        {"q": "Perisytiharan rasmi penubuhan negara Malaysia dilakukan pada tarikh ___.", "a": "16 september 1963"},
        {"q": "Di manakah lokasi upacara pengisytiharan Malaysia peringkat persekutuan diadakan secara gilang-gemilang?", "a": "stadium merdeka kuala lumpur"},
        {"q": "Tunku Abdul Rahman membacakan Pemasyahiran Malaysia di Kuala Lumpur, manakala di Kuching ia dibacakan oleh Tan Sri ___.", "a": "khaw kai bo"},
        {"q": "Adakah wilayah Brunei akhirnya membatalkan hasrat untuk menyertai Malaysia pada saat-saat akhir?", "a": "ya"},
        {"q": "Pada tahun berapakah Singapura keluar dari gagasan Malaysia untuk menjadi sebuah negara republik yang bebas?", "a": "1965"},
        {"q": "Hari Malaysia disambut pada ___ September setiap tahun dan diisytiharkan sebagai cuti umum di seluruh negara.", "a": "16"},
        {"q": "Adakah penubuhan Malaysia berjaya mewujudkan sebuah wilayah negara yang lebih luas, maju, dan makmur?", "a": "ya"},
        {"q": "Sikap muafakat antara pemimpin Tanah Melayu, Sabah, dan Sarawak membuktikan kepentingan diplomasi dalam ___ negara.", "a": "membina"},
        {"q": "Kita mestilah sentiasa mengekalkan semangat integrasi nasional antara Semenanjung, Sabah, dan ___.", "a": "sarawak"},
        {"q": "Adakah wajar kita membeza-bezakan rakyat Malaysia berdasarkan wilayah asal usul mereka?", "a": "tidak"},
        {"q": "Kepelbagaian etnik dan budaya di Sabah dan Sarawak seperti kaum Ibad, Kadazandusun, dan Murut memperkayakan lagi ___ budaya Malaysia.", "a": "warisan"},
        {"q": "Apakah nama monumen atau tugu peringatan yang dibina di Keningau, Sabah untuk memperingati syarat kesetiaan pembentukan Malaysia?", "a": "batu sumpah keningau"},
        {"q": "Adakah kawalan imigresen ke Sabah dan Sarawak kekal dilindungi sebagai hak autonomi negeri tersebut?", "a": "ya"},
        {"q": "Kejayaan menamatkan konfrontasi Indonesia dicapai melalui jalan perundingan damai yang ditandatangani di bandar ___.", "a": "bangkok atau jakarta"},
        {"q": "Sikap sabar pemimpin menghadapi provokasi luar menyelamatkan negara daripada kancah ___ bersenjata yang besar.", "a": "peperangan"},
        {"q": "Apakah nama perjanjian rasmi yang ditandatangani oleh wakil kerajaan British, Tanah Melayu, Sabah, Sarawak, dan Singapura di London pada Julai 1963?", "a": "perjanjian malaysia atau london agreement"},
        {"q": "Adakah bendera negara Malaysia mengalami perubahan bilangan jalur selepas penyertaan Sabah dan Sarawak?", "a": "ya"},
        {"q": "Bintang pecah 14 pada Jalur Gemilang melambangkan gabungan 13 buah negeri dan wilayah ___.", "a": "persekutuan"},
        {"q": "Sebutkan kepentingan mengekalkan kestabilan politik dalam sebuah negara persekutuan.", "a": "untuk memajukan ekonomi dan menjamin keselamatan rakyat"},
        {"q": "Adakah kita patut meraikan Hari Malaysia dengan penuh rasa bangga dan bersyukur?", "a": "ya"},
        {"q": "Perpaduan kaum merentasi Laut China Selatan menjadi nadi kekuatan kedaulatan ___.", "a": "malaysia"},
        {"q": "Sabah, Sarawak, Tanah Melayu, sehati ___.", "a": "sejiwa"},
        {"q": "Satu reka bentuk negara persekutuan, lambang kehebatan visi ___.", "a": "pemimpin"},
        {"q": "Pertahankan perpaduan wilayah, elakkan hasutan ___.", "a": "perpecahan"},
        {"q": "Malaysia teguh berdiri, tanah airku yang ___.", "a": "tercinta"},
        {"q": "Satu hati, satu matlamat, Malaysia ___.", "a": "berjaya"}
    ],

"lambang_dan_identiti_negara": [
        {"q": "Apakah nama lambang rasmi kerajaan Malaysia yang menjadi simbol kedaulatan dan kemegahan negara?", "a": "jata negara"},
        {"q": "Dua ekor haiwan apakah yang terdapat pada Jata Negara yang melambangkan keberanian?", "a": "harimau"},
        {"q": "Apakah cogan kata rasmi negara yang tertulis pada reben Jata Negara?", "a": "bersekutu bertambah mutu"},
        {"q": "Bintang pecah 14 pada Jata Negara melambangkan perpaduan 13 buah negeri dan ___.", "a": "kerajaan persekutuan"},
        {"q": "Adakah lima bilah keris pada Jata Negara melambangkan lima buah Negeri-negeri Melayu Tidak Bersekutu dahulu?", "a": "ya"},
        {"q": "Empat warna di tengah-tengah perisai (merah, hitam, putih, kuning) merujuk kepada Negeri-negeri Melayu ___.", "a": "bersekutu"},
        {"q": "Apakah nama bendera rasmi negara Malaysia?", "a": "jalur gemilang"},
        {"q": "Siapakah nama tokoh yang telah mereka bentuk bendera asal Persekutuan Tanah Melayu?", "a": "mohamed hamzah"},
        {"q": "Berapakah jumlah keseluruhan jalur berwarna merah dan putih yang terdapat pada Jalur Gemilang?", "a": "empat belas"},
        {"q": "Warna apakah pada Jalur Gemilang yang melambangkan kedaulatan Raja-raja Melayu?", "a": "kuning"},
        {"q": "Warna biru tua pada Jalur Gemilang melambangkan ___ rakyat yang berbilang kaum.", "a": "perpaduan"},
        {"q": "Adakah warna merah pada bendera negara membawa maksud keberanian dan kesediaan berkorban?", "a": "ya"},
        {"q": "Lambang bulan sabit pada Jalur Gemilang merujuk kepada Islam sebagai agama ___.", "a": "persekutuan"},
        {"q": "Apakah nama lagu kebangsaan negara Malaysia?", "a": "negaraku"},
        {"q": "Irama lagu 'Negaraku' diambil daripada rentak lagu rasmi negeri Perak yang berjudul ___.", "a": "terang bulan"},
        {"q": "Adakah kita wajib berdiri tegak dan rapat kaki sebagai tanda hormat apabila lagu 'Negaraku' dinyanyikan?", "a": "ya"},
        {"q": "Lirik lagu 'Negaraku' menekankan doa agar sultan atau raja kita dapat memerintah dengan ___.", "a": "selamat dan takhta"},
        {"q": "Apakah nama bunga kebangsaan bagi negara Malaysia?", "a": "bunga raya"},
        {"q": "Siapakah Perdana Menteri yang telah mengisytiharkan bunga raya sebagai bunga kebangsaan pada tahun 1960?", "a": "tunku abdul rahman"},
        {"q": "Bunga raya dipilih kerana warnanya yang merah merah menyala melambangkan nilai ___.", "a": "keberanian"},
        {"q": "Adakah lima kelopak bunga raya melambangkan lima prinsip Rukun Negara?", "a": "ya"},
        {"q": "Sikap menghormati lambang negara membuktikan tahap semangat ___ yang tinggi dalam diri seseorang.", "a": "patriotisme"},
        {"q": "Adakah perbuatan membiarkan bendera negara jatuh ke tanah atau menggunakannya sebagai alas meja dibenarkan?", "a": "tidak"},
        {"q": "Jata Negara boleh ditemukan pada dokumen rasmi kerajaan seperti kad pengenalan dan ___.", "a": "pasport"},
        {"q": "Simbol pokok pinang dan jambatan pada Jata Negara mewakili negeri ___.", "a": "pulau pinang"},
        {"q": "Simbol pokok melaka pada perisai Jata Negara mewakili negeri ___.", "a": "melaka"},
        {"q": "Adakah negeri Sabah dan Sarawak turut diwakili oleh lambang negeri masing-masing di bahagian bawah perisai Jata Negara?", "a": "ya"},
        {"q": "Penciptaan bendera negara membuktikan bahawa kita adalah sebuah negara yang ___ daripada penjajahan.", "a": "bebas atau merdeka"},
        {"q": "Lagu kebangsaan berfungsi untuk membangkitkan semangat kesetiaan dan ___ cinta akan tanah air.", "a": "rasa"},
        {"q": "Adakah murid yang menyanyikan lagu kebangsaan secara main-main boleh dikenatus tindakan disiplin?", "a": "ya"},
        {"q": "Penggunaan lambang negara diatur di bawah undang-undang rasmi yang dinamakan Akta ___ dan Nama.", "a": "lambang"},
        {"q": "Apabila bendera Jalur Gemilang sudah terlalu uzur atau koyak, cara melupuskannya yang betul ialah dengan cara ___ secara tertutup.", "a": "membakarnya"},
        {"q": "Adakah wajar kita mengubah lirik lagu 'Negaraku' mengikut rentak muzik moden sesuka hati?", "a": "tidak"},
        {"q": "Warna putih pada Jalur Gemilang membawa maksud kesucian dan ___.", "a": "keikhlasan"},
        {"q": "Bintang pecah 14 pada bendera negara juga dikenali sebagai Bintang ___.", "a": "persekutuan"},
        {"q": "Adakah lagu kebangsaan mula diperdengarkan secara rasmi pada malam 31 Ogos 1957?", "a": "ya"},
        {"q": "Bunga raya tergolong dalam keluarga tumbuhan yang dinamakan ___.", "a": "hibiscus"},
        {"q": "Kepelbagaian kegunaan bunga raya dalam perubatan tradisional menjadikannya dekat dengan kehidupan ___ tempatan.", "a": "masyarakat"},
        {"q": "Adakah jata negara mengalami beberapa kali perubahan reka bentuk seiring dengan perkembangan sejarah penubuhan Malaysia?", "a": "ya"},
        {"q": "Lambang bulan sabit dan bintang diletakkan di bahagian ___ perisai Jata Negara.", "a": "atas"},
        {"q": "Setiap lambang negara dicipta dengan penuh makna yang mendalam untuk memandu hala tuju ___.", "a": "bangsa"},
        {"q": "Adakah kenderaan rasmi Perdana Menteri menggunakan plat khas yang mempamerkan lambang Jata Negara?", "a": "ya"},
        {"q": "Kibarkan Jalur Gemilang dengan penuh rasa bangga, terutama sepanjang Bulan ___.", "a": "kemerdekaan atau kebangsaan"},
        {"q": "Identiti negara yang kukuh membentuk ___ diri yang disegani di peringkat antarabangsa.", "a": "jati"},
        {"q": "Cintailah lambang negara kita kerana ia adalah maruah ___.", "a": "kita atau tanah air"},
        {"q": "Jalur Gemilang berkibar megah, tanda negara ___.", "a": "merdeka"},
        {"q": "Satu Jata, Satu Bendera, Satu Lagu, Bersatu ___.", "a": "kita"},
        {"q": "Hormati identiti negara, kekalkan kedaulatan ___.", "a": "malaysia"},
        {"q": "Negaraku tanah tumpahnya darah ___.", "a": "ku"},
        {"q": "Lambang negara dipelihara, maruah bangsa ___.", "a": "terjaga"}
    ],

    "rukun_negara_dan_kaum_di_malaysia": [
        {"q": "Apakah nama ideologi kebangsaan yang digubal untuk membentuk perpaduan kaum selepas peristiwa 13 Mei 1969?", "a": "rukun negara"},
        {"q": "Rukun Negara telah diisytiharkan oleh Yang di-Pertuan Agong pada 31 Ogos tahun ___.", "a": "1970"},
        {"q": "Berapakah jumlah prinsip yang terkandung di dalam Rukun Negara?", "a": "lima"},
        {"q": "Sebutkan prinsip pertama di dalam Rukun Negara.", "a": "kepercayaan kepada tuhan"},
        {"q": "Prinsip kedua Rukun Negara ialah Kesetiaan kepada ___ dan Negara.", "a": "raja"},
        {"q": "Apakah prinsip ketiga Rukun Negara?", "a": "keluhuran perlembagaan"},
        {"q": "Prinsip keempat Rukun Negara menggariskan tentang Kedaulatan Undang-___.", "a": "undang"},
        {"q": "Apakah prinsip kelima Rukun Negara?", "a": "kesopanan dan kesusilaan"},
        {"q": "Prinsip 'Kepercayaan kepada Tuhan' mendidik rakyat agar mempunyai pegangan ___ demi membentuk peribadi yang baik.", "a": "agama"},
        {"q": "Adakah amalan menghormati institusi beraja terkandung di dalam prinsip kedua Rukun Negara?", "a": "ya"},
        {"q": "Prinsip 'Keluhuran Perlembagaan' menuntut rakyat supaya menghormati undang-undang ___ negara.", "a": "tertinggi"},
        {"q": "Prinsip 'Kesopanan dan Kesusilaan' bertujuan membentuk warganegara yang berbudi ___ dan berakhlak mulia.", "a": "bahasa"},
        {"q": "Masyarakat Malaysia terdiri daripada pelbagai kaum seperti Melayu, Cina, India, dan bumiputera Sabah serta ___.", "a": "sarawak"},
        {"q": "Kaum terbesar di Semenanjung Malaysia ialah kaum ___.", "a": "melayu"},
        {"q": "Adakah kaum Kadazandusun merupakan antara kaum bumiputera terbesar yang menetap di negeri Sabah?", "a": "ya"},
        {"q": "Sebutkan etnik bumiputera terbesar yang terdapat di negeri Sarawak.", "a": "iban"},
        {"q": "Etnik Orang Asli di Semenanjung Malaysia terbahagi kepada tiga kumpulan utama, iaitu Senoi, Negrito, dan Melayu ___.", "a": "proto"},
        {"q": "Adakah perayaan Hari Gawai merupakan pesta menuai tradisional yang disambut oleh kaum Iban dan Bidayuh di Sarawak?", "a": "ya"},
        {"q": "Apakah nama pesta menuai padi yang disambut setahun sekali oleh kaum Kadazandusun di Sabah?", "a": "pesta kaamatan"},
        {"q": "Tarian ___ merupakan tarian tradisional etnik Iban yang ditarikan semasa perayaan Hari Gawai.", "a": "ngajat"},
        {"q": "Adakah tarian Singa dan tarian Naga merupakan warisan budaya seni bagi kaum Cina?", "a": "ya"},
        {"q": "Apakah nama tarian tradisional kaum India yang terkenal dengan gerakan tangan dan ekspresi mata yang tajam?", "a": "bharatanatyam"},
        {"q": "Makanan tradisional seperti nasi lemak, roti canai, dan char kuey teow membuktikan wujudnya ___ budaya pemakanan di Malaysia.", "a": "asimilasi atau kepelbagaian"},
        {"q": "Adakah pakaian tradisional baju kurung dan baju melayu sering dipakai semasa sambutan Hari Raya Aidilfitri?", "a": "ya"},
        {"q": "Apakah nama pakaian tradisional wanita kaum Cina yang mempunyai kolar tinggi dan potongan mengikut bentuk badan?", "a": "cheongsam"},
        {"q": "Pakaian tradisional wanita kaum India yang diperbuat daripada kain panjang yang dililit indah dinamakan ___.", "a": "sari"},
        {"q": "Adakah perayaan Deepavali dirayakan oleh penganut agama Hindu sebagai simbol kemenangan cahaya ke atas kegelapan?", "a": "ya"},
        {"q": "Sambutan Tahun Baru Cina ditandai dengan pemberian ___ berwarna merah kepada ahli keluarga yang belum berkahwin.", "a": "angpau"},
        {"q": "Sikap toleransi dan saling menghormati adat resam kaum lain merupakan kunci utama kepada ___ nasional.", "a": "perpaduan"},
        {"q": "Adakah amalan 'rumah terbuka' semasa musim perayaan membantu mengeratkan hubungan antara kaum di Malaysia?", "a": "ya"},
        {"q": "Kepelbagaian kaum di negara kita mestilah dilihat sebagai satu ___ dan bukannya punca perpecahan.", "a": "keunikan atau kekuatan"},
        {"q": "Sikap prejudis atau bersangka buruk terhadap kaum lain boleh ___ keharmonian hidup bermasyarakat.", "a": "merosakkan"},
        {"q": "Adakah Rukun Negara wajib dihafal dan diamalkan oleh setiap murid sekolah di Malaysia?", "a": "ya"},
        {"q": "Melalui prinsip Kedaulatan Undang-undang, tiada individu yang berada ___ daripada undang-undang.", "a": "lebih tinggi"},
        {"q": "Masyarakat asli suku kaum Penan di Sarawak terkenal dengan kemahiran membuat kraf tangan hasil ___.", "a": "hutan"},
        {"q": "Adakah bahasa Melayu bertindak sebagai bahasa penyatu komunikasi antara pelbagai kaum di Malaysia?", "a": "ya"},
        {"q": "Apakah nama alat muzik tradisional kaum Cina yang berbentuk bulat dan dipetik seperti gitar?", "a": "ruan atau pipa"},
        {"q": "Alat muzik gendang tradisional kaum India yang dimainkan dengan kedua-dua belah tangan dinamakan ___.", "a": "mridangam atau dholak"},
        {"q": "Adakah amalan mengejek makanan atau budaya tradisional etnik lain bertentangan dengan prinsip kelima Rukun Negara?", "a": "ya"},
        {"q": "Perlembagaan Persekutuan menjamin hak kebebasan ___ bagi setiap warganegara Malaysia.", "a": "beragama"},
        {"q": "Saling berkunjung ke rumah rakan yang berlainan bangsa membina jambatan ___ yang kukuh.", "a": "kemesraan atau kasih sayang"},
        {"q": "Adakah wajar murid sekolah membentuk kumpulan rakan berdasarkan faktor kaum sahaja?", "a": "tidak"},
        {"q": "Kita mestilah bangga menjadi bangsa Malaysia yang hidup bersatu padu di bawah naungan ___.", "a": "jalur gemilang"},
        {"q": "Rukun Negara menjadi kompas moral dalam melahirkan masyarakat yang ___.", "a": "adil atau harmoni"},
        {"q": "Suku kaum Bajau di Sabah terkenal dengan gelaran 'Koboi ___' kerana kehebatan mereka menunggang kuda.", "a": "timur"},
        {"q": "Bersatu kita teguh, bercerai kita ___.", "a": "roboh"},
        {"q": "Lima prinsip Rukun Negara, panduan hidup warganegara ___.", "a": "sejati"},
        {"q": "Kepelbagaian kaum satu keunikan, perpaduan erat membawa ___.", "a": "kemakmuran"},
        {"q": "Hormati budaya, sanjung ___.", "a": "tradisi"},
        {"q": "Malaysia harmoni, rakyat sehati ___.", "a": "sejiwa"}
    ],

    "pemimpin_negara_dan_perdana_menteri": [
        {"q": "Apakah nama jawatan bagi ketua eksekutif kerajaan yang memimpin pentadbiran negara Malaysia?", "a": "perdana menteri"},
        {"q": "Siapakah nama Perdana Menteri Malaysia yang pertama?", "a": "tunku abdul rahman putra al-haj"},
        {"q": "Tunku Abdul Rahman digelar sebagai Bapa ___.", "a": "kemerdekaan"},
        {"q": "Siapakah nama Perdana Menteri Malaysia yang kedua yang terkenal dengan gelaran Bapa Pembangunan?", "a": "tun abdul razak hussein"},
        {"q": "Tun Abdul Razak melancarkan Dasar Ekonomi Baru (DEB) untuk membasmi ___ dalam kalangan rakyat.", "a": "kemiskinan"},
        {"q": "Siapakah nama Perdana Menteri Malaysia yang ketiga yang mendapat gelaran Bapa Perpaduan?", "a": "tun hussein onn"},
        {"q": "Tun Hussein Onn sangat tegas dalam mengukuhkan perpaduan kaum dan menjaga ___ negara.", "a": "keamanan"},
        {"q": "Siapakah nama Perdana Menteri Malaysia yang keempat yang memimpin negara selama 22 tahun dalam fasa pertama pentadbirannya?", "a": "tun dr. mahathir mohamad"},
        {"q": "Tun Dr. Mahathir Mohamad digelar sebagai Bapa ___ kerana membawa era industri moden di Malaysia.", "a": "pemodenan"},
        {"q": "Wawasan 2020 yang bermatlamat menjadikan Malaysia sebuah negara maju telah diilhamkan oleh ___.", "a": "tun dr. mahathir mohamad"},
        {"q": "Siapakah Perdana Menteri Malaysia kelima yang memperkenalkan konsep Islam Hadhari dan digelar Bapa Pembangunan Modal Insan?", "a": "tun abdullah ahmad badawi"},
        {"q": "Tun Abdullah Ahmad Badawi mesra dengan panggilan 'Pak ___' oleh rakyat Malaysia.", "a": "lah"},
        {"q": "Adakah Perdana Menteri dilantik secara rasmi oleh Yang di-Pertuan Agong mengikut peruntukan Perlembagaan Persekutuan?", "a": "ya"},
        {"q": "Seseorang Perdana Menteri mestilah mendapat sokongan ___ ahli Dewan Rakyat di Parlimen.", "a": "majoriti"},
        {"q": "Adakah projek pembinaan Menara Berkembar PETRONAS (KLCC) dilaksanakan semasa zaman pentadbiran Tun Dr. Mahathir Mohamad?", "a": "ya"},
        {"q": "Apakah nama pusat pentadbiran kerajaan persekutuan yang baharu yang dibuka semasa era kepimpinan Perdana Menteri keempat?", "a": "putrajaya"},
        {"q": "Tun Abdul Razak menubuhkan FELDA untuk membantu masyarakat luar bandar meningkatkan taraf ekonomi melalui pertanian ___.", "a": "kelapa sawit dan getah"},
        {"q": "Adakah Tunku Abdul Rahman yang mengetuai rombongan ke London bagi menuntut kemerdekaan negara?", "a": "ya"},
        {"q": "Setiap Perdana Menteri mempunyai sumbangan yang amat besar dalam mencorakkan ___ masa depan negara.", "a": "kemajuan"},
        {"q": "Sikap kepimpinan yang berwibawa, bijaksana, dan prihatin adalah ciri utama barisan ___ negara kita.", "a": "pemimpin"},
        {"q": "Adakah kita patut menghargai dan menghormati jasa-jasa mantan Perdana Menteri negara?", "a": "ya"},
        {"q": "Apakah nama kediaman rasmi bagi Perdana Menteri Malaysia yang terletak di Putrajaya?", "a": "seri perdana"},
        {"q": "Tun Hussein Onn aktif menubuhkan skim Amanah Saham Nasional (ASN) untuk membantu meningkatkan ___ kaum bumiputera.", "a": "ekonomi"},
        {"q": "Adakah Tun Dr. Mahathir Mohamad merupakan pencetus idea penubuhan syarikat kereta nasional pertama negara, PROTON?", "a": "ya"},
        {"q": "Koridor Raya Multimedia (MSC) dibina untuk memajukan sektor teknologi ___ di Malaysia.", "a": "maklumat atau it"},
        {"q": "Tun Abdullah Ahmad Badawi memberikan tumpuan yang besar kepada pembangunan sektor ___ moden.", "a": "pertanian"},
        {"q": "Adakah barisan pemimpin negara kita sentiasa mengutamakan kestabilan politik demi menarik pelabur asing?", "a": "ya"},
        {"q": "Setiausaha politik dan jemaah menteri bertindak sebagai pasukan pembantu kepada ___ dalam mentadbir negara.", "a": "perdana menteri"},
        {"q": "Sikap keterbukaan menerima teguran rakyat diamalkan oleh pemimpin demi mengekalkan amalan ___.", "a": "demokrasi"},
        {"q": "Adakah wajar kita melemparkan fitnah atau tohmahan jahat terhadap institusi pemimpin negara di media sosial?", "a": "tidak"},
        {"q": "Menghormati pemimpin bermaksud kita menghargai institusi tata kelola ___ negara.", "a": "pentadbiran"},
        {"q": "Tunku Abdul Rahman berjaya menangani ancaman komunis awal melalui strategi diplomasi dan ___.", "a": "perundingan"},
        {"q": "Dasar Pandang Ke Timur yang diperkenalkan era 1980-an bertujuan mencontohi etika kerja cemerlang dari negara Jepun dan ___.", "a": "korea selatan"},
        {"q": "Adakah jambatan pertama yang menghubungkan Pulau Pinang dengan tanah besar dibina pada era Tun Dr. Mahathir Mohamad?", "a": "ya"},
        {"q": "Mengkaji biografi Perdana Menteri menyuntik inspirasi kepada murid untuk menjadi ___ berwibawa pada masa hadapan.", "a": "pemimpin"},
        {"q": "Seseorang pemimpin yang cemerlang sentiasa mendahulukan kepentingan ___ berbanding kepentingan diri sendiri.", "a": "rakyat atau negara"},
        {"q": "Apakah nama agensi yang menguruskan keselamatan sempadan maritim negara yang diperkukuh oleh kerajaan?", "a": "apmm atau maritim malaysia"},
        {"q": "Adakah dasar luar Malaysia yang mengamalkan prinsip berkecuali membantu mengekalkan hubungan diplomatik yang baik dengan semua negara?", "a": "ya"},
        {"q": "Slogan 'Bersih, Cekap, dan Amanah' menjadi teras amalan kerja penjawat awam yang diperkenalkan oleh ___.", "a": "tun dr. mahathir mohamad"},
        {"q": "Pemimpin bertukar ganti, namun perjuangan membina kemakmuran negara tetap ___.", "a": "diteruskan"},
        {"q": "Adakah kestabilan ekonomi sesebuah negara banyak bergantung kepada kebijaksanaan corak kepimpinan Perdana Menterinya?", "a": "ya"},
        {"q": "Kita mestilah sentiasa ___ kepimpinan negara agar Malaysia kekal aman dan makmur.", "a": "menyokong atau menghormati"},
        {"q": "Pemimpin adil membawa berkat, rakyat makmur negara ___.", "a": "selamat"},
        {"q": "Sumbangan pemimpin masa lalu, asas kekuatan generasi ___.", "a": "hari ini"},
        {"q": "Sanjungi jasa pemimpin kita, elakkan budaya meremehkan ___ mereka.", "a": "pengorbanan"},
        {"q": "Satu kepimpinan, satu visi, memacu kemajuan ___.", "a": "bangsa"},
        {"q": "Bapa Kemerdekaan memulakan langkah, Bapa Pembangunan meneruskan ___.", "a": "agenda"},
        {"q": "Pemimpin berwibawa, negara ___.", "a": "disegani"},
        {"q": "Taat setia kepada pemimpin, tanda cinta akan ___.", "a": "negara"},
        {"q": "Terima kasih Perdana Menteri, jasa mu tetap abadi di dalam ___ sejarah.", "a": "lipatan"}
    ]
};