// =========================================================================
// DATA SOALAN BAHASA MELAYU - TAHAP MUDAH (EASY BLOCK)
// SETIAP KATEGORI MEMPUNYAI TEPAT 50 SOALAN (ARAS RENDAH & MESRA MURID)
// =========================================================================

const malayLanguageData = {
    // 🟢 TAHAP MUDAH (+1 XP) - KATEGORI 1: KATA NAMA (50 SOALAN)
    "kata_nama": [
        {"q": "Apakah jenis kata nama bagi perkataan 'kucing' dan 'sekolah'?", "a": "kata nama am"},
        {"q": "Apakah jenis kata nama bagi perkataan 'Melaka' dan 'Proton Saga'?", "a": "kata nama khas"},
        {"q": "Kata Nama Khas mestilah ditulis dengan huruf ___ di permulaan perkataan.", "a": "besar"},
        {"q": "Perkataan 'saya', 'kamu', dan 'dia' ialah contoh kata ganti nama ___.", "a": "diri"},
        {"q": "Kata ganti diri ketiga yang digunakan khas untuk raja atau sultan ialah ___.", "a": "baginda"},
        {"q": "Apakah kata ganti nama tanya yang digunakan untuk menanyakan orang?", "a": "siapa"},
        {"q": "Apakah kata ganti nama tanya yang digunakan untuk menanyakan benda atau haiwan?", "a": "apa"},
        {"q": "Apakah kata ganti nama tunjuk untuk menunjukkan benda atau tempat yang dekat?", "a": "ini"},
        {"q": "Apakah kata ganti nama tunjuk untuk menunjukkan benda atau tempat yang jauh?", "a": "itu"},
        {"q": "Kata ganti diri ketiga yang digunakan secara hormat untuk tokoh atau orang berjasa ialah ___.", "a": "beliau"},
        {"q": "Apakah kata ganti diri pertama yang digunakan apabila bercakap dengan raja?", "a": "patik"},
        {"q": "Apakah kata ganti diri pertama yang digunakan oleh raja atau sultan sendiri?", "a": "beta"},
        {"q": "Apakah kata ganti diri kedua yang digunakan untuk merujuk orang yang ramai?", "a": "kalian"},
        {"q": "Apakah kata ganti nama tanya yang digunakan untuk menanyakan tempat?", "a": "mana"},
        {"q": "Apakah kata ganti nama tanya yang digunakan untuk menanyakan masa atau waktu?", "a": "bila"},
        {"q": "Apakah kata ganti nama tanya yang digunakan untuk menanyakan harga atau bilangan?", "a": "berapa"},
        {"q": "Apakah kata ganti nama tanya yang digunakan untuk menanyakan sebab atau punca?", "a": "mengapa"},
        {"q": "Perkataan 'Sang Kancil' dan 'Si Comel' dikategorikan sebagai kata nama ___.", "a": "khas"},
        {"q": "Kata ganti diri pertama untuk sekumpulan orang (tidak termasuk orang yang mendengar) ialah ___.", "a": "kami"},
        {"q": "Kata ganti diri pertama untuk sekumpulan orang (termasuk orang yang mendengar) ialah ___.", "a": "kita"},
        {"q": "Perkataan 'harimau' dan 'gajah' ialah kata nama am bagi kumpulan ___.", "a": "haiwan"},
        {"q": "Perkataan 'Hospital Kuala Lumpur' ialah contoh kata nama ___.", "a": "khas"},
        {"q": "Apakah kata ganti diri kedua yang paling biasa digunakan untuk kawan sebaya?", "a": "kamu"},
        {"q": "Apakah kata ganti diri ketiga yang digunakan untuk seorang kawan atau orang biasa?", "a": "dia"},
        {"q": "Apakah kata ganti diri pertama yang paling sopan digunakan untuk diri sendiri sehari-hari?", "a": "saya"},
        {"q": "Perkataan 'meja' dan 'kerusi' ialah kata nama am bagi kumpulan ___.", "a": "benda"},
        {"q": "Perkataan 'Persatuan Bulan Sabit Merah' ialah contoh kata nama ___.", "a": "khas"},
        {"q": "Apakah kata ganti diri kedua dalam ayat: 'Awak hendak pergi ke mana?'", "a": "awak"},
        {"q": "Apakah kata ganti diri pertama dalam ayat: 'Aku mahu makan nasi lemak.'", "a": "aku"},
        {"q": "Perkataan 'SJKC Chung Hwa' ditulis dengan huruf besar di awal perkataan kerana ia kata nama ___.", "a": "khas"},
        {"q": "Perkataan 'bapa', 'ibu', dan 'adik' merujuk kata nama am bagi ___.", "a": "manusia"},
        {"q": "Perkataan 'kasut', 'baju', dan 'beg' ialah contoh kata nama ___.", "a": "am"},
        {"q": "Perkataan 'Pulau Langkawi' ialah kata nama khas bagi jenis ___.", "a": "tempat"},
        {"q": "Nama bendera negara kita ialah 'Jalur Gemilang'. Jalur Gemilang ialah kata nama ___.", "a": "khas"},
        {"q": "Perkataan 'Sungai Rajang' ditulis menggunakan huruf besar kerana ia kata nama ___.", "a": "khas"},
        {"q": "Perkataan 'balai polis', 'taman', dan 'kedai' ialah kata nama am bagi ___.", "a": "tempat"},
        {"q": "Perkataan 'buku', 'pembaris', dan 'pensel' ialah kata nama am bagi ___.", "a": "benda"},
        {"q": "Perkataan 'doktor', 'jururawat', dan 'tentera' ialah kata nama am bagi ___.", "a": "manusia"},
        {"q": "Apakah kata ganti diri kedua yang digunakan dalam surat rasmi atau kad arahan?", "a": "anda"},
        {"q": "Apakah kata ganti diri pertama yang digunakan dalam cerita zaman dahulu atau bangsawan?", "a": "hamba"},
        {"q": "Perkataan 'negeri' ialah kata nama am, manakala perkataan 'Selangor' ialah kata nama ___.", "a": "khas"},
        {"q": "Perkataan 'kereta' ialah kata nama am, manakala perkataan 'Perodua Myvi' ialah kata nama ___.", "a": "khas"},
        {"q": "Perkataan 'gunung' ialah kata nama am, manakala perkataan 'Gunung Kinabalu' ialah kata nama ___.", "a": "khas"},
        {"q": "Perkataan 'laut' ialah kata nama am, manakala perkataan 'Laut China Selatan' ialah kata nama ___.", "a": "khas"},
        {"q": "Perkataan 'bendera' ialah kata nama am, manakala perkataan 'Malaysia' ialah kata nama ___.", "a": "khas"},
        {"q": "Kata ganti nama tanya mestilah diakhiri dengan tanda ___ di hujung ayat.", "a": "tanya"},
        {"q": "Kata ganti nama tunjuk 'ini' digunakan untuk benda yang berada di kedudukan ___.", "a": "dekat"},
        {"q": "Kata ganti nama tunjuk 'itu' digunakan untuk benda yang berada di kedudukan ___.", "a": "jauh"},
        {"q": "Tukar perkataan 'tupai' menjadi kata nama khas dengan menambah kata panggilan haiwan: ___ Tupai.", "a": "Sang"},
        {"q": "Apakah jenis ganti nama bagi perkataan 'mereka'?", "a": "kata ganti diri ketiga"}
    ],

    // 🟢 TAHAP MUDAH (+1 XP) - KATEGORI 2: KATA KERJA (50 SOALAN)
    "kata_kerja": [
        {"q": "Apakah kata kerja bagi perbuatan membersihkan lantai menggunakan penyapu?", "a": "menyapu"},
        {"q": "Apakah kata kerja bagi perbuatan membaca buku cerita?", "a": "membaca"},
        {"q": "Burung bergerak di udara dengan menggunakan sayapnya untuk ___.", "a": "terbang"},
        {"q": "Adik sedang ___ televisyen di ruang tamu bersama emak.", "a": "menonton"},
        {"q": "Ikan mas itu bergerak di dalam akuarium dengan cara ___.", "a": "berenang"},
        {"q": "Perbuatan memotong bawang kecil menggunakan pisau dipanggil ___.", "a": "menghiris"},
        {"q": "Perbuatan menyanyikan lagu di atas pentas dipanggil ___.", "a": "menyanyi"},
        {"q": "Perbuatan mengumpul wang simpanan ke dalam tabung dipanggil ___.", "a": "menabung"},
        {"q": "Apakah perkataan lawan bagi kata kerja 'membeli'?", "a": "menjual"},
        {"q": "Apakah perkataan lawan bagi kata kerja 'membuka'?", "a": "menutup"},
        {"q": "Perbuatan menghasilkan tulisan menggunakan pensel di atas kertas dipanggil ___.", "a": "menulis"},
        {"q": "Perbuatan bergerak dengan sangat laju menggunakan kaki dipanggil ___.", "a": "berlari"},
        {"q": "Perbuatan bergerak secara santai menggunakan kaki dipanggil ___.", "a": "berjalan"},
        {"q": "Perbuatan menutup mata untuk berehat pada waktu malam dipanggil ___.", "a": "tidur"},
        {"q": "Perbuatan memasukkan makanan seperti nasi ke dalam mulut dipanggil ___.", "a": "makan"},
        {"q": "Perbuatan memasukkan cecair seperti air kosong ke dalam mulut dipanggil ___.", "a": "minum"},
        {"q": "Perbuatan membersihkan tangan menggunakan air dan sabun dipanggil ___.", "a": "membasuh"},
        {"q": "Perbuatan membuat gambar pemandangan menggunakan pensel warna dipanggil ___.", "a": "melukis"},
        {"q": "Perbuatan mencampakkan sampah ke dalam tong sampah dipanggil ___.", "a": "membuang"},
        {"q": "Perbuatan meletakkan benih pokok bunga ke dalam tanah dipanggil ___.", "a": "menanam"},
        {"q": "Perbuatan mencurahkan air pada pokok bunga di taman dipanggil ___.", "a": "menyiram"},
        {"q": "Perbuatan menolak bola dengan kuat menggunakan kaki dipanggil ___.", "a": "menendang"},
        {"q": "Perbuatan menyambut bola yang dibaling menggunakan tangan dipanggil ___.", "a": "menangkap"},
        {"q": "Perbuatan membawa beg sekolah di atas belakang badan dipanggil ___.", "a": "menggalas"},
        {"q": "Perbuatan membawa baldi air di sebelah tangan yang lurus ke bawah dipanggil ___.", "a": "menjinjing"},
        {"q": "Perbuatan membawa barang berat di atas bahu dipanggil ___.", "a": "memikul"},
        {"q": "Perbuatan membawa anak kecil di dalam dakapan tangan dipanggil ___.", "a": "mendakap"},
        {"q": "Ibu memasak beras di dalam periuk elektrik. Perbuatan ini dipanggil ___ nasi.", "a": "menanak"},
        {"q": "Ibu memasak ikan di dalam kuali berisi minyak panas. Perbuatan ini dipanggil ___.", "a": "menggoreng"},
        {"q": "Kakak memasak telur di dalam air yang sedang mendidih. Perbuatan ini dipanggil ___.", "a": "merebus"},
        {"q": "Perbuatan membuang kulit buah epal menggunakan pisau dipanggil ___.", "a": "mengupas"},
        {"q": "Abang memotong sebatang kayu menggunakan gergaji. Perbuatan ini dipanggil ___.", "a": "memotong"},
        {"q": "Apakah perkataan lawan bagi kata kerja 'menang'?", "a": "kalah"},
        {"q": "Apakah perkataan lawan bagi kata kerja 'menangis'?", "a": "ketawa"},
        {"q": "Perbuatan bergerak naik ke atas kawasan bukit atau gunung dipanggil ___.", "a": "mendaki"},
        {"q": "Perbuatan memasukkan surat ke dalam peti surat dipanggil ___.", "a": "memasukkan"},
        {"q": "Perbuatan mengeluarkan wang dari dalam tabung simpanan dipanggil ___.", "a": "mengeluarkan"},
        {"q": "Abang membersihkan habuk pada cermin tingkap menggunakan kain. Perbuatan ini dipanggil ___.", "a": "mengelap"},
        {"q": "Murid-murid beratur sebelum ___ bas untuk pulang ke rumah.", "a": "menaiki"},
        {"q": "Bapa menggunakan stereng untuk ___ kereta menuju ke pejabat.", "a": "memandu"},
        {"q": "Kamil mengayuh pedal untuk ___ basikal baharunya di taman.", "a": "menunggang"},
        {"q": "Kanak-kanak itu melonjakkan badannya ke atas tilam. Perbuatan ini dipanggil ___.", "a": "melompat"},
        {"q": "Murid-murid sedang ___ taklimat yang disampaikan oleh guru besar.", "a": "mendengar"},
        {"q": "Saya menggunakan mata untuk ___ keindahan burung terbang di langit.", "a": "melihat"},
        {"q": "Adik suka ___ mainan baharu di kedai runcit itu.", "a": "membeli"},
        {"q": "Kakak ___ sekuntum bunga mawar yang berkembang mekar di taman.", "a": "memetik"},
        {"q": "Perbuatan meletakkan buku-buku secara kemas di atas rak dipanggil ___.", "a": "menyusun"},
        {"q": "Perbuatan menghilangkan kedutan pada baju menggunakan seterika panas dipanggil ___.", "a": "menggosok"},
        {"q": "Perbuatan memotong kertas lukisan menggunakan gunting dipanggil ___.", "a": "menggunting"},
        {"q": "Sebelum bermain bola, Ali ___ tali kasutnya supaya tidak longgar.", "a": "mengikat"}
    ],

    // 🟢 TAHAP MUDAH (+1 XP) - KATEGORI 3: KATA ADJEKTIF (50 SOALAN)
    "kata_adjektif": [
        {"q": "Perkataan 'merah', 'hijau', dan 'kuning' ialah kata adjektif jenis ___.", "a": "warna"},
        {"q": "Apakah kata adjektif yang sesuai untuk pisau yang mudah memotong daging?", "a": "tajam"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'tebal'?", "a": "nipis"},
        {"q": "Apakah kata adjektif untuk menggambarkan bau wangi pada minyak wangi?", "a": "wangi"},
        {"q": "Apakah kata adjektif untuk menggambarkan rasa manis pada gula?", "a": "manis"},
        {"q": "Apakah kata adjektif bagi rasa buah peria atau ubat batuk?", "a": "pahit"},
        {"q": "Apakah kata adjektif bagi keadaan air yang telah diletakkan ketulan ais?", "a": "sejuk"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'mahal'?", "a": "murah"},
        {"q": "Bilik tidur yang tidak dikemas selepas bangun tidur akan kelihatan ___.", "a": "sepah"},
        {"q": "Murid yang rajin mengulang kaji pelajaran akan menjadi ___.", "a": "bijak"},
        {"q": "Perkataan 'biru', 'putih', dan 'hitam' ialah kata adjektif jenis ___.", "a": "warna"},
        {"q": "Apakah bentuk bagi objek bola, guli, dan buah oren?", "a": "bulat"},
        {"q": "Apakah kata adjektif bentuk bagi sebatang pembaris atau tiang lampu?", "a": "lurus"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'panjang'?", "a": "pendek"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'besar'?", "a": "kecil"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'tinggi'?", "a": "rendah"},
        {"q": "Apakah kata adjektif bau bagi longgokan sampah yang tidak dibuang?", "a": "busuk"},
        {"q": "Apakah kata adjektif rasa bagi air laut atau garam dapur?", "a": "masin"},
        {"q": "Apakah kata adjektif rasa bagi sebiji buah mangga muda atau lemon?", "a": "masam"},
        {"q": "Apakah kata adjektif rasa bagi segelas air masakan kosong tanpa gula?", "a": "tawar"},
        {"q": "Air yang sedang mendidih di atas dapur gas mempunyai suhu yang ___.", "a": "panas"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'kaya'?", "a": "miskin"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'bersih'?", "a": "kotor"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'rajin'?", "a": "malas"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'pantas' atau 'laju'?", "a": "lambat"},
        {"q": "Pakaian sekolah yang telah dibasuh dan digosok akan kelihatan sangat ___.", "a": "rapi"},
        {"q": "Suasana di dalam pasar malam itu sangat ___ dengan suara penjual.", "a": "bising"},
        {"q": "Suasana di dalam perpustakaan sekolah mestilah sentiasa ___.", "a": "sunyi"},
        {"q": "Permukaan batu jalan tar itu terasa ___ apabila disentuh.", "a": "kasar"},
        {"q": "Kain sutera itu terasa sangat ___ dan selesa dipakai.", "a": "lembut"},
        {"q": "Jarak dari rumah saya ke sekolah tidak jauh, iaitu sangat ___.", "a": "dekat"},
        {"q": "Negara England terletak sangat ___ dari negara Malaysia.", "a": "jauh"},
        {"q": "Apakah kata adjektif perasaan bagi seorang murid yang mendapat hadiah?", "a": "gembira"},
        {"q": "Adik berasa sangat ___ apabila kucing kesayangannya hilang.", "a": "sedih"},
        {"q": "Kanak-kanak itu berasa ___ apabila ternampak seekor anjing garang.", "a": "takut"},
        {"q": "Bapa menjadi ___ apabila mendapati cermin keretanya pecah.", "a": "marah"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'gemuk'?", "a": "kurus"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'muda'?", "a": "tua"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'baharu'?", "a": "lama"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'berat'?", "a": "ringan"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'luas'?", "a": "sempit"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'terang'?", "a": "gelap"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'dalam' untuk sungai?", "a": "dangkal"},
        {"q": "Apakah perkataan lawan bagi kata adjektif 'berani'?", "a": "takut"},
        {"q": "Tubuh badan kita akan menjadi ___ jika kita rajin bersukan.", "a": "sihat"},
        {"q": "Adik tidak dapat hadir ke sekolah kerana badannya ___.", "a": "sakit"},
        {"q": "Apakah kata adjektif rasa bagi sebiji cili padi?", "a": "pedas"},
        {"q": "Apakah bentuk bagi sebiji telur ayam?", "a": "bujur"},
        {"q": "Laluan jalan di kawasan pergunungan itu kelihatan ___.", "a": "bengkang-bengkok"},
        {"q": "Badannya berbau ___ selepas selesai menyertai acara larian.", "a": "busuk"}
    ],

    // 🟢 TAHAP MUDAH (+1 XP) - KATEGORI 4: KATA TUGAS (50 SOALAN)
    "kata_tugas": [
        {"q": "Apakah kata hubung yang digunakan untuk menggabungkan dua nama setara, contohnya: Ali ___ Abu?", "a": "dan"},
        {"q": "Kamu mahu minum air teh ___ air kopi? (Kata hubung pilihan)", "a": "atau"},
        {"q": "Abang tidak dapat hadir ke sekolah hari ini ___ dia demam.", "a": "kerana"},
        {"q": "___ bising di dalam bilik darjah semasa guru tiada. (Kata perintah larangan)", "a": "jangan"},
        {"q": "___ ambilkan saya sebatang pensel di atas meja itu. (Kata perintah permintaan)", "a": "tolong"},
        {"q": "___ nama kawan baik yang duduk di sebelah kamu? (Kata tanya manusia)", "a": "siapa"},
        {"q": "___kah cara untuk membuat kapal terbang kertas ini? (Kata tanya cara)", "a": "bagaimana"},
        {"q": "Buku latihan BM itu diletakkan di ___ meja tulis. (Kata arah)", "a": "atas"},
        {"q": "Siti menerima sepucuk surat ___ kawan penanya di Sarawak.", "a": "daripada"},
        {"q": "Kami sekeluarga bertolak ke kampung halaman ___ hari Sabtu lepas.", "a": "pada"},
        {"q": "Adik berjalan kaki ___ sekolah pada setiap pagi. (Kata sendi arah tempat)", "a": "ke"},
        {"q": "Rombongan pengakap itu baru sahaja pulang ___ hutan. (Kata sendi asal tempat)", "a": "dari"},
        {"q": "Sila berikan surat kebenaran ini ___ guru kelas kamu.", "a": "kepada"},
        {"q": "Beg sekolah berwarna biru ini dibeli ___ adik bongsu saya.", "a": "untuk"},
        {"q": "Makanan kucing yang dibeli oleh bapa adalah ___ kucing jalanan.", "a": "bagi"},
        {"q": "Ibu memasak lauk di dapur ___ mendengar siaran radio.", "a": "sambil"},
        {"q": "Adik tergelincir di atas lantai ___ menangis dengan kuat.", "a": "lalu"},
        {"q": "___kah harga sekilo buah rambutan yang dijual ini? (Kata tanya jumlah)", "a": "berapa"},
        {"q": "___kah kamu akan bertolak ke bandar Melaka? (Kata tanya masa)", "a": "bila"},
        {"q": "___kah kamu tidak menyiapkan kerja sekolah semalam? (Kata tanya sebab)", "a": "mengapa"},
        {"q": "___ yang tersimpan di dalam kotak misteri itu? (Kata tanya benda)", "a": "apa"},
        {"q": "Di ___kah letaknya bangunan sekolah baharu itu? (Kata tanya tempat)", "a": "mana"},
        {"q": "___lah masuk ke dalam rumah saya yang kecil ini. (Kata perintah silaan)", "a": "jemput"},
        {"q": "___ duduk di atas kerusi masing-masing dengan tertib. (Kata perintah silaan)", "a": "sila"},
        {"q": "Kita ___ usah bertengkar tentang perkara yang kecil ini. (Kata perintah larangan santai)", "a": "usah"},
        {"q": "Abang ___ makan nasi lemak sebelum pergi bermain bola tadi. (Kata bantu sudah)", "a": "sudah"},
        {"q": "Kami sekeluarga ___ bertolak ke Pulau Langkawi esok pagi. (Kata bantu masa hadapan)", "a": "akan"},
        {"q": "Adik bongsu ___ sedang tidur nyenyak di dalam buaian. (Kata bantu sedang)", "a": "sedang"},
        {"q": "Saya ___ belum menyiapkan lukisan pemandangan sawah padi.", "a": "belum"},
        {"q": "Murid-murid ___ menggunakan komputer di bilik siber ini. (Kata bantu keupayaan)", "a": "boleh"},
        {"q": "Rumah banglo yang terletak di atas bukit itu ___ besar. (Kata penguat)", "a": "sangat"},
        {"q": "Buah mangga yang dipetik oleh bapa manis ___ hal rasanya. (Kata penguat belakang)", "a": "sekali"},
        {"q": "Menara Berkembar Petronas ialah bangunan yang ___ tinggi di Malaysia.", "a": "paling"},
        {"q": "Cuaca pada petang ini kelihatan ___ panas berbanding semalam. (Kata penguat)", "a": "amat"},
        {"q": "Kereta lumba itu dipandu dengan ___ laju di litar lumba.", "a": "terlalu"},
        {"q": "Saya ___ tahu cara untuk menunggang basikal roda dua. (Kata nafi perbuatan)", "a": "tidak"},
        {"q": "Beg sekolah yang berwarna merah ini ___ kepunyaan saya. (Kata nafi nama)", "a": "bukan"},
        {"q": "Anak kucing yang comel itu berada di ___ meja makan. (Kata arah bawah)", "a": "bawah"},
        {"q": "Buku rujukan itu disimpan dengan rapi di ___ laci meja.", "a": "dalam"},
        {"q": "Murid-murid dilarang berlari di ___ kawasan bilik darjah. (Kata arah luar)", "a": "luar"},
        {"q": "Kereta bapa diletakkan secara selari di ___ rumah. (Kata arah hadapan)", "a": "hadapan"},
        {"q": "Sebuah reban ayam dibina oleh datuk di ___ rumah kampung. (Kata arah belakang)", "a": "belakang"},
        {"q": "Sebuah pasu bunga diletakkan di ___ televisyen ruang tamu. (Kata arah tepi)", "a": "tepi"},
        {"q": "Kawanan burung kelihatan terbang bebas di ___ langit biru. (Kata arah atas)", "a": "atas"},
        {"q": "___, comelnya anak kucing parsi yang baru dibeli ini! (Kata seru kagum)", "a": "amboi"},
        {"q": "___, sakitnya jari tangan saya akibat terkena pisau! (Kata seru sakit)", "a": "aduh"},
        {"q": "___, berani kamu menceroboh masuk ke dalam kawasan ini! (Kata seru marah)", "a": "cis"},
        {"q": "___, kamu pun ada di pesta buku ini juga rupanya! (Kata seru hairan)", "a": "eh"},
        {"q": "___, cantiknya pemandangan matahari terbit di tepi pantai! (Kata seru kagum)", "a": "wah"},
        {"q": "___, syabas! Kamu berjaya mendapat tempat pertama dalam peperiksaan! (Kata seru gembira)", "a": "oh"}
    ],

"penjodoh_bilangan": [
        {"q": "Penjodoh bilangan yang sesuai untuk manusia seperti guru, polis dan doktor ialah ___.", "a": "orang"},
        {"q": "Penjodoh bilangan untuk haiwan seperti kucing, burung, dan ikan ialah ___.", "a": "ekor"},
        {"q": "Penjodoh bilangan untuk benda yang besar seperti rumah, kereta, dan sekolah ialah ___.", "a": "buah"},
        {"q": "Penjodoh bilangan untuk benda yang panjang seperti sungai, pensel, dan pembaris ialah ___.", "a": "batang"},
        {"q": "Penjodoh bilangan untuk benda yang tajam seperti pisau, gunting, dan kapak ialah ___.", "a": "bilah"},
        {"q": "Penjodoh bilangan untuk benda yang nipis dan lembut seperti kertas, kain, dan baju ialah ___.", "a": "helai"},
        {"q": "Penjodoh bilangan untuk benda yang berbentuk bulat seperti telur, guli, dan oren ialah ___.", "a": "biji"},
        {"q": "Penjodoh bilangan untuk barang perhiasan bulat seperti cincin atau subang ialah ___.", "a": "bentuk"},
        {"q": "Bapa membeli lima ___ sate ayam yang dibakar di atas arang.", "a": "cucuk"},
        {"q": "Ibu menerima se___ surat kiriman daripada abang yang berada di universiti.", "a": "pucuk"},
        {"q": "Ibu memotong dua ___ roti untuk sarapan pagi kakak.", "a": "keping"},
        {"q": "Abang membeli se___ kasut sukan baharu di kedai jenama terkenal itu.", "a": "pasang"},
        {"q": "Nelayan itu menggunakan se___ tali nilon yang panjang untuk mengikat bot.", "a": "utas"},
        {"q": "Adik membaca se___ majalah kanak-kanak yang dipinjam dari perpustakaan.", "a": "naskah"},
        {"q": "Abang makan tiga ___ durian kampung yang manis itu.", "a": "ulas"},
        {"q": "Ibu membeli se___ pisang emas di pasar tani pagi tadi.", "a": "sikat"},
        {"q": "Pak Cik Lim memetik se___ kelapa muda dari pokok di belakang rumahnya.", "a": "tandan"},
        {"q": "Emak mengambil se___ daun pandan untuk mewangikan air sirap.", "a": "rumpun"},
        {"q": "Kakak membeli dua ___ sayur sawi di kedai runcit Pak Abu.", "a": "ikat"},
        {"q": "Atok mengumpul se___ kayu api untuk memasak air di luar rumah.", "a": "berkas"},
        {"q": "Polis itu membawa se___ senapang patah semasa melakukan rondaan.", "a": "laras"},
        {"q": "Adik menggunakan se___ sabun mandi untuk membersihkan badannya.", "a": "buku"},
        {"q": "Siti memotong se___ kek hari jadi untuk diberikan kepada kawannya.", "a": "potong"},
        {"q": "Adik terlanggar se___ batu besar semasa bermain di padang.", "a": "ketul"},
        {"q": "Abang memberikan se___ bunga mawar merah kepada ibu.", "a": "kuntum"},
        {"q": "Kakak menyimpan dua ___ gambar kenangan di dalam album.", "a": "keping"},
        {"q": "Adik memakai se___ anting-anting mutiara yang sangat comel.", "a": "pasang"},
        {"q": "Nenek menghadiahi kakak se___ rantai leher emas yang cantik.", "a": "utas"},
        {"q": "Bapa sedang membaca se___ surat khabar di ruang tamu.", "a": "naskah"},
        {"q": "Ibu memasukkan beberapa ___ bawang putih ke dalam masakan.", "a": "ulas"},
        {"q": "Kelihatan se___ pokok buluh tumbuh dengan subur di tepi sungai.", "a": "rumpun"},
        {"q": "Bapa membawa pulang dua ___ buah rambutan dari dusun nangka.", "a": "ikat"},
        {"q": "Abang mengikat se___ surat lama menggunakan seutas tali.", "a": "berkas"},
        {"q": "Ibu membeli dua ___ roti sandwic di kedai roti.", "a": "buku"},
        {"q": "Kami makan beberapa ___ buah tembikai yang sejuk dan manis.", "a": "potong"},
        {"q": "Kakak memasukkan dua ___ daging lembu ke dalam sup.", "a": "ketul"},
        {"q": "Terdapat se___ bunga matahari yang besar di halaman rumah.", "a": "kuntum"},
        {"q": "Ibu merebus lima ___ telur ayam untuk dibuat inti sandwic.", "a": "biji"},
        {"q": "Se___ doktor sedang memeriksa kesihatan pesakit di klinik.", "a": "orang"},
        {"q": "Adik menggalas se___ beg sekolah yang berwarna biru muda.", "a": "buah"},
        {"q": "Bapa menggunakan se___ pembaris panjang untuk membuat garisan lurus.", "a": "batang"},
        {"q": "Kamal memenangi sepuluh ___ guli dalam permainan tradisional itu.", "a": "biji"},
        {"q": "Terdapat se___ burung merpati sedang hinggap di atas bumbung.", "a": "ekor"},
        {"q": "Bapa memandu se___ kereta baharu untuk pergi ke tempat kerja.", "a": "buah"},
        {"q": "Rumah datuk terletak berhampiran dengan se___ sungai yang jernih.", "a": "batang"},
        {"q": "Kakak menggunakan se___ gunting untuk memotong kain ela.", "a": "bilah"},
        {"q": "Siti memakai se___ baju kurung yang berwarna merah jambu.", "a": "helai"},
        {"q": "Se___ polis sedang mengawal lalu lintas yang sibuk di bandar.", "a": "orang"},
        {"q": "Abang berjaya memancing tiga ___ ikan keli di kolam itu.", "a": "ekor"},
        {"q": "Di dalam bilik darjah kami terdapat dua puluh ___ meja kayu.", "a": "buah"}
    ],

    // 🟡 TAHAP SEDERHANA (+2 XP) - KATEGORI 6: SINONIM & ANTONIM (50 SOALAN)
    "sinonim_antonim": [
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'rakan'?", "a": "kawan"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'kediaman'?", "a": "rumah"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'pintar'?", "a": "bijak"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'dingin'?", "a": "sejuk"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'bersih'?", "a": "kotor"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'rajin'?", "a": "malas"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'menang'?", "a": "kalah"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'pantas'?", "a": "lambat"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'kaya'?", "a": "miskin"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'sedih'?", "a": "duka"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'harum'?", "a": "wangi"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'pohon'?", "a": "pokok"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'jelita'?", "a": "cantik"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'seronok'?", "a": "gembira"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'sukar'?", "a": "susah"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'siang'?", "a": "malam"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'tinggi'?", "a": "rendah"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'gemuk'?", "a": "kurus"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'panjang'?", "a": "pendek"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'tebal'?", "a": "nipis"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'baharu'?", "a": "lama"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'mahal'?", "a": "murah"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'berani'?", "a": "takut"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'lapar'?", "a": "kenyang"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'dahaga'?", "a": "haus"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'sihat'?", "a": "sakit"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'terang'?", "a": "gelap"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'tajam'?", "a": "tumpul"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'lembut'?", "a": "keras"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'jinak'?", "a": "liar"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'hampir'?", "a": "dekat"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'gemar'?", "a": "suka"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'pelawak'?", "a": "badut"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'mentari'?", "a": "matahari"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'warga'?", "a": "rakyat"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'hulu' sungai?", "a": "hilir"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'dalam' untuk laut?", "a": "dangkal"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'luas'?", "a": "sempit"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'hidup'?", "a": "mati"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'awal'?", "a": "lewat"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'untung'?", "a": "rugi"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'jantan' untuk haiwan?", "a": "betina"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'pemurah'?", "a": "kedekut"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'bising'?", "a": "sunyi"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'gembira'?", "a": "sedih"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'kerap'?", "a": "selalu"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'cuai'?", "a": "leka"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'pakaian'?", "a": "baju"},
        {"q": "Apakah sinonim (perkataan sama maksud) bagi perkataan 'pondok'?", "a": "teratak"},
        {"q": "Apakah antonim (perkataan lawan) bagi perkataan 'asli'?", "a": "palsu"}
    ],

    // 🟡 TAHAP SEDERHANA (+2 XP) - KATEGORI 7: AYAT TUNGGAL (50 SOALAN)
    "ayat_tunggal": [
        {"q": "Ayat tunggal mengandungi ___ subjek dan satu predikat.", "a": "satu"},
        {"q": "Adakah ayat 'Ali membaca buku cerita' merupakan contoh ayat tunggal?", "a": "ya"},
        {"q": "Dalam ayat 'Kucing itu sangat comel', bahagian manakah yang merupakan subjek?", "a": "kucing itu"},
        {"q": "Dalam ayat 'Bapa memandu kereta baharu', bahagian manakah yang merupakan predikat?", "a": "memandu kereta baharu"},
        {"q": "Ayat tunggal dibina tanpa menggunakan sebarang kata ___.", "a": "hubung"},
        {"q": "Adakah frasa 'Kakak sedang tidur di bilik' dikira sebagai satu ayat tunggal?", "a": "ya"},
        {"q": "Tentukan sama ada ayat 'Saya suka makan nasi ayam' ialah ayat tunggal atau majmuk?", "a": "ayat tunggal"},
        {"q": "Ayat susunan biasa dalam bahasa Melayu bermula dengan unsur ___.", "a": "subjek"},
        {"q": "Adakah ayat 'Ahmad dan Chong bermain bola' sebuah ayat tunggal?", "a": "tidak"},
        {"q": "Ayat tunggal terdiri daripada hanya satu ___ (klausa bebas).", "a": "klausa"},
        {"q": "Subjek dalam ayat tunggal 'Adik menangis' ialah perkataan ___.", "a": "adik"},
        {"q": "Predikat dalam ayat tunggal 'Adik menangis' ialah perkataan ___.", "a": "menangis"},
        {"q": "Adakah ayat 'Ibu memasak di dapur' sebuah ayat tunggal?", "a": "ya"},
        {"q": "Subjek dalam ayat 'Rumah itu sangat besar' ialah frasa ___.", "a": "rumah itu"},
        {"q": "Predikat dalam ayat 'Rumah itu sangat besar' ialah frasa ___.", "a": "sangat besar"},
        {"q": "Adakah ayat 'Saya membaca buku sambil mendengar lagu' ayat tunggal?", "a": "tidak"},
        {"q": "Ayat tunggal hanya mempunyai ___ predikat sahaja.", "a": "satu"},
        {"q": "Subjek biasanya terdiri daripada frasa ___ dalam susunan biasa.", "a": "nama"},
        {"q": "Tentukan jenis ayat bagi: 'Cikgu Aminah sedang mengajar.'", "a": "ayat tunggal"},
        {"q": "Adakah ayat 'Abang belum pulang dari sekolah' ayat tunggal?", "a": "ya"},
        {"q": "Subjek bagi ayat 'Baju biru itu kepunyaan saya' ialah ___.", "a": "baju biru itu"},
        {"q": "Predikat bagi ayat 'Baju biru itu kepunyaan saya' ialah ___.", "a": "kepunyaan saya"},
        {"q": "Adakah perkataan 'tetapi' boleh digunakan dalam ayat tunggal?", "a": "tidak"},
        {"q": "Tentukan subjek bagi ayat 'Kuala Lumpur ibu negara Malaysia'.", "a": "kuala lumpur"},
        {"q": "Tentukan predikat bagi ayat 'Kuala Lumpur ibu negara Malaysia'.", "a": "ibu negara malaysia"},
        {"q": "Adakah ayat 'Burung itu terbang tinggi' mempunyai satu klausa sahaja?", "a": "ya"},
        {"q": "Tentukan sama ada ayat 'Saya mahu makan atau minum' ialah ayat tunggal.", "a": "tidak"},
        {"q": "Subjek dalam ayat 'Pokok kelapa itu sangat tinggi' ialah ___.", "a": "pokok kelapa itu"},
        {"q": "Predikat dalam ayat 'Pokok kelapa itu sangat tinggi' ialah ___.", "a": "sangat tinggi"},
        {"q": "Adakah ayat 'Kami bermain bola di padang' ialah ayat tunggal?", "a": "ya"},
        {"q": "Subjek bagi ayat 'Kasut sukan ini sangat mahal' ialah ___.", "a": "kasut sukan ini"},
        {"q": "Predikat bagi ayat 'Kasut sukan ini sangat mahal' ialah ___.", "a": "sangat mahal"},
        {"q": "Ayat tunggal juga dikenali sebagai ayat ___ dalam aspek klausa.", "a": "mudah"},
        {"q": "Adakah ayat 'Dia tidak hadir kerana sakit' sebuah ayat tunggal?", "a": "tidak"},
        {"q": "Tentukan subjek bagi ayat 'Beg sekolah adik berwarna merah'.", "a": "beg sekolah adik"},
        {"q": "Tentukan predikat bagi ayat 'Beg sekolah adik berwarna merah'.", "a": "berwarna merah"},
        {"q": "Adakah ayat 'Siti pandai tetapi malas' sebuah ayat tunggal?", "a": "tidak"},
        {"q": "Subjek bagi ayat 'Kereta baharu bapa berwarna hitam' ialah ___.", "a": "kereta baharu bapa"},
        {"q": "Predikat bagi ayat 'Kereta baharu bapa berwarna hitam' ialah ___.", "a": "berwarna hitam"},
        {"q": "Adakah ayat 'Gajah ialah haiwan yang besar' sebuah ayat tunggal?", "a": "ya"},
        {"q": "Subjek bagi ayat 'Abang saya seorang doktor' ialah ___.", "a": "abang saya"},
        {"q": "Predikat bagi ayat 'Abang saya seorang doktor' ialah ___.", "a": "seorang doktor"},
        {"q": "Adakah ayat 'Ayam jantan itu berkokok' mempunyai kata hubung?", "a": "tidak"},
        {"q": "Tentukan jenis ayat: 'Murid-murid sedang beratur di tapak perhimpunan.'", "a": "ayat tunggal"},
        {"q": "Subjek bagi ayat 'Buah betik ini sangat manis' ialah ___.", "a": "buah betik ini"},
        {"q": "Predikat bagi ayat 'Buah betik ini sangat manis' ialah ___.", "a": "sangat manis"},
        {"q": "Adakah ayat 'Saya dan emak pergi ke pasar' sebuah ayat tunggal?", "a": "tidak"},
        {"q": "Tentukan subjek bagi ayat 'Telefon bimbit ini sangat canggih'.", "a": "telefon bimbit ini"},
        {"q": "Tentukan predikat bagi ayat 'Telefon bimbit ini sangat canggih'.", "a": "sangat canggih"},
        {"q": "Ayat tunggal yang lengkap mesti diakhiri dengan tanda ___ dalam penulisan.", "a": "titik"}
    ],

    // 🟡 TAHAP SEDERHANA (+2 XP) - KATEGORI 8: AYAT MAJMUK (50 SOALAN)
    "ayat_majmuk": [
        {"q": "Ayat majmuk dibentuk dengan menggabungkan dua atau lebih ayat ___.", "a": "tunggal"},
        {"q": "Apakah kata hubung yang sesuai untuk menggabungkan ayat ini: 'Ali makan nasi' + 'Abu makan mi'?", "a": "dan"},
        {"q": "Ayat majmuk 'Siti menangis kerana lapar' dibentuk menggunakan kata hubung pancangan ___.", "a": "kerana"},
        {"q": "Adakah ayat 'Aminah lulus ujian kerana dia rajin belajar' merupakan ayat majmuk?", "a": "ya"},
        {"q": "Kata hubung 'atau' digunakan dalam ayat majmuk untuk menunjukkan aspek ___.", "a": "pilihan"},
        {"q": "Lengkapkan ayat majmuk ini: Abang mahu bermain bola di padang ___ hari hujan lebat.", "a": "tetapi"},
        {"q": "Kakak menyanyi ___ menari di atas pentas. (Kata hubung perbuatan serentak)", "a": "sambil"},
        {"q": "Gabungan beberapa ayat tunggal dengan bantuan kata hubung akan menghasilkan ayat ___.", "a": "majmuk"},
        {"q": "Adakah ayat 'Saya suka menyanyi dan menari' merupakan sebuah ayat tunggal?", "a": "tidak"},
        {"q": "Kata hubung 'supaya' digunakan dalam ayat majmuk untuk menyatakan tujuan atau ___.", "a": "harapan"},
        {"q": "Lengkapkan ayat: Ali membasuh kasutnya ___ bersih. (Kata hubung keterangan)", "a": "sehingga"},
        {"q": "Adakah perkataan 'dan' merupakan kata hubung gabungan dalam ayat majmuk?", "a": "ya"},
        {"q": "Ayat 'Saya membaca buku cerita ___ adik bermain guli' sesuai menggunakan kata hubung manakala.", "a": "manakala"},
        {"q": "Lengkapkan ayat: Kasut sukan itu cantik ___ harganya terlalu mahal.", "a": "tetapi"},
        {"q": "Adakah ayat 'Bapa mencuci kereta manakala emak menyiram pokok bunga' ayat majmuk?", "a": "ya"},
        {"q": "Ayat majmuk mengandungi lebih daripada ___ subjek atau predikat.", "a": "satu"},
        {"q": "Siti mengulang kaji pelajaran ___ dia mendapat keputusan yang cemerlang. (Kata hubung tujuan)", "a": "supaya"},
        {"q": "Adakah ayat 'Kami makan nasi lemak di kantin sekolah' sebuah ayat majmuk?", "a": "tidak"},
        {"q": "Kata hubung 'lalu' digunakan untuk menunjukkan perbuatan yang dilakukan secara ___.", "a": "berturutan"},
        {"q": "Lengkapkan ayat: Adik masuk ke dalam bilik tidur ___ menutup pintu.", "a": "lalu"},
        {"q": "Adakah perkataan 'kerana' digunakan untuk menyatakan sebab atau alasan?", "a": "ya"},
        {"q": "Lengkapkan ayat: Kamu suka makan buah betik ___ buah tembikai?", "a": "atau"},
        {"q": "Ayat 'Abang sangat tinggi tetapi adik pendek' menggunakan kata hubung pertentangan ___.", "a": "tetapi"},
        {"q": "Lengkapkan ayat: Atuk memakai cermin mata ___ membaca surat khabar lama.", "a": "semasa"},
        {"q": "Lengkapkan ayat: Kakak menyapu sampah ___ mendengar lagu di radio.", "a": "sambil"},
        {"q": "Adakah ayat 'Zaki dan Raju kawan baik' dikategorikan sebagai ayat majmuk gabungan?", "a": "ya"},
        {"q": "Lengkapkan ayat: Ibu membelikan adik sebuah permainan baharu ___ adik mendapat nombor satu.", "a": "kerana"},
        {"q": "Lengkapkan ayat: Kita mestilah rajin bersenam ___ badan kita sentiasa sihat.", "a": "supaya"},
        {"q": "Adakah perkataan 'sambil' menunjukkan dua perbuatan dilakukan pada waktu yang sama?", "a": "ya"},
        {"q": "Lengkapkan ayat: Murid-murid beratur ___ menaiki bas sekolah.", "a": "sebelum"},
        {"q": "Lengkapkan ayat: Kita perlu membasuh tangan ___ makan hidangan tengah hari.", "a": "sebelum"},
        {"q": "Lengkapkan ayat: Abang mengemas bilik tidurnya ___ selesai bangun daripada tidur.", "a": "selepas"},
        {"q": "Adakah ayat 'Kucing itu mengejar tikus lalu menangkapnya' sebuah ayat majmuk?", "a": "ya"},
        {"q": "Lengkapkan ayat: Bapa membaca majalah otomotif ___ menunggu ibu membeli sayur.", "a": "sementara"},
        {"q": "Lengkapkan ayat: Rumah itu kelihatan sungguh sunyi ___ penghuninya pulang ke kampung.", "a": "sejak"},
        {"q": "Adakah perkataan 'atau' memberikan dua pilihan kepada pelaku dalam ayat?", "a": "ya"},
        {"q": "Lengkapkan ayat: Fatimah sangat rajin ___ adiknya sangat malas belajar.", "a": "manakala"},
        {"q": "Lengkapkan ayat: Sila pastikan suis kipas dimatikan ___ kamu keluar dari bilik.", "a": "apabila"},
        {"q": "Adakah ayat 'Saya tidak tahu bahawa esok hari cuti' merupakan ayat majmuk?", "a": "ya"},
        {"q": "Lengkapkan ayat: Cikgu Aminah memberitahu ___ ujian bertulis akan diadakan esok.", "a": "bahawa"},
        {"q": "Lengkapkan ayat: Kami tetap pergi berkelah di pantai ___ hari hujan renyai-renyai.", "a": "walaupun"},
        {"q": "Adakah perkataan 'walaupun' digunakan untuk menyatakan unsur pertentangan atau kelonggaran?", "a": "ya"},
        {"q": "Lengkapkan ayat: Adik menangis dengan kuat ___ mainan kesayangannya rosak.", "a": "kerana"},
        {"q": "Lengkapkan ayat: Encik Tan memandu kereta dengan berhati-hati ___ jalan raya itu licin.", "a": "kerana"},
        {"q": "Adakah ayat 'Buku ini sangat tebal' contoh ayat majmuk?", "a": "tidak"},
        {"q": "Lengkapkan ayat: Pelajar itu belajar dengan tekun ___ berjaya mencapai cita-citanya.", "a": "demi"},
        {"q": "Lengkapkan ayat: Kami sekeluarga memakai baju melayu berwarna hijau ___ menyambut hari raya.", "a": "semasa"},
        {"q": "Adakah perkataan 'bahawa' termasuk dalam kumpulan kata hubung pancangan?", "a": "ya"},
        {"q": "Lengkapkan ayat: Ali bangun dari kerusi ___ berjalan ke hadapan papan putih.", "a": "lalu"},
        {"q": "Ayat majmuk yang digabungkan mesti diakhiri dengan tanda ___ dalam penulisan ayat.", "a": "titik"}
    ],

"kesalahan_tatabahasa": [
        {"q": "Adakah betul struktur frasa 'demi untuk negara'?", "a": "tidak"},
        {"q": "Apakah pembetulan untuk frasa 'sejak dari kecil'?", "a": "sejak kecil"},
        {"q": "Apakah pembetulan untuk kesalahan frasa 'paling tinggi sekali'?", "a": "paling tinggi"},
        {"q": "Adakah betul struktur frasa 'dua buah rumah-rumah'?", "a": "tidak"},
        {"q": "Betulkan kesalahan kata hubung dalam ayat: 'Saya membaca buku bila lapang.'", "a": "apabila"},
        {"q": "Pilih perkataan yang betul untuk kawasan ulu: 'pedalaman' atau 'pendalaman'?", "a": "pedalaman"},
        {"q": "Pilih perkataan yang betul untuk proses mendalami ilmu: 'pedalaman' atau 'pendalaman'?", "a": "pendalaman"},
        {"q": "Pilih ejaan yang betul: 'mengcat' atau 'mengecat'?", "a": "mengecat"},
        {"q": "Pilih ejaan yang betul: 'mengebom' atau 'mengbom'?", "a": "mengebom"},
        {"q": "Betulkan kesalahan dalam frasa 'oleh kerana'.", "a": "oleh sebab"},
        {"q": "Betulkan kesalahan dalam frasa 'selain dari itu'.", "a": "selain itu"},
        {"q": "Betulkan kesalahan dalam frasa 'paling terbesar'.", "a": "terbesar"},
        {"q": "Betulkan kesalahan dalam frasa 'tersangat indah sekali'.", "a": "sangat indah"},
        {"q": "Betulkan kesalahan dalam frasa 'banyak rumah-rumah'.", "a": "banyak rumah"},
        {"q": "Betulkan kesalahan dalam frasa 'para-para guru'.", "a": "para guru"},
        {"q": "Antara 'bukan' dan 'tidak', perkataan manakah yang menafikan frasa nama?", "a": "bukan"},
        {"q": "Antara 'bukan' dan 'tidak', perkataan manakah yang menafikan frasa kerja?", "a": "tidak"},
        {"q": "Antara 'bukan' dan 'tidak', perkataan manakah yang menafikan frasa adjektif?", "a": "tidak"},
        {"q": "Betulkan kesalahan kata ganti nama objek dalam ayat: 'Kucing itu ia sangat comel.'", "a": "kucing itu sangat comel"},
        {"q": "Adakah perkataan 'di dalam' ditulis rapat (didalam) apabila menunjukkan ruang bilik?", "a": "tidak"},
        {"q": "Adakah perkataan 'di atas' ditulis rapat (diatas) apabila menunjukkan tempat di atas meja?", "a": "tidak"},
        {"q": "Adakah perkataan 'di sana' ditulis rapat (disana) apabila menunjukkan tempat yang jauh?", "a": "tidak"},
        {"q": "Betulkan kesalahan frasa 'bersebelahan rumah'.", "a": "bersebelahan dengan rumah"},
        {"q": "Betulkan kesalahan imbuhan dalam ayat: 'Mereka memperbesarkan rumah.'", "a": "memperbesar"},
        {"q": "Betulkan kesalahan imbuhan dalam ayat: 'Guru memperdalamkan ilmu murid.'", "a": "memperdalam"},
        {"q": "Betulkan kesalahan frasa 'berulang-ulang kali'.", "a": "berulang kali"},
        {"q": "Betulkan kesalahan frasa 'di atas perhatian tuan'.", "a": "atas perhatian"},
        {"q": "Betulkan kesalahan frasa 'Sila jemput masuk.'", "a": "sila masuk"},
        {"q": "Betulkan kesalahan frasa 'Tolong jangan bising.'", "a": "jangan bising"},
        {"q": "Betulkan kesalahan frasa 'Minta sila beratur.'", "a": "sila beratur"},
        {"q": "Betulkan kesalahan kata sendi dalam ayat: 'Alif memberikan buku pada Amin.'", "a": "kepada"},
        {"q": "Betulkan kesalahan kata sendi dalam ayat: 'Baju ini dibuat dari sutera.'", "a": "daripada"},
        {"q": "Betulkan kesalahan kata sendi dalam ayat: 'Dia datang daripada kampung.'", "a": "dari"},
        {"q": "Betulkan kesalahan kata sendi dalam ayat: 'Surat itu dihantar dari posmen.'", "a": "oleh"},
        {"q": "Betulkan kesalahan frasa 'sehubungan itu'.", "a": "sehubungan dengan itu"},
        {"q": "Betulkan kesalahan frasa 'berhubung itu'.", "a": "berhubung dengan itu"},
        {"q": "Betulkan kesalahan frasa 'mempunyai banyak kebaikan-kebaikan'.", "a": "mempunyai banyak kebaikan"},
        {"q": "Betulkan kesalahan frasa 'pelbagai jenis-jenis bunga'.", "a": "pelbagai jenis bunga"},
        {"q": "Betulkan kesalahan frasa 'semua murid-murid'.", "a": "semua murid"},
        {"q": "Betulkan kesalahan frasa 'antara faktor-faktor'.", "a": "antara faktor"},
        {"q": "Betulkan kesalahan frasa 'setengah murid'.", "a": "sesetengah murid"},
        {"q": "Betulkan kesalahan frasa 'tiap murid'.", "a": "setiap murid"},
        {"q": "Betulkan kesalahan frasa 'kedua ibu bapa'.", "a": "kedua-dua ibu bapa"},
        {"q": "Betulkan kesalahan frasa 'bersemuka dengan'.", "a": "bersemuka"},
        {"q": "Betulkan kesalahan frasa 'saling bantu-membantu'.", "a": "bantu-membantu"},
        {"q": "Betulkan kesalahan frasa 'saling hormat-menghormati'.", "a": "hormat-menghormati"},
        {"q": "Pilih ejaan yang betul: 'meresmikan' atau 'merasmikan'?", "a": "merasmikan"},
        {"q": "Betulkan kesalahan penggunaan imbuhan dalam frasa 'mewarnakan gambar'.", "a": "mewarnai gambar"},
        {"q": "Betulkan kesalahan penggunaan kata kerja dalam frasa 'menghadiahi sebuah buku'.", "a": "menghadiahkan sebuah buku"},
        {"q": "Betulkan kesalahan penggunaan kata kerja dalam frasa 'menghadiahkan ibu sebentuk cincin'.", "a": "menghadiahi ibu"}
    ],

    "peribahasa": [
        {"q": "Peribahasa untuk orang yang mementingkan diri sendiri: 'Bagai ___ dalam belukar, melepaskan pucuk masing-masing.'", "a": "enau"},
        {"q": "Peribahasa untuk orang yang sentiasa bekerjasama: 'Bagai aur dengan ___.'", "a": "tebing"},
        {"q": "Maksud peribahasa 'Kais pagi makan pagi, kais petang makan petang' merujuk kepada orang yang ___.", "a": "miskin"},
        {"q": "Peribahasa untuk mendidik kanak-kanak dari kecil: 'Melentur ___ biarlah dari rebungnya.'", "a": "buluh"},
        {"q": "Peribahasa untuk kelakuan anak mengikut sifat ibu bapa: 'Bagaimana acuan begitulah ___.'", "a": "kuihnya"},
        {"q": "Sifat orang yang sombong setelah mendapat kekayaan: 'Seperti kacang lupakan ___.'", "a": "kulit"},
        {"q": "Apakah maksud simpulan bahasa 'berat tulang'?", "a": "malas"},
        {"q": "Apakah maksud simpulan bahasa 'ringan tulang'?", "a": "rajin"},
        {"q": "Maksud simpulan bahasa 'anak emas' ialah anak yang ___.", "a": "disayangi"},
        {"q": "Maksud simpulan bahasa 'kaki ayam' ialah tidak memakai ___.", "a": "kasut"},
        {"q": "Seseorang yang tidak tahu membaca atau menulis dipanggil 'Buta ___'.", "a": "huruf"},
        {"q": "Orang yang suka mencuri dipanggil 'Panjang ___'.", "a": "tangan"},
        {"q": "Perasaan iri hati atau cemburu dipanggil 'Busuk ___'.", "a": "hati"},
        {"q": "Orang yang cepat marah dipanggil 'Darah ___'.", "a": "panas"},
        {"q": "Maksud simpulan bahasa 'ulat buku' ialah orang yang suka ___ buku.", "a": "membaca"},
        {"q": "Sesuatu perkara yang sudah terlambat dan tidak berguna lagi diumpamakan 'Nasi sudah menjadi ___'.", "a": "bubur"},
        {"q": "Maksud simpulan bahasa 'mandi peluh' ialah bekerja dengan ___.", "a": "kuat"},
        {"q": "Maksud simpulan bahasa 'makan angin' ialah pergi ___.", "a": "melancong"},
        {"q": "Seseorang yang tidak memihak kepada mana-mana pihak dipanggil 'Atas ___'.", "a": "pagar"},
        {"q": "Maksud simpulan bahasa 'tidur-tidur ayam' ialah tidur yang tidak ___.", "a": "lena"},
        {"q": "Peribahasa untuk menyatakan muafakat: 'Bulat air kerana pembetung, bulat kata kerana ___.'", "a": "muafakat"},
        {"q": "Orang yang berlagak pandai padahal berpengetahuan sempit: 'Seperti katak di bawah ___.'", "a": "tempurung"},
        {"q": "Nasihat agar berhati-hati semasa bercakap: 'Sebab pulut santan binasa, sebab ___ badan binasa.'", "a": "mulut"},
        {"q": "Melakukan pekerjaan atau memberi nasihat yang sia-sia: 'Mencurah air ke daun ___.'", "a": "keladi"},
        {"q": "Peribahasa untuk perbalahan adik-beradik yang akan berbaik semula: 'Carik-carik bulu ayam, lama-lama ___ juga.'", "a": "bercantum"},
        {"q": "Maksud simpulan bahasa 'telinga nipis' ialah orang yang cepat ___.", "a": "marah"},
        {"q": "Seseorang yang menerima rasuah dipanggil 'Makan ___'.", "a": "suap"},
        {"q": "Pasangan pengantin yang sangat sepadan diumpamakan 'Bagai pinang dibelah ___.'", "a": "dua"},
        {"q": "Maksud simpulan bahasa 'muka tebal' ialah tidak tahu ___.", "a": "malu"},
        {"q": "Orang yang degil dan tidak mahu mendengar nasihat: 'Masuk telinga kanan, keluar telinga ___.'", "a": "kiri"},
        {"q": "Sifat orang yang khianat secara diam-diam: 'Gunting dalam ___.'", "a": "lipatan"},
        {"q": "Musuh yang berada dalam kalangan kita sendiri dipanggil 'Musuh dalam ___'.", "a": "selimut"},
        {"q": "Maksud simpulan bahasa 'khabar angin' ialah berita yang belum tentu ___.", "a": "sahih"},
        {"q": "Maksud simpulan bahasa 'buah tangan' ialah ___ yang dibawa semasa melawat seseorang.", "a": "hadiah"},
        {"q": "Maksud simpulan bahasa 'pencuci mulut' ialah makanan ___ selepas makan berat.", "a": "manis"},
        {"q": "Menyimpan rahsia dengan baik: 'Biar pecah di perut, jangan pecah di ___.'", "a": "mulut"},
        {"q": "Maksud 'anak angkat' ialah anak orang lain yang ___ seperti anak sendiri.", "a": "dipelihara"},
        {"q": "Orang yang cepat berasa takut sebelum bertanding dipanggil 'Darah ___'.", "a": "gemuruh"},
        {"q": "Maksud simpulan bahasa 'langkah seribu' ialah ___ dengan cepat kerana ketakutan.", "a": "berlari"},
        {"q": "Maksud simpulan bahasa 'lipas kudung' ialah melakukan kerja dengan sangat ___.", "a": "pantas"},
        {"q": "Seseorang yang suka bercakap banyak atau bising dipanggil 'Mulut ___'.", "a": "murai"},
        {"q": "Maksud simpulan bahasa 'hati batu' ialah seorang yang sangat ___.", "a": "degil"},
        {"q": "Seseorang yang tidak tahu menghargai pemberian: 'Seperti kera mendapat ___.'", "a": "bunga"},
        {"q": "Maksud simpulan bahasa 'tangkai jering' ialah orang yang sangat ___.", "a": "kedekut"},
        {"q": "Seseorang yang menjadi tumpuan perbualan orang ramai dipanggil 'Buah ___'.", "a": "mulut"},
        {"q": "Keuntungan yang datang secara tiba-tiba tanpa disangka dipanggil 'Mendapat durian ___'.", "a": "runtuh"},
        {"q": "Maksud simpulan bahasa 'tanda mata' ialah ___ untuk kenangan.", "a": "hadiah"},
        {"q": "Maksud simpulan bahasa 'otak cair' ialah seorang yang sangat ___.", "a": "bijak"},
        {"q": "Orang yang bodoh dan lembap dipanggil 'Otak ___'.", "a": "udang"},
        {"q": "Menyesuaikan diri di tempat baharu: 'Masuk kandang kambing mengembik, masuk kandang kerbau ___.'", "a": "menguak"}
    ],

    "ayat_aktif_pasif": [
        {"q": "Tukarkan ayat aktif 'Ali membaca buku itu' kepada ayat pasif.", "a": "buku itu dibaca oleh ali"},
        {"q": "Tukarkan ayat aktif 'Saya memakan nasi lemak' kepada ayat pasif.", "a": "nasi lemak saya makan"},
        {"q": "Tukarkan ayat aktif 'Kamu mesti menyiapkan kerja rumah ini' kepada ayat pasif.", "a": "kerja rumah ini mesti kamu siapkan"},
        {"q": "Tukarkan ayat aktif 'Mereka mengecat bangunan sekolah' kepada ayat pasif.", "a": "bangangan sekolah dicecat oleh mereka"},
        {"q": "Tukarkan ayat pasif 'Roti itu dimakan oleh adik' kepada ayat aktif.", "a": "adik memakan roti itu"},
        {"q": "Tukarkan ayat pasif 'Baju itu telah saya cuci' kepada ayat aktif.", "a": "saya telah mencuci baju itu"},
        {"q": "Tukarkan ayat pasif 'Surat itu perlu kau hantar' kepada ayat aktif.", "a": "kau perlu menghantar surat itu"},
        {"q": "Adakah ayat 'Beg itu dibeli oleh saya' betul tatabahasanya?", "a": "tidak"},
        {"q": "Apakah bentuk pasif yang betul untuk kata kerja 'membasuh' bagi kata ganti nama diri pertama (saya)?", "a": "saya basuh"},
        {"q": "Apakah bentuk pasif yang betul untuk kata kerja 'membasuh' bagi kata ganti nama diri kedua (kamu)?", "a": "kamu basuh"},
        {"q": "Apakah bentuk pasif yang betul untuk kata kerja 'membasuh' bagi kata ganti nama diri ketiga (dia)?", "a": "dibasuh olehnya"},
        {"q": "Tukarkan ayat aktif 'Kakak menyiram bunga-bunga itu' kepada ayat pasif.", "a": "bunga-bunga itu disiram oleh kakak"},
        {"q": "Tukarkan ayat aktif 'Kami membersihkan bilik darjah' kepada ayat pasif.", "a": "bilik darjah kami bersihkan"},
        {"q": "Tukarkan ayat aktif 'Dia mengunci pintu pagar' kepada ayat pasif.", "a": "pintu pagar dikunci olehnya"},
        {"q": "Tukarkan ayat aktif 'Abang memandu kereta baharu' kepada ayat pasif.", "a": "kereta baharu dipandu oleh abang"},
        {"q": "Tukarkan ayat aktif 'Engkau telah memecahkan pasu ini' kepada ayat pasif.", "a": "pasu ini telah engkau pecahkan"},
        {"q": "Tukarkan ayat aktif 'Beliau merasmikan kempen itu' kepada ayat pasif.", "a": "kempen itu dirasmikan oleh beliau"},
        {"q": "Tukarkan ayat pasif 'Ikan itu digoreng oleh ibu' kepada ayat aktif.", "a": "ibu menggoreng ikan itu"},
        {"q": "Tukarkan ayat pasif 'Sampah itu telah kami buang' kepada ayat aktif.", "a": "kami telah membuang sampah itu"},
        {"q": "Tukarkan ayat pasif 'Nasihat guru mesti kalian dengar' kepada ayat aktif.", "a": "kalian mesti mendengar nasihat guru"},
        {"q": "Adakah ayat 'Kereta itu dipandu oleh kami' betul tatabahasanya?", "a": "tidak"},
        {"q": "Adakah ayat 'Rumah itu mereka cat' betul tatabahasanya?", "a": "tidak"},
        {"q": "Betulkan ayat pasif diri ketiga berikut: 'Buku itu dia baca.'", "a": "buku itu dibaca olehnya"},
        {"q": "Betulkan ayat pasif diri pertama berikut: 'Kek itu dimakan oleh saya.'", "a": "kek itu saya makan"},
        {"q": "Betulkan ayat pasif diri kedua berikut: 'Surat itu ditulis oleh kamu.'", "a": "surat itu kamu tulis"},
        {"q": "Tukarkan 'Ibu menjahit baju kurung' kepada ayat pasif.", "a": "baju kurung dijahit oleh ibu"},
        {"q": "Tukarkan 'Adik mengejar kucing hitam' kepada ayat pasif.", "a": "kucing hitam dikejar oleh adik"},
        {"q": "Tukarkan 'Saya melukis pemandangan bendang' kepada ayat pasif.", "a": "pemandangan bendang saya lukis"},
        {"q": "Tukarkan 'Awak patut memulangkan pembaris ini' kepada ayat pasif.", "a": "pembaris ini patut awak pulangkan"},
        {"q": "Tukarkan 'Kalian perlu menjaga kebersihan' kepada ayat pasif.", "a": "kebersihan perlu kalian jaga"},
        {"q": "Tukarkan 'Bapa memotong rumput panjang' kepada ayat pasif.", "a": "rumput panjang dipotong oleh bapa"},
        {"q": "Tukarkan 'Siti menyapu lantai dapur' kepada ayat pasif.", "a": "lantai dapur disapu oleh siti"},
        {"q": "Tukarkan 'Mereka mengutip derma kilat' kepada ayat pasif.", "a": "derma kilat dikutip oleh mereka"},
        {"q": "Tukarkan 'Burung itu membina sarang' kepada ayat pasif.", "a": "sarang dibina oleh burung itu"},
        {"q": "Tukarkan 'Kami menyusun kerusi kayu' kepada ayat pasif.", "a": "kerusi kayu kami susun"},
        {"q": "Tukarkan 'Saya memotong dahan pokok' kepada ayat pasif.", "a": "dahan pokok saya potong"},
        {"q": "Tukarkan 'Kamu memasak mi goreng' kepada ayat pasif.", "a": "mi goreng kamu masak"},
        {"q": "Tukarkan 'Dia memetik buah mangga' kepada ayat pasif.", "a": "buah mangga dipetik olehnya"},
        {"q": "Tukarkan 'Kita harus menanam pokok' kepada ayat pasif.", "a": "pokok harus kita tanam"},
        {"q": "Tukarkan 'Pihak polis menangkap pencuri' kepada ayat pasif.", "a": "pencuri ditangkap oleh pihak polis"},
        {"q": "Tukarkan 'Banjir melanda kampung kami' kepada ayat pasif.", "a": "kampung kami dilanda banjir"},
        {"q": "Tukarkan 'Hujan lebat membasahi bumi' kepada ayat pasif.", "a": "bumi dibasahi hujan lebat"},
        {"q": "Tukarkan 'Anjing itu menggigit kasut bapa' kepada ayat pasif.", "a": "kasut bapa digigit oleh anjing itu"},
        {"q": "Tukarkan 'Saya mengelap cermin tingkap' kepada ayat pasif.", "a": "cermin tingkap saya lap"},
        {"q": "Tukarkan 'Anda mesti mengisi borang ini' kepada ayat pasif.", "a": "borang ini mesti anda isi"},
        {"q": "Tukarkan 'Dia membuang tin kosong' kepada ayat pasif.", "a": "tin kosong dibuang olehnya"},
        {"q": "Tukarkan 'Guru memeriksa buku latihan' kepada ayat pasif.", "a": "buku latihan diperiksa oleh guru"},
        {"q": "Tukarkan 'Tukang kayu membuat meja makan' kepada ayat pasif.", "a": "meja makan dibuat oleh tukang kayu"},
        {"q": "Tukarkan 'Saya membeli sepasang kasut' kepada ayat pasif.", "a": "sepasang kasut saya beli"},
        {"q": "Tukarkan 'Mereka merancang majlis perpisahan' kepada ayat pasif.", "a": "majlis perpisahan dirancang oleh mereka"}
    ],

    "susunan_songsang": [
        {"q": "Tukarkan ayat susunan biasa 'Pelajar itu sangat rajin' kepada susunan songsang.", "a": "sangat rajin pelajar itu"},
        {"q": "Tukarkan ayat susunan biasa 'Kucing itu sedang tidur' kepada susunan songsang.", "a": "sedang tidur kucing itu"},
        {"q": "Tukarkan ayat susunan biasa 'Rumah Encik Tan sangat besar' kepada susunan songsang.", "a": "sangat besar rumah encik tan"},
        {"q": "Tukarkan ayat susunan biasa 'Bapa saya seorang guru' kepada susunan songsang.", "a": "seorang guru bapa saya"},
        {"q": "Tukarkan ayat susunan biasa 'Baju adik merah' kepada susunan songsang.", "a": "merah baju adik"},
        {"q": "Tukarkan ayat susunan biasa 'Dia masih belum makan' kepada susunan songsang.", "a": "masih belum makan dia"},
        {"q": "Tukarkan ayat susunan biasa 'Hujan turun dengan lebat' kepada susunan songsang.", "a": "turun dengan lebat hujan"},
        {"q": "Tukarkan ayat susunan biasa 'Anak kecil itu sedang menangis' kepada susunan songsang.", "a": "sedang menangis anak kecil itu"},
        {"q": "Tukarkan ayat susunan biasa 'Pokok kelapa itu sangat tinggi' kepada susunan songsang.", "a": "sangat tinggi pokok kelapa itu"},
        {"q": "Tukarkan ayat susunan biasa 'Ubat ini sangat pahit' kepada susunan songsang.", "a": "sangat pahit ubat ini"},
        {"q": "Tukarkan ayat susunan biasa 'Bas sekolah telah tiba' kepada susunan songsang.", "a": "telah tiba bas sekolah"},
        {"q": "Tukarkan ayat susunan biasa 'Bilik tidurnya sungguh kemas' kepada susunan songsang.", "a": "sungguh kemas bilik tidurnya"},
        {"q": "Tukarkan ayat susunan biasa 'Guru besar sedang berucap' kepada susunan songsang.", "a": "sedang berucap guru besar"},
        {"q": "Tukarkan ayat susunan biasa 'Air laut itu masin' kepada susunan songsang.", "a": "masin air laut itu"},
        {"q": "Tukarkan ayat susunan biasa 'Abang akan bertolak esok' kepada susunan songsang.", "a": "akan bertolak esok abang"},
        {"q": "Tukarkan ayat susunan biasa 'Siti sedang membaca buku' kepada susunan songsang.", "a": "sedang membaca buku siti"},
        {"q": "Tukarkan ayat susunan biasa 'Pencuri itu melarikan diri' kepada susunan songsang.", "a": "melarikan diri pencuri itu"},
        {"q": "Tukarkan ayat susunan biasa 'Mereka belum sampai lagi' kepada susunan songsang.", "a": "belum sampai lagi mereka"},
        {"q": "Tukarkan ayat susunan biasa 'Kereta baharu bapa sangat laju' kepada susunan songsang.", "a": "sangat laju kereta baharu bapa"},
        {"q": "Tukarkan ayat susunan biasa 'Makanan ini sungguh enak' kepada susunan songsang.", "a": "sungguh enak makanan ini"},
        {"q": "Ayat yang meletakkan predikat di hadapan subjek dipanggil ayat susunan ___?", "a": "songsang"},
        {"q": "Ayat biasa dalam bahasa Melayu bermula dengan unsur ___?", "a": "subjek"},
        {"q": "Tukarkan ayat biasa 'Kakak sedang memasak di dapur' kepada susunan songsang seluruh predikat.", "a": "sedang memasak di dapur kakak"},
        {"q": "Tukarkan 'Adik kecil itu comel betul' kepada susunan songsang.", "a": "comel betul adik kecil itu"},
        {"q": "Tukarkan 'Bunga mawar itu wangi sekali' kepada susunan songsang.", "a": "wangi sekali bunga mawar itu"},
        {"q": "Tukarkan 'Pihak polis tiba di tempat kejadian' kepada susunan songsang.", "a": "tiba di tempat kejadian pihak polis"},
        {"q": "Tukarkan 'Burung-burung itu terbang tinggi' kepada susunan songsang.", "a": "terbang tinggi burung-burung itu"},
        {"q": "Tukarkan 'Buku rujukan itu amat tebal' kepada susunan songsang.", "a": "amat tebal buku rujukan itu"},
        {"q": "Tukarkan 'Sungai itu sangat dalam' kepada susunan songsang.", "a": "sangat dalam sungai itu"},
        {"q": "Tukarkan 'Harga barang itu mahal sangat' kepada susunan songsang.", "a": "mahal sangat harga barang itu"},
        {"q": "Tukarkan 'Datuk sedang berehat di pondok' kepada susunan songsang.", "a": "sedang berehat di pondok datuk"},
        {"q": "Tukarkan 'Cuaca hari ini mendung' kepada susunan songsang.", "a": "mendung cuaca hari ini"},
        {"q": "Tukarkan 'Kasut sekolah saya masih basah' kepada susunan songsang.", "a": "masih basah kasut sekolah saya"},
        {"q": "Tukarkan 'Dia ke sekolah dengan bas' kepada susunan songsang.", "a": "ke sekolah dengan bas dia"},
        {"q": "Tukarkan 'Pekerja itu rajin bekerja' kepada susunan songsang.", "a": "rajin bekerja pekerja itu"},
        {"q": "Tukarkan 'Lukisan adik sangat cantik' kepada susunan songsang.", "a": "sangat cantik lukisan adik"},
        {"q": "Tukarkan 'Kain sutera itu lembut sekali' kepada susunan songsang.", "a": "lembut sekali kain sutera itu"},
        {"q": "Tukarkan 'Badan ahli sukan itu sasa' kepada susunan songsang.", "a": "sasa badan ahli sukan itu"},
        {"q": "Tukarkan 'Suasana di kampung aman damai' kepada susunan songsang.", "a": "aman damai suasana di kampung"},
        {"q": "Tukarkan 'Matahari terbit di sebelah timur' kepada susunan songsang.", "a": "terbit di sebelah timur matahari"},
        {"q": "Tukarkan 'Dia tidak hadir hari ini' kepada susunan songsang.", "a": "tidak hadir hari ini dia"},
        {"q": "Tukarkan 'Kami tinggal di Kuala Lumpur' kepada susunan songsang.", "a": "tinggal di kuala lumpur kami"},
        {"q": "Tukarkan 'Abang lulus dalam peperiksaan' kepada susunan songsang.", "a": "lulus dalam peperiksaan abang"},
        {"q": "Tukarkan 'Kanak-kanak itu gembira sekali' kepada susunan songsang.", "a": "gembira sekali kanak-kanak itu"},
        {"q": "Tukarkan 'Rumah itu kosong tanpa penghuni' kepada susunan songsang.", "a": "kosong tanpa penghuni rumah itu"},
        {"q": "Tukarkan 'Pisau dapur itu tumpul' kepada susunan songsang.", "a": "tumpul pisau dapur itu"},
        {"q": "Tukarkan 'Air sungai itu mengalir tenang' kepada susunan songsang.", "a": "mengalir tenang air sungai itu"},
        {"q": "Tukarkan 'Pelancong asing itu telah pulang' kepada susunan songsang.", "a": "telah pulang pelancong asing itu"},
        {"q": "Tukarkan 'Kerja sekolah saya sudah siap' kepada susunan songsang.", "a": "sudah siap kerja sekolah saya"},
        {"q": "Tukarkan 'Dia menangis kerana lapar' kepada susunan songsang.", "a": "menangis kerana lapar dia"}
    ]
};