// ==========================================
// 1. SCIENCE QUESTION DATA (16 Categories)
// ==========================================
const scienceData = {
"scientific_skills": [
        {"q": "Using senses to gather information about objects or phenomena is known as ___?", "options": ["predicting", "observing", "classifying", "inferring"], "a": 1},
        {"q": "The tool used to measure the length of a book is a ___?", "options": ["thermometer", "stopwatch", "ruler", "beaker"], "a": 2},
        {"q": "The sense used to smell a flower is the sense of ___?", "options": ["sight", "taste", "smell", "touch"], "a": 2},
        {"q": "The sense used to taste an orange is the sense of ___?", "options": ["smell", "taste", "hearing", "touch"], "a": 1},
        {"q": "The sense used to hear a bell is the sense of ___?", "options": ["sight", "smell", "taste", "hearing"], "a": 3},
        {"q": "The sense used to see the color of a leaf is the sense of ___?", "options": ["sight", "touch", "hearing", "smell"], "a": 0},
        {"q": "The sense used to feel if an object is hot is the sense of ___?", "options": ["taste", "smell", "touch", "sight"], "a": 2},
        {"q": "Giving an early explanation for an observation is making an ___?", "options": ["inference", "experiment", "observation", "hypothesis"], "a": 0},
        {"q": "Making an expectation about what will happen next is called ___?", "options": ["inferring", "predicting", "measuring", "classifying"], "a": 1},
        {"q": "Grouping objects based on similar characteristics is known as ___?", "options": ["measuring", "observing", "classifying", "predicting"], "a": 2},
        {"q": "The standard metric unit for measuring temperature is degree ___?", "options": ["fahrenheit", "celsius", "kelvin", "joule"], "a": 1},
        {"q": "A scientific tool used to measure temperature accurately is a ___?", "options": ["ruler", "thermometer", "stopwatch", "microscope"], "a": 1},
        {"q": "A tool used to measure time accurately in a race is a ___?", "options": ["thermometer", "ruler", "stopwatch", "weighing scale"], "a": 2},
        {"q": "The standard unit for a very short duration of time is the ___?", "options": ["hour", "minute", "second", "millisecond"], "a": 2},
        {"q": "A tool used to measure the mass of an object is a weighing ___?", "options": ["cylinder", "scale", "tape", "flask"], "a": 1},
        {"q": "The standard unit for heavy mass is the ___?", "options": ["gram", "milligram", "kilogram", "tonne"], "a": 2},
        {"q": "A tool used to measure the volume of a liquid is a measuring ___?", "options": ["cylinder", "flask", "tube", "beaker"], "a": 0},
        {"q": "The standard unit for liquid volume in small amounts is the ___?", "options": ["litre", "millilitre", "gallon", "pint"], "a": 1},
        {"q": "The variable that is intentionally changed in an experiment is the ___ variable?", "options": ["responding", "constant", "manipulated", "fixed"], "a": 2},
        {"q": "The variable that is observed or measured in an experiment is the ___ variable?", "options": ["manipulated", "responding", "constant", "control"], "a": 1},
        {"q": "The variable that is kept the same throughout the experiment is the ___ variable?", "options": ["manipulated", "responding", "constant", "dependent"], "a": 2},
        {"q": "A testable statement about the relationship between variables is a ___?", "options": ["conclusion", "theory", "hypothesis", "fact"], "a": 2},
        {"q": "The tool used to see very tiny objects like bacteria is a ___?", "options": ["telescope", "microscope", "binoculars", "magnifying glass"], "a": 1},
        {"q": "The tool used to see very distant objects in space is a ___?", "options": ["telescope", "microscope", "periscope", "stethoscope"], "a": 0},
        {"q": "Recording and sharing data in tables or charts is known as ___?", "options": ["observing", "measuring", "communicating", "predicting"], "a": 2},
        {"q": "One way to communicate scientific data visually is by using a ___?", "options": ["graph", "paragraph", "story", "song"], "a": 0},
        {"q": "The tool used to clean a test tube is called a test tube ___?", "options": ["sponge", "cloth", "brush", "wipe"], "a": 2},
        {"q": "Where should liquid chemical waste safely be disposed of in the lab?", "options": ["dustbin", "sink", "floor", "garden"], "a": 1},
        {"q": "Where should solid waste be disposed of in the lab?", "options": ["sink", "toilet", "dustbin", "window"], "a": 2},
        {"q": "What formation must students form before entering the science room?", "options": ["circle", "line", "group", "square"], "a": 1},
        {"q": "What activity is strictly forbidden in the science room?", "options": ["reading", "writing", "eating", "listening"], "a": 2},
        {"q": "Who should you report an accident to immediately?", "options": ["friend", "principal", "parents", "teacher"], "a": 3},
        {"q": "A tool used to put out small fires is a fire ___?", "options": ["blanket", "extinguisher", "hose", "alarm"], "a": 1},
        {"q": "Representing a specimen accurately through art is a scientific ___?", "options": ["drawing", "painting", "sculpture", "sketching"], "a": 0},
        {"q": "The standard unit for measuring area is the ___ centimetre?", "options": ["cubic", "square", "linear", "flat"], "a": 1},
        {"q": "The correct eye level when reading a liquid scale must match the ___?", "options": ["meniscus", "bottom", "top", "edge"], "a": 0},
        {"q": "Using a hand lens makes a specimen look ___?", "options": ["smaller", "bigger", "clearer", "darker"], "a": 1},
        {"q": "Live specimens should be safely returned to their natural ___?", "options": ["habitat", "cage", "bottle", "box"], "a": 0},
        {"q": "The skill of handling science equipment correctly is known as ___ skills?", "options": ["process", "manipulative", "thinking", "observational"], "a": 1},
        {"q": "Arranging data from the smallest value to the largest is known as ___ order?", "options": ["descending", "ascending", "random", "alphabetical"], "a": 1},
        {"q": "The main purpose of an experiment is to test a ___?", "options": ["theory", "law", "hypothesis", "fact"], "a": 2},
        {"q": "A summary of the results at the end of an experiment is called a ___?", "options": ["hypothesis", "procedure", "conclusion", "variable"], "a": 2},
        {"q": "The tool used to measure the girth of a tree is a measuring ___?", "options": ["tape", "ruler", "stick", "scale"], "a": 0},
        {"q": "The unit for measuring a very short length is the ___?", "options": ["centimetre", "metre", "kilometre", "millimetre"], "a": 3},
        {"q": "Anything that can be measured and changed in an experiment is a ___?", "options": ["constant", "variable", "control", "result"], "a": 1},
        {"q": "Measuring the change in litmus paper color uses the skill of ___?", "options": ["observing", "predicting", "classifying", "inferring"], "a": 0},
        {"q": "The trait of a scientist who always wants to find out more is ___?", "options": ["laziness", "curiosity", "impatience", "anger"], "a": 1},
        {"q": "A science room must have good airflow or ___?", "options": ["ventilation", "lighting", "heating", "cooling"], "a": 0},
        {"q": "The first step in a scientific investigation is ___ the problem?", "options": ["solving", "identifying", "ignoring", "guessing"], "a": 1},
        {"q": "An ancient tool used to measure time using falling sand is the ___?", "options": ["sundial", "water clock", "hourglass", "pendulum"], "a": 2}
    ],
    "human_life_processes": [
        {"q": "The main organ used for breathing is the ___?", "options": ["heart", "lungs", "kidneys", "liver"], "a": 1},
        {"q": "The gas we inhale during breathing is ___?", "options": ["carbon dioxide", "nitrogen", "oxygen", "hydrogen"], "a": 2},
        {"q": "The gas we exhale during breathing is carbon ___?", "options": ["monoxide", "dioxide", "trioxide", "peroxide"], "a": 1},
        {"q": "The path of air during inhalation ends at the ___?", "options": ["nose", "trachea", "lungs", "mouth"], "a": 2},
        {"q": "The path of air during exhalation ends at the ___?", "options": ["lungs", "trachea", "nose", "alveoli"], "a": 2},
        {"q": "The small air sacs in the lungs for gas exchange are the ___?", "options": ["bronchi", "alveoli", "trachea", "capillaries"], "a": 1},
        {"q": "Chest movement during inhalation goes upwards and ___?", "options": ["inwards", "downwards", "outwards", "sideways"], "a": 2},
        {"q": "Chest movement during exhalation goes downwards and ___?", "options": ["inwards", "outwards", "upwards", "sideways"], "a": 0},
        {"q": "The breathing rate when we are sleeping is ___?", "options": ["high", "moderate", "low", "zero"], "a": 2},
        {"q": "The breathing rate when we are running is ___?", "options": ["low", "moderate", "high", "zero"], "a": 2},
        {"q": "The process of removing waste from the body is ___?", "options": ["digestion", "respiration", "excretion", "circulation"], "a": 2},
        {"q": "The process of removing undigested food from the body is ___?", "options": ["excretion", "defecation", "respiration", "digestion"], "a": 1},
        {"q": "The organ that excretes urine is the ___?", "options": ["liver", "skin", "lungs", "kidneys"], "a": 3},
        {"q": "The organ that excretes sweat is the ___?", "options": ["lungs", "kidneys", "skin", "heart"], "a": 2},
        {"q": "The organ that excretes carbon dioxide is the ___?", "options": ["kidneys", "lungs", "skin", "liver"], "a": 1},
        {"q": "The liquid waste product of the kidneys is ___?", "options": ["sweat", "blood", "urine", "saliva"], "a": 2},
        {"q": "The waste product released through the skin is ___?", "options": ["urine", "feces", "sweat", "tears"], "a": 2},
        {"q": "Besides carbon dioxide, the lungs also excrete water ___?", "options": ["vapor", "liquid", "ice", "droplets"], "a": 0},
        {"q": "Excretion is important to humans to ensure we stay ___?", "options": ["sick", "healthy", "tired", "hungry"], "a": 1},
        {"q": "The body's reaction to a change in its surroundings is a response to ___?", "options": ["stimuli", "food", "sleep", "exercise"], "a": 0},
        {"q": "Closing your eyes when bright light shines is a response to ___?", "options": ["sound", "light", "touch", "temperature"], "a": 1},
        {"q": "Shivering when it is very cold is a response to ___?", "options": ["light", "sound", "temperature", "pain"], "a": 2},
        {"q": "Pulling your hand away from a hot stove is a response to ___?", "options": ["heat", "light", "sound", "smell"], "a": 0},
        {"q": "The sense organ used for hearing sound stimuli is the ___?", "options": ["eyes", "ears", "nose", "tongue"], "a": 1},
        {"q": "The sense organ used for tasting food is the ___?", "options": ["nose", "tongue", "skin", "eyes"], "a": 1},
        {"q": "The sense organ used for smelling is the ___?", "options": ["tongue", "ears", "nose", "skin"], "a": 2},
        {"q": "The sense organ used for touch and temperature is the ___?", "options": ["eyes", "skin", "nose", "ears"], "a": 1},
        {"q": "Humans reproduce to ensure species survival by giving ___?", "options": ["eggs", "birth", "seeds", "spores"], "a": 1},
        {"q": "Passing characteristics from parents to offspring is called ___?", "options": ["growth", "inheritance", "learning", "mutation"], "a": 1},
        {"q": "An example of a physical trait inherited from parents is the type of ___?", "options": ["clothes", "hair", "shoes", "food"], "a": 1},
        {"q": "Another example of an inherited characteristic is the color of our ___?", "options": ["eyesight", "skin", "voice", "teeth"], "a": 1},
        {"q": "The inherited colored part of the eye is called the ___?", "options": ["pupil", "cornea", "iris", "retina"], "a": 2},
        {"q": "A harmful and addictive substance found in cigarettes is ___?", "options": ["caffeine", "nicotine", "alcohol", "sugar"], "a": 1},
        {"q": "A bad habit that seriously damages the lungs is ___?", "options": ["sleeping", "running", "smoking", "eating"], "a": 2},
        {"q": "A substance that slows down response to stimuli when consumed is ___?", "options": ["water", "juice", "alcohol", "milk"], "a": 2},
        {"q": "Substances that cause hallucinations and loss of coordination are ___?", "options": ["vitamins", "minerals", "drugs", "proteins"], "a": 2},
        {"q": "The muscle that helps in the breathing process is the ___?", "options": ["heart", "bicep", "diaphragm", "tricep"], "a": 2},
        {"q": "The bones that protect the heart and lungs form the rib ___?", "options": ["cage", "box", "wall", "shield"], "a": 0},
        {"q": "Difficulty in passing out feces is called ___?", "options": ["diarrhea", "constipation", "indigestion", "vomiting"], "a": 1},
        {"q": "To prevent constipation, we must eat enough ___?", "options": ["fat", "sugar", "fiber", "salt"], "a": 2},
        {"q": "The gas required by body cells to stay alive is ___?", "options": ["oxygen", "carbon dioxide", "nitrogen", "helium"], "a": 0},
        {"q": "The temporary storage organ for urine in the body is the ___?", "options": ["kidney", "bladder", "liver", "stomach"], "a": 1},
        {"q": "Undigested food waste is known as ___?", "options": ["urine", "sweat", "feces", "saliva"], "a": 2},
        {"q": "Is height an inherited characteristic?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "Can a scar from an injury be inherited?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "The human life cycle begins from a ___?", "options": ["toddler", "child", "baby", "teenager"], "a": 2},
        {"q": "Jumping when hearing a loud thunder is a response to ___?", "options": ["light", "sound", "temperature", "touch"], "a": 1},
        {"q": "Breathing rate is measured as breaths per ___?", "options": ["second", "minute", "hour", "day"], "a": 1},
        {"q": "The windpipe that connects the nose to the lungs is the ___?", "options": ["esophagus", "trachea", "vein", "artery"], "a": 1},
        {"q": "The process of making new individuals is ___?", "options": ["respiration", "digestion", "reproduction", "excretion"], "a": 2}
    ],
    "animal_classification": [
        {"q": "Animals with a backbone are called ___?", "options": ["invertebrates", "vertebrates", "amphibians", "mammals"], "a": 1},
        {"q": "Animals without a backbone are called ___?", "options": ["vertebrates", "invertebrates", "reptiles", "birds"], "a": 1},
        {"q": "The breathing organ of a fish is the ___?", "options": ["lungs", "spiracles", "gills", "skin"], "a": 2},
        {"q": "The breathing organ of a grasshopper is the ___?", "options": ["lungs", "gills", "spiracles", "skin"], "a": 2},
        {"q": "A worm breathes through its moist ___?", "options": ["lungs", "spiracles", "gills", "skin"], "a": 3},
        {"q": "The breathing organ of a cat is the ___?", "options": ["gills", "lungs", "spiracles", "skin"], "a": 1},
        {"q": "Animals that live both on land and in water are ___?", "options": ["reptiles", "amphibians", "mammals", "fish"], "a": 1},
        {"q": "A frog in water breathes through its moist ___?", "options": ["lungs", "gills", "skin", "spiracles"], "a": 2},
        {"q": "A frog on land breathes using its ___?", "options": ["lungs", "gills", "skin", "spiracles"], "a": 0},
        {"q": "Animals that eat only plants are called ___?", "options": ["carnivores", "omnivores", "herbivores", "predators"], "a": 2},
        {"q": "Animals that eat only other animals are called ___?", "options": ["herbivores", "carnivores", "omnivores", "scavengers"], "a": 1},
        {"q": "Animals that eat both plants and animals are called ___?", "options": ["herbivores", "carnivores", "omnivores", "producers"], "a": 2},
        {"q": "Is a cow a herbivore, carnivore, or omnivore?", "options": ["carnivore", "herbivore", "omnivore", "insectivore"], "a": 1},
        {"q": "Is a tiger a herbivore, carnivore, or omnivore?", "options": ["herbivore", "omnivore", "carnivore", "insectivore"], "a": 2},
        {"q": "Is a chicken a herbivore, carnivore, or omnivore?", "options": ["herbivore", "carnivore", "omnivore", "insectivore"], "a": 2},
        {"q": "Animals that give birth to their young are ___?", "options": ["birds", "reptiles", "amphibians", "mammals"], "a": 3},
        {"q": "Animals that lay eggs and have feathers are ___?", "options": ["mammals", "birds", "reptiles", "fish"], "a": 1},
        {"q": "Animals with dry scales that lay eggs are ___?", "options": ["amphibians", "reptiles", "mammals", "birds"], "a": 1},
        {"q": "A whale breathes through its ___?", "options": ["gills", "spiracles", "lungs", "skin"], "a": 2},
        {"q": "A dolphin is classified as a ___?", "options": ["fish", "mammal", "amphibian", "reptile"], "a": 1},
        {"q": "A platypus is a unique mammal because it lays ___?", "options": ["eggs", "spores", "seeds", "larvae"], "a": 0},
        {"q": "Insects have how many legs?", "options": ["four", "six", "eight", "ten"], "a": 1},
        {"q": "A spider is an invertebrate because it has no ___?", "options": ["legs", "eyes", "backbone", "skin"], "a": 2},
        {"q": "Which group of vertebrates are warm-blooded and have fur?", "options": ["birds", "reptiles", "amphibians", "mammals"], "a": 3},
        {"q": "The breathing organ of a shrimp is the ___?", "options": ["lungs", "spiracles", "gills", "skin"], "a": 2},
        {"q": "A butterfly breathes through its ___?", "options": ["lungs", "gills", "skin", "spiracles"], "a": 3},
        {"q": "An example of a reptile that lives in water is a ___?", "options": ["frog", "turtle", "dolphin", "shark"], "a": 1},
        {"q": "Birds breathe using their ___?", "options": ["gills", "skin", "lungs", "spiracles"], "a": 2},
        {"q": "Is a crocodile a vertebrate or invertebrate?", "options": ["invertebrate", "vertebrate", "both", "neither"], "a": 1},
        {"q": "A penguin is classified as a ___?", "options": ["mammal", "reptile", "amphibian", "bird"], "a": 3},
        {"q": "The hard outer covering of an insect is an ___?", "options": ["endoskeleton", "exoskeleton", "shell", "skin"], "a": 1},
        {"q": "An animal that produces milk for its young is a ___?", "options": ["mammal", "bird", "reptile", "amphibian"], "a": 0},
        {"q": "Salamanders and newts are examples of ___?", "options": ["reptiles", "amphibians", "mammals", "fish"], "a": 1},
        {"q": "A snail is an example of an ___?", "options": ["invertebrate", "vertebrate", "mammal", "amphibian"], "a": 0},
        {"q": "Does a snake have a backbone?", "options": ["yes", "no", "sometimes", "rarely"], "a": 0},
        {"q": "Animals that hunt other animals for food are ___?", "options": ["prey", "producers", "predators", "decomposers"], "a": 2},
        {"q": "Animals that are hunted and eaten are ___?", "options": ["predators", "scavengers", "prey", "producers"], "a": 2},
        {"q": "A bat is the only mammal that can ___?", "options": ["swim", "run", "fly", "jump"], "a": 2},
        {"q": "Is an eagle a carnivore?", "options": ["no", "yes", "sometimes", "rarely"], "a": 1},
        {"q": "Do all mammals live on land?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "Is a shark a mammal or a fish?", "options": ["mammal", "fish", "amphibian", "reptile"], "a": 1},
        {"q": "Invertebrates like crabs have a hard ___?", "options": ["skin", "shell", "scale", "feather"], "a": 1},
        {"q": "Which organ do tadpoles use to breathe?", "options": ["lungs", "spiracles", "gills", "skin"], "a": 2},
        {"q": "A lizard is classified as a ___?", "options": ["amphibian", "reptile", "mammal", "bird"], "a": 1},
        {"q": "The group of animals that feed their young with milk are ___?", "options": ["mammals", "birds", "reptiles", "fish"], "a": 0},
        {"q": "Are most insects vertebrates or invertebrates?", "options": ["vertebrates", "invertebrates", "both", "neither"], "a": 1},
        {"q": "A dragonfly is an example of an ___?", "options": ["arachnid", "crustacean", "insect", "amphibian"], "a": 2},
        {"q": "The breathing organ of a caterpillar is the ___?", "options": ["gills", "lungs", "skin", "spiracles"], "a": 3},
        {"q": "Is a bear an omnivore?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "An animal with a streamlined body for swimming is a ___?", "options": ["bird", "fish", "mammal", "insect"], "a": 1}
    ],
        
"plant_processes": [
        {"q": "The process by which plants make their own food is ___?", "options": ["respiration", "digestion", "photosynthesis", "transpiration"], "a": 2},
        {"q": "The green pigment found in leaves is called ___?", "options": ["melanin", "chlorophyll", "carotene", "hemoglobin"], "a": 1},
        {"q": "The gas absorbed by plants for photosynthesis is carbon ___?", "options": ["monoxide", "dioxide", "peroxide", "trioxide"], "a": 1},
        {"q": "The gas released by plants during photosynthesis is ___?", "options": ["nitrogen", "oxygen", "hydrogen", "helium"], "a": 1},
        {"q": "The main source of energy for photosynthesis is ___?", "options": ["wind", "soil", "water", "sunlight"], "a": 3},
        {"q": "What do plants absorb from the soil for photosynthesis?", "options": ["sunlight", "oxygen", "water", "carbon dioxide"], "a": 2},
        {"q": "The food produced by photosynthesis is stored as ___?", "options": ["fat", "protein", "starch", "mineral"], "a": 2},
        {"q": "Which part of the plant usually carries out photosynthesis?", "options": ["roots", "leaves", "stem", "flowers"], "a": 1},
        {"q": "Plant shoots grow towards which stimulus?", "options": ["gravity", "water", "light", "touch"], "a": 2},
        {"q": "Plant roots grow towards which stimulus?", "options": ["light", "water", "heat", "wind"], "a": 1},
        {"q": "Plant roots also respond to the downward pull of ___?", "options": ["gravity", "light", "water", "magnetism"], "a": 0},
        {"q": "Mimosa pudica (touch-me-not) leaves fold inward when ___?", "options": ["watered", "heated", "touched", "illuminated"], "a": 2},
        {"q": "Venus flytrap leaves snap shut in response to ___?", "options": ["light", "touch", "water", "sound"], "a": 1},
        {"q": "A potato plant usually stores starch in its underground ___?", "options": ["root", "stem", "leaf", "flower"], "a": 1},
        {"q": "Tiny pores on the surface of leaves are called ___?", "options": ["alveoli", "stomata", "chloroplasts", "veins"], "a": 1},
        {"q": "How do non-flowering plants like ferns reproduce?", "options": ["seeds", "cuttings", "spores", "suckers"], "a": 2},
        {"q": "How do banana plants reproduce?", "options": ["seeds", "spores", "suckers", "cuttings"], "a": 2},
        {"q": "Hibiscus plants usually reproduce through stem ___?", "options": ["suckers", "cuttings", "leaves", "roots"], "a": 1},
        {"q": "How do mushrooms reproduce?", "options": ["spores", "seeds", "suckers", "flowers"], "a": 0},
        {"q": "Onions typically reproduce using underground ___?", "options": ["roots", "leaves", "stems", "seeds"], "a": 2},
        {"q": "The scattering of seeds away from the parent plant is called ___?", "options": ["pollination", "germination", "dispersal", "fertilization"], "a": 2},
        {"q": "Seeds dispersed by wind are usually light and have ___?", "options": ["hooks", "wings", "shells", "flesh"], "a": 1},
        {"q": "An example of a seed dispersed by wind is the ___?", "options": ["coconut", "mango", "dandelion", "burs"], "a": 2},
        {"q": "Seeds dispersed by water have a husk that is ___?", "options": ["spongy", "heavy", "sticky", "sweet"], "a": 0},
        {"q": "An example of a fruit dispersed by water is the ___?", "options": ["apple", "coconut", "papaya", "tomato"], "a": 1},
        {"q": "Fruits dispersed by animals are usually brightly colored and ___?", "options": ["dry", "fleshy", "spongy", "light"], "a": 1},
        {"q": "Seeds dispersed by an explosive mechanism will naturally ___?", "options": ["float", "fly", "burst", "sink"], "a": 2},
        {"q": "A seed dispersed by an explosive mechanism is the rubber ___?", "options": ["seed", "fruit", "leaf", "root"], "a": 0},
        {"q": "Seeds must be dispersed far away to avoid ___?", "options": ["predators", "sunlight", "competition", "water"], "a": 2},
        {"q": "A cactus stores water in the desert using its fleshy ___?", "options": ["leaves", "stem", "roots", "flowers"], "a": 1},
        {"q": "Some plants shed their leaves in the dry season to prevent water ___?", "options": ["gain", "loss", "absorption", "pollution"], "a": 1},
        {"q": "A plant that sheds its leaves during dry seasons is the rubber ___?", "options": ["tree", "bush", "vine", "grass"], "a": 0},
        {"q": "Needle-like leaves help pine trees prevent water ___?", "options": ["freezing", "loss", "absorption", "coloring"], "a": 1},
        {"q": "What protects a rose plant from enemies?", "options": ["poison", "bad smell", "thorns", "latex"], "a": 2},
        {"q": "What liquid protects a papaya tree from insects?", "options": ["water", "nectar", "latex", "sap"], "a": 2},
        {"q": "Bamboo protects itself from enemies using fine ___?", "options": ["hairs", "spikes", "thorns", "scales"], "a": 0},
        {"q": "Fine hairs on bamboo stems can cause ___?", "options": ["sleepiness", "blindness", "itchiness", "deafness"], "a": 2},
        {"q": "A rafflesia flower protects itself from herbivores by releasing a bad ___?", "options": ["taste", "sound", "smell", "toxin"], "a": 2},
        {"q": "Some plants like the pong-pong tree protect themselves by being ___?", "options": ["spiky", "poisonous", "camouflage", "hard"], "a": 1},
        {"q": "Does a mushroom make its own food?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "Do all plants produce flowers?", "options": ["yes", "no", "mostly", "rarely"], "a": 1},
        {"q": "What part of the plant holds it firmly in the ground?", "options": ["stem", "leaves", "roots", "flowers"], "a": 2},
        {"q": "The tube that transports water from roots to leaves is the ___?", "options": ["phloem", "stomata", "vein", "xylem"], "a": 3},
        {"q": "The tube that transports food from leaves to other parts is the ___?", "options": ["xylem", "phloem", "capillary", "artery"], "a": 1},
        {"q": "A lotus floats on water because its stem contains air ___?", "options": ["spaces", "bubbles", "balloons", "pockets"], "a": 0},
        {"q": "Morning glory plants get enough sunlight using their climbing ___?", "options": ["roots", "leaves", "stems", "flowers"], "a": 2},
        {"q": "A pineapple plant protects itself from being eaten using its sharp ___?", "options": ["roots", "stem", "leaves", "fruit"], "a": 2},
        {"q": "Plants are known as what in a food chain?", "options": ["consumers", "producers", "decomposers", "predators"], "a": 1},
        {"q": "Does a plant need oxygen to survive?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "What do seeds need to germinate? Water, air, and ___?", "options": ["soil", "light", "warmth", "fertilizer"], "a": 2}
    ],
    "microorganisms": [
        {"q": "Very tiny living things that cannot be seen with the naked eye are ___?", "options": ["insects", "microorganisms", "dust", "minerals"], "a": 1},
        {"q": "The tool used to see microorganisms clearly is a ___?", "options": ["telescope", "microscope", "magnifying glass", "binoculars"], "a": 1},
        {"q": "A type of microorganism used to make bread rise is ___?", "options": ["bacteria", "virus", "yeast", "algae"], "a": 2},
        {"q": "Mushrooms and molds belong to which biological group?", "options": ["plants", "animals", "bacteria", "fungi"], "a": 3},
        {"q": "A type of microorganism often found in yogurt is ___?", "options": ["virus", "bacteria", "yeast", "protozoa"], "a": 1},
        {"q": "The smallest type of microorganism is a ___?", "options": ["bacteria", "fungi", "virus", "algae"], "a": 2},
        {"q": "Microorganisms breathe, move and ___?", "options": ["grow", "talk", "think", "sleep"], "a": 0},
        {"q": "Dough rising is proof that yeast is ___?", "options": ["sleeping", "breathing", "dying", "swimming"], "a": 1},
        {"q": "What do fungi produce to reproduce?", "options": ["seeds", "eggs", "spores", "babies"], "a": 2},
        {"q": "Food turns moldy because of the growth of ___?", "options": ["viruses", "bacteria", "algae", "fungi"], "a": 3},
        {"q": "Diseases caused by microorganisms are called ___ diseases.", "options": ["genetic", "infectious", "chronic", "deficiency"], "a": 1},
        {"q": "Is a mushroom technically a type of fungi?", "options": ["no", "yes", "sometimes", "rarely"], "a": 1},
        {"q": "Can some bacteria be useful to humans?", "options": ["no", "yes", "never", "rarely"], "a": 1},
        {"q": "Tooth decay is primarily caused by ___?", "options": ["sugar", "bacteria", "viruses", "fungi"], "a": 1},
        {"q": "A medicine used specifically to kill bacteria is an ___?", "options": ["antiviral", "antibiotic", "painkiller", "vaccine"], "a": 1},
        {"q": "What do we wear on our face to prevent spreading viruses through coughing?", "options": ["glasses", "mask", "hat", "scarf"], "a": 1},
        {"q": "Washing hands with soap helps to physically remove ___?", "options": ["skin cells", "dirt only", "microorganisms", "water"], "a": 2},
        {"q": "Which microorganism causes the common flu?", "options": ["bacteria", "fungi", "virus", "protozoa"], "a": 2},
        {"q": "An example of a single-celled microorganism found in pond water is ___?", "options": ["yeast", "virus", "protozoa", "mold"], "a": 2},
        {"q": "Microorganisms need air, food, and ___ to grow.", "options": ["light", "soil", "water", "heat"], "a": 2},
        {"q": "What temperature condition is best for typical microorganism growth? ___ temperature.", "options": ["freezing", "room", "boiling", "oven"], "a": 1},
        {"q": "Can certain microorganisms live in very cold places?", "options": ["yes", "no", "never", "impossible"], "a": 0},
        {"q": "Is Amoeba a type of protozoa?", "options": ["no", "yes", "sometimes", "rarely"], "a": 1},
        {"q": "The fuzzy green spots on old bread are usually ___?", "options": ["bacteria", "algae", "viruses", "fungi"], "a": 3},
        {"q": "Does extreme heat kill most microorganisms?", "options": ["no", "yes", "sometimes", "rarely"], "a": 1},
        {"q": "Vaccinations help our body fight against ___?", "options": ["bacteria only", "fungi", "viruses", "allergies"], "a": 2},
        {"q": "Are all microorganisms harmful?", "options": ["yes", "no", "always", "mostly"], "a": 1},
        {"q": "What is the common term for harmful microorganisms that cause illness?", "options": ["germs", "bugs", "pests", "weeds"], "a": 0},
        {"q": "Which process is used to make tap water safe from germs?", "options": ["filtration", "boiling", "chlorination", "freezing"], "a": 2},
        {"q": "Is Penicillium a type of useful fungi?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "Microorganisms that live in water and can make their own food are ___?", "options": ["protozoa", "fungi", "bacteria", "algae"], "a": 3},
        {"q": "The study of microorganisms is called ___?", "options": ["biology", "microbiology", "zoology", "botany"], "a": 1},
        {"q": "Can we see a single bacterium with our bare eyes?", "options": ["yes", "no", "sometimes", "easily"], "a": 1},
        {"q": "Does freezing kill all microorganisms?", "options": ["yes", "no", "always", "mostly"], "a": 1},
        {"q": "Microorganisms grow much faster in ___ conditions.", "options": ["dry", "damp", "freezing", "bright"], "a": 1},
        {"q": "The process where yeast makes bread rise is called ___?", "options": ["respiration", "photosynthesis", "fermentation", "digestion"], "a": 2},
        {"q": "Is COVID-19 caused by a bacteria or a virus?", "options": ["bacteria", "virus", "fungi", "protozoa"], "a": 1},
        {"q": "Are microorganisms used in making soil compost?", "options": ["no", "yes", "never", "rarely"], "a": 1},
        {"q": "Spoiled food usually has a very bad ___?", "options": ["taste only", "look", "smell", "color"], "a": 2},
        {"q": "The process where microorganisms break down dead things is ___?", "options": ["digestion", "decomposition", "fermentation", "respiration"], "a": 1},
        {"q": "Does stomach acid help kill some germs?", "options": ["yes", "no", "never", "rarely"], "a": 0},
        {"q": "Microorganisms breathe in order to produce ___?", "options": ["oxygen", "water", "food", "energy"], "a": 3},
        {"q": "A microscopic type of algae often found in oceans is ___?", "options": ["seaweed", "kelp", "phytoplankton", "moss"], "a": 2},
        {"q": "Can viruses reproduce outside a living host cell?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "Using a separate cutting board for meat prevents cross-___?", "options": ["infection", "contamination", "pollination", "reaction"], "a": 1},
        {"q": "Is yeast a multicellular or unicellular organism?", "options": ["multicellular", "unicellular", "both", "neither"], "a": 1},
        {"q": "Is Paramecium a type of protozoa?", "options": ["no", "yes", "sometimes", "rarely"], "a": 1},
        {"q": "Which sense helps you safely identify rotten food from a distance?", "options": ["sight", "taste", "smell", "touch"], "a": 2},
        {"q": "Microorganisms are found virtually ___?", "options": ["nowhere", "in water only", "in soil only", "everywhere"], "a": 3},
        {"q": "A visible group of bacteria growing together is called a ___?", "options": ["herd", "flock", "colony", "pack"], "a": 2}
    ],

"energy_forms": [
        {"q": "What is the primary source of energy on Earth?", "options": ["Moon", "Earth", "Sun", "Stars"], "a": 2},
        {"q": "Energy possessed by a moving object is called ___ energy?", "a": "kinetic"},
        {"q": "Energy stored in food, wood, or batteries is called ___ energy?", "options": ["kinetic", "chemical", "potential", "heat"], "a": 1},
        {"q": "Energy that we can see is called ___ energy?", "a": "light"},
        {"q": "Energy produced by vibrating objects is called ___ energy?", "options": ["light", "sound", "heat", "electrical"], "a": 1},
        {"q": "Energy that makes us feel warm is called ___ energy?", "a": "heat"},
        {"q": "Energy stored in a stretched rubber band or lifted object is ___ energy?", "options": ["potential", "kinetic", "nuclear", "chemical"], "a": 0},
        {"q": "Energy flowing through electrical wires is called ___ energy?", "a": "electrical"},
        {"q": "Energy generated from the splitting of atoms is ___ energy?", "options": ["chemical", "nuclear", "potential", "kinetic"], "a": 1},
        {"q": "Is energy from the Sun renewable or nonrenewable?", "a": "renewable"},
        {"q": "Are fossil fuels renewable or nonrenewable?", "options": ["renewable", "nonrenewable", "both", "neither"], "a": 1},
        {"q": "An example of a fossil fuel extracted from the ground is ___?", "a": "petroleum"},
        {"q": "Energy source from plant and animal waste is called ___?", "options": ["fossil", "biomass", "geothermal", "hydroelectric"], "a": 1},
        {"q": "Electricity generated from moving water is called ___?", "a": "hydroelectric"},
        {"q": "Principle: Energy cannot be created or ___?", "options": ["stored", "transferred", "destroyed", "used"], "a": 2},
        {"q": "In a battery, chemical energy changes to ___ energy?", "a": "electrical"},
        {"q": "In a light bulb, electrical energy changes to light and ___ energy?", "options": ["sound", "heat", "kinetic", "chemical"], "a": 1},
        {"q": "In a radio, electrical energy changes to ___ energy?", "a": "sound"},
        {"q": "A solar panel changes solar energy to ___ energy?", "options": ["heat", "electrical", "chemical", "light"], "a": 1},
        {"q": "When you rub your hands together, kinetic energy changes to ___ energy?", "a": "heat"},
        {"q": "A television converts electrical energy into sound and ___ energy?", "options": ["heat", "light", "kinetic", "chemical"], "a": 1},
        {"q": "An electric iron converts electrical energy into ___ energy?", "a": "heat"},
        {"q": "A falling apple changes potential energy into ___ energy?", "options": ["kinetic", "heat", "sound", "chemical"], "a": 0},
        {"q": "During photosynthesis, solar energy changes into ___ energy?", "a": "chemical"},
        {"q": "Energy that can be replenished constantly is called ___ energy?", "options": ["nonrenewable", "potential", "renewable", "kinetic"], "a": 2},
        {"q": "Energy that will run out and cannot be replaced quickly is ___ energy?", "a": "nonrenewable"},
        {"q": "Wind turbines use what type of energy source?", "options": ["water", "wind", "sun", "geothermal"], "a": 1},
        {"q": "Is coal a renewable energy source?", "a": "no"},
        {"q": "Is ocean wave a renewable energy source?", "options": ["yes", "no", "sometimes", "rarely"], "a": 0},
        {"q": "Energy obtained from hot rocks deep underground is ___ energy?", "a": "geothermal"},
        {"q": "Switching off lights when leaving a room helps to ___ energy?", "options": ["create", "save", "destroy", "waste"], "a": 1},
        {"q": "Carpooling helps to save fuel, specifically ___ fuels?", "a": "fossil"},
        {"q": "Food provides humans with ___ energy?", "options": ["potential", "heat", "chemical", "kinetic"], "a": 2},
        {"q": "When a bow is pulled back, it gains ___ energy?", "a": "potential"},
        {"q": "The faster a car moves, the more ___ energy it has.", "options": ["potential", "heat", "kinetic", "sound"], "a": 2},
        {"q": "A ringing school bell produces ___ energy?", "a": "sound"},
        {"q": "A lit candle converts chemical energy into light and ___ energy?", "options": ["kinetic", "heat", "sound", "electrical"], "a": 1},
        {"q": "A moving bicycle has ___ energy?", "a": "kinetic"},
        {"q": "A laptop runs on ___ energy?", "options": ["chemical", "electrical", "heat", "nuclear"], "a": 1},
        {"q": "The energy stored in fossil fuels originally came from the ___?", "a": "Sun"},
        {"q": "Riding a bicycle instead of driving helps save ___?", "options": ["fuel", "water", "time", "food"], "a": 0},
        {"q": "Solar panels are usually placed on the ___?", "a": "roof"},
        {"q": "Do plants use kinetic energy to make food?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "The main form of energy you get from sitting near a campfire is ___ energy?", "a": "heat"},
        {"q": "A book resting high up on a shelf has ___ energy?", "options": ["potential", "kinetic", "chemical", "heat"], "a": 0},
        {"q": "A washing machine converts electrical energy mainly into ___ energy?", "a": "kinetic"},
        {"q": "An electric toaster converts electrical energy into ___ energy?", "options": ["sound", "heat", "light", "kinetic"], "a": 1},
        {"q": "Are natural gas reserves limitless?", "a": "no"},
        {"q": "Using energy wisely ensures we have enough for the ___?", "options": ["past", "present", "future", "moment"], "a": 2},
        {"q": "Batteries store energy in the form of ___ energy?", "a": "chemical"}
    ],
    "light_properties": [
        {"q": "Light travels in a ___ line.", "options": ["curved", "straight", "zigzag", "wavy"], "a": 1},
        {"q": "The bouncing of light off a surface is called ___?", "a": "reflection"},
        {"q": "The bending of light as it moves between different materials is called ___?", "options": ["reflection", "refraction", "absorption", "dispersion"], "a": 1},
        {"q": "An object that allows all light to pass through it is ___?", "a": "transparent"},
        {"q": "An object that allows only some light to pass through it is ___?", "options": ["transparent", "translucent", "opaque", "reflective"], "a": 1},
        {"q": "An object that does not allow any light to pass through it is ___?", "a": "opaque"},
        {"q": "Is clear glass transparent, translucent, or opaque?", "options": ["transparent", "translucent", "opaque", "absorbent"], "a": 0},
        {"q": "Is wood transparent, translucent, or opaque?", "a": "opaque"},
        {"q": "Is frosted glass transparent, translucent, or opaque?", "options": ["transparent", "translucent", "opaque", "reflective"], "a": 1},
        {"q": "A dark area formed when light is blocked by an object is a ___?", "a": "shadow"},
        {"q": "If an object is moved closer to the light source, the shadow becomes ___?", "options": ["smaller", "bigger", "unchanged", "brighter"], "a": 1},
        {"q": "If the screen is moved further from the object, the shadow becomes ___?", "a": "bigger"},
        {"q": "Shadows are formed because light travels in a ___ line?", "options": ["curved", "zigzag", "straight", "broken"], "a": 2},
        {"q": "A tool that uses reflection to see behind or around corners is a ___?", "a": "periscope"},
        {"q": "A surface that reflects light well is usually smooth and ___?", "options": ["dull", "rough", "shiny", "dark"], "a": 2},
        {"q": "An example of an object that reflects light is a ___?", "a": "mirror"},
        {"q": "A pencil looks bent in a glass of water due to ___?", "options": ["reflection", "refraction", "absorption", "dispersion"], "a": 1},
        {"q": "The size of a pool looks shallower than it is due to ___?", "a": "refraction"},
        {"q": "A tool used to see tiny objects by refracting light is a ___?", "options": ["telescope", "periscope", "microscope", "kaleidoscope"], "a": 2},
        {"q": "A tool used to see distant stars through refraction or reflection is a ___?", "a": "telescope"},
        {"q": "A glass object that separates white light into seven colors is a ___?", "options": ["lens", "mirror", "prism", "filter"], "a": 2},
        {"q": "The seven colors of light are seen in a ___?", "a": "rainbow"},
        {"q": "The first color in a rainbow is ___?", "options": ["blue", "green", "red", "violet"], "a": 2},
        {"q": "A mirror with a flat surface is called a ___ mirror?", "a": "plane"},
        {"q": "A mirror that curves outwards is a ___ mirror?", "options": ["plane", "concave", "convex", "flat"], "a": 2},
        {"q": "A mirror that curves inwards is a ___ mirror?", "a": "concave"},
        {"q": "Side mirrors of a car are usually ___ mirrors?", "options": ["concave", "plane", "convex", "tinted"], "a": 2},
        {"q": "Security mirrors in shops are usually ___ mirrors?", "a": "convex"},
        {"q": "Dentists use a ___ mirror to see teeth clearly?", "options": ["concave", "convex", "plane", "two-way"], "a": 0},
        {"q": "Does a shadow have colors?", "a": "no"},
        {"q": "When light hits a mirror, it is ___?", "options": ["absorbed", "refracted", "reflected", "scattered"], "a": 2},
        {"q": "What happens to light when it enters a prism?", "a": "refraction"},
        {"q": "Can light pass through a brick wall?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "Is water a transparent material?", "a": "yes"},
        {"q": "Is a shadow always the same shape as the object?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "What is the natural source of light for Earth?", "a": "sun"},
        {"q": "Lenses in spectacles work based on light ___?", "options": ["reflection", "refraction", "absorption", "dispersion"], "a": 1},
        {"q": "A magnifying glass uses which property of light?", "a": "refraction"},
        {"q": "Light travels faster in air than in ___?", "options": ["space", "vacuum", "water", "nothing"], "a": 2},
        {"q": "A periscope contains two ___?", "a": "mirrors"},
        {"q": "Can we see objects in a completely dark room?", "options": ["yes", "no", "sometimes", "barely"], "a": 1},
        {"q": "To see an object, light must be ___ into our eyes.", "a": "reflected"},
        {"q": "Does air allow light to pass through?", "options": ["yes", "no", "partially", "never"], "a": 0},
        {"q": "A shadow is shortest when the sun is ___?", "a": "overhead"},
        {"q": "Shadows are longest during sunrise and ___?", "options": ["noon", "sunset", "midnight", "morning"], "a": 1},
        {"q": "The image in a plane mirror is always the same ___ as the object.", "a": "size"},
        {"q": "Is clear plastic a transparent material?", "options": ["yes", "no", "sometimes", "barely"], "a": 0},
        {"q": "Refraction happens because the ___ of light changes.", "a": "speed"},
        {"q": "A rainbow is formed when sunlight is refracted by ___?", "options": ["dust", "raindrops", "mirrors", "leaves"], "a": 1},
        {"q": "Can a shadow be formed by a transparent object?", "a": "no"}
    ],
    "electricity_basics": [
        {"q": "What provides electrical energy in a simple circuit?", "options": ["bulb", "wire", "switch", "battery"], "a": 3},
        {"q": "What component converts electrical energy into light energy in a circuit?", "a": "bulb"},
        {"q": "The component used to connect all parts of a circuit is the ___?", "options": ["battery", "wire", "bulb", "switch"], "a": 1},
        {"q": "The component used to complete or break a circuit is the ___?", "a": "switch"},
        {"q": "A circuit where electricity can flow fully is called a ___ circuit?", "options": ["open", "closed", "broken", "short"], "a": 1},
        {"q": "A circuit where the path of electricity is broken is called an ___ circuit?", "a": "open"},
        {"q": "If the switch is open, will the bulb light up?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "If the switch is closed, will the bulb light up?", "a": "yes"},
        {"q": "A circuit with only one path for electricity to flow is a ___ circuit?", "options": ["parallel", "series", "open", "short"], "a": 1},
        {"q": "A circuit with more than one path for electricity to flow is a ___ circuit?", "a": "parallel"},
        {"q": "In which circuit do bulbs share the exact same path?", "options": ["parallel", "series", "open", "short"], "a": 1},
        {"q": "In which circuit is each bulb on a different branch?", "a": "parallel"},
        {"q": "Adding more dry cells in a series circuit makes the bulb ___?", "options": ["dimmer", "brighter", "unchanged", "explode"], "a": 1},
        {"q": "Adding more bulbs in a series circuit makes the bulbs ___?", "a": "dimmer"},
        {"q": "Which type of circuit is typically used in most houses?", "options": ["series", "parallel", "open", "short"], "a": 1},
        {"q": "If one bulb blows in a series circuit, do the others stay lit?", "a": "no"},
        {"q": "If one bulb blows in a parallel circuit, do the others stay lit?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "The positive and negative symbols on a dry cell represent its ___?", "a": "terminals"},
        {"q": "Materials that allow electricity to flow through them are called ___?", "options": ["insulators", "resistors", "conductors", "batteries"], "a": 2},
        {"q": "Materials that do not allow electricity to flow through them are called ___?", "a": "insulators"},
        {"q": "Is a metal spoon a conductor or an insulator?", "options": ["conductor", "insulator", "both", "neither"], "a": 0},
        {"q": "Is a plastic ruler a conductor or an insulator?", "a": "insulator"},
        {"q": "Is a copper wire an insulator?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "Is rubber considered an insulator?", "a": "yes"},
        {"q": "Wires are covered with plastic to provide ___?", "options": ["conduction", "insulation", "heat", "light"], "a": 1},
        {"q": "What hazard might you experience if you touch a switch with wet hands?", "a": "shock"},
        {"q": "Is water a conductor of electricity?", "options": ["yes", "no", "sometimes", "rarely"], "a": 0},
        {"q": "A safety device that breaks the circuit when current is too high is a ___?", "a": "fuse"},
        {"q": "Which component is represented by a long and short line in a diagram?", "options": ["bulb", "switch", "cell", "wire"], "a": 2},
        {"q": "The continuous flow of electricity is also known as electrical ___?", "a": "current"},
        {"q": "Do identical bulbs in a parallel circuit share the same brightness?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "Can a dry cell store energy forever?", "a": "no"},
        {"q": "What form of energy is stored inside a dry cell?", "options": ["chemical", "electrical", "kinetic", "heat"], "a": 0},
        {"q": "Using many appliances on one socket can cause an electrical ___?", "a": "overload"},
        {"q": "Objects in our homes that use electricity to work are called ___?", "options": ["gadgets", "appliances", "toys", "machines"], "a": 1},
        {"q": "Is a rubber eraser a conductor?", "a": "no"},
        {"q": "Is a metal safety pin a conductor?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "A drawing that uses symbols to show a circuit is a circuit ___?", "a": "diagram"},
        {"q": "If the wires are not connected to the terminals, will the bulb light?", "options": ["yes", "no", "sometimes", "rarely"], "a": 1},
        {"q": "What happens to the brightness of bulbs in parallel if one is removed?", "a": "unchanged"},
        {"q": "Does adding a second cell to a single-bulb circuit make it brighter?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "Is a glass rod a conductor?", "a": "no"},
        {"q": "Does a bulb light up if it is physically 'blown'?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "The thin wire inside a bulb that glows is called the ___?", "a": "filament"},
        {"q": "When electricity flows through a bulb, it produces light and ___?", "options": ["sound", "heat", "kinetic", "chemical"], "a": 1},
        {"q": "Should we put metal objects into an electrical socket?", "a": "no"},
        {"q": "Should we repair electrical items while they are still plugged in?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "A heavy-duty car battery is also known as an ___?", "a": "accumulator"},
        {"q": "Electricity from a wall socket originally comes from a power ___?", "options": ["station", "bank", "house", "cell"], "a": 0},
        {"q": "To save electricity, we should use energy-efficient ___?", "a": "appliances"}
    ],
        
"heat_and_temperature": [
        {"q": "A form of energy that flows from hot to cold is ___?", "options": ["light", "sound", "heat", "electricity"], "a": 2},
        {"q": "The degree of hotness or coldness of an object is its ___?", "a": "temperature"},
        {"q": "The standard metric unit for temperature is degrees ___?", "options": ["Fahrenheit", "Kelvin", "Celsius", "Joule"], "a": 2},
        {"q": "A tool used to directly measure temperature is a ___?", "a": "thermometer"},
        {"q": "What happens to the temperature of water when it is heated?", "options": ["decreases", "increases", "stays same", "drops"], "a": 1},
        {"q": "What happens to the temperature of water when it is cooled?", "a": "decreases"},
        {"q": "At what degree Celsius does water boil?", "options": ["0", "50", "100", "212"], "a": 2},
        {"q": "At what degree Celsius does ice melt?", "a": "0"},
        {"q": "When an object gains heat, its physical size will ___?", "options": ["shrink", "expand", "disappear", "melt"], "a": 1},
        {"q": "When an object loses heat, its physical size will ___?", "a": "contract"},
        {"q": "Gaps are left between railway tracks to allow for thermal ___?", "options": ["expansion", "contraction", "vibration", "cooling"], "a": 0},
        {"q": "Electric wires are hung loosely to prevent snapping during thermal ___?", "a": "contraction"},
        {"q": "What happens to the liquid level in a thermometer when it gets hot?", "options": ["drops", "stays same", "rises", "disappears"], "a": 2},
        {"q": "What happens to the liquid level in a thermometer when it gets cold?", "a": "drops"},
        {"q": "The silvery liquid used in a traditional thermometer is ___?", "options": ["silver", "mercury", "lead", "water"], "a": 1},
        {"q": "A balloon expands in hot water because the air inside experiences ___?", "a": "expansion"},
        {"q": "A metal ball cannot pass through a ring after heating because it ___?", "options": ["contracted", "expanded", "melted", "froze"], "a": 1},
        {"q": "To open a tight metal bottle cap, we should soak it in hot ___?", "a": "water"},
        {"q": "The main source of heat for the Earth is the ___?", "options": ["core", "Sun", "moon", "volcano"], "a": 1},
        {"q": "When we rub our palms, they feel warm because of ___?", "a": "friction"},
        {"q": "Does a large bucket of water hold more heat than a cup at the same temperature?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "Are 'Heat' and 'Temperature' exactly the same scientific concept?", "a": "no"},
        {"q": "Water changes into steam at what temperature in Celsius?", "options": ["0", "50", "100", "200"], "a": 2},
        {"q": "Materials that allow heat to flow through them easily are called ___?", "a": "conductors"},
        {"q": "Materials that do not allow heat to flow through them easily are called ___?", "options": ["conductors", "metals", "insulators", "radiators"], "a": 2},
        {"q": "Is aluminum considered a good heat conductor?", "a": "yes"},
        {"q": "Is wood considered a good heat insulator?", "options": ["yes", "no", "sometimes", "rarely"], "a": 0},
        {"q": "Cooking pot handles are usually made of plastic to provide ___?", "a": "insulation"},
        {"q": "What happens to the mass of a metal bar after it expands?", "options": ["increases", "decreases", "unchanged", "doubles"], "a": 2},
        {"q": "Thermal expansion refers to an increase in physical ___?", "a": "size"},
        {"q": "Thermal contraction refers to a decrease in physical ___?", "options": ["mass", "weight", "size", "energy"], "a": 2},
        {"q": "The normal temperature of a healthy human body is around 37 degrees ___?", "a": "Celsius"},
        {"q": "Can heat travel through a total vacuum?", "options": ["yes", "no", "sometimes", "never"], "a": 0},
        {"q": "Heat always travels from a higher temperature to a ___ temperature?", "a": "lower"},
        {"q": "A thermometer should be read at eye level with the ___?", "options": ["bulb", "meniscus", "stem", "bottom"], "a": 1},
        {"q": "When water vapor loses heat and turns into liquid, it ___?", "a": "condenses"},
        {"q": "When liquid water loses a lot of heat and turns solid, it ___?", "options": ["melts", "boils", "condenses", "freezes"], "a": 3},
        {"q": "A clinical thermometer is specifically used to measure body ___?", "a": "temperature"},
        {"q": "What fabric item protects us from the cold by trapping body heat?", "options": ["blanket", "t-shirt", "shorts", "silk"], "a": 0},
        {"q": "Must ice gain or lose heat in order to melt?", "a": "gain"},
        {"q": "Concrete bridges have expansion joints to prevent severe ___?", "options": ["melting", "cracking", "cooling", "shrinking"], "a": 1},
        {"q": "If we put an inflated balloon in the freezer, its size will ___?", "a": "shrink"},
        {"q": "The process of a solid completely changing into a liquid is called ___?", "options": ["freezing", "boiling", "melting", "condensation"], "a": 2},
        {"q": "The process of a liquid slowly changing into a gas is called ___?", "a": "evaporation"},
        {"q": "Is standard air a good conductor of heat?", "options": ["yes", "no", "sometimes", "very good"], "a": 1},
        {"q": "Between 40 degrees and 80 degrees, the hotter one is ___?", "a": "80"},
        {"q": "When hot steam touches a cold surface, it turns back into ___?", "options": ["ice", "water", "air", "frost"], "a": 1},
        {"q": "The transfer of heat through a circulating liquid or gas is called ___?", "a": "convection"},
        {"q": "The transfer of heat through direct contact in a solid is called ___?", "options": ["convection", "conduction", "radiation", "insulation"], "a": 1},
        {"q": "The transfer of heat through empty space via electromagnetic waves is called ___?", "a": "radiation"}
    ],
    "states_of_matter": [
        {"q": "Anything that has mass and occupies space is called ___?", "options": ["energy", "matter", "vacuum", "light"], "a": 1},
        {"q": "The three states of matter are solid, liquid, and ___?", "a": "gas"},
        {"q": "Does a solid have a fixed shape?", "options": ["yes", "no", "sometimes", "rarely"], "a": 0},
        {"q": "Does a solid have a fixed volume?", "a": "yes"},
        {"q": "Does a liquid have a fixed shape?", "options": ["yes", "no", "always", "sometimes"], "a": 1},
        {"q": "Does a liquid have a fixed volume?", "a": "yes"},
        {"q": "Does a gas have a fixed shape?", "options": ["yes", "no", "always", "sometimes"], "a": 1},
        {"q": "Does a gas have a fixed volume?", "a": "no"},
        {"q": "Which state of matter can be compressed easily?", "options": ["solid", "liquid", "gas", "plasma"], "a": 2},
        {"q": "The process of a liquid turning into a solid is ___?", "a": "freezing"},
        {"q": "The process of a solid turning into a liquid is ___?", "options": ["freezing", "melting", "boiling", "condensation"], "a": 1},
        {"q": "The process of a liquid turning into a gas at its boiling point is ___?", "a": "boiling"},
        {"q": "The process of a liquid turning into a gas below its boiling point is ___?", "options": ["boiling", "evaporation", "freezing", "melting"], "a": 1},
        {"q": "The process of a gas turning into a liquid is ___?", "a": "condensation"},
        {"q": "At what degree Celsius does water freeze?", "options": ["-10", "0", "10", "100"], "a": 1},
        {"q": "At what degree Celsius does water boil?", "a": "100"},
        {"q": "Cloud formation is a result of which process?", "options": ["evaporation", "melting", "condensation", "freezing"], "a": 2},
        {"q": "Rain is part of the natural ___ cycle?", "a": "water"},
        {"q": "Small droplets of water on the outside of a cold glass are caused by ___?", "options": ["evaporation", "melting", "condensation", "freezing"], "a": 2},
        {"q": "Drying clothes under the sun involves the process of ___?", "a": "evaporation"},
        {"q": "Is a stone a solid, liquid, or gas?", "options": ["solid", "liquid", "gas", "plasma"], "a": 0},
        {"q": "Is oxygen a solid, liquid, or gas?", "a": "gas"},
        {"q": "Is cooking oil a solid, liquid, or gas?", "options": ["solid", "liquid", "gas", "plasma"], "a": 1},
        {"q": "When ice melts, its particle arrangement becomes less ___?", "a": "orderly"},
        {"q": "In which state are particles packed very closely together?", "options": ["gas", "liquid", "solid", "plasma"], "a": 2},
        {"q": "In which state can particles move freely and far apart?", "a": "gas"},
        {"q": "The constant movement of water between Earth and sky is the water ___?", "options": ["wheel", "cycle", "fall", "slide"], "a": 1},
        {"q": "What provides energy for the water cycle?", "a": "Sun"},
        {"q": "Does air have mass?", "options": ["yes", "no", "sometimes", "rarely"], "a": 0},
        {"q": "Does air occupy space?", "a": "yes"},
        {"q": "Ice is the ___ state of water?", "options": ["liquid", "gas", "solid", "plasma"], "a": 2},
        {"q": "Steam is the ___ state of water?", "a": "gas"},
        {"q": "When water evaporates, it turns into water ___?", "options": ["vapor", "ice", "snow", "frost"], "a": 0},
        {"q": "The process that happens when we see morning dew on leaves is ___?", "a": "condensation"},
        {"q": "A liquid takes the shape of its container because it has no fixed ___?", "options": ["volume", "shape", "mass", "density"], "a": 1},
        {"q": "Can a solid flow like a liquid?", "a": "no"},
        {"q": "What happens to the volume of gas if it is put in a larger container?", "options": ["decreases", "increases", "stays same", "disappears"], "a": 1},
        {"q": "Is smoke an example of a gas?", "a": "yes"},
        {"q": "Is honey a liquid?", "options": ["yes", "no", "solid", "gas"], "a": 0},
        {"q": "Particles in a liquid can ___ over each other.", "a": "slide"},
        {"q": "To change a liquid to a gas, must it gain or lose heat?", "options": ["gain", "lose", "maintain", "share"], "a": 0},
        {"q": "To change a liquid to a solid, must it gain or lose heat?", "a": "lose"},
        {"q": "Is a sponge a solid?", "options": ["yes", "no", "liquid", "gas"], "a": 0},
        {"q": "The bubbles in boiling water are filled with water ___?", "a": "vapor"},
        {"q": "Does evaporation only happen at 100°C?", "options": ["yes", "no", "always", "sometimes"], "a": 1},
        {"q": "A state of matter that has no fixed shape and no fixed volume is ___?", "a": "gas"},
        {"q": "What is the result of water vapor losing heat high in the sky?", "options": ["clouds", "sun", "stars", "wind"], "a": 0},
        {"q": "Can we see water vapor?", "a": "no"},
        {"q": "Is fine sand a solid or liquid?", "options": ["solid", "liquid", "gas", "plasma"], "a": 0},
        {"q": "Water is the only substance found naturally in all three ___?", "a": "states"}
    ],
    "food_chains": [
        {"q": "An organism that makes its own food using sunlight is a ___?", "options": ["consumer", "producer", "decomposer", "predator"], "a": 1},
        {"q": "Animals that eat plants or other animals are called ___?", "a": "consumers"},
        {"q": "A diagram showing 'who eats whom' is a food ___?", "options": ["web", "chain", "pyramid", "cycle"], "a": 1},
        {"q": "The main source of energy for all food chains is the ___?", "a": "Sun"},
        {"q": "An animal that hunts and eats other animals is a ___?", "options": ["prey", "producer", "predator", "scavenger"], "a": 2},
        {"q": "An animal that is hunted and eaten by another animal is ___?", "a": "prey"},
        {"q": "In a food chain, the arrows represent the flow of ___?", "options": ["water", "energy", "air", "heat"], "a": 1},
        {"q": "Plants are producers because they perform ___?", "a": "photosynthesis"},
        {"q": "An animal that eats only producers (plants) is a ___?", "options": ["carnivore", "omnivore", "herbivore", "decomposer"], "a": 2},
        {"q": "An animal that eats only other consumers (meat) is a ___?", "a": "carnivore"},
        {"q": "An animal that eats both plants and animals is an ___?", "options": ["herbivore", "carnivore", "omnivore", "producer"], "a": 2},
        {"q": "Several food chains linked together form a food ___?", "a": "web"},
        {"q": "A consumer that eats only plants is a ___ consumer.", "options": ["primary", "secondary", "tertiary", "apex"], "a": 0},
        {"q": "An animal that eats a primary consumer is a ___ consumer.", "a": "secondary"},
        {"q": "An animal at the top of a food chain is an ___ predator.", "options": ["alpha", "apex", "omega", "ultimate"], "a": 1},
        {"q": "What happens to the number of prey if predators increase?", "a": "decreases"},
        {"q": "What happens to the number of predators if prey disappears?", "options": ["increases", "decreases", "stays same", "doubles"], "a": 1},
        {"q": "Organisms that break down dead plants and animals are ___?", "a": "decomposers"},
        {"q": "An example of a producer in a pond is ___?", "options": ["frog", "fish", "algae", "snake"], "a": 2},
        {"q": "An example of a producer on land is ___?", "a": "grass"},
        {"q": "A hawk eating a snake is an example of a ___?", "options": ["prey", "producer", "predator", "herbivore"], "a": 2},
        {"q": "In the chain Grass -> Grasshopper -> Bird, what type of consumer is the bird?", "a": "secondary"},
        {"q": "In the chain Leaf -> Caterpillar -> Bird, the leaf is a ___?", "options": ["consumer", "producer", "decomposer", "prey"], "a": 1},
        {"q": "Can a food chain start with an animal?", "a": "no"},
        {"q": "Energy ___ as it moves up the food chain.", "options": ["increases", "decreases", "stays same", "fluctuates"], "a": 1},
        {"q": "A habitat with many linked food chains is very ___?", "a": "stable"},
        {"q": "If all plants in a habitat die, the animals will eventually ___?", "options": ["migrate", "evolve", "die", "adapt"], "a": 2},
        {"q": "Is a mushroom a producer?", "a": "no"},
        {"q": "Is a tiger a primary consumer?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "A cow eating grass is a ___ consumer.", "a": "primary"},
        {"q": "Does a food web show more realistic eating habits than a chain?", "options": ["yes", "no", "sometimes", "rarely"], "a": 0},
        {"q": "Which organism has the most energy in a food chain?", "a": "producer"},
        {"q": "In a food chain, the least energy is held by the apex ___?", "options": ["producer", "prey", "predator", "decomposer"], "a": 2},
        {"q": "An eagle is a predator, its prey could be a ___?", "a": "snake"},
        {"q": "Small animals in the sea that eat algae are primary ___?", "options": ["producers", "consumers", "decomposers", "predators"], "a": 1},
        {"q": "Can an animal be both a predator and a prey?", "a": "yes"},
        {"q": "Humans are usually classified as ___ in a food web.", "options": ["herbivores", "carnivores", "omnivores", "producers"], "a": 2},
        {"q": "If frogs are removed, what happens to the insect population?", "a": "increases"},
        {"q": "Paddy plant -> Rat -> Snake. Who is the secondary consumer?", "options": ["paddy plant", "rat", "snake", "none"], "a": 2},
        {"q": "Is a cat a predator to a mouse?", "a": "yes"},
        {"q": "Plankton -> Small fish -> Big fish. Who is the producer?", "options": ["plankton", "small fish", "big fish", "sun"], "a": 0},
        {"q": "Most food chains have no more than ___ steps.", "a": "five"},
        {"q": "Energy is lost in the form of ___ at each level.", "options": ["light", "sound", "heat", "kinetic"], "a": 2},
        {"q": "A scavenger eats ___ animals.", "a": "dead"},
        {"q": "Is a vulture a scavenger?", "options": ["yes", "no", "sometimes", "rarely"], "a": 0},
        {"q": "Is a spider a predator?", "a": "yes"},
        {"q": "A caterpillar is a ___ to a bird.", "options": ["predator", "producer", "prey", "decomposer"], "a": 2},
        {"q": "Fungi and bacteria are examples of ___?", "a": "decomposers"},
        {"q": "Does a food chain work without sunlight?", "options": ["yes", "no", "sometimes", "always"], "a": 1},
        {"q": "The position of an organism in a food chain is its ___ level.", "a": "trophic"}
    ],

"materials_properties": [
        {"q": "Materials like wood and cotton come from ___?", "a": "plants"},
        {"q": "Materials like silk and wool come from ___?", "a": "animals"},
        {"q": "Materials like metal and glass come from ___?", "a": "rocks"},
        {"q": "Materials like plastic and synthetic cloth come from ___?", "a": "petroleum"},
        {"q": "A material that can be stretched and returns to its original shape is ___?", "a": "elastic"},
        {"q": "Is a rubber band elastic or non-elastic?", "a": "elastic"},
        {"q": "Materials that allow water to pass through or be soaked up are ___?", "a": "absorbent"},
        {"q": "Materials that do not soak up water are called ___?", "a": "waterproof"},
        {"q": "Is a raincoat made of absorbent or waterproof material?", "a": "waterproof"},
        {"q": "A material that allows light to pass through clearly is ___?", "a": "transparent"},
        {"q": "Is a metal spoon transparent?", "a": "no"},
        {"q": "Materials that allow electricity to flow through are electrical ___?", "a": "conductors"},
        {"q": "Most objects made of ___ are good electrical conductors.", "a": "metal"},
        {"q": "Materials that do not allow heat to flow through easily are ___?", "a": "insulators"},
        {"q": "Why is a cooking pot made of metal? Because it is a heat ___.", "a": "conductor"},
        {"q": "Why is a towel made of cotton? Because it ___ water.", "a": "absorbs"},
        {"q": "An object that stays on the surface of water is said to ___?", "a": "float"},
        {"q": "An object that goes to the bottom of water is said to ___?", "a": "sink"},
        {"q": "Is a heavy coin likely to float or sink?", "a": "sink"},
        {"q": "Is a dry leaf likely to float or sink?", "a": "float"},
        {"q": "Leather comes from the skin of ___?", "a": "animals"},
        {"q": "What is the basic source material of a plastic bottle?", "a": "petroleum"},
        {"q": "Is glass considered a natural or artificial material?", "a": "artificial"},
        {"q": "The ability of a material to support a heavy load without breaking is its ___?", "a": "strength"},
        {"q": "Is a paper bag stronger than a plastic bag when wet?", "a": "no"},
        {"q": "Objects made of iron will ___ when exposed to water and air.", "a": "rust"},
        {"q": "To prevent rusting, we can ___ the metal surface.", "a": "paint"},
        {"q": "Is gold a metal that rusts easily?", "a": "no"},
        {"q": "A magnet can easily attract objects made of ___?", "a": "iron"},
        {"q": "Is aluminum attracted to a magnet?", "a": "no"},
        {"q": "Which material is primarily used to make car tires?", "a": "rubber"},
        {"q": "Ceramics are generally made from baked ___?", "a": "clay"},
        {"q": "Is a glazed ceramic vase waterproof?", "a": "yes"},
        {"q": "Is a kitchen sponge an absorbent material?", "a": "yes"},
        {"q": "Are most plastics good heat insulators?", "a": "yes"},
        {"q": "Electrical wires are covered in plastic because it is an ___?", "a": "insulator"},
        {"q": "Which material is best for making the surface of a mirror?", "a": "glass"},
        {"q": "Is cotton considered a natural fiber?", "a": "yes"},
        {"q": "Is nylon considered a synthetic fiber?", "a": "yes"},
        {"q": "Synthetic materials are mostly made from ___?", "a": "petroleum"},
        {"q": "A window pane is made of glass because it is ___?", "a": "transparent"},
        {"q": "Is a wooden bridge a good electrical conductor?", "a": "no"},
        {"q": "Wool is used to make sweaters because it traps ___?", "a": "heat"},
        {"q": "Which is more elastic: a steel wire or ___?", "a": "rubber"},
        {"q": "An umbrella must be made of ___ material.", "a": "waterproof"},
        {"q": "Do all metals sink in water?", "a": "no"},
        {"q": "Copper is used in wires because it is a good ___?", "a": "conductor"},
        {"q": "Can a material be both waterproof and transparent?", "a": "yes"},
        {"q": "Is paper made from animals?", "a": "no"},
        {"q": "What stretchy material is best for a swimming cap?", "a": "latex"}
    ],
    "solar_system": [
        {"q": "The center of the solar system is the ___?", "a": "Sun"},
        {"q": "How many planets are there in our solar system?", "a": "eight"},
        {"q": "The closest planet to the Sun is ___?", "a": "Mercury"},
        {"q": "The largest planet in the solar system is ___?", "a": "Jupiter"},
        {"q": "The 'Red Planet' is known as ___?", "a": "Mars"},
        {"q": "The planet famous for its beautiful rings is ___?", "a": "Saturn"},
        {"q": "The coldest and furthest planet from the Sun is ___?", "a": "Neptune"},
        {"q": "The third planet from the Sun is ___?", "a": "Earth"},
        {"q": "The hottest planet in the solar system is ___?", "a": "Venus"},
        {"q": "Small rocky objects that orbit the Sun, mostly between Mars and Jupiter?", "a": "asteroids"},
        {"q": "A 'dirty snowball' made of ice and dust that orbits the Sun is a ___?", "a": "comet"},
        {"q": "Natural satellites that orbit planets are called ___?", "a": "moons"},
        {"q": "A path followed by a planet around the Sun is an ___?", "a": "orbit"},
        {"q": "The spinning of the Earth on its axis is called ___?", "a": "rotation"},
        {"q": "The movement of the Earth around the Sun is called ___?", "a": "revolution"},
        {"q": "How many hours does it take for Earth to complete one rotation?", "a": "24"},
        {"q": "How many days does it take for Earth to complete one revolution roughly?", "a": "365"},
        {"q": "The Earth rotates from west to ___.", "a": "east"},
        {"q": "The Sun appears to rise in the ___?", "a": "east"},
        {"q": "The Sun appears to set in the ___?", "a": "west"},
        {"q": "The rotation of the Earth causes day and ___?", "a": "night"},
        {"q": "The imaginary line through the center of the Earth is the ___?", "a": "axis"},
        {"q": "Does the Sun move around the Earth?", "a": "no"},
        {"q": "The moon reflects light from the ___?", "a": "Sun"},
        {"q": "How many days does it take for the Moon to orbit the Earth roughly?", "a": "27"},
        {"q": "The different shapes of the Moon seen from Earth are called ___?", "a": "phases"},
        {"q": "The phase when the Moon is not visible at all is the ___ moon.", "a": "new"},
        {"q": "The phase when the Moon looks like a complete circle is the ___ moon.", "a": "full"},
        {"q": "Which planet is known as Earth's twin?", "a": "Venus"},
        {"q": "Is Pluto still classified as a major planet?", "a": "no"},
        {"q": "What is Pluto classified as now? A ___ planet.", "a": "dwarf"},
        {"q": "Gravity on the Moon is ___ than on Earth.", "a": "weaker"},
        {"q": "Does the Moon have its own light?", "a": "no"},
        {"q": "The force that keeps planets in their orbits is ___?", "a": "gravity"},
        {"q": "Which planet rotates on its side?", "a": "Uranus"},
        {"q": "The belt between Mars and Jupiter is the ___ belt.", "a": "asteroid"},
        {"q": "A meteor that hits the Earth's surface is a ___?", "a": "meteorite"},
        {"q": "A 'shooting star' is actually a ___?", "a": "meteor"},
        {"q": "Which planet has the most visible rings?", "a": "Saturn"},
        {"q": "Is the Sun a planet or a star?", "a": "star"},
        {"q": "The shape of a planet's orbit is an ___?", "a": "ellipse"},
        {"q": "Does Venus have any moons?", "a": "no"},
        {"q": "Does Mercury have an atmosphere?", "a": "no"},
        {"q": "Which planet is known for the Great Red Spot?", "a": "Jupiter"},
        {"q": "The only planet currently known to support life is ___?", "a": "Earth"},
        {"q": "Why is Mars red? Because of iron ___ in the soil.", "a": "oxide"},
        {"q": "A collection of billions of stars and solar systems is a ___?", "a": "galaxy"},
        {"q": "What is the name of our galaxy? The Milky ___.", "a": "Way"},
        {"q": "Is the Earth's axis straight or tilted?", "a": "tilted"},
        {"q": "Tides on Earth are caused by the pull of the ___?", "a": "Moon"}
    ],
    "machines_simple": [
        {"q": "A tool that makes work easier and faster is a ___?", "a": "machine"},
        {"q": "A simple machine with a slanted surface to move loads up is a ___?", "a": "ramp"},
        {"q": "A simple machine with a grooved wheel and a rope is a ___?", "a": "pulley"},
        {"q": "A simple machine consisting of a rigid bar that turns on a fixed point is a ___?", "a": "lever"},
        {"q": "The fixed point on which a lever turns is called the ___?", "a": "fulcrum"},
        {"q": "The force applied to a lever to move a load is called the ___?", "a": "effort"},
        {"q": "The object being moved by a lever is called the ___?", "a": "load"},
        {"q": "A simple machine made of a wheel attached to a central shaft is a wheel and ___?", "a": "axle"},
        {"q": "A simple machine that is thick at one end and tapers to a thin edge is a ___?", "a": "wedge"},
        {"q": "An inclined plane wrapped around a cylinder or cone is a ___?", "a": "screw"},
        {"q": "A wheel with teeth around its rim is a ___?", "a": "gear"},
        {"q": "A pair of scissors is an example of which simple machine?", "a": "lever"},
        {"q": "A staircase is an example of an inclined ___?", "a": "plane"},
        {"q": "An axe is an example of which simple machine?", "a": "wedge"},
        {"q": "A flagpole uses which simple machine to raise the flag?", "a": "pulley"},
        {"q": "A doorknob is an example of a wheel and ___?", "a": "axle"},
        {"q": "A bottle cap is an example of which simple machine?", "a": "screw"},
        {"q": "What type of simple machine is a playground slide? An inclined ___.", "a": "plane"},
        {"q": "Which simple machine is used to cut or split objects?", "a": "wedge"},
        {"q": "Which simple machine is used to hold objects firmly together?", "a": "screw"},
        {"q": "A see-saw is an example of a first-class ___?", "a": "lever"},
        {"q": "A wheelbarrow is an example of a second-class ___?", "a": "lever"},
        {"q": "A fishing rod is an example of a third-class ___?", "a": "lever"},
        {"q": "Two gears working together can change the ___ of motion.", "a": "direction"},
        {"q": "A combination of two or more simple machines is a ___ machine.", "a": "complex"},
        {"q": "Is a bicycle an example of a complex machine?", "a": "yes"},
        {"q": "Simple machines help us by reducing the ___ needed to do work.", "a": "effort"},
        {"q": "Is a knife essentially a wedge?", "a": "yes"},
        {"q": "Is a ramp an inclined plane?", "a": "yes"},
        {"q": "A crane uses a system of ___ to lift heavy loads.", "a": "pulleys"},
        {"q": "In a wheel and axle, the larger circular part is the ___?", "a": "wheel"},
        {"q": "The rod that goes through the center of a wheel is the ___?", "a": "axle"},
        {"q": "Which machine uses a spiral thread?", "a": "screw"},
        {"q": "When two gears mesh, they turn in ___ directions.", "a": "opposite"},
        {"q": "A nutcracker is an example of a ___?", "a": "lever"},
        {"q": "The longer the inclined plane, the ___ effort is needed.", "a": "less"},
        {"q": "Is a mechanical pencil sharpener a complex machine?", "a": "yes"},
        {"q": "A machine built to last without harming the environment is ___?", "a": "sustainable"},
        {"q": "Maintenance like ___ prevents metal machines from rusting.", "a": "oiling"},
        {"q": "A sweeping broom is a type of ___?", "a": "lever"},
        {"q": "Tweezers are a type of ___?", "a": "lever"},
        {"q": "The part of a screw that winds around its body is the ___?", "a": "thread"},
        {"q": "Can a pulley change the direction of an applied force?", "a": "yes"},
        {"q": "Is a hammer used to pull nails a simple machine?", "a": "yes"},
        {"q": "Is a manual hand drill considered a complex machine?", "a": "yes"},
        {"q": "The specific place where the effort is applied is the effort ___?", "a": "point"},
        {"q": "Does a simple machine create new energy?", "a": "no"},
        {"q": "Which is easier: lifting a heavy load straight up or using a ___?", "a": "ramp"},
        {"q": "A ladder leaning against a wall is an example of an inclined ___?", "a": "plane"},
        {"q": "Keeping machines clean helps them to last ___?", "a": "longer"}
    ],

    "food_preservation": [
        {"q": "The process of treating food to stop it from spoiling is ___?", "a": "preservation"},
        {"q": "Heating liquid to a high temperature to kill germs is ___?", "a": "boiling"},
        {"q": "Preserving food by removing all its water is ___?", "a": "drying"},
        {"q": "Using salt to preserve food like fish is ___?", "a": "salting"},
        {"q": "Preserving food in a vinegar or sugar solution is ___?", "a": "pickling"},
        {"q": "The process of heating liquid then cooling it quickly is ___?", "a": "pasteurization"},
        {"q": "Storing food in airtight metallic containers is ___?", "a": "canning"},
        {"q": "Storing food in air-tight plastic bags with no air is ___ packing?", "a": "vacuum"},
        {"q": "Keeping food at very low temperatures (below 0°C) is ___?", "a": "freezing"},
        {"q": "Keeping food in the refrigerator (above 0°C) is ___?", "a": "cooling"},
        {"q": "Coating food with melted wax to prevent air contact is ___?", "a": "waxing"},
        {"q": "Exposing food to wood smoke for preservation is ___?", "a": "smoking"},
        {"q": "Salt and sugar act as natural ___ in food preservation.", "a": "preservatives"},
        {"q": "Which method is best for preserving fresh milk?", "a": "pasteurization"},
        {"q": "Which method is commonly used to make salted fish?", "a": "salting"},
        {"q": "Drying food can be done using the oven or ___?", "a": "sunlight"},
        {"q": "What is the main biological cause of food spoilage?", "a": "microorganisms"},
        {"q": "Spoiled food often changes in color, smell, and ___?", "a": "taste"},
        {"q": "Why does vacuum packing prevent spoilage? It removes the ___.", "a": "air"},
        {"q": "Canned food can last for a long ___?", "a": "time"},
        {"q": "Pasteurization is named after scientist Louis ___?", "a": "Pasteur"},
        {"q": "Honey is a natural preservative because it lacks ___?", "a": "water"},
        {"q": "Does freezing kill microorganisms or just stop them?", "a": "stop"},
        {"q": "Which ingredient is heavily boiled with fruit to make jams?", "a": "sugar"},
        {"q": "The acid in vinegar helps to prevent the growth of ___.", "a": "bacteria"},
        {"q": "Is canned food completely safe to eat if the can is heavily dented?", "a": "no"},
        {"q": "Preserved food is much easier to ___ to other places.", "a": "transport"},
        {"q": "Food preservation helps to avoid food ___?", "a": "wastage"},
        {"q": "Which method is commonly used for chili or dried shrimp?", "a": "drying"},
        {"q": "Waxing is usually done on which type of food?", "a": "fruits"},
        {"q": "High acidity in pickling prevents the growth of ___?", "a": "microorganisms"},
        {"q": "What happens to the taste of food after pickling in vinegar? It becomes ___.", "a": "sour"},
        {"q": "Smoking food removes water and adds ___?", "a": "flavor"},
        {"q": "Should we check the expiry ___ before buying food?", "a": "date"},
        {"q": "Does boiling water kill most living microorganisms?", "a": "yes"},
        {"q": "Which preservation method places food in a sealed tin?", "a": "canning"},
        {"q": "Salt is used to preserve eggs because it draws out ___?", "a": "water"},
        {"q": "Keeping food in a cool place slows down its ___?", "a": "spoilage"},
        {"q": "What is used to coat some apples to keep them shiny and fresh?", "a": "wax"},
        {"q": "Preserved food can be eaten out of its natural ___?", "a": "season"},
        {"q": "Is pickling considered a modern or traditional method?", "a": "traditional"},
        {"q": "Does drying fundamentally change the texture of food?", "a": "yes"},
        {"q": "Pasteurization is mainly used for milk and fruit ___?", "a": "juice"},
        {"q": "Can vacuum packing be used effectively for nuts?", "a": "yes"},
        {"q": "Microorganisms cannot grow well without sufficient ___?", "a": "moisture"},
        {"q": "A bulging can is a strong sign that the food inside is ___?", "a": "spoiled"},
        {"q": "Is standard refrigeration a permanent preservation method?", "a": "no"},
        {"q": "Ultra-High Temperature (UHT) is a form of ___?", "a": "pasteurization"},
        {"q": "Why do we preserve food for emergencies? To increase its shelf ___.", "a": "life"},
        {"q": "The main goal of preservation is to create an ___ environment for germs.", "a": "unsuitable"}
    ],
    "preservation_conservation": [
        {"q": "Protecting the environment and living things from being destroyed is ___?", "a": "preservation"},
        {"q": "Using natural resources wisely to avoid wastage is ___?", "a": "conservation"},
        {"q": "Animals that no longer exist on Earth are ___?", "a": "extinct"},
        {"q": "An example of a famous extinct giant reptile is a ___?", "a": "dinosaur"},
        {"q": "An example of an extinct flightless bird from Mauritius is the ___?", "a": "dodo"},
        {"q": "Animals or plants facing the severe threat of extinction are ___?", "a": "endangered"},
        {"q": "An example of an endangered ape in Malaysia is the ___?", "a": "orangutan"},
        {"q": "Is the Malayan Tiger currently an endangered species?", "a": "yes"},
        {"q": "The main cause of animal extinction today is human ___?", "a": "activities"},
        {"q": "Illegal hunting and capturing of wild animals is called ___?", "a": "poaching"},
        {"q": "Cutting down forests on a massive scale is called ___?", "a": "deforestation"},
        {"q": "The place where an animal or plant naturally lives is its ___?", "a": "habitat"},
        {"q": "Reforestation means ___ trees in a depleted forest.", "a": "replanting"},
        {"q": "Setting up a National Park is a strict effort for nature ___?", "a": "preservation"},
        {"q": "Reducing, reusing, and recycling are essential parts of resource ___?", "a": "conservation"},
        {"q": "Is the giant Rafflesia flower considered endangered?", "a": "yes"},
        {"q": "Is the leatherback sea turtle endangered?", "a": "yes"},
        {"q": "Poachers illegally hunt elephants to take their ___?", "a": "tusks"},
        {"q": "Poachers illegally hunt tigers primarily for their ___?", "a": "skin"},
        {"q": "Poachers illegally hunt rhinoceros primarily for their ___?", "a": "horns"},
        {"q": "What happens to animals when their habitat is completely destroyed? They ___.", "a": "die"},
        {"q": "Severe water pollution can kill ___ life.", "a": "aquatic"},
        {"q": "Is the Woolly Mammoth an extinct animal?", "a": "yes"},
        {"q": "Creating a forest reserve is a crucial way to protect ___?", "a": "biodiversity"},
        {"q": "The set of rules that protects wildlife in Malaysia is a ___.", "a": "law"},
        {"q": "Education helps people understand the ___ of protecting nature.", "a": "importance"},
        {"q": "Is the Giant Panda still considered an endangered species?", "a": "yes"},
        {"q": "An area protected specifically to save turtles is a turtle ___?", "a": "sanctuary"},
        {"q": "Massive oil spills in the ocean cause severe water ___?", "a": "pollution"},
        {"q": "Global warming is worsened by too much carbon ___ gas.", "a": "dioxide"},
        {"q": "Can biological extinction ever be naturally reversed?", "a": "no"},
        {"q": "Sustainable logging practices help to maintain healthy ___?", "a": "forests"},
        {"q": "The gradual removal of the top layer of soil is soil ___?", "a": "erosion"},
        {"q": "Mangrove forests protect the coastline from harsh ___?", "a": "erosion"},
        {"q": "Recycling paper helps to save living ___?", "a": "trees"},
        {"q": "What is the current conservation status of the Javan Rhino?", "a": "endangered"},
        {"q": "Is hunting for sport allowed in strictly protected areas?", "a": "no"},
        {"q": "A place where animals are bred to increase their population is a breeding ___?", "a": "center"},
        {"q": "Is the Quagga (a zebra subspecies) an extinct animal?", "a": "yes"},
        {"q": "Using solar energy is an excellent way of ___ energy.", "a": "conserving"},
        {"q": "Is heavy air pollution a direct threat to living things?", "a": "yes"},
        {"q": "Should we buy luxury products made from endangered animals?", "a": "no"},
        {"q": "The delicate balance of nature and living things is the ___?", "a": "ecosystem"},
        {"q": "Which global organization works to protect nature? (Abbreviation)", "a": "WWF"},
        {"q": "Is the Dugong (sea cow) an endangered marine animal?", "a": "yes"},
        {"q": "Planting trees in urban areas is known as urban ___?", "a": "forestry"},
        {"q": "Actively saving water at home is an act of ___?", "a": "conservation"},
        {"q": "The main reason for the extinction of the Dodo was ___?", "a": "overhunting"},
        {"q": "Is the Tasmanian Tiger officially classified as extinct?", "a": "yes"},
        {"q": "We must protect nature and wildlife for our ___ generations.", "a": "future"}
    ]
};
