// ==========================================
// DATA SOALAN REKA BENTUK DAN TEKNOLOGI (4 Kategori Pertama)
// ==========================================
const rbtData = {
"keselamatan_bengkel": [
        {"q": "Ruang bilik khas tempat kita melakukan aktiviti dan kerja amali kemahiran dipanggil ___?", "a": "bengkel"},
        {"q": "Baju sekolah perlulah dimasukkan ke dalam seluar supaya penampilan diri kelihatan ___?", "a": "kemas"},
        {"q": "Bagi mengelakkan kemalangan, rambut murid yang panjang perlulah di___ semasa berada di dalam bengkel.", "a": "ikat"},
        {"q": "Untuk melindungi tapak kaki daripada kecederaan, kasut yang dipakai ke bengkel mestilah daripada jenis yang ___?", "a": "bertutup"},
        {"q": "Pakaian sekolah yang bersih dapat dihalang daripada menjadi kotor semasa amali dengan memakai ___?", "a": "apron"},
        {"q": "Setiap kali masuk ke bengkel, tingkap dan pintu perlu dibuka untuk memastikan pengaliran ___ yang baik.", "a": "udara"},
        {"q": "Bukaan tingkap membolehkan cahaya yang cukup masuk supaya persekitaran ruang bengkel menjadi ___?", "a": "terang"},
        {"q": "Kecuaian semasa menggunakan alatan tangan yang tajam boleh menyebabkan kecelakaan, luka, atau ___?", "a": "kecederaan"},
        {"q": "Jika berlaku sebarang kecederaan atau kemalangan di dalam bengkel, laporkan dengan segera kepada ___?", "a": "guru"},
        {"q": "Semua sisa potongan kayu yang tidak digunakan lagi perlu dibuang terus ke dalam tong ___?", "a": "sampah"},
        {"q": "Bagi mengelakkan insiden kebakaran, bahan mudah terbakar perlu sentiasa dijauhkan daripada punca ___?", "a": "api"},
        {"q": "Papan tanda kawasan larangan bermaksud murid sama sekali dilarang untuk ___ ke ruang tersebut.", "a": "masuk"},
        {"q": "Semua alatan tangan yang telah selesai digunakan perlu dibersihkan dan di___ semula di tempat asalnya.", "a": "simpan"},
        {"q": "Sebarang cecair atau minyak yang tumpah di atas lantai perlu segera di___ supaya permukaan lantai tidak licin.", "a": "bersih"},
        {"q": "Perbuatan bermain, bergurau, dan berlari di dalam kawasan bengkel adalah dilarang ___?", "a": "keras"},
        {"q": "Bagi menjimatkan tenaga dan menjaga keselamatan, alatan elektrik mesti dimatikan suisnya selepas selesai di___?", "a": "guna"},
        {"q": "Peti khas yang diletakkan di dinding bengkel dan mengandungi ubat luka dipanggil peti pertolongan ___?", "a": "cemas"},
        {"q": "Alat pemadam api jenis silinder merah di bengkel digunakan untuk mengawal dan memadam kebakaran ___?", "a": "kecil"},
        {"q": "Langkah pertama penggunaan alat pemadam api: Tarik ___ picu keselamatan pada alat pemadam api tersebut.", "a": "pin"},
        {"q": "Langkah kedua penggunaan alat pemadam api: Halakan muncung hos tepat ke arah pangkal ___.", "a": "api"},
        {"q": "Langkah ketiga penggunaan alat pemadam api: Tekan ___ pemicit pemadam perlahan-lahan untuk melepaskan semburan.", "a": "tuil"},
        {"q": "Balutan nipis penjagaan luka boleh didapati dengan mudah di dalam peti rawatan ___?", "a": "cemas"},
        {"q": "Murid-murid jangan lupa untuk matikan suis utama elektrik selepas semua peralatan mesin selesai di___?", "a": "guna"},
        {"q": "Bagi mengelakkan kecederaan tangan, alatan tajam mestilah dipegang menggunakan postur genggaman tangan yang ___?", "a": "betul"},
        {"q": "Setiap alatan yang telah siap diguna perlu dibersihkan terlebih dahulu sebelum di___ dengan rapi ke dalam panel almari.", "a": "simpan"},
        {"q": "Permukaan meja kerja kayu perlu disapu dan di___ daripada sebarang habuk serta sisa selepas tamat kelas amali.", "a": "bersih"},
        {"q": "Untuk mengelakkan bahaya renjatan elektrik, tangan yang basah dilarang keras daripada memegang plug atau ___?", "a": "suis"},
        {"q": "Pemakaian sarung tangan fabrik semasa kerja amali bertujuan untuk bertindak sebagai kain pelindung ___?", "a": "tangan"},
        {"q": "Pemakaian topeng pelitup muka dapat melindungi sistem pernafasan dengan menghalang kita daripada menghidu habuk ___?", "a": "kayu"},
        {"q": "Murid dilarang sama sekali bergurau senda terutamanya ketika sedang memegang dan membawa alatan yang ___?", "a": "tajam"},
        {"q": "Murid-murid diwajibkan untuk sentiasa patuh pada semua undang-undang dan peraturan keselamatan semasa berada di dalam ___?", "a": "bengkel"},
        {"q": "Pintu bilik bengkel mesti sentiasa ditutup rapat dan dikunci setelah kelas tamat dan apabila semua murid telah ___?", "a": "keluar"},
        {"q": "Sisa keratan kayu yang dibiarkan bersepah di lantai boleh membahayakan rakan kawan kita kerana ia boleh menyebabkan mereka ___?", "a": "tersadung"},
        {"q": "Sebelum memulakan kerja, pastikan alatan mesin elektrik berada dalam keadaan yang baik, tidak cacat, atau ___?", "a": "rosak"},
        {"q": "Kabel pendawaian atau kulit wayar elektrik yang terdedah boleh mengundang bahaya kemalangan maut akibat renjatan ___?", "a": "elektrik"},
        {"q": "Sekiranya murid menyedari terdapat kerosakan pada alatan tangan, laporkan perkara tersebut kepada guru kelas dengan ___?", "a": "segera"},
        {"q": "Kain buruk kotor yang telah digunakan untuk mengelap meja perlu di___ menggunakan air bersih sebelum disidai semula.", "a": "basuh"},
        {"q": "Pelitup mata plastik (goggle) wajib dipakai bagi bertindak sebagai cermin pelindung mata daripada kemasukan serpihan habuk dan ___?", "a": "habuk"},
        {"q": "Sisa kotoran seperti serbuk gergaji kayu yang bertaburan di atas lantai perlu disapu sehingga bersih menggunakan alat ___?", "a": "penyapu"},
        {"q": "Bagi murid perempuan yang memakai tudung, hujung tudung wajib di___ ke dalam apron supaya tidak tersangkut pada bahagian mesin.", "a": "selit"},
        {"q": "Bagi murid yang memakai baju sekolah berlengan panjang, bahagian pergelangan lengan tersebut perlulah dilipat supaya menjadi lebih ___?", "a": "pendek"},
        {"q": "Semua alatan dan barang amali dilarang sama sekali dan tidak boleh sesuka hati dibawa  ___ bengkel.", "a": "keluar"},
        {"q": "Pastikan semua kerusi dan bangku telah disusun dengan kemas dengan memasukkannya ke bawah meja kerja sebelum bersedia untuk ___?", "a": "pulang"},
        {"q": "Sebelum meninggalkan ruang bengkel, ketua kelas perlulah membantu mematikan semua suis peralatan elektrik, suis kipas, dan suis ___?", "a": "lampu"},
        {"q": "Murid-murid hanya dibenarkan melangkah masuk ke dalam kelas kemahiran bengkel apabila mendapat arahan dan kebenaran daripada ___?", "a": "guru"},
        {"q": "Jika rakan mengalami luka kecil yang berdarah akibat tercucuk paku halus, bersihkan luka tersebut dan balut dengan segera menggunakan ___?", "a": "plaster"},
        {"q": "Peralatan keselamatan sangat penting dan tidak boleh dijadikan bahan mainan, jadi jangan sengaja memicit dan menekan alat pemadam ___?", "a": "api"},
        {"q": "Papan tanda yang menunjukkan amaran dan peringatan bahaya di dalam ruangan bengkel lazimnya dicat dengan warna garang iaitu warna ___?", "a": "merah"},
        {"q": "Pematuhan kepada etika dan disiplin peraturan bengkel amat penting bagi menjaga dan menjamin tahap ___ semua pihak yang terlibat.", "a": "keselamatan"},
        {"q": "Pengaliran udara yang segar dan bebas habuk dapat menjadikan suasana di dalam bengkel pembelajaran lebih kondusif, aman, dan ___?", "a": "selesa"}
    ],

"pengenalan_reka_bentuk": [
        {"q": "Proses penghasilan idea untuk sesuatu produk atau objek baharu dipanggil reka ___?", "a": "bentuk"},
        {"q": "Fungsi utama sesuatu reka bentuk adalah untuk menyelesaikan masalah kehidupan ___?", "a": "manusia"},
        {"q": "Elemen garisan yang dilukis sebenarnya bermula daripada penyambungan satu titik ke ___?", "a": "titik"},
        {"q": "Pertemuan antara hujung garisan dengan titik permulaannya yang bercantum akan membentuk ___?", "a": "rupa"},
        {"q": "Rupa pada lukisan yang bersifat rata dan tiada isi padu dikenali sebagai ciri dua ___?", "a": "dimensi"},
        {"q": "Bentuk tiga dimensi yang mempunyai fizikal sebenar dan boleh dipegang ialah bentuk ___?", "a": "konkrit"},
        {"q": "Bentuk yang hanya kelihatan wujud di dalam lukisan atau gambar foto dikenali sebagai bentuk ___?", "a": "ilusi"},
        {"q": "Kesan atau sifat permukaan pada sesuatu objek yang boleh dilihat atau dirasa dipanggil ___?", "a": "jalinan"},
        {"q": "Permukaan tayar yang kasar dan boleh dirasai apabila dipegang merupakan contoh jalinan ___?", "a": "sentuh"},
        {"q": "Corak pada kain langsir yang hanya boleh dilihat tetapi rata apabila disentuh dipanggil jalinan ___?", "a": "tampak"},
        {"q": "Kawasan lapang atau jarak kekosongan yang terdapat di antara dua objek dipanggil ___?", "a": "ruang"},
        {"q": "Merah, biru, dan juga hijau tergolong dalam elemen reka bentuk iaitu ___?", "a": "warna"},
        {"q": "Warna seperti merah dan jingga yang memberikan kesan terang dan garang tergolong dalam kategori warna ___?", "a": "panas"},
        {"q": "Warna seperti biru dan hijau yang memberikan kesan tenang dan damai tergolong dalam kategori warna ___?", "a": "sejuk"},
        {"q": "Campuran warna asas merah yang digabungkan dengan warna kuning akan menghasilkan rona warna ___?", "a": "jingga"},
        {"q": "Campuran warna asas biru yang digabungkan dengan warna kuning akan menghasilkan rona warna ___?", "a": "hijau"},
        {"q": "Campuran warna asas biru yang digabungkan dengan warna merah akan menghasilkan rona warna ___?", "a": "ungu"},
        {"q": "Aplikasi reka bentuk dan teknologi dicipta untuk menjadikan aktiviti kehidupan manusia lebih ___?", "a": "mudah"},
        {"q": "Penghasilan produk teknologi moden oleh pereka dapat membantu memajukan sosioekonomi sesebuah ___?", "a": "negara"},
        {"q": "Lakaran garisan yang beralun dan melengkung biasanya memberikan kesan pergerakan yang ___?", "a": "lembut"},
        {"q": "Lakaran garisan putus-putus kebiasaannya digunakan untuk menunjukkan bahagian objek yang ___?", "a": "tersembunyi"},
        {"q": "Rupa geometri mempunyai sudut dan bucu yang stabil seperti rupa bentuk kotak segi ___?", "a": "empat"},
        {"q": "Rupa organik mempunyai sifat bebas dan tidak bersudut seperti rupa bentuk sehelai ___?", "a": "daun"},
        {"q": "Objek yang dilukis besar di hadapan dan kecil di belakang akan mewujudkan kesan ilusi ___?", "a": "ruang"},
        {"q": "Pengulangan susunan rupa yang sama pada sesuatu corak akan membentuk prinsip rekaan yang ___?", "a": "harmoni"},
        {"q": "Untuk mendapatkan ton warna pastel yang lebih terang, ia perlu dicampurkan dengan warna ___?", "a": "putih"},
        {"q": "Untuk mendapatkan ton warna yang lebih gelap, ia perlu dicampurkan dengan sedikit warna ___?", "a": "hitam"},
        {"q": "Rupa bentuk objek sebenar yang difokuskan di dalam sesuatu lukisan dipanggil sebagai rupa ___?", "a": "positif"},
        {"q": "Kawasan latar belakang yang kosong di luar imej utama lukisan dipanggil sebagai rupa ___?", "a": "negatif"},
        {"q": "Penggunaan pengetahuan sains dalam proses inovasi dan penciptaan produk baharu dipanggil ___?", "a": "teknologi"},
        {"q": "Reka bentuk saiz dan bentuk kasut direka bergantung rapat kepada ukuran anatomi ___?", "a": "kaki"},
        {"q": "Ciptaan kenderaan pengangkutan darat seperti kereta sangat membantu dalam memudahkan urusan ___?", "a": "perjalanan"},
        {"q": "Rekaan kanopi atau atap payung dicipta untuk melindungi pemakainya daripada hujan dan cuaca ___?", "a": "panas"},
        {"q": "Garisan lurus yang menegak memberikan gambaran struktur binaan yang nampak kuat, stabil, dan ___?", "a": "teguh"},
        {"q": "Garisan beralun memberikan kesan pergerakan yang mendamaikan seperti rupa alun ___?", "a": "ombak"},
        {"q": "Elemen bentuk tiga dimensi mesti mempunyai tiga ukuran utama iaitu panjang, lebar, dan ___?", "a": "tinggi"},
        {"q": "Reka bentuk meja makan yang mempunyai empat batang kaki amat mementingkan ciri ___?", "a": "kestabilan"},
        {"q": "Kerusi di dalam kelas direka bentuk khas dengan saiz yang sesuai untuk kegunaan murid ___?", "a": "duduk"},
        {"q": "Sifat jalinan pada kulit buah durian yang berduri tajam akan terasa menyakitkan dan sangat ___?", "a": "kasar"},
        {"q": "Permukaan cermin tingkap kaca mempunyai jalinan sentuh yang sangat rata dan ___?", "a": "licin"},
        {"q": "Penghasilan produk baharu atau penambahbaikan pada produk sedia ada dipanggil sebagai ___?", "a": "inovasi"},
        {"q": "Lakaran percambahan idea biasanya dibuat dengan pantas menggunakan pensel di atas sehelai ___?", "a": "kertas"},
        {"q": "Lakaran awal bagi menterjemahkan idea selalunya dilukis secara bebas (freehand) tanpa menggunakan ___?", "a": "pembaris"},
        {"q": "Lakaran idea yang paling baik dan menepati kriteria akan dipilih untuk dijadikan sebagai lakaran ___?", "a": "akhir"},
        {"q": "Gandingan warna seperti hitam dan putih diiktiraf di dalam seni reka sebagai rona warna ___?", "a": "neutral"},
        {"q": "Garisan yang condong atau senget selalunya memberikan gambaran keadaan yang goyah dan tidak ___?", "a": "stabil"},
        {"q": "Elemen nilai estetika amat penting dalam reka bentuk supaya produk yang dihasilkan kelihatan ___?", "a": "cantik"},
        {"q": "Dalam prinsip perspektif, objek ilusi yang berada lebih jauh perlulah dilukis bersaiz lebih ___?", "a": "kecil"},
        {"q": "Dalam prinsip perspektif, objek ilusi yang berada pada kedudukan dekat perlulah dilukis bersaiz ___?", "a": "besar"},
        {"q": "Proses mencari ilham untuk menghasilkan reka bentuk produk yang unik memerlukan daya pemikiran yang ___?", "a": "kreatif"}
    ],

    "reka_bentuk_pembungkusan": [
        {"q": "Bekas atau bahan balutan yang berfungsi untuk memelihara dan melindungi produk di dalamnya dipanggil ___?", "a": "pembungkusan"},
        {"q": "Fungsi keselamatan utama sesuatu pembungkusan adalah untuk melindungi kualiti ___?", "a": "produk"},
        {"q": "Pembungkusan secara vakum menyedut udara keluar bagi mengelakkan makanan agar tidak cepat ___?", "a": "rosak"},
        {"q": "Label pada pembungkusan berfungsi untuk menyampaikan butiran yang penting iaitu ___?", "a": "maklumat"},
        {"q": "Bagi makanan yang ada jangka hayat, maklumat pembungkusan yang paling penting ialah tarikh ___?", "a": "luput"},
        {"q": "Pemilihan warna pembungkusan yang terang bertujuan untuk menarik perhatian pelanggan atau ___?", "a": "pembeli"},
        {"q": "Bekas pembungkusan yang menggunakan material kaca memerlukan penjagaan rapi kerana ia mudah ___?", "a": "pecah"},
        {"q": "Kelemahan pembungkusan kertas yang nipis adalah ia tidak kalis air dan sangat mudah ___?", "a": "koyak"},
        {"q": "Bahan pembungkusan mesra alam (biodegradasi) sangat baik kerana sisanya mudah reput dan boleh di___ semula.", "a": "kitar"},
        {"q": "Pensijilan logo Halal JAKIM pada pembungkusan adalah sangat penting bagi pengguna beragama ___?", "a": "islam"},
        {"q": "Maklumat isi padu bagi produk berbentuk cecair di dalam botol selalunya ditulis dalam unit ___?", "a": "mililiter"},
        {"q": "Botol air mineral yang dijual di kantin lazimnya menggunakan bahan pembungkusan jenis ___?", "a": "plastik"},
        {"q": "Kotak kasut direka bentuk menggunakan kepingan kertas keras dan tebal yang dipanggil sebagai ___?", "a": "kadbod"},
        {"q": "Penutup botol cecair ubat mestilah ditutup dengan rapat dan ketat agar isinya tidak tumpah atau ___?", "a": "bocor"},
        {"q": "Bungkusan pek makanan ringan seperti snek cip kentang mesti kedap dan dipam gelembung ___?", "a": "udara"},
        {"q": "Gelembung udara yang disuntik di dalam pek makanan ringan berfungsi untuk menghalang cip daripada ___?", "a": "hancur"},
        {"q": "Tanda nama komersial yang membezakan sesuatu produk dengan pengeluar yang lain dipanggil sebagai ___?", "a": "jenama"},
        {"q": "Reka bentuk pembungkusan dengan grafik maskot kartun yang unik dapat membuatkan produk lebih laris dan ___?", "a": "laku"},
        {"q": "Material bekas botol daripada kaca agak stabil kerana ia berat dan struktur permukaannya lebih ___?", "a": "tebal"},
        {"q": "Susu lembu segar dari ladang pada masa kini lebih popular dibungkus di dalam bungkusan ___?", "a": "kotak"},
        {"q": "Penutup botol ubat batuk moden direka dengan ciri kunci pusing (child-proof) bagi menjaga keselamatan ___?", "a": "kanak-kanak"},
        {"q": "Tin minuman ringan kebanyakannya diproses menggunakan bahan logam tahan karat iaitu ___?", "a": "aluminium"},
        {"q": "Barang kaca perlu dibalut dengan pembalut gelembung (bubble wrap) bagi menyerap hentakan dan mengelakkannya ___?", "a": "retak"},
        {"q": "Senarai ramuan bahan yang digunakan untuk membuat produk akan dicetak pada bahagian pelekat ___?", "a": "label"},
        {"q": "Corak garisan hitam putih pada produk iaitu kod bar (barcode) akan diimbas oleh juruwang untuk mengira ___?", "a": "harga"},
        {"q": "Reka bentuk beg pembungkusan di pasar raya perlu mempunyai pemegang (tali) yang kuat supaya senang di___?", "a": "bawa"},
        {"q": "Pembalutan untuk majlis sambutan hari lahir biasanya dibungkus menggunakan kertas corak pembalut ___?", "a": "hadiah"},
        {"q": "Reka bentuk pembungkusan tradisional yang menggunakan daun pisang dikategorikan sebagai bahan ___?", "a": "semulajadi"},
        {"q": "Nasi lemak panas yang dibungkus menggunakan daun pisang akan mengeluarkan bau aroma yang ___?", "a": "wangi"},
        {"q": "Kelongsong pulut untuk hidangan ketupat dianyam membentuk segi tiga menggunakan lilitan daun ___?", "a": "palas"},
        {"q": "Penggunaan pembungkus biodegradasi dapat membantu kelestarian bumi dan mengurangkan lambakan sisa ___?", "a": "sampah"},
        {"q": "Kelemahan tapak beg kertas adalah ia sangat mudah koyak dan terburai sekiranya ia terkena air dan ___?", "a": "basah"},
        {"q": "Makanan seperti sardin yang dibungkus di dalam tin kedap udara membolehkannya disimpan lebih ___?", "a": "lama"},
        {"q": "Pemilihan plastik pembungkus untuk aiskrim sejuk perlulah daripada jenis material yang kalis ___?", "a": "air"},
        {"q": "Pembungkus telur direka bentuk bersekat-sekat (tray) untuk melindungi cengkerangnya yang sangat ___?", "a": "nipis"},
        {"q": "Pembahagi berpetak diletakkan di dalam kotak buah epal bagi mengelakkan buah tersebut rosak akibat ___?", "a": "berlanggar"},
        {"q": "Tarikh dikilangkan pada sesuatu produk merujuk kepada tarikh bilakah produk tersebut siap ___?", "a": "dibuat"},
        {"q": "Reka bentuk bekas berbentuk tiub yang fleksibel membolehkan cecair likat seperti ubat gigi mudah di___?", "a": "picit"},
        {"q": "Kertas kerajang aluminium (aluminium foil) sering digunakan untuk membungkus makanan bagi mengekalkan suhu ___?", "a": "panas"},
        {"q": "Kotak pembungkusan kek sering mempunyai 'tingkap' jernih supaya pelanggan dapat melihat kek di bahagian ___?", "a": "dalam"},
        {"q": "Bagi menambat hati pembeli, susunan reka bentuk grafik pada kotak pembungkusan perlulah kreatif dan ___?", "a": "inovatif"},
        {"q": "Anyaman kraf tradisional kelarai selalunya dihasilkan menggunakan tikar anyaman daun pandan atau daun ___?", "a": "mengkuang"},
        {"q": "Pengilang komersial banyak menggunakan pembungkusan plastik kerana kos materialnya yang sangat ___?", "a": "murah"},
        {"q": "Barang kemas seperti cincin biasanya dibungkus di dalam kotak kecil berbaldu supaya kelihatan mewah dan ___?", "a": "eksklusif"},
        {"q": "Bentuk bekas silinder memanjang yang bertebing tinggi sangat sesuai digunakan untuk rekaan botol ___?", "a": "air"},
        {"q": "Teks panduan cara penggunaan yang dicetak pada label amat berguna sebagai rujukan terutamanya bagi pengguna ___?", "a": "baru"},
        {"q": "Logo amaran gambar tengkorak pada bungkusan asid diletakkan bagi memberikan peringatan tentang bahaya ___?", "a": "keselamatan"},
        {"q": "Kotak barangan kaca akan dilabelkan dengan simbol cawan retak (fragile) sebagai amaran mudah ___?", "a": "pecah"},
        {"q": "Simbol grafik orang membuang sampah mengingatkan pengguna agar membuang sisa bungkusan ke dalam ___?", "a": "tong"},
        {"q": "Setiap produk keluaran tempatan digalakkan memakai logo 'Buatan Malaysia' sebagai tanda ia dihasilkan di negara ___?", "a": "malaysia"}
    ],

"reka_bentuk_makanan": [
        {"q": "Gaya susunan hidangan makanan yang kreatif dan menarik di dalam pinggan dipanggil reka ___?", "a": "bentuk"},
        {"q": "Daya tarikan visual makanan yang menarik mampu menaikkan selera dan merembeskan air ___?", "a": "liur"},
        {"q": "Gaya hiasan bahan sampingan yang disusun cantik di sekeliling hidangan utama dipanggil ___?", "a": "gubahan"},
        {"q": "Seni ukiran halus pada buah tembikai lazimnya dihasilkan menggunakan bilah pisau ukir yang ___?", "a": "tajam"},
        {"q": "Syarat utama bagi bekas, pinggan, atau dulang hidangan adalah ia perlu dipastikan sentiasa ___?", "a": "bersih"},
        {"q": "Sayur segar seperti lobak merah sangat popular untuk diukir menjadi bentuk kelopak ___?", "a": "bunga"},
        {"q": "Rona warna-warni yang kontras pada makanan dapat menyerlahkan lagi tambah nilai deria ___?", "a": "estetika"},
        {"q": "Makanan yang dibalut dengan pembungkusan bento yang cantik di kedai akan kelihatan eksklusif dan ___?", "a": "mahal"},
        {"q": "Bagi memotong roti yang keras dengan lancar, alatan yang paling sesuai digunakan ialah pisau ___?", "a": "gerigi"},
        {"q": "Muncung nozel digunakan untuk memicit isian krim atau aising coklat dari dalam kelongsong beg ___?", "a": "paip"},
        {"q": "Penggunaan bekas acuan atau mangkuk jernih dapat menyerlahkan lapisan warna-warni agar-agar atau ___?", "a": "puding"},
        {"q": "Bahan perhiasan hidangan salad selalunya ditambah dengan buah tomato ceri berbentuk bulat bersaiz ___?", "a": "kecil"},
        {"q": "Alat penekap (cutter) ditekan ke atas doh untuk membentuk rupa pastri atau ___?", "a": "biskut"},
        {"q": "Pada bahagian puncak gubahan puding, hiasan pucuk pudina diletakkan untuk menaikkan aroma yang ___?", "a": "wangi"},
        {"q": "Kepingan roti untuk hidangan sandwic kebiasaannya dipotong secara melintang untuk membentuk rupa segi ___?", "a": "tiga"},
        {"q": "Rebusan nasi himpit selalunya dipotong secara dadu untuk membentuk kiub segi empat ___?", "a": "sama"},
        {"q": "Elemen kebersihan tangan daripada kuman wajib diutamakan semasa proses menyentuh dan menyediakan ___?", "a": "makanan"},
        {"q": "Pemakaian sarung tangan plastik nipis dapat mengelakkan jangkitan kuman dan memastikan tangan sentiasa ___?", "a": "bersih"},
        {"q": "Segala sisa kupasan dan lebihan kotoran bahan hiasan makanan mestilah dibuang segera ke dalam ___?", "a": "tong"},
        {"q": "Pisau tukang masak (chef's knife) berbilah lebar amat sesuai digunakan untuk memotong ketulan rangka ayam dan bahan yang ___?", "a": "tebal"},
        {"q": "Peraturan keselamatan di dapur menetapkan papan pemotong untuk daging mentah perlu diasingkan daripada papan pemotong ___?", "a": "sayur"},
        {"q": "Konsep kotak bekal Jepun atau bento disusun secara padat dan diasingkan lauk pauknya mengikut ___?", "a": "petak"},
        {"q": "Hidangan nasi goreng kampung kelihatan lebih lazat apabila dihias dengan telur dadar yang dipotong ___?", "a": "nipis"},
        {"q": "Pencucuk koktail atau lidi digunakan untuk menyambung dan menstabilkan bahagian susunan hirisan ___?", "a": "buah"},
        {"q": "Alat pencedok (scoop) digunakan dengan cara menekan dan memusing isinya untuk membentuk bebola buah yang ___?", "a": "bulat"},
        {"q": "Gubahan susunan kuih-muih kenduri di dalam dulang perlulah diatur secara seragam dan ___?", "a": "kemas"},
        {"q": "Sos yang pekat boleh dilukis secara simetri sebagai corak hiasan tambahan di kawasan birai ___?", "a": "pinggan"},
        {"q": "Pisau palet yang leper amat sesuai digunakan untuk meratakan sapuan mentega atau jem strawberi yang ___?", "a": "manis"},
        {"q": "Untuk mendapatkan tekstur sayur kubis atau epal yang halus, ia perlu disagat rapi menggunakan alat ___?", "a": "parut"},
        {"q": "Kraf lipatan pada hujung kuih pau dicubit dan dilipat dengan teliti supaya menyerupai bentuk kelopak ___?", "a": "bunga"},
        {"q": "Pewarna makanan cecair yang dibeli mestilah mempunyai label kelulusan yang disahkan selamat untuk di___?", "a": "makan"},
        {"q": "Warna biru pada hidangan nasi kerabu secara tradisinya diekstrak daripada pewarna bunga telang yang ___?", "a": "asli"},
        {"q": "Warna hijau pada kuih onde-onde diperoleh daripada perahan air ekstrak daun yang wangi iaitu daun ___?", "a": "pandan"},
        {"q": "Deretan potongan buah-buahan yang dicucuk bergilir-gilir pada batang lidi panjang dipanggil sebagai hidangan ___ buah-buahan.", "a": "kebab"},
        {"q": "Hujung kelim karipap dilipat dan dipusing dengan kemas secara beralun-alun supaya membentuk rupa ___?", "a": "ombak"},
        {"q": "Aiskrim vanila sundae yang manis sering ditaburkan dengan hiasan taburan manik ___ berwarna-warni.", "a": "gula"},
        {"q": "Fokus utama reka bentuk penyediaan kotak bekal bento sentiasa mengutamakan kandungan makanan yang padat dan ___?", "a": "sihat"},
        {"q": "Dalam piramid makanan, kumpulan pada aras tertinggi iaitu minyak, garam, dan gula ___ perlu dikurangkan pengambilannya.", "a": "manis"},
        {"q": "Penggunaan pinggan bulat berwarna putih rata dapat mempamerkan serlahan warna susunan hidangan dengan lebih ___?", "a": "jelas"},
        {"q": "Acuan mangkuk silikon yang bersifat lentur dan lembut sangat mudah diterbalikkan pada bahagian ___ untuk mengeluarkan puding.", "a": "mulut"},
        {"q": "Hiasan sampingan di dalam pinggan tidak patut terlalu berlebihan supaya hidangan utama tidak kelihatan berserabut dan ___?", "a": "sarat"},
        {"q": "Tambahan kekacang di dalam adunan biskut akan memberikan tekstur rangup dan gigitan rasa yang lebih ___?", "a": "sedap"},
        {"q": "Perancangan reka bentuk susunan makanan yang menarik di dalam pinggan wajar di___ terlebih dahulu dalam bentuk lakaran kasar.", "a": "lukis"},
        {"q": "Pengiraan anggaran jumlah kos modal bahan makanan perlu dibuat dengan teliti agar perniagaan tidak mengalami kerugian atau ___?", "a": "rugi"},
        {"q": "Peralatan dapur perlu sentiasa dibersihkan bagi mengelakkan pencemaran makanan dan penyebaran bakteria berbahaya daripada ___?", "a": "kuman"},
        {"q": "Bagi menghilangkan sisa racun serangga, buah-buahan dan sayur-sayuran wajib dibilas serta dibasuh menggunakan ___ yang bersih.", "a": "air"},
        {"q": "Penggunaan daun salad yang sudah layu dan kekuningan akan menjejaskan selera dan menjadikan persembahan pinggan tidak ___?", "a": "segar"},
        {"q": "Hidangan kanak-kanak akan menjadi lebih menarik jika tembikai diukir menggunakan corak rekaan yang comel dan bersaiz ___?", "a": "mini"},
        {"q": "Kotak bekal bento untuk murid kanak-kanak sering menggunakan tema watak animasi dengan hidangan yang dipotong menyerupai rupa ___?", "a": "kartun"},
        {"q": "Kemahiran membentuk dan menggubah hidangan makanan sentiasa memerlukan cetusan idea peribadi yang sangat ___?", "a": "kreatif"}
    ],

    "pengaturcaraan_t4": [
        {"q": "Aktiviti menulis dan menyusun set arahan kod jujukan untuk mesin komputer dipanggil sistem ___?", "a": "pengaturcaraan"},
        {"q": "Siri senarai langkah dan turutan yang sistematik untuk menyelesaikan sesuatu masalah dipanggil arahan ___?", "a": "algoritma"},
        {"q": "Antara ciri algoritma yang baik adalah ia mempunyai urutan langkah satu persatu yang disusun secara ___?", "a": "tertib"},
        {"q": "Cara penulisan algoritma yang ditaip menggunakan teks ayat ringkas seakan bahasa pertuturan manusia dipanggil ___?", "a": "pseudokod"},
        {"q": "Rajah panduan yang menggunakan lukisan simbol bergambar grafik untuk menunjukkan proses pengaturcaraan ialah carta ___?", "a": "alir"},
        {"q": "Bentuk simbol bujur di dalam carta alir digunakan untuk menandakan titik permulaan program, iaitu ___?", "a": "mula"},
        {"q": "Simbol kotak condong atau segi empat selari dalam carta alir digunakan untuk menyatakan perlakuan membaca ___ atau memaparkan output.", "a": "input"},
        {"q": "Simbol kotak segi empat tepat biasa dalam carta alir digunakan khusus untuk mencatatkan arahan proses atau ___?", "a": "tindakan"},
        {"q": "Simbol berbentuk rombus bersoal dalam carta alir menandakan syarat ujian bersyarat untuk cabang proses ___?", "a": "pilihan"},
        {"q": "Garisan lurus bersambung yang mempunyai anak panah di dalam carta alir berfungsi untuk menunjukkan arah ___ proses.", "a": "aliran"},
        {"q": "Syarat utama penulisan skrip pseudokod ialah pada baris yang paling atas, ia mesti dimulakan dengan perkataan ___?", "a": "mula"},
        {"q": "Manakala bagi baris yang paling bawah, skrip kod pseudokod mestilah dihabiskan dengan perkataan ___?", "a": "tamat"},
        {"q": "Perisian aplikasi atur cara berasaskan blok kod bergambar haiwan yang sering dipelajari di sekolah rendah ialah ___?", "a": "scratch"},
        {"q": "Ikon gambar pelakon atau objek yang digerakkan di dalam ruang aplikasi Scratch dipanggil sebagai watak atau ___?", "a": "sprite"},
        {"q": "Haiwan kucing berwarna oren merupakan ikon watak asas (default sprite) yang digunakan di dalam aplikasi perisian ___?", "a": "scratch"},
        {"q": "Gambar paparan ruang belakang pada pentas animasi Scratch (stage) dipanggil sebagai latar belakang atau ___?", "a": "backdrop"},
        {"q": "Di dalam Scratch, penulisan koding dilakukan secara visual dengan menyusun arahan baris kod yang saling bersambung seakan blok kepingan ___?", "a": "lego"},
        {"q": "Blok skrip koding kategori pergerakan berwarna biru dikumpulkan di bawah tab arahan berbahasa Inggeris iaitu ___?", "a": "motion"},
        {"q": "Blok berwarna ungu yang berfungsi untuk menukar rupa, kostum, atau dialog watak diletakkan di bawah tab arahan ___?", "a": "looks"},
        {"q": "Fungsi untuk memasukkan rekodan bunyi atau kesan bunyi seperti 'Meow' terletak pada blok arahan tab ungu jambu iaitu ___?", "a": "sound"},
        {"q": "Simbol ikon bendera hijau (green flag) di atas pentas akan ditekan bagi memberi tanda arahan untuk program ___ beroperasi.", "a": "mula"},
        {"q": "Simbol ikon butang poligon berwarna merah di sebelah bendera hijau ditekan sebagai tanda untuk arahan program ___?", "a": "berhenti"},
        {"q": "Blok arahan 'Events' yang bertindak sebagai pencetus mula (trigger) sesuatu skrip kod dipaparkan dengan warna asas ___?", "a": "kuning"},
        {"q": "Memasukkan angka pada arahan pergerakan 'move 10 steps' akan menjadikan watak kucing bergerak ke arah ___?", "a": "depan"},
        {"q": "Menetapkan arahan darjah 'turn 15 degrees' akan menjadikan badan watak kucing mengubah arah atau ___?", "a": "pusing"},
        {"q": "Ruang kerja kosong yang luas di bahagian tengah aplikasi untuk menyusun bongkah blok arahan dipanggil kawasan 'Script ___'?", "a": "area"},
        {"q": "Istilah ralat bagi kerosakan, kesilapan ejaan, atau baris arahan sistem koding yang sangkut dipanggil pepijat atau ___?", "a": "bug"},
        {"q": "Proses membaiki, membetulkan, dan menguji masalah ralat koding pada program komputer dipanggil proses nyah ___?", "a": "pepijat"},
        {"q": "Alat peranti digital elektronik seperti cip memori pada mesin basuh automatik hanya berfungsi dengan memahami bahasa ___?", "a": "mesin"},
        {"q": "Sistem pengaturcaraan merupakan satu set susunan ayat langkah demi langkah untuk memberi bahasa arahan kepada ___?", "a": "komputer"},
        {"q": "Cip peranti otak kecil yang mengawal perkakasan elektrik automatik di rumah dikenali sebagai cip ___?", "a": "mikropengawal"},
        {"q": "Peranti elektronik sistem pintar seperti telefon pintar dan televisyen pintar pada asalnya dibangunkan dan dikawal oleh sistem ___?", "a": "kod"},
        {"q": "Blok arahan logik bersyarat seperti pernyataan 'If... then...' (Jika... maka...) merupakan cabang pengaturcaraan struktur laluan ___?", "a": "pilihan"},
        {"q": "Blok arahan urutan 'repeat 10' yang memusing dan mengulang perlakuan sesuatu benda yang sama dipanggil arahan ___?", "a": "gelung"},
        {"q": "Aliran pelaksanaan arahan set baris kod yang disusun lurus menurun langkah demi langkah dipanggil sebagai kawalan struktur ___?", "a": "jujukan"},
        {"q": "Dalam menentukan kedudukan lokasi watak secara garis lintang mendatar pada pentas Scratch, titik pergerakan diukur menggunakan paksi ___?", "a": "x"},
        {"q": "Bagi pergerakan lurus mendaki ke atas atau menegak secara pacak, lokasi koordinatnya ditentukan oleh nilai paksi ___?", "a": "y"},
        {"q": "Penggunaan skrip blok arahan 'say hello' akan memaparkan cetakan buih gelembung dialog dalam bentuk kotak ___?", "a": "teks"},
        {"q": "Bagi menjaga dan memelihara fail hasil projek kerja koding supaya tidak hilang, fail perlulah dimuat turun dan disimpan pada menu ___?", "a": "fail"},
        {"q": "Arahan yang ditetapkan jika watak melanggar sempadan bingkai skrin supaya ia melantun semula ialah fungsi arahan blok 'if on ___ bounce'.", "a": "edge"},
        {"q": "Fungsi untuk menetapkan tempoh jeda masa atau melengahkan arahan seterusnya boleh disekat dengan menggunakan blok 'wait 1 sec' atau ___?", "a": "tunggu"},
        {"q": "Kod kawalan bersyarat 'forever' akan mengulang tugasan tanpa henti dan berterusan tanpa rehat, mewakili arahan ___ ulangan.", "a": "gelung"},
        {"q": "Dalam membina logik pseudokod membancuh teh panas, contoh langkah awalnya ialah menyediakan cawan, uncang teh, gula, dan ___ panas.", "a": "air"},
        {"q": "Dalam carta alir logik membancuh minuman, pertanyaan bersyarat seperti 'adakah minuman sudah manis?' diletakkan dalam bentuk kotak ___?", "a": "rombus"},
        {"q": "Untuk melengkapkan proses akhir atau memaparkan output hasil jawapan di dalam carta alir, kita perlu menggunakan kotak condong berbentuk segi empat ___?", "a": "selari"},
        {"q": "Cara yang betul untuk membaca susur galur carta alir adalah bermula dari kotak teratas menurun ke bawah berpandukan garisan anak ___?", "a": "panah"},
        {"q": "Di bawah tab kumpulan 'Events', skrip blok pencetus utamanya yang memulakan pergerakan watak apabila diklik ialah ikon bendera berwarna ___?", "a": "hijau"},
        {"q": "Mempelajari kemahiran bidang sains komputer dan koding mampu melatih minda murid untuk berfikir secara kritis dan ___?", "a": "logik"},
        {"q": "Aktiviti berlatih menulis, menguji, dan membaiki susunan blok kod amat membantu dalam melatih kemahiran murid menyelesaikan ___?", "a": "masalah"},
        {"q": "Peluang kerjaya masa hadapan dalam bidang teknologi maklumat (IT) yang tugasnya membina aplikasi dan atur cara program digital dipanggil sebagai ___?", "a": "pengaturcara"}
    ],

"teknologi_rumah_tangga": [
        {"q": "Proses mencantumkan dua keping fabrik atau lebih menggunakan benang dan jarum dikenali sebagai seni ___?", "a": "jahitan"},
        {"q": "Alatan tajam yang mempunyai lubang kecil pada pangkalnya untuk memasukkan benang dipanggil ___?", "a": "jarum"},
        {"q": "Alatan yang digunakan khusus untuk memotong kepingan fabrik dengan kemas dan lurus ialah ___ fabrik.", "a": "gunting"},
        {"q": "Proses mengambil ukuran badan atau panjang fabrik sebelum dipotong memerlukan penggunaan pita ___?", "a": "ukur"},
        {"q": "Mata jahitan sementara yang digunakan untuk menetapkan kedudukan fabrik sebelum dijahit kekal dikenali sebagai jahitan jelujur ___?", "a": "kasar"},
        {"q": "Jahitan tangan kekal yang sangat kukuh dan mempunyai rupa bentuk menyerupai jahitan mesin dikenali sebagai jahitan ___?", "a": "kia"},
        {"q": "Jahitan yang digunakan untuk mengemaskan bahagian tepi fabrik supaya tidak mudah berbulu atau meretas ialah jahitan lilit ___?", "a": "ubi"},
        {"q": "Jahitan yang digunakan sebagai hiasan atau kemasan tepi fabrik yang membentuk corak bersilang dikenali sebagai jahitan silang ___?", "a": "pangkah"},
        {"q": "Alatan beroda dengan mata bergigi tajam yang digunakan untuk memindahkan tanda pola ke atas fabrik dipanggil roda ___?", "a": "surih"},
        {"q": "Kertas karbon tukang jahit digunakan bersama-sama roda surih untuk memindahkan ___ pola ke atas permukaan fabrik.", "a": "tanda"},
        {"q": "Kapur tukang jahit digunakan khusus untuk melukis garisan dan memindahkan tanda pola secara terus ke atas permukaan ___?", "a": "kain"},
        {"q": "Alatan kecil bersarung yang digunakan untuk meretas dan menanggalkan mata jahitan yang tersilap dipanggil peretas ___?", "a": "jahitan"},
        {"q": "Semasa memotong fabrik, kepingan pola kertas perlu disemat supaya kedudukannya tidak beralih menggunakan jarum ___?", "a": "peniti"},
        {"q": "Benang jahitan perlulah dimasukkan terlebih dahulu ke dalam lubang halus pada jarum yang dipanggil ___ jarum.", "a": "mata"},
        {"q": "Bekas pelapik lembut yang digunakan untuk mencucuk dan menyimpan jarum dengan selamat dipanggil kusyen ___?", "a": "pin"},
        {"q": "Sisa kepingan fabrik lebihan yang terhasil selepas kerja menggunting fabrik selesai dipanggil perca ___?", "a": "kain"},
        {"q": "Salah satu contoh artikel jahitan mudah yang sering dihasilkan oleh murid di sekolah ialah sarung ___?", "a": "bantal"},
        {"q": "Mata jahitan kekal yang berfungsi untuk menyambungkan dua helaian fabrik secara tetap dan kemas ialah jahitan jelujur ___?", "a": "halus"},
        {"q": "Jahitan kia lazimnya dijahit secara rapat-rapat untuk memastikan cantuman fabrik menjadi amat ___?", "a": "kukuh"},
        {"q": "Bahan asas dan utama yang paling penting dalam penghasilan sesuatu artikel jahitan semestinya ialah ___?", "a": "fabrik"},
        {"q": "Lembaran tali halus yang dimasukkan ke dalam jarum untuk mencantumkan kepingan fabrik dipanggil ___?", "a": "benang"},
        {"q": "Sarung logam atau plastik yang dipakai pada jari untuk melindunginya daripada tercucuk jarum dipanggil ___?", "a": "didal"},
        {"q": "Kertas draf yang mengandungi lukisan panduan ukuran untuk membentuk pakaian atau artikel jahitan dipanggil kertas ___?", "a": "pola"},
        {"q": "Tanda garisan yang dilukis menggunakan kapur tukang jahit sangat mudah dihilangkan apabila fabrik tersebut di___?", "a": "basuh"},
        {"q": "Gunting fabrik dilarang keras penggunaannya untuk memotong kertas bagi memastikan bilah matanya sentiasa kekal ___?", "a": "tajam"},
        {"q": "Pembaris sesiku L digunakan dalam kerja mendraf pola untuk memastikan sudut lurus ukuran fabrik sentiasa ___?", "a": "tepat"},
        {"q": "Fabrik jenis kapas yang lembut dan mudah menyerap peluh amat bersesuaian untuk dijadikan pakaian harian atau baju ___?", "a": "tidur"},
        {"q": "Fabrik semula jadi yang mempunyai permukaan licin, berkilat, dan kebiasaannya dijual dengan harga yang mahal ialah kain ___?", "a": "sutera"},
        {"q": "Fabrik yang tebal, lembut, dan sedikit berbulu yang amat sesuai digunakan untuk membuat selimut atau baju sejuk ialah kain ___?", "a": "flanel"},
        {"q": "Penggunaan benang sulam yang lebih tebal dapat menjadikan hasil jahitan corak bunga tampak lebih ___ pada permukaan fabrik.", "a": "timbul"},
        {"q": "Kekabu atau kapas gentian poliester yang gebu kebiasaannya dimasukkan ke dalam artikel jahitan sebagai bahan ___ bantal.", "a": "isi"},
        {"q": "Aksesori hiasan seperti butang berlubang dua lazimnya dilekatkan pada fabrik menggunakan teknik jahitan ___?", "a": "silang"},
        {"q": "Teknik jahitan hiasan yang melibatkan tampalan corak fabrik ke atas permukaan fabrik utama dipanggil seni tampal hias atau ___?", "a": "aplike"},
        {"q": "Hiasan reben yang diikat membentuk rupa rama-rama amat menarik jika dijahit pada artikel seperti pemegang periuk atau sarung tangan ___?", "a": "ketuhar"},
        {"q": "Sesuatu produk atau hasil ciptaan fabrik yang telah siap dijahit sepenuhnya dikenali sebagai artikel ___?", "a": "jahitan"},
        {"q": "Pada permulaan dan akhir jahitan, benang perlulah dijahit dengan simpul mati supaya cantuman fabrik tidak mudah ___?", "a": "terbuka"},
        {"q": "Alatan gunting kecil berhujung tajam yang dikhususkan untuk memotong lebihan hujung benang dengan pantas ialah gunting pemotong benang atau ___?", "a": "snipper"},
        {"q": "Fabrik jenis felt amat digemari untuk kraf jahitan kerana teksturnya mudah dibentuk dan bahagian sisinya tidak mudah ___ walaupun digunting.", "a": "berbulu"},
        {"q": "Jahitan insang pari bukan sahaja berfungsi mengemaskan bahagian tepi fabrik, malah membuatkan hasil artikel jahitan kelihatan sangat ___?", "a": "cantik"},
        {"q": "Bagi memastikan keselamatan jari, jarum peniti pada fabrik perlulah dicabut satu persatu ketika kerja-kerja jahitan mesin sedang ___?", "a": "berjalan"},
        {"q": "Roda surih perlu digelek dan ditekan di atas garisan kertas pola untuk tujuan memindahkan ___ ke atas permukaan fabrik.", "a": "tanda"},
        {"q": "Fabrik jenis denim atau jeans berwarna biru selalunya menjadi pilihan untuk pakaian kerja yang tahan lasak kerana struktur kainnya yang ___?", "a": "tebal"},
        {"q": "Benang yang diperbuat daripada gentian poliester amat popular kerana sifat fizikalnya yang kuat, tahan lasak, dan amat sukar ___?", "a": "putus"},
        {"q": "Jarum yang dikhususkan untuk penggunaan mesin jahit direka dengan lubang di bahagian mata bawah dan tidak boleh digunakan untuk jahitan ___?", "a": "tangan"},
        {"q": "Pembaris lurus kayu lazimnya digunakan oleh tukang jahit untuk mengambil ukuran panjang fabrik di dalam unit sentimeter atau ___?", "a": "meter"},
        {"q": "Kesemua alatan seperti jarum, benang, dan gunting perlu disusun atur dengan kemas di dalam sebuah kotak penyimpanan khusus iaitu kotak ___?", "a": "jahitan"},
        {"q": "Fabrik jenis tuala yang mempunyai kadar serapan air yang tinggi bukan sahaja sesuai dijadikan pengelap, malah boleh dijahit sebagai alas ___?", "a": "meja"},
        {"q": "Biji manik kecil yang berkilat boleh dijahit rapat-rapat dengan kemas pada permukaan fabrik untuk dijadikan elemen hiasan tambahan pada ___?", "a": "baju"},
        {"q": "Jaluran kain renda (lace) yang berkerawang sering dijahit sebagai kemasan untuk menambah seri cantik pada bahagian ___ artikel jahitan.", "a": "tepi"},
        {"q": "Penguasaan ilmu dan kemahiran menjahit yang baik bukan sahaja menjadi satu hobi, malah boleh digunakan untuk menjana sumber wang ___?", "a": "pendapatan"}
    ],

    "kejuruteraan": [
        {"q": "Sumber tenaga alam semula jadi yang sentiasa ada dan tidak akan kehabisan dipanggil sebagai tenaga boleh ___?", "a": "baharu"},
        {"q": "Sumber tenaga haba dan cahaya yang diperoleh secara langsung daripada pancaran matahari dipanggil sebagai tenaga ___?", "a": "suria"},
        {"q": "Kepingan kaca yang direka khusus untuk menyerap haba dan cahaya matahari dipanggil sebagai panel ___?", "a": "solar"},
        {"q": "Struktur bilah kipas gergasi yang berputar menggunakan daya tiupan udara untuk menjana elektrik dipanggil kincir ___?", "a": "angin"},
        {"q": "Aliran air sungai yang deras di kawasan empangan membolehkan penjanaan elektrik melalui stesen jana kuasa tenaga ___?", "a": "hidro"},
        {"q": "Bahan organik seperti sisa reput tumbuhan dan najis haiwan boleh diproses untuk menghasilkan sumber tenaga ___?", "a": "biomas"},
        {"q": "Tenaga haba semula jadi yang terhasil daripada wap panas di bawah permukaan kerak bumi dipanggil sebagai tenaga ___?", "a": "geoterma"},
        {"q": "Pergerakan alun air laut yang besar di kawasan perairan pantai boleh digunakan untuk menjana elektrik di stesen tenaga ___?", "a": "ombak"},
        {"q": "Pemasangan panel suria di kawasan kediaman merupakan satu langkah pintar untuk menjimatkan kos bayaran bil elektrik ___?", "a": "rumah"},
        {"q": "Pembebasan asap kotor dari stesen jana kuasa pembakaran arang batu akan mendatangkan kesan pencemaran kepada udara dan ___ sekitar.", "a": "alam"},
        {"q": "Sumber bahan api fosil tidak boleh baharu seperti petroleum dan diesel lama-kelamaan pasti akan menyusut dan ___?", "a": "habis"},
        {"q": "Sel fotovoltaik pada panel solar berfungsi untuk menukarkan serapan cahaya matahari secara terus kepada arus ___?", "a": "elektrik"},
        {"q": "Kenderaan hibrid moden direka menggunakan gabungan sistem enjin pembakaran petrol dan motor berkuasa ___?", "a": "bateri"},
        {"q": "Kuasa elektrik daripada panel solar akan disimpan dalam bentuk tenaga kimia di dalam bateri untuk digunakan terutamanya pada waktu ___?", "a": "malam"},
        {"q": "Komponen motor arus terus (DC) berfungsi untuk menukarkan bekalan tenaga elektrik kepada pergerakan kinetik atau ___?", "a": "mekanikal"},
        {"q": "Komponen gear berbentuk roda bergigi berfungsi untuk memindahkan kuasa putaran dan mengawal kelajuan pergerakan ___?", "a": "enjin"},
        {"q": "Suis merupakan komponen kawalan mekanikal yang membolehkan pengguna menyambung dan memutuskan aliran litar ___?", "a": "elektrik"},
        {"q": "Diod pemancar cahaya (LED) merupakan komponen jimat kuasa yang mampu mengeluarkan pancaran cahaya yang sangat ___?", "a": "terang"},
        {"q": "Dalam penyambungan litar, wayar kuprum yang disalut dengan penebat berwarna merah sentiasa digunakan untuk mewakili laluan arus ___?", "a": "positif"},
        {"q": "Manakala, wayar kuprum bersalut getah berwarna hitam pula perlu disambungkan pada terminal litar yang mewakili laluan arus ___?", "a": "negatif"},
        {"q": "Pemegang bateri merupakan sarung khas yang berfungsi untuk memegang kedudukan dan menyambungkan bekalan tenaga sel ___?", "a": "kering"},
        {"q": "Dinamo yang bergeser pada roda tayar basikal akan memutar gandar dalamnya untuk menjana elektrik dan menyalakan lampu pada masa ia di___?", "a": "kayuh"},
        {"q": "Sistem kincir angin bergantung sepenuhnya kepada kuasa tiupan udara bagi mendapatkan daya tolakan untuk memusingkan struktur ___ kipasnya.", "a": "bilah"},
        {"q": "Penggunaan sumber tenaga boleh baharu adalah sangat mesra alam serta dapat membantu mengurangkan pemanasan global demi menyelamatkan planet ___?", "a": "bumi"},
        {"q": "Panel solar yang dipasang pada bumbung kediaman akan berfungsi menyerap sumber haba cahaya secara maksimum pada waktu ___?", "a": "siang"},
        {"q": "Di dalam stesen jana kuasa kincir angin mahupun empangan hidro, terdapat mesin penjana (generator) yang menukarkan gerak mekanikal kepada tenaga ___?", "a": "elektrik"},
        {"q": "Model kereta solar bersaiz cilik akan bergerak memecut dengan sangat laju apabila diuji di trek terbuka pada keadaan cuaca panas tengah ___?", "a": "hari"},
        {"q": "Penggunaan bahan kitar semula seperti botol minuman plastik kosong amat sesuai diinovasikan sebagai rangka asas bagi struktur badan ___ mainan.", "a": "kereta"},
        {"q": "Batang lidi sate kayu yang lurus dan panjang sering dipotong dan diaplikasikan sebagai batang gandar bagi memegang bahagian ___ roda.", "a": "tayar"},
        {"q": "Penutup botol plastik yang ditebuk lubang pada bahagian tengahnya secara seimbang amat sesuai dijadikan sebagai struktur roda yang ___?", "a": "bulat"},
        {"q": "Penggunaan pita pelekat dua muka (double-sided tape) amat membantu untuk mengikat dan meletakkan motor DC dengan kukuh pada bahagian tapak atau ___ kenderaan.", "a": "casis"},
        {"q": "Kepingan bod lekap (mounting board) mempunyai struktur yang ringan tetapi kuat, menjadikannya bahan yang ideal untuk membina bingkai badan sesuatu ___?", "a": "model"},
        {"q": "Pembaris keluli sering digunakan untuk mengambil dan menanda ukuran pada bod lekap supaya hasil pemotongan pisau dapat dipandu dengan lurus dan ___?", "a": "tepat"},
        {"q": "Demi keselamatan mata bilah pisau dan permukaan meja, proses keratan bod lekap wajib dilakukan di atas permukaan alas ___ pelindung (cutting mat).", "a": "pemotong"},
        {"q": "Penggunaan alat pistol gam panas (hot glue gun) amat berkesan untuk mencantumkan sisa bahan dengan ikatan yang kukuh pada binaan ___?", "a": "projek"},
        {"q": "Fasa ujian penilaian prestasi model kereta solar perlulah dijalankan di atas permukaan trek mendatar yang lurus pada cuaca terbuka dan ___?", "a": "panas"},
        {"q": "Sekiranya kereta solar didapati bergerak berundur ke belakang semasa diuji, kedudukan penyambungan klip wayar positif dan negatif pada enjin motor perlulah di___?", "a": "tukar"},
        {"q": "Jika sesebuah model kereta elektrik didapati hanya mampu bergerak dengan teramat perlahan, ini menandakan kuasa cas pada simpanan baterinya mungkin sudah ___?", "a": "lemah"},
        {"q": "Di Malaysia, sumber bekalan utama tenaga elektrik hidro terbesar dijana melalui stesen empangan mega di sungai Empangan ___ yang terletak di Sarawak.", "a": "bakun"},
        {"q": "Kenderaan elektrik (EV) merupakan inovasi teknologi yang sangat berkesan bagi mengurangkan pencemaran sisa pelepasan gas ___ ke udara.", "a": "karbon"},
        {"q": "Model kereta perlumbaan direka khusus dengan bentuk fizikal berkonsepkan aerodinamik bagi membolehkannya membelah dan memotong ___ lintangan angin dengan laju.", "a": "rintangan"},
        {"q": "Struktur bumbung perhentian bas moden kini sering dilengkapi dengan unit kepingan panel solar bertujuan untuk menjana elektrik kepada nyalaan lampu ___ pada waktu malam.", "a": "led"},
        {"q": "Ilmu reka bentuk dan ciptaan inovasi kejuruteraan menyumbang kepada terhasilnya pelbagai alat mekanikal moden yang banyak memudahkan urusan jalan kerja ___ manusia.", "a": "harian"},
        {"q": "Sumber tenaga geoterma dapat dikesan wujud secara semula jadi di kawasan gunung berapi melalui kejadian fenomena pembebasan wap haba tanah dan lubang pancutan air ___?", "a": "panas"},
        {"q": "Kalkulator elektronik harian pada masa kini juga dilengkapi dengan aplikasi teknologi tenaga suria yang dibekalkan melalui sel kepingan panel yang bersaiz amat ___?", "a": "kecil"},
        {"q": "Peralihan berterusan industri dunia ke arah peluasan amalan penggunaan teknologi tenaga hijau amat membantu memulihara keindahan alam sekitar supaya sentiasa terpelihara dan kekal ___?", "a": "bersih"},
        {"q": "Pergantungan berlebihan loji stesen jana kuasa terhadap bekalan sumber bahan api fosil seperti arang batu telah mewujudkan krisis pemanasan global melalui fenomena kesan rumah ___?", "a": "hijau"},
        {"q": "Pembangunan inovasi struktur kincir angin luar pesisir laut kini diperluaskan dengan kemampuan teknologi berkapasiti lebih maju bagi menjana dan menyumbang bekalan kuasa elektrik yang sangat ___?", "a": "besar"},
        {"q": "Kumpulan murid yang berjaya menyiapkan dan mereka bentuk projek model kereta yang berkeupayaan bergerak laju dan cemerlang melepasi garisan ujian litar layak mencatat gred markah yang ___?", "a": "tinggi"},
        {"q": "Murid yang menunjukkan kemahiran, daya kreativiti, dan kecemerlangan yang tinggi di dalam mempraktikkan penguasaan ilmu reka bentuk kejuruteraan akan menjadi perintis serta aset negara pada masa ___?", "a": "depan"}
    ],

"pengaturcaraan_t5": [
        {"q": "Papan litar elektronik bersaiz kecil yang berfungsi sebagai otak untuk mengawal perkakasan dipanggil papan ___?", "a": "mikropengawal"},
        {"q": "Sistem kawalan lampu isyarat di persimpangan jalan raya beroperasi secara ___?", "a": "automatik"},
        {"q": "Papan mikropengawal kecil yang popular dan sering dipelajari oleh murid di sekolah dikenali sebagai micro___?", "a": "bit"},
        {"q": "Huruf A dan B yang terdapat pada permukaan papan mikropengawal berfungsi sebagai suis butang ___?", "a": "tekan"},
        {"q": "Paparan skrin matriks pada papan mikropengawal ini terdiri daripada 25 biji lampu ___ kecil.", "a": "led"},
        {"q": "Wayar penyambung yang mempunyai klip penyepit logam pada bahagian hujungnya dipanggil wayar klip ___?", "a": "buaya"},
        {"q": "Papan mikropengawal perlu disambungkan pada komputer untuk proses memuat turun kod menggunakan kabel ___?", "a": "usb"},
        {"q": "Perisian penyunting berasaskan web yang digunakan untuk membina atur cara blok dikenali sebagai Microsoft Make___?", "a": "code"},
        {"q": "Laci blok arahan yang digunakan khusus untuk memasukkan nilai angka dipanggil sebagai blok ___?", "a": "nombor"},
        {"q": "Blok arahan yang digunakan untuk memaparkan gabungan teks atau mesej huruf pada skrin dipanggil blok ___?", "a": "rentetan"},
        {"q": "Blok arahan gelung (loop) digunakan untuk mengarahkan sistem supaya mengulang arahan yang sama secara berkali-___?", "a": "kali"},
        {"q": "Arahan bersyarat yang membuat pilihan seperti 'jika-maka' (if-then) berada di bawah kategori blok ___?", "a": "logik"},
        {"q": "Blok arahan 'on start' akan melaksanakan kod atur cara hanya sekali sebaik sahaja sistem dihidupkan pada peringkat ___?", "a": "awal"},
        {"q": "Blok arahan 'forever' pula akan mengulang kod atur cara secara berterusan tanpa henti atau sampai bila-___?", "a": "bila"},
        {"q": "Komponen peranti yang berfungsi untuk mengesan keadaan cuaca panas atau sejuk di sekeliling dipanggil penderia ___?", "a": "suhu"},
        {"q": "Komponen input elektronik yang bertindak balas dan mengesan keadaan gelap atau terang dipanggil penderia ___?", "a": "cahaya"},
        {"q": "Arahan pengaturcaraan untuk memainkan melodi lagu atau bunyi audio boleh dijumpai di dalam laci blok ___?", "a": "muzik"},
        {"q": "Bagi membuat animasi grafik denyutan jantung pada paparan LED, kita perlu melukis atau memilih ikon yang menyerupai bentuk ___?", "a": "hati"},
        {"q": "Pek bateri bersaiz AAA lazimnya dipasang sebagai sumber kuasa tambahan bagi menghidupkan papan litar ___?", "a": "microbit"},
        {"q": "Kecacatan atau kerosakan struktur kod yang menyebabkan atur cara gagal berfungsi dipanggil ralat atau ___?", "a": "pepijat"},
        {"q": "Proses menyemak, mencari, dan membaiki ralat di dalam sesuatu kod atur cara dipanggil sebagai proses nyah___?", "a": "pepijat"},
        {"q": "Papan mikropengawal dapat mengesan gegaran atau pergerakan cerun dengan menggunakan penderia ___ yang terbina padanya.", "a": "pecutan"},
        {"q": "Pin sambungan bumi yang mewakili kutub negatif pada papan mikropengawal dilabelkan dengan huruf singkatan ___?", "a": "gnd"},
        {"q": "Kerja menulis atur cara dan menyusun blok arahan untuk dilaksanakan oleh komputer dipanggil sebagai aktiviti ___?", "a": "pengekodan"},
        {"q": "Atur cara yang dimuat turun ke dalam komputer akan menggunakan format fail '.hex' yang direka khas untuk papan mikropengawal micro:___?", "a": "bit"},
        {"q": "Bagi menggunakan perisian MakeCode, pengguna perlu menaip alamat URL tapak web pada aplikasi pelayar web dengan sambungan rangkaian ___?", "a": "internet"},
        {"q": "Blok arahan 'play tone' berfungsi untuk mengarahkan komponen supaya mengeluarkan nada dan frekuensi ___?", "a": "bunyi"},
        {"q": "Kipas pintar automatik akan berputar dengan lebih laju apabila penderia mengesan keadaan suhu persekitaran yang ___?", "a": "panas"},
        {"q": "Pintu automatik di pasar raya direka untuk terbuka dengan sendiri apabila sistemnya mengesan kehadiran pengunjung menggunakan penderia ___?", "a": "gerakan"},
        {"q": "Komponen buzer luaran yang disambungkan menggunakan wayar klip buaya pada pin litar akan mengeluarkan bunyi amaran isyarat ___?", "a": "bip"},
        {"q": "Wayar klip buaya yang digunakan untuk menyalurkan bekalan arus elektrik lazimnya dikepit pada pin bekalan kuasa bernilai 3 ___?", "a": "volt"},
        {"q": "Sistem loceng rumah ditekan menggunakan input jenis suis butang untuk mengeluarkan isyarat ___ yang kuat.", "a": "bunyi"},
        {"q": "Dalam sains komputer, pemboleh ubah dicipta untuk menyimpan rekod data yang nilainya sentiasa berubah-ubah seperti nilai ___?", "a": "markah"},
        {"q": "Jika blok input pada butang A diatur cara sebagai paparan teks, skrin LED akan menunjukkan paparan huruf abjad atau ___ apabila ditekan.", "a": "huruf"},
        {"q": "Blok arahan input 'on shake' yang digabungkan dengan fungsi matematik boleh digunakan untuk memaparkan titik ikon dadu secara ___?", "a": "rawak"},
        {"q": "Sistem lampu isyarat di persimpangan jalan raya dikawal secara automatik untuk memaparkan nyalaan lampu yang terdiri daripada tiga ___?", "a": "warna"},
        {"q": "Komponen output elektronik bersaiz kecil yang akan menyala dan memberikan isyarat amaran sekiranya disambung dengan betul dipanggil lampu ___?", "a": "led"},
        {"q": "Cip mikropengawal bertindak sebagai otak utama peranti elektronik yang berfungsi untuk mengawal keseluruhan operasi sesebuah ___?", "a": "sistem"},
        {"q": "Robot kereta pintar dapat bergerak ke hadapan tanpa melanggar objek halangan dengan panduan penderia jarak jenis ___?", "a": "ultrasonik"},
        {"q": "Mekanisme sistem palang tol pintar dinaikkan dan diturunkan dengan menggunakan putaran sudut daripada sebuah motor ___?", "a": "servo"},
        {"q": "Blok arahan 'pause' digunakan untuk memberhentikan atau melengahkan atur cara seketika berdasarkan tetapan kiraan masa dalam mili___?", "a": "saat"},
        {"q": "Laci blok matematik dalam perisian pengaturcaraan membolehkan kita melakukan operasi kiraan asas seperti operasi tambah, tolak, darab, dan ___?", "a": "bahagi"},
        {"q": "Penderia suhu yang terbina di dalam papan mikropengawal membolehkan papan tersebut mengukur tahap darjah bacaan ___ persekitaran.", "a": "suhu"},
        {"q": "Penggunaan atur cara pada cip papan induk mesin basuh membolehkannya mengarahkan pergerakan dan putaran dram ___?", "a": "motor"},
        {"q": "Periuk nasi elektrik moden yang dikawal oleh atur cara mikropengawal akan memulakan proses memasak secara tepat apabila ditekan pada suis ___?", "a": "butang"},
        {"q": "Kod atur cara yang cemerlang mempunyai struktur kawalan arahan yang tepat, kemas, dan bebas daripada sebarang kecacatan atau ___?", "a": "ralat"},
        {"q": "Fail projek pengaturcaraan MakeCode yang telah disiapkan perlulah dimuat turun dan disimpan ke dalam ___ yang dikhaskan di dalam komputer.", "a": "folder"},
        {"q": "Dalam atur cara laluan, kereta robot akan diarahkan supaya terus bergerak ke hadapan sekiranya penderia mendapati jalan di hadapannya cerah dan ___?", "a": "jelas"},
        {"q": "Fail projek atur cara boleh dikongsi bersama dengan kawan-kawan dengan cara menjana pautan web internet untuk rakan ___?", "a": "lihat"},
        {"q": "Penguasaan kemahiran dalam bidang sains komputer dan IT sejak usia muda wajar dipupuk demi menyediakan murid bagi mendepani cabaran kerjaya pada masa ___?", "a": "depan"}
    ],

    "teknologi_pertanian": [
        {"q": "Aktiviti bercucuk tanam yang menggunakan kaedah menjimatkan ruang di kawasan kediaman bandar dikenali sebagai konsep pertanian ___?", "a": "bandar"},
        {"q": "Teknik penanaman sayur tanpa tanah dengan merendamkan akar di dalam bekas takung cecair nutrisi baja dipanggil sistem ___ hidroponik.", "a": "takungan"},
        {"q": "Aktiviti pertanian bandar merupakan satu inisiatif hijau yang amat sesuai dipraktikkan oleh para penduduk di perumahan apartmen atau pangsapuri ___?", "a": "tinggi"},
        {"q": "Bagi mengurangkan pencemaran, barangan buangan terpakai seperti botol air plastik boleh dikitar semula untuk dijadikan sebagai bekas ___ sayur.", "a": "tanaman"},
        {"q": "Penanaman menggunakan sistem hidroponik membekalkan zat air baja kepada akar secara terus tanpa menggunakan sebarang medium tanah ___?", "a": "hitam"},
        {"q": "Saluran batang paip PVC yang dipotong dan ditebuk lubang akan digunakan sebagai palung untuk menempatkan pasu hidroponik pokok ___?", "a": "sayur"},
        {"q": "Dalam kaedah hidroponik, medium tanaman seperti span yang telah dipotong dadu akan diserap basah dengan air bagi tujuan menyemai ___ benih.", "a": "biji"},
        {"q": "Sayuran seperti bayam, kangkung, dan sawi amat sesuai ditanam menggunakan kaedah hidroponik kerana tergolong dalam jenis sayuran berdaun ___?", "a": "hijau"},
        {"q": "Bulu mineral buatan atau gentian kaca (rockwool) bersifat seperti span untuk menakung air dan mengekalkan kelembapan bagi percambahan ___?", "a": "benih"},
        {"q": "Sistem tanaman pasu siraman sendiri sering menggunakan benang, kain kapas, atau tali mop yang bertindak sebagai sumbu untuk menyerap air ___ naik ke akar.", "a": "baja"},
        {"q": "Inovasi tanaman yang menggabungkan kaedah penanaman hidroponik dan ternakan akuakultur (ternakan ikan) pada kitaran air yang sama dipanggil sistem ___?", "a": "akuaponik"},
        {"q": "Larutan pati cecair kimia yang sering dicampur sebagai nutrisi kepada pembesaran pokok tanaman hidroponik dikenali secara komersial sebagai baja ___?", "a": "ab"},
        {"q": "Bebola Leca (tanah liat bakar) bertindak sebagai media tanaman hidroponik yang tahan lama, kemas, dan sangat baik untuk mencengkam serta menyokong struktur akar ___?", "a": "pokok"},
        {"q": "Pemilihan media penanaman seperti batuan kelikir sangat membantu mengekalkan keutuhan pokok selain tidak mencemarkan takungan air dan memastikannya sentiasa kekal ___?", "a": "bersih"},
        {"q": "Bakul semaian khas bersaiz kecil yang berlubang di bahagian bawah atau sisinya (netpot) membolehkan sistem pokok menjuntaikan helaian ___ ke arah bekas takungan baja.", "a": "akar"},
        {"q": "Untuk mencipta sistem takungan botol siraman sendiri, botol plastik akan dibelah dua dan sumbu benang akan dijuntaikan daripada penutupnya hingga ke paras air di bahagian ___?", "a": "bawah"},
        {"q": "Bagi mengawal pembiakan jentik-jentik dan larva nyamuk denggi di dalam bekas air takungan hidroponik, kita boleh memasukkan sejenis bahan pencegah jentik-jentik iaitu serbuk ___?", "a": "abate"},
        {"q": "Pancaran sinaran cahaya matahari adalah elemen kritikal bagi membolehkan pokok memproses makanannya sendiri yang mana proses itu dikenali dalam sains sebagai ___?", "a": "fotosintesis"},
        {"q": "Penggunaan jaring kalis serangga yang dipasang membaluti kawasan bekas penanaman sangat efektif bagi mengelakkan pokok sayur di___ oleh ulat, belalang, dan serangga perosak.", "a": "makan"},
        {"q": "Cawan penyukat kecil mahupun penutup botol boleh digunakan bagi memudahkan proses menyukat larutan campuran pati cecair baja mengikut saranan label dalam kiraan unit mili___?", "a": "liter"},
        {"q": "Amalan memperbanyakkan penanaman pokok hijau di dalam atau di luar kawasan rumah secara tidak langsung akan bertindak menyedut udara berbahaya dan menurunkan kadar gas karbon ___?", "a": "dioksida"},
        {"q": "Sayur-sayuran yang berjaya ditanam di persekitaran kawasan rumah mempunyai kualiti kesegaran yang tinggi, bebas racun sintetik, dan lebih berkhasiat serta sihat apabila di___?", "a": "makan"},
        {"q": "Penghasilan sayur organik dan hidroponik amat terjamin kualitinya selain dapat mengurangkan risiko penyerapan sisa racun kimia sekali gus dapat mengekalkan tubuh badan yang ___?", "a": "sihat"},
        {"q": "Penggunaan inovasi pertanian bandar seperti taman dinding atau menara paip PVC bertingkat membolehkan kita menanam pelbagai tanaman secara efisien di ruang kawasan yang amat ___?", "a": "sempit"},
        {"q": "Pilihan pokok renek kecil berbau harum atau jenis daun rempah seperti pudina, daun sup, dan pandan amat bersesuaian untuk ditanam dalam pasu hidroponik sebagai hiasan hijau di kawasan ___?", "a": "dapur"},
        {"q": "Untuk mengelakkan kehadiran alga, bekas penanaman lut sinar seperti botol mineral perlu disembur cat atau dibalut menggunakan pembalut berwarna gelap supaya dapat mengurangkan pembentukan lumut ___?", "a": "hijau"},
        {"q": "Kehadiran pembiakan lumut hijau di dalam air bekas takungan baja perlu sentiasa dicegah bagi memastikan unsur nutrien oksigen pokok sayur tidak terancam dan tidak menjadikan tumbesarannya terbantut atau ___?", "a": "bantut"},
        {"q": "Biji benih pokok atau kekacang lazimnya akan melalui tempoh proses melembutkan lapisan kulit melalui rendaman basah semalaman sebelum ditanam untuk memaksimumkan kadar proses peratusan benih ber___?", "a": "cambah"},
        {"q": "Langkah menyemai biji benih yang bersifat terlampau halus ke dalam bukaan garisan belahan span hidroponik basah menjadi lebih kemas dan cepat dengan teknik menggunakan bilah pencungkil batang anak ___?", "a": "lidi"},
        {"q": "Struktur pembesaran pokok dalam sistem penanaman jenis takungan air tertutup memerlukan juraian pemanjangan akar sihat daripada span merentasi ruangan udara ke arah takungan bekalan nutrisi air cecair ___?", "a": "baja"},
        {"q": "Tahap aras penakungan takungan kotak baja hidroponik wajar diselia dengan konsisten setiap masa agar penambahan nutrien dilakukan sekiranya berlaku kekeringan bagi mengekalkan takat campuran bekalan aliran air ___?", "a": "paip"},
        {"q": "Penyediaan campuran bahan asas formulasi komposisi larutan cecair kepekatan tinggi seperti Pati A dan Pati B secara asalnya tidak boleh digabungkan di dalam bekas botol simpanan yang sama agar ia tidak terus mengeras ___?", "a": "beku"},
        {"q": "Dalam inovasi ekosistem hidupan teknologi sistem akuaponik, pokok sayuran bertindak menyerap khasiat bekalan organik nitrogen, ammonia, dan bahan kumuh terus daripada kitaran turasan bahan buangan sisa perkumuhan ___ ikan.", "a": "najis"},
        {"q": "Sebagai kesinambungan daripada kaedah turasan pada inovasi teknologi akuaponik, pertumbuhan kelebatan akar pokok menguraikan penapisan biologi bagi membersihkan air kitaran buangan secara selamat semula ke arah ekosistem kolam ___?", "a": "ikan"},
        {"q": "Pembelajaran teknik inovasi kemahiran asas pertanian bercucuk tanam bukan sekadar memenuhi keperluan akademik silibus pendidikan, malah boleh dijadikan satu gaya hidup riadah sihat kepada aktiviti berfaedah masa lapang musim ___?", "a": "cuti"},
        {"q": "Penglibatan dalam industri pertanian bandar menerusi penghasilan penuaian harian produk berterusan secara tidak langsung mendorong nilai keusahawanan melalui pengurangan pergantungan kebergantungan kos dapur belian lauk pasar dan ___?", "a": "pasar"},
        {"q": "Aplikasi elemen mesra alam untuk penanaman teknik organik menggantikan struktur serbuk tanah menggunakan campuran sabut tempurung fiber kelapa (cocopeat) disebabkan teksturnya yang berspan, lebih ringan serta berupaya tinggi mengekalkan simpanan cecair ___?", "a": "air"},
        {"q": "Inisiatif teknologi penjimatan mesra kitar semula mendidik amalan penukaran sisa dedaun bahan buangan harian lebihan domestik buangan bahan dapur dapur dan sisa sisa tumbuhan kering diubah suai secara kaedah proses pemeraman degradasi campuran perubatan baja komposisi bahan ___?", "a": "organik"},
        {"q": "Kepelbagaian corak pelan aplikasi teknologi pertanian yang dikemas kini mengadaptasi sistem tanaman taman secara bergantung struktur vertikal menegak yang disandarkan pada kerangka pagar atau permukaan pelan menegak ruang dinding supaya ia tidak memakan bahagian kawasan tapak pemijak ___?", "a": "lantai"},
        {"q": "Elemen integrasi pembangunan aplikasi kaedah agihan penyaluran paip air mikro-tiub kecil membekalkan penyiraman kawalan tepat langsung ke bahagian zon percambahan pokok tanaman untuk mendisiplinkan aspek pengurangan pembaziran limpahan kos bekalan aliran cecair sumber bekalan ___?", "a": "titisan"},
        {"q": "Bagi menyokong aplikasi infrastruktur struktur kekuatan reka bentuk pada bahagian pembinaan beban takungan PVC saluran gantung secara vertikal pelan menegak atas, kabel utiliti tegangan logam besi digunakan bagi mengelakkan daripada impak kegagalan berisiko kemudaratan sekiranya sistem ikatan penyokong tergelincir mendarat ke tapak ___?", "a": "bawah"},
        {"q": "Penyediaan tapak pemotongan manual semasa kerja-kerja memproses penutup palung atau penebukan lekatan pada kawasan dinding lilitan bekas perlu dikerjakan cermat secara terkawal susulan permukaan keluli pemotong bilah logam pisau tajam yang sangat bahaya agar dielakkan kemungkinan impak insiden malang fizikal tangan ter___?", "a": "luka"},
        {"q": "Sekiranya peringkat ujian rintis permulaan pendawaian litar pam siraman menemui isu tekanan paip pemantauan mengesan kegagalan atau limpahan tirisan kebocoran perpaipan persimpangan sambungan PVC penyaluran sistem saluran, ia wajar dibersihkan untuk prosedur baik pulih kecacatan sebelum dilapisi lekatan sapuan lelehan pelekat kompaun kimia kalis air cecair ___?", "a": "tampal"},
        {"q": "Meter piawaian ketepatan parameter uji kepekatan mineral digital atau penguji ukuran EC jenis alat peranti penyukatan portabel elektronik dimasukkan bersentuhan permukaan larutan pati baja cecair larutan hidroponik dianalisa dan memaparkan bacaan ukuran penentuan petunjuk rintangan kekonduksian berdasarkan kuasa laluan sambungan cas bateri isyarat nilai voltan arus ___?", "a": "elektrik"},
        {"q": "Kategori keutamaan tanaman persekitaran rumah bagi kategori sistem pemilihan kultivar sayur yang mengeluarkan struktur jalinan jaringan daun lembut halus dan menyejukkan sedap rangup lazat meriah hasil seperti daun batavia salad atau kubis sawi sedia subur berskala tempoh penuaian singkat pantas lazimnya lazat dijadikan kunyahan ulam-ulaman segar dalam bentuk yang terus segar dimakan secara langsung sewaktu masih ___?", "a": "mentah"},
        {"q": "Kawalan penyelenggaraan keselamatan penuaian racun sifar biologi bagi membasmi kemusnahan jangkitan serangan koloni pemusnah makhluk kecil haiwan yang gemar mengunyah tisu lembut pokok disyorkan dibendung pengaplikasian melalui semburan halauan pati organik bau kuat perahan ekstrak semulajadi sulingan cecair asap perapan larutan cuka ___ kayu demi mencegah ancaman anasir kumpulan musuh biologi haiwan perosak serangga ___?", "a": "perosak"},
        {"q": "Perubahan kerosakan rupa isyarat status ancaman pembesaran kecacatan yang menunjukkan rupa keadaan jalinan ikatan pangkal akar mula reput berkulat luruh kusam hancur merosot kejatuhan bertukar bertukar warnanya kearah kegelapan lendir hitam hancur rosak menandakan takat piawaian indeks air kolam palung bekalan nutrisi medium aliran oksigen cecair cecair penakungan takungan simpanan baja airnya sudah berkeladak meruap berkulat menjadi beracun tercemar terdedah basi serta keadaan fizikalnya sudah lagi tidak sihat tidak ___?", "a": "bersih"},
        {"q": "Potensi keberhasilan tuaian sayuran buahan jenis tanaman kategori penuaian penghasilan petikan buah berhasil ranum matang yang dibiak menerusi sokongan alternatif nutrisi sistem palung hidroponik air ini seperti buah kacang panjang, tomato atau lada cilinya terbukti membuktikan penampakan warna kualiti keremajaan kulit kilatan terang, kerangupan kualiti jus daging dan pedas yang amat kepekatannya amat padu amat ___?", "a": "pedas"},
        {"q": "Langkah praktikal ketika penuaian mengutip hasil pucuk ranting rimbun tumbuhan sayur kekacang ulam ulaman berpokok tunas kangkung hidroponik atau ulam bayam adalah sekadar kaedah mengerat batangnya, di mana baki akar batang yang masih tersisa tidak dicabut kekal dibiarkan merangsang pembelahan pengeluaran gandaan meremajakan hasil penuaian yang segar kembali dengan kebangkitan tumbesaran kemunculan pertumbuhan cabang penghasilan pertumbuhan pembukaan putik helaian daun generasi hasil pucuk daun pucuk yang ___?", "a": "baru"},
        {"q": "Pendedahan literasi integrasi sains ilmu dan kemahiran teknikal pengukuhan disiplin teknologi pertanian berskala mampan moden mampu menyuntik transformasi inovasi menjana ekonomi kendiri sara diri generasi di samping berikhtiar berkerjasama memainkan kebertanggungjawapan menangani kebergantungan luar rantaian cabaran kelangsungan pengukuhan asas rizab kestabilan ketersediaan stok rizab bekalan pemakanan sumber negara untuk sekuriti jaminan pasaran domestik jaminan nutrisi rantaian stok bekalan asas ___?", "a": "makanan"}
    ],

"elektromekanikal": [
    {"q": "Produk yang menggabungkan elemen elektrik dan komponen mekanikal dikenali sebagai produk ___?", "a": "elektromekanikal"},
    {"q": "Sistem yang berfungsi untuk membekalkan arus elektrik kepada sesuatu produk dipanggil sistem ___?", "a": "elektrik"},
    {"q": "Sistem yang menggunakan peranti kawalan rumit seperti cip mikropengawal dipanggil sistem ___?", "a": "elektronik"},
    {"q": "Sistem pergerakan yang melibatkan komponen roda, gear, dan putaran dikenali sebagai sistem ___?", "a": "mekanikal"},
    {"q": "Komponen roda bergigi yang berfungsi untuk memindahkan kelajuan dan kuasa putaran dikenali sebagai ___?", "a": "gear"},
    {"q": "Komponen roda beralur yang memegang tali sawat untuk memindahkan pergerakan dipanggil ___?", "a": "takal"},
    {"q": "Tali getah atau penghubung yang memusingkan dua roda takal secara serentak dikenali sebagai tali ___?", "a": "sawat"},
    {"q": "Motor arus terus (DC) berfungsi menukarkan tenaga elektrik kepada tenaga pergerakan atau tenaga ___?", "a": "mekanikal"},
    {"q": "Komponen yang berfungsi untuk memutus dan menyambungkan aliran litar elektrik dipanggil ___?", "a": "suis"},
    {"q": "Bateri berfungsi sebagai sumber bekalan tenaga utama di dalam sesebuah litar ___?", "a": "elektrik"},
    {"q": "Bekas khas yang direka untuk meletakkan dan memegang sel kering dengan kemas dipanggil ___ bateri.", "a": "pemegang"},
    {"q": "Rantai besi pada basikal berfungsi untuk menghubungkan pergerakan putaran di antara dua ___?", "a": "gear"},
    {"q": "Dalam penyambungan litar, wayar yang disalut dengan penebat berwarna merah sentiasa mewakili kutub ___?", "a": "positif"},
    {"q": "Wayar yang disalut dengan penebat berwarna hitam pula mesti disambungkan pada terminal litar yang mewakili kutub ___?", "a": "negatif"},
    {"q": "Mesin basuh moden berfungsi menggunakan gabungan sistem kawalan elektrik dan putaran dram berkonsep ___?", "a": "elektromekanikal"},
    {"q": "Pemutar skru Philip direka khusus dengan bahagian hujung matanya yang berbentuk silang atau alur ___?", "a": "pangkah"},
    {"q": "Pemutar skru rata mempunyai bahagian hujung mata yang berbentuk satu garis ___?", "a": "lurus"},
    {"q": "Bod impra, iaitu kepingan plastik berongga yang ringan, sangat sesuai digunakan untuk membina struktur badan ___?", "a": "projek"},
    {"q": "Alatan yang mempunyai mata pisau yang sangat tajam untuk memotong bahan seperti bod impra dengan kemas ialah pisau ___?", "a": "kraf"},
    {"q": "Papan bergrid yang digunakan untuk mengelakkan permukaan meja tercalar semasa proses pemotongan dipanggil alas ___?", "a": "pemotong"},
    {"q": "Alatan tangan yang digunakan untuk memegang, membengkok, atau memotong dawai halus dipanggil ___ muncung tirus.", "a": "playar"},
    {"q": "Tukul kuku kambing lazimnya digunakan untuk mengetuk paku dan mencabut ___ pada papan kayu.", "a": "paku"},
    {"q": "Bagi memotong lebihan bahan logam seperti kepingan zink dengan mudah, kita perlu menggunakan alat gunting ___?", "a": "logam"},
    {"q": "Gergaji puting mempunyai bilah yang lurus dan biasa digunakan untuk memotong kayu kecil secara garis ___?", "a": "lurus"},
    {"q": "Jika tali sawat terputus, pergerakan daripada enjin atau roda motor tidak akan dapat ___ ke takal yang lain.", "a": "bergerak"},
    {"q": "Sistem gear rak dan pinan lazimnya digunakan pada pergerakan enjin bermotor seperti sistem pintu pagar ___?", "a": "automatik"},
    {"q": "Mesin pengisar jus di dapur dapat memutarkan bilahnya menggunakan daya kuasa ___ elektrik.", "a": "motor"},
    {"q": "Pita pelekat dua muka (double-sided tape) digunakan untuk mencantumkan bahagian kotak projek supaya ia tercantum lebih ___?", "a": "kukuh"},
    {"q": "Apabila suis ditekan supaya tertutup, litar akan bersambung penuh dan membolehkan arus elektrik ___?", "a": "mengalir"},
    {"q": "Apabila suis dibuka, litar tersebut akan terputus dan keadaan ini menyebabkan lampu mentol ___?", "a": "padam"},
    {"q": "Komponen Diod Pemancar Cahaya (LED) boleh menyala dengan memancarkan cahaya yang amat ___?", "a": "terang"},
    {"q": "Proses mencantumkan sambungan wayar dan komponen pada papan litar dilakukan menggunakan alat pemanas logam iaitu alat ___?", "a": "pemateri"},
    {"q": "Bahan timah pateri yang dicairkan akan menyejuk dan mengeras untuk mengikat sambungan wayar litar dengan sangat ___?", "a": "kuat"},
    {"q": "Papan litar elektronik yang biasanya berwarna hijau dan mengandungi laluan cetakan tembaga dipanggil papan litar bercetak atau ___?", "a": "pcb"},
    {"q": "Bateri telefon pintar dan komputer riba biasanya menggunakan jenis litium-ion yang membolehkan ia dicas semula secara berkali-___?", "a": "kali"},
    {"q": "Kereta mainan kawalan jauh dapat bergerak dengan laju hasil daripada gabungan sistem kawalan elektrik dan pergerakan ___?", "a": "mekanikal"},
    {"q": "Pemilihan saiz gear motor yang lebih besar akan membolehkan roda putaran berputar dengan amat ___?", "a": "laju"},
    {"q": "Semasa merancang projek, idea rekaan awal hendaklah dilakar menggunakan pensel di atas helaian ___?", "a": "kertas"},
    {"q": "Projek palang tol yang memerlukan pergerakan bukaan pada darjah dan sudut tertentu sangat sesuai menggunakan putaran motor ___?", "a": "servo"},
    {"q": "Sistem takal dan tali sawat pada kren pembinaan direka khusus untuk memanjat dan mengangkat bahan binaan yang sangat ___?", "a": "berat"},
    {"q": "Penggunaan bahan guna semula seperti kotak dan botol terpakai dapat mengurangkan pembaziran dan menjimatkan kos ___ projek.", "a": "modal"},
    {"q": "Dalam reka bentuk badan kenderaan, bahagian bumbungnya perlu dipasang dengan rapat supaya air hujan tidak dapat ___ ke dalam.", "a": "masuk"},
    {"q": "Penggunaan cat semburan pelbagai warna pada fasa kemasan akan menjadikan reka bentuk luaran projek tampak lebih ___?", "a": "cantik"},
    {"q": "Setiap projek elektromekanikal yang telah siap pemasangannya mestilah dihidupkan untuk di___ kefungsiannya terlebih dahulu.", "a": "uji"},
    {"q": "Kerosakan litar pintas boleh berlaku dan merosakkan sistem sekiranya sambungan wayar kutub positif tersentuh wayar kutub ___?", "a": "negatif"},
    {"q": "Kerosakan akibat litar pintas boleh menyebabkan komponen terbakar, berasap, dan mengeluarkan bau yang sangat ___?", "a": "hangit"},
    {"q": "Kabel wayar penyambung litar yang berselirat perlu diikat, disusun, dan dibalut dengan pita penebat supaya kelihatan lebih ___?", "a": "kemas"},
    {"q": "Lakaran rajah litar dan komponen yang disediakan dalam manual pengguna berfungsi sebagai rujukan dan panduan ___ sesuatu projek.", "a": "pemasangan"},
    {"q": "Penciptaan robot elektromekanikal dalam sektor industri pembuatan sangat membantu bagi meringankan beban tugas tenaga dan otot ___?", "a": "manusia"},
    {"q": "Setiap hasil inovasi RBT dan projek binaan mekanikal yang dicipta oleh murid dengan titik peluh sendiri wajar dihormati dan di___?", "a": "hargai"}
],

"pengaturcaraan_t6": [
    {"q": "Papan litar elektronik yang berfungsi sebagai otak untuk mengawal pergerakan robot pintar dipanggil ___?", "a": "mikropengawal"},
    {"q": "Set arahan yang ditulis menggunakan blok kod komputer bagi menggerakkan perkakasan dipanggil sebagai sistem ___?", "a": "pengaturcaraan"},
    {"q": "Pergerakan robot beroda kebiasaannya digerakkan menggunakan kuasa daripada motor arus ___?", "a": "terus"},
    {"q": "Robot kereta dapat mengelak daripada melanggar halangan dan dinding dengan menggunakan penderia ___?", "a": "ultrasonik"},
    {"q": "Robot penjejak garisan membaca laluan berwarna gelap pada lantai menggunakan penderia ___?", "a": "inframerah"},
    {"q": "Komponen output elektronik yang berfungsi untuk mengeluarkan bunyi isyarat atau penggera dipanggil ___?", "a": "buzer"},
    {"q": "Komponen output berupa lampu kecil yang menyala dan memancarkan cahaya dipanggil sebagai ___?", "a": "led"},
    {"q": "Papan mikropengawal robot kebiasaannya dihidupkan menggunakan bekalan kuasa daripada bateri yang boleh di___?", "a": "cas"},
    {"q": "Blok kawalan (gelung) yang mengarahkan robot mengulang pergerakan tanpa henti dipanggil blok ___?", "a": "selamanya"},
    {"q": "Blok bersyarat seperti 'jika...maka' digunakan dalam pengaturcaraan komputer untuk menguji keputusan ___?", "a": "logik"},
    {"q": "Arahan kod yang digunakan untuk mematikan putaran motor tayar supaya robot tidak bergerak ialah fungsi ___?", "a": "berhenti"},
    {"q": "Apabila kedua-dua tayar robot berputar ke arah hadapan secara lurus, ia sedang melakukan pergerakan ___?", "a": "maju"},
    {"q": "Arahan kod untuk memutarkan tayar ke arah arah berlawanan akan membuatkan robot bergerak secara ___?", "a": "undur"},
    {"q": "Apabila satu tayar berputar dan satu tayar lagi berhenti, keadaan ini membolehkan robot mengubah arah atau ___?", "a": "belok"},
    {"q": "Proses memuat naik fail kod ke dalam papan mikropengawal perlu dilakukan menggunakan kabel ___?", "a": "usb"},
    {"q": "Kecacatan, kesilapan, atau ralat yang berlaku semasa penulisan kod arahan komputer dipanggil ___?", "a": "pepijat"},
    {"q": "Proses mengenal pasti dan membaiki ralat dalam sesuatu kod atur cara dikenali sebagai proses nyah___?", "a": "pepijat"},
    {"q": "Komponen cip yang berfungsi untuk mengawal kelajuan dan arah putaran motor tayar dipanggil litar ___?", "a": "pemacu"},
    {"q": "Jika kedua-dua motor tayar robot berputar ke arah hadapan secara serentak, robot akan bergerak ke ___?", "a": "depan"},
    {"q": "Jika tayar kiri berputar ke hadapan dan tayar kanan berhenti, robot akan membelok ke arah ___?", "a": "kanan"},
    {"q": "Penderia ultrasonik biasanya membaca dan mengukur jarak halangan di hadapannya dalam unit ukuran ___?", "a": "sentimeter"},
    {"q": "Penderia ultrasonik mengesan halangan dengan memantulkan gelombang bunyi gema apabila terkena pada sesuatu ___?", "a": "objek"},
    {"q": "Perintang Peka Cahaya (LDR) merupakan penderia yang amat peka terhadap perubahan darjah kecerahan sumber ___?", "a": "cahaya"},
    {"q": "Dalam melukis carta alir, simbol berbentuk bujur digunakan untuk mewakili proses mula dan ___?", "a": "tamat"},
    {"q": "Pseudokod ialah satu kaedah menulis langkah-langkah algoritma dan arahan dalam format struktur ___?", "a": "teks"},
    {"q": "Satu ruang memori khas di dalam atur cara yang menyimpan data untuk tujuan pengiraan dipanggil pemboleh ___?", "a": "ubah"},
    {"q": "Dalam perisian pengaturcaraan seperti mBlock, watak grafik yang dipaparkan pada skrin dipanggil ___?", "a": "sprite"},
    {"q": "Wayar penyambung (jumper) digunakan untuk menyambungkan komponen elektronik dengan komponen pada papan ___?", "a": "litar"},
    {"q": "Laluan yang membawa isyarat bacaan dari penderia masuk ke dalam papan mikropengawal dipanggil port ___?", "a": "input"},
    {"q": "Laluan yang menghantar isyarat arahan dari mikropengawal keluar ke arah motor atau buzer dipanggil port ___?", "a": "output"},
    {"q": "Teknik membina atur cara dengan menyusun blok kod menggunakan tetikus dikenali sebagai kaedah tarik dan ___?", "a": "lepas"},
    {"q": "Pintu cermin automatik di pasar raya boleh terbuka dan tertutup dengan menggunakan penderia kesan ___?", "a": "gerakan"},
    {"q": "Lampu jalan automatik akan dihidupkan dengan sendirinya apabila penderia mengesan suasana sudah menjadi ___?", "a": "gelap"},
    {"q": "Sistem siraman pokok automatik akan menyiram air berdasarkan bacaan penderia pada tahap kelembapan ___?", "a": "tanah"},
    {"q": "Apabila suis litar bateri ditekan kepada mod 'ON', sistem mikropengawal robot akan mula ___?", "a": "hidup"},
    {"q": "Robot yang telah siap dibina dan diprogramkan perlu diuji pergerakannya di atas permukaan lantai atau papan ___?", "a": "trek"},
    {"q": "Di kilang pembuatan kereta, proses memasang tayar dikendalikan oleh lengan mekanikal automatik atau dikenali sebagai ___?", "a": "robot"},
    {"q": "Sektor perindustrian menggunakan robot secara meluas kerana ia boleh melakukan kerja berat siang dan malam tanpa rasa ___?", "a": "penat"},
    {"q": "Struktur kawalan jujukan merupakan proses aliran atur cara yang melaksanakan arahan secara lurus dan berturutan mengikut ___?", "a": "langkah"},
    {"q": "Jika klip wayar disambung pada terminal litar dengan salah, litar pintas boleh berlaku dan papan mikropengawal akan ___?", "a": "rosak"},
    {"q": "Mesin pembersih hampagas automatik digunakan di rumah secara meluas untuk menyedut sisa kotoran dan ___?", "a": "habuk"},
    {"q": "Pertandingan cabaran robotik di sekolah melatih murid menguji kepantasan robot serta berlawan secara sihat sesama ___?", "a": "kawan"},
    {"q": "Fail projek atur cara yang telah siap dibina boleh dikongsi melalui ruang storan awan dengan menghantar pautan ___?", "a": "web"},
    {"q": "Individu profesional yang kerjayanya mereka bentuk dan menulis kod perisian pengaturcaraan dikenali sebagai jurutera ___?", "a": "komputer"},
    {"q": "Pembelajaran pengaturcaraan dapat menajamkan fikiran logik dan melatih murid untuk bijak menyelesaikan ___?", "a": "masalah"},
    {"q": "Penggunaan struktur kawalan gelung (looping) membolehkan satu atur cara berulang untuk menjimatkan penyusunan ___?", "a": "blok"},
    {"q": "Dalam binaan carta alir, simbol segi empat selari digunakan secara meluas untuk menunjukkan proses output atau data ___?", "a": "masuk"},
    {"q": "Bagi memudahkan kerja pengaturcaraan pada komputer tablet, murid boleh menaip dan memindahkan kod hanya dengan menyentuh ___?", "a": "skrin"},
    {"q": "Penggunaan ilmu robotik dan kecerdasan buatan (AI) di kilang-kilang membawa negara maju ke arah sistem ekonomi ___?", "a": "automatik"},
    {"q": "Bagi memastikan masa depan negara terus cemerlang, murid perlulah bijak IT dan menguasai kemahiran ilmu ___?", "a": "teknologi"}
],

"pembangunan_produk": [
    {"q": "Apakah istilah bagi sesuatu barangan yang dicipta dalam subjek RBT?", "a": "produk"},
    {"q": "Apakah proses menghasilkan sesuatu barangan binaan baharu untuk keperluan orang ramai?", "a": "pembangunan"},
    {"q": "Penghasilan produk yang mengandungi idea baharu dan unik dikenali sebagai ___?", "a": "inovasi"},
    {"q": "Apakah panggilannya bagi draf idea awal yang dilukis menggunakan pensel di atas kertas?", "a": "lakaran"},
    {"q": "Kita perlulah menilai dan memilih satu lukisan yang terbaik untuk dijadikan sebagai lakaran ___?", "a": "akhir"},
    {"q": "Proses mengubah suai produk lama supaya mempunyai fungsi yang lebih baik dinamakan ___?", "a": "penambahbaikan"},
    {"q": "Apakah alatan yang digunakan untuk mengukur dimensi panjang dan tinggi sesuatu bahan projek?", "a": "pembaris"},
    {"q": "Senarai peralatan dan perkakasan yang diperlukan untuk membuat projek dikenali sebagai bahan dan ___?", "a": "alatan"},
    {"q": "Jumlah keseluruhan modal wang ringgit yang dikeluarkan untuk menghasilkan sesuatu projek dipanggil ___?", "a": "kos"},
    {"q": "Bayaran wang untuk menghargai tenaga dan titik peluh pekerja dinamakan sebagai kos ___?", "a": "upah"},
    {"q": "Kos bagi bayaran bil elektrik, air, dan sewa kilang sepanjang pengurusan projek dipanggil kos ___?", "a": "overhed"},
    {"q": "Apabila kos bahan, kos upah, dan kos overhed dijumlahkan, kita akan mendapat kos ___?", "a": "pengeluaran"},
    {"q": "Apabila menjual barangan di pasaran, harga jualan mestilah dinaikkan sedikit untuk mendapatkan ___?", "a": "untung"},
    {"q": "Proses mencantum, memotong, dan membina bahan projek akan menghasilkan bentuk model ___?", "a": "sebenar"},
    {"q": "Proses mencantikkan dan melindungi produk dengan menggunakan kotak atau bekas dinamakan ___?", "a": "pembungkusan"},
    {"q": "Apakah kaedah yang digunakan untuk menyebarkan maklumat dan kelebihan produk kepada pembeli?", "a": "iklan"},
    {"q": "Mempromosikan produk melalui aktiviti berkongsi (share) dan menyukai (like) di aplikasi internet menggunakan platform ___?", "a": "sosial"},
    {"q": "Kertas helai bercetak yang mengandungi gambar dan maklumat produk untuk diedarkan dipanggil ___?", "a": "risalah"},
    {"q": "Aktiviti berdiri di hadapan kelas untuk menceritakan kelebihan produk yang dihasilkan dipanggil ___?", "a": "pembentangan"},
    {"q": "Penerangan produk yang jelas dan lancar akan membuatkan pelanggan berasa lebih ___?", "a": "yakin"},
    {"q": "Suis produk perlu dihidupkan semasa pengujian untuk memastikan komponennya tidak ___?", "a": "rosak"},
    {"q": "Bahagian kayu yang longgar atau patah boleh disambung semula dengan menggunakan ___?", "a": "panas"},
    {"q": "Aktiviti pemasaran dan perniagaan secara dalam talian (e-dagang) dijalankan melalui platform ___?", "a": "internet"},
    {"q": "Reka bentuk produk yang selamat memastikan tangan pengguna tidak mengalami sebarang ___?", "a": "luka"},
    {"q": "Kualiti produk yang baik memastikan strukturnya tahan lama dan sangat ___?", "a": "kukuh"},
    {"q": "Maklumat grafik pada kotak pembungkusan produk biasanya mengandungi harga dan nama ___?", "a": "jenama"},
    {"q": "Buku rekod kewangan digunakan untuk mencatat aliran wang keluar dan wang ___?", "a": "masuk"},
    {"q": "Untuk menyiapkan tugasan projek dengan jayanya, semua ahli kumpulan perlulah saling ___?", "a": "bekerjasama"},
    {"q": "Bahan terpakai seperti surat khabar dan botol plastik yang boleh digunakan semula dinamakan sisa ___?", "a": "kitar"},
    {"q": "Jadual kerja mingguan yang digunakan untuk merancang tempoh masa menyiapkan projek dipanggil Carta ___?", "a": "gantt"},
    {"q": "Penggunaan cat sembur atau varnis sebagai kemasan akhir akan menjadikan produk kelihatan ___?", "a": "cantik"},
    {"q": "Peniaga akan berasa gembira apabila barangan jualan mereka habis dengan cepat atau ___?", "a": "laris"},
    {"q": "Barangan yang berkualiti tinggi tetapi dijual pada harga yang berpatutan amat ___?", "a": "berbaloi"},
    {"q": "Bahan seperti reben, labuci, dan hiasan sulaman digunakan pada produk sebagai benda ___?", "a": "hiasan"},
    {"q": "Buku manual yang disediakan bersama produk berfungsi untuk mengajar pengguna tentang cara ___?", "a": "guna"},
    {"q": "Slip bercetak yang diberikan kepada pelanggan sebagai bukti pembayaran di kedai dipanggil bil ___?", "a": "jualan"},
    {"q": "Pendaftaran hak cipta logo atau reka bentuk produk dilakukan untuk mendapatkan cap ___?", "a": "paten"},
    {"q": "Kemahiran menguruskan perniagaan dan pasaran wang dapat mengasah bakat murid sebagai seorang ___?", "a": "usahawan"},
    {"q": "Sifat peniaga yang jujur, ikhlas, dan adil dalam urusan timbangan menunjukkan sikap ___?", "a": "amanah"},
    {"q": "Berani berpidato dan bercakap dengan jelas di hadapan orang ramai dapat memupuk sifat ___?", "a": "keyakinan"},
    {"q": "Kempen menjaga alam sekitar menggalakkan penggunaan beg mesra alam bagi menggantikan beg ___?", "a": "plastik"},
    {"q": "Keuntungan perniagaan perlulah dibahagikan secara adil bersama semua ahli di dalam ___?", "a": "kumpulan"},
    {"q": "Ujian kejatuhan dilakukan ke atas produk untuk memastikan strukturnya kuat dan tidak mudah ___?", "a": "pecah"},
    {"q": "Ilmu pengurusan kewangan yang dipelajari hari ini sangat penting untuk menjamin ekonomi masa ___?", "a": "depan"},
    {"q": "Pertandingan mencipta robot pintar merupakan peluang terbaik bagi murid menunjukkan daya ___?", "a": "bakat"},
    {"q": "Ulasan, kritikan, dan teguran membina daripada guru bertujuan untuk menjadikan idea kita lebih ___?", "a": "baik"},
    {"q": "Murid perlu menyiapkan tugasan projek ini dengan lengkap untuk lulus dalam subjek ___?", "a": "rbt"},
    {"q": "Mengkaji masalah yang dihadapi oleh pengguna akan membantu kita mencipta jalan penyelesaian yang ___?", "a": "baru"},
    {"q": "Apabila melayan soalan daripada pelanggan, kita perlulah bercakap dengan sopan sambil mengukir ___?", "a": "senyum"},
    {"q": "Kejayaan menghasilkan sesuatu produk adalah hasil daripada usaha kita yang ___?", "a": "gigih"}
]
};
