// ==========================================
// 1. MATHEMATICS QUESTION DATA (Part 1: 8 Categories)
// ==========================================
const mathData = {
    "number_recognition": [
        {"q": "What is the place value of 7 in 742?", "a": "hundreds"},
        {"q": "Write 5,042 in words.", "a": "five thousand and forty-two"},
        {"q": "Round off 184 to the nearest ten.", "a": "180"},
        {"q": "Partition 308 according to digit value.", "a": "300 + 8"},
        {"q": "What is the digit value of 4 in 4,120?", "a": "4000"},
        {"q": "What number comes before 3,000?", "a": "2999"},
        {"q": "Arrange in ascending order: 12, 5, 18, 10.", "a": "5, 10, 12, 18"},
        {"q": "Write 'seven thousand and eighty' in figures.", "a": "7080"},
        {"q": "Round off 92 to the nearest ten.", "a": "90"},
        {"q": "What is the place value of 0 in 5,042?", "a": "hundreds"},
        {"q": "What is the digit value of 9 in 9,500?", "a": "9000"},
        {"q": "Complete this: 400 + 50 + ___ = 452", "a": "2"},
        {"q": "Write 3,412 in words.", "a": "three thousand four hundred and twelve"},
        {"q": "Round off 1,245 to the nearest thousand.", "a": "1000"},
        {"q": "What number comes after 9,999?", "a": "10000"},
        {"q": "Partition 615 according to place value.", "a": "6 hundreds + 1 ten + 5 ones"},
        {"q": "Which is larger: 4,050 or 4,500?", "a": "4500"},
        {"q": "Write 8,004 in words.", "a": "eight thousand and four"},
        {"q": "What is the place value of 3 in 135?", "a": "tens"},
        {"q": "Round off 888 to the nearest hundred.", "a": "900"},
        {"q": "What is the digit value of 2 in 2,781?", "a": "2000"},
        {"q": "Write 'six hundred and fifteen' in figures.", "a": "615"},
        {"q": "Arrange in descending order: 100, 400, 200, 300.", "a": "400, 300, 200, 100"},
        {"q": "Partition 7,800 according to digit value.", "a": "7000 + 800"},
        {"q": "What is the even number between 11 and 13?", "a": "12"},
        {"q": "What is the place value of 5 in 5,123?", "a": "thousands"},
        {"q": "Round off 43 to the nearest ten.", "a": "40"},
        {"q": "Write 1,001 in words.", "a": "one thousand and one"},
        {"q": "What is the digit value of 7 in 370?", "a": "70"},
        {"q": "Complete this: 2,000 + ___ + 4 = 2,304", "a": "300"},
        {"q": "What is the odd number after 21?", "a": "23"},
        {"q": "Write 'two thousand four hundred and nine' in figures.", "a": "2409"},
        {"q": "Round off 7,500 to the nearest thousand.", "a": "8000"},
        {"q": "What is the place value of 9 in 1,009?", "a": "ones"},
        {"q": "Partition 555 according to digit value.", "a": "500 + 50 + 5"},
        {"q": "Write 4,820 in words.", "a": "four thousand eight hundred and twenty"},
        {"q": "Which is smaller: 1,201 or 1,102?", "a": "1102"},
        {"q": "What is the digit value of 1 in 1,999?", "a": "1000"},
        {"q": "Round off 19 to the nearest ten.", "a": "20"},
        {"q": "What number comes before 500?", "a": "499"},
        {"q": "Write 'nine hundred and one' in figures.", "a": "901"},
        {"q": "What is the place value of 4 in 45,120?", "a": "ten thousands"},
        {"q": "Partition 2,130 according to place value.", "a": "2 thousands + 1 hundred + 3 tens"},
        {"q": "What is the digit value of 8 in 182?", "a": "80"},
        {"q": "Write 5,555 in words.", "a": "five thousand five hundred and fifty-five"},
        {"q": "Round off 649 to the nearest hundred.", "a": "600"},
        {"q": "Complete the pattern: 2, 4, 6, ___", "a": "8"},
        {"q": "What number comes after 1,099?", "a": "1100"},
        {"q": "What is the place value of 6 in 3,678?", "a": "hundreds"},
        {"q": "Write 'one hundred and twenty-three' in figures.", "a": "123"}
    ],
    "addition_basic": [
        {"q": "15 + 15 = ?", "a": "30"},
        {"q": "20 + 80 = ?", "a": "100"},
        {"q": "120 + 30 = ?", "a": "150"},
        {"q": "45 + 5 = ?", "a": "50"},
        {"q": "500 + 500 = ?", "a": "1000"},
        {"q": "12 + 13 = ?", "a": "25"},
        {"q": "60 + 40 = ?", "a": "100"},
        {"q": "25 + 25 = ?", "a": "50"},
        {"q": "300 + 200 = ?", "a": "500"},
        {"q": "9 + 8 = ?", "a": "17"},
        {"q": "150 + 150 = ?", "a": "300"},
        {"q": "1,000 + 2,000 = ?", "a": "3000"},
        {"q": "44 + 11 = ?", "a": "55"},
        {"q": "70 + 20 = ?", "a": "90"},
        {"q": "55 + 45 = ?", "a": "100"},
        {"q": "800 + 100 = ?", "a": "900"},
        {"q": "19 + 2 = ?", "a": "21"},
        {"q": "250 + 50 = ?", "a": "300"},
        {"q": "3,000 + 4,000 = ?", "a": "7000"},
        {"q": "16 + 14 = ?", "a": "30"},
        {"q": "90 + 10 = ?", "a": "100"},
        {"q": "125 + 125 = ?", "a": "250"},
        {"q": "600 + 300 = ?", "a": "900"},
        {"q": "7 + 6 = ?", "a": "13"},
        {"q": "400 + 600 = ?", "a": "1000"},
        {"q": "2,500 + 2,500 = ?", "a": "5000"},
        {"q": "33 + 33 = ?", "a": "66"},
        {"q": "85 + 15 = ?", "a": "100"},
        {"q": "50 + 50 + 50 = ?", "a": "150"},
        {"q": "1,200 + 800 = ?", "a": "2000"},
        {"q": "18 + 18 = ?", "a": "36"},
        {"q": "75 + 25 = ?", "a": "100"},
        {"q": "1,000 + 9,000 = ?", "a": "10000"},
        {"q": "40 + 40 = ?", "a": "80"},
        {"q": "220 + 30 = ?", "a": "250"},
        {"q": "15 + 7 = ?", "a": "22"},
        {"q": "500 + 250 = ?", "a": "750"},
        {"q": "6,000 + 1,500 = ?", "a": "7500"},
        {"q": "35 + 15 = ?", "a": "50"},
        {"q": "110 + 90 = ?", "a": "200"},
        {"q": "14 + 14 = ?", "a": "28"},
        {"q": "2,200 + 300 = ?", "a": "2500"},
        {"q": "8 + 9 = ?", "a": "17"},
        {"q": "60 + 60 = ?", "a": "120"},
        {"q": "450 + 50 = ?", "a": "500"},
        {"q": "7,000 + 3,000 = ?", "a": "10000"},
        {"q": "21 + 21 = ?", "a": "42"},
        {"q": "95 + 5 = ?", "a": "100"},
        {"q": "130 + 70 = ?", "a": "200"},
        {"q": "10 + 20 + 30 = ?", "a": "60"}
    ],
    "subtraction_basic": [
        {"q": "20 - 5 = ?", "a": "15"},
        {"q": "50 - 10 = ?", "a": "40"},
        {"q": "100 - 50 = ?", "a": "50"},
        {"q": "80 - 20 = ?", "a": "60"},
        {"q": "1,000 - 500 = ?", "a": "500"},
        {"q": "15 - 8 = ?", "a": "7"},
        {"q": "45 - 15 = ?", "a": "30"},
        {"q": "300 - 100 = ?", "a": "200"},
        {"q": "90 - 45 = ?", "a": "45"},
        {"q": "10 - 7 = ?", "a": "3"},
        {"q": "200 - 150 = ?", "a": "50"},
        {"q": "5,000 - 2,000 = ?", "a": "3000"},
        {"q": "33 - 11 = ?", "a": "22"},
        {"q": "75 - 25 = ?", "a": "50"},
        {"q": "120 - 60 = ?", "a": "60"},
        {"q": "900 - 400 = ?", "a": "500"},
        {"q": "18 - 9 = ?", "a": "9"},
        {"q": "250 - 50 = ?", "a": "200"},
        {"q": "4,000 - 1,000 = ?", "a": "3000"},
        {"q": "60 - 30 = ?", "a": "30"},
        {"q": "100 - 1 = ?", "a": "99"},
        {"q": "500 - 250 = ?", "a": "250"},
        {"q": "800 - 700 = ?", "a": "100"},
        {"q": "12 - 4 = ?", "a": "8"},
        {"q": "1,000 - 100 = ?", "a": "900"},
        {"q": "3,500 - 500 = ?", "a": "3000"},
        {"q": "44 - 22 = ?", "a": "22"},
        {"q": "95 - 5 = ?", "a": "90"},
        {"q": "150 - 75 = ?", "a": "75"},
        {"q": "2,000 - 1 = ?", "a": "1999"},
        {"q": "17 - 8 = ?", "a": "9"},
        {"q": "80 - 40 = ?", "a": "40"},
        {"q": "1,000 - 999 = ?", "a": "1"},
        {"q": "66 - 33 = ?", "a": "33"},
        {"q": "210 - 10 = ?", "a": "200"},
        {"q": "14 - 7 = ?", "a": "7"},
        {"q": "600 - 300 = ?", "a": "300"},
        {"q": "7,500 - 2,500 = ?", "a": "5000"},
        {"q": "25 - 12 = ?", "a": "13"},
        {"q": "110 - 10 = ?", "a": "100"},
        {"q": "16 - 8 = ?", "a": "8"},
        {"q": "3,000 - 1,500 = ?", "a": "1500"},
        {"q": "9 - 5 = ?", "a": "4"},
        {"q": "40 - 4 = ?", "a": "36"},
        {"q": "450 - 50 = ?", "a": "400"},
        {"q": "10,000 - 5,000 = ?", "a": "5000"},
        {"q": "22 - 11 = ?", "a": "11"},
        {"q": "88 - 44 = ?", "a": "44"},
        {"q": "130 - 30 = ?", "a": "100"},
        {"q": "50 - 25 - 5 = ?", "a": "20"}
    ],
    "multiplication_table": [
        {"q": "2 x 2 = ?", "a": "4"},
        {"q": "3 x 3 = ?", "a": "9"},
        {"q": "4 x 4 = ?", "a": "16"},
        {"q": "5 x 5 = ?", "a": "25"},
        {"q": "6 x 6 = ?", "a": "36"},
        {"q": "7 x 7 = ?", "a": "49"},
        {"q": "8 x 8 = ?", "a": "64"},
        {"q": "9 x 9 = ?", "a": "81"},
        {"q": "10 x 10 = ?", "a": "100"},
        {"q": "2 x 8 = ?", "a": "16"},
        {"q": "3 x 7 = ?", "a": "21"},
        {"q": "4 x 6 = ?", "a": "24"},
        {"q": "5 x 9 = ?", "a": "45"},
        {"q": "11 x 2 = ?", "a": "22"},
        {"q": "12 x 3 = ?", "a": "36"},
        {"q": "6 x 2 = ?", "a": "12"},
        {"q": "7 x 3 = ?", "a": "21"},
        {"q": "8 x 4 = ?", "a": "32"},
        {"q": "9 x 5 = ?", "a": "45"},
        {"q": "10 x 5 = ?", "a": "50"},
        {"q": "2 x 9 = ?", "a": "18"},
        {"q": "3 x 8 = ?", "a": "24"},
        {"q": "4 x 7 = ?", "a": "28"},
        {"q": "5 x 6 = ?", "a": "30"},
        {"q": "11 x 11 = ?", "a": "121"},
        {"q": "12 x 12 = ?", "a": "144"},
        {"q": "6 x 8 = ?", "a": "48"},
        {"q": "7 x 5 = ?", "a": "35"},
        {"q": "8 x 3 = ?", "a": "24"},
        {"q": "9 x 4 = ?", "a": "36"},
        {"q": "2 x 7 = ?", "a": "14"},
        {"q": "3 x 6 = ?", "a": "18"},
        {"q": "4 x 5 = ?", "a": "20"},
        {"q": "5 x 4 = ?", "a": "20"},
        {"q": "1 x 100 = ?", "a": "100"},
        {"q": "0 x 50 = ?", "a": "0"},
        {"q": "6 x 7 = ?", "a": "42"},
        {"q": "7 x 8 = ?", "a": "56"},
        {"q": "8 x 9 = ?", "a": "72"},
        {"q": "9 x 3 = ?", "a": "27"},
        {"q": "10 x 8 = ?", "a": "80"},
        {"q": "11 x 3 = ?", "a": "33"},
        {"q": "12 x 5 = ?", "a": "60"},
        {"q": "6 x 9 = ?", "a": "54"},
        {"q": "7 x 4 = ?", "a": "28"},
        {"q": "8 x 5 = ?", "a": "40"},
        {"q": "9 x 2 = ?", "a": "18"},
        {"q": "10 x 3 = ?", "a": "30"},
        {"q": "11 x 5 = ?", "a": "55"},
        {"q": "12 x 2 = ?", "a": "24"}
    ],
    "division_basic": [
        {"q": "4 / 2 = ?", "a": "2"},
        {"q": "9 / 3 = ?", "a": "3"},
        {"q": "16 / 4 = ?", "a": "4"},
        {"q": "25 / 5 = ?", "a": "5"},
        {"q": "36 / 6 = ?", "a": "6"},
        {"q": "49 / 7 = ?", "a": "7"},
        {"q": "64 / 8 = ?", "a": "8"},
        {"q": "81 / 9 = ?", "a": "9"},
        {"q": "100 / 10 = ?", "a": "10"},
        {"q": "12 / 2 = ?", "a": "6"},
        {"q": "15 / 3 = ?", "a": "5"},
        {"q": "20 / 4 = ?", "a": "5"},
        {"q": "30 / 5 = ?", "a": "6"},
        {"q": "42 / 6 = ?", "a": "7"},
        {"q": "56 / 7 = ?", "a": "8"},
        {"q": "72 / 8 = ?", "a": "9"},
        {"q": "27 / 9 = ?", "a": "3"},
        {"q": "50 / 10 = ?", "a": "5"},
        {"q": "14 / 2 = ?", "a": "7"},
        {"q": "18 / 3 = ?", "a": "6"},
        {"q": "24 / 4 = ?", "a": "6"},
        {"q": "35 / 5 = ?", "a": "7"},
        {"q": "48 / 6 = ?", "a": "8"},
        {"q": "63 / 7 = ?", "a": "9"},
        {"q": "80 / 8 = ?", "a": "10"},
        {"q": "90 / 9 = ?", "a": "10"},
        {"q": "110 / 11 = ?", "a": "10"},
        {"q": "144 / 12 = ?", "a": "12"},
        {"q": "8 / 2 = ?", "a": "4"},
        {"q": "21 / 3 = ?", "a": "7"},
        {"q": "32 / 4 = ?", "a": "8"},
        {"q": "45 / 5 = ?", "a": "9"},
        {"q": "54 / 6 = ?", "a": "9"},
        {"q": "28 / 7 = ?", "a": "4"},
        {"q": "40 / 8 = ?", "a": "5"},
        {"q": "18 / 9 = ?", "a": "2"},
        {"q": "60 / 10 = ?", "a": "6"},
        {"q": "10 / 2 = ?", "a": "5"},
        {"q": "24 / 3 = ?", "a": "8"},
        {"q": "28 / 4 = ?", "a": "7"},
        {"q": "40 / 5 = ?", "a": "8"},
        {"q": "30 / 6 = ?", "a": "5"},
        {"q": "70 / 7 = ?", "a": "10"},
        {"q": "48 / 8 = ?", "a": "6"},
        {"q": "36 / 9 = ?", "a": "4"},
        {"q": "80 / 10 = ?", "a": "8"},
        {"q": "22 / 11 = ?", "a": "2"},
        {"q": "60 / 12 = ?", "a": "5"},
        {"q": "6 / 2 = ?", "a": "3"},
        {"q": "12 / 4 = ?", "a": "3"}
    ],
    "shapes_and_space": [
        {"q": "How many sides does a triangle have?", "a": "3"},
        {"q": "How many vertices does a cube have?", "a": "8"},
        {"q": "Name the 2D shape with 4 equal sides.", "a": "square"},
        {"q": "Which 3D shape has one apex and a circular base?", "a": "cone"},
        {"q": "How many flat surfaces does a cylinder have?", "a": "2"},
        {"q": "Name the shape with 5 sides.", "a": "pentagon"},
        {"q": "How many diagonals does a rectangle have?", "a": "2"},
        {"q": "Which 3D shape has no vertices and no flat surfaces?", "a": "sphere"},
        {"q": "How many sides does a hexagon have?", "a": "6"},
        {"q": "What is the shape of a die surface?", "a": "square"},
        {"q": "How many flat surfaces does a cuboid have?", "a": "6"},
        {"q": "Name the shape with 8 sides.", "a": "octagon"},
        {"q": "Does a circle have vertices?", "a": "none"},
        {"q": "How many edges does a cube have?", "a": "12"},
        {"q": "Name a 3D shape with a square base and 4 triangular faces.", "a": "pyramid"},
        {"q": "How many vertices does a cylinder have?", "a": "none"},
        {"q": "What is the shape of an orange?", "a": "sphere"},
        {"q": "How many sides does a heptagon have?", "a": "7"},
        {"q": "Name a shape with 2 parallel sides and 4 vertices.", "a": "trapezium"},
        {"q": "How many curved surfaces does a cone have?", "a": "1"},
        {"q": "Does a sphere have edges?", "a": "none"},
        {"q": "How many vertices does a triangle have?", "a": "3"},
        {"q": "What shape resembles a soda can?", "a": "cylinder"},
        {"q": "How many curved surfaces does a sphere have?", "a": "1"},
        {"q": "Name a 4-sided polygon where sides are not all equal.", "a": "rectangle"},
        {"q": "How many edges does a cuboid have?", "a": "12"},
        {"q": "What dimension is a pyramid?", "a": "3D"},
        {"q": "How many vertices does a pentagon have?", "a": "5"},
        {"q": "A shape with 10 sides is called?", "a": "decagon"},
        {"q": "How many flat surfaces does a cone have?", "a": "1"},
        {"q": "What is the shape of a coin's surface?", "a": "circle"},
        {"q": "How many edges does a cylinder have?", "a": "2"},
        {"q": "Name the 3D shape where all flat surfaces are the same size.", "a": "cube"},
        {"q": "How many vertices does a hexagon have?", "a": "6"},
        {"q": "What shape is a house roof often?", "a": "pyramid"},
        {"q": "How many sides does a circle have?", "a": "1"},
        {"q": "Does a cuboid have 8 vertices?", "a": "yes"},
        {"q": "Name a shape with one center and one circumference.", "a": "circle"},
        {"q": "How many flat surfaces does a square-based pyramid have?", "a": "5"},
        {"q": "How many vertices does a cone have?", "a": "1"},
        {"q": "What shape is a piece of A4 paper?", "a": "rectangle"},
        {"q": "How many edges does a sphere have?", "a": "none"},
        {"q": "Name a 3D shape with a uniform cross-section.", "a": "prism"},
        {"q": "How many sides does a rhombus have?", "a": "4"},
        {"q": "Does a cylinder have a curved surface?", "a": "yes"},
        {"q": "How many vertices does an octagon have?", "a": "8"},
        {"q": "What is the shape of an egg?", "a": "oval"},
        {"q": "How many flat surfaces does a triangular prism have?", "a": "5"},
        {"q": "Does a cube have 12 edges?", "a": "yes"},
        {"q": "Name the simplest polygon.", "a": "triangle"}
    ],
    "fractions_intro": [
        {"q": "1/2 + 1/2 = ?", "a": "1"},
        {"q": "Which is larger: 1/3 or 1/5?", "a": "1/3"},
        {"q": "Convert 0.25 to a fraction.", "a": "1/4"},
        {"q": "1/4 of 20 is?", "a": "5"},
        {"q": "Convert 1/2 to a percentage.", "a": "50%"},
        {"q": "Simplify 5/10.", "a": "1/2"},
        {"q": "1 - 1/4 = ?", "a": "3/4"},
        {"q": "2/5 + 1/5 = ?", "a": "3/5"},
        {"q": "Which is smaller: 2/3 or 1/3?", "a": "1/3"},
        {"q": "Convert 0.75 to a fraction.", "a": "3/4"},
        {"q": "1/2 of 100 = ?", "a": "50"},
        {"q": "Simplify 4/8.", "a": "1/2"},
        {"q": "3/4 - 1/4 = ?", "a": "2/4"},
        {"q": "Convert 1/5 to a decimal.", "a": "0.2"},
        {"q": "2/3 + 1/3 = ?", "a": "1"},
        {"q": "The fraction for a half is?", "a": "1/2"},
        {"q": "The fraction for a quarter is?", "a": "1/4"},
        {"q": "1/10 of 50 is?", "a": "5"},
        {"q": "Convert 0.1 to a fraction.", "a": "1/10"},
        {"q": "Which is larger: 1/2 or 3/4?", "a": "3/4"},
        {"q": "Simplify 2/6.", "a": "1/3"},
        {"q": "4/5 - 2/5 = ?", "a": "2/5"},
        {"q": "1/3 of 15 = ?", "a": "5"},
        {"q": "Convert 1/4 to a decimal.", "a": "0.25"},
        {"q": "Equivalent fraction for 1/2 is?", "a": "2/4"},
        {"q": "3/10 + 4/10 = ?", "a": "7/10"},
        {"q": "1/2 of 10 = ?", "a": "5"},
        {"q": "Simplify 3/9.", "a": "1/3"},
        {"q": "5/5 equals which whole number?", "a": "1"},
        {"q": "Convert 0.5 to a fraction.", "a": "1/2"},
        {"q": "Which is smaller: 1/10 or 1/2?", "a": "1/10"},
        {"q": "1/4 + 1/4 + 1/4 = ?", "a": "3/4"},
        {"q": "2/4 simplified becomes?", "a": "1/2"},
        {"q": "1/5 of 25 = ?", "a": "5"},
        {"q": "Convert 2/10 to a decimal.", "a": "0.2"},
        {"q": "The fraction for three quarters is?", "a": "3/4"},
        {"q": "6/8 simplified.", "a": "3/4"},
        {"q": "1 - 2/3 = ?", "a": "1/3"},
        {"q": "1/2 of RM10 = ?", "a": "RM5"},
        {"q": "Convert 0.4 to a fraction.", "a": "2/5"},
        {"q": "Which is larger: 4/5 or 1/5?", "a": "4/5"},
        {"q": "A fraction where the numerator is bigger than the denominator?", "a": "improper fraction"},
        {"q": "1/8 + 1/8 = ?", "a": "2/8"},
        {"q": "1/2 of 60 minutes = ?", "a": "30 minutes"},
        {"q": "Simplify 10/20.", "a": "1/2"},
        {"q": "3/5 of 10 = ?", "a": "6"},
        {"q": "Convert 1/100 to a decimal.", "a": "0.01"},
        {"q": "Improper fraction for 1.5 is?", "a": "3/2"},
        {"q": "7/9 - 4/9 = ?", "a": "3/9"},
        {"q": "Does 1/2 equal 0.5?", "a": "yes"}
    ],
    "decimal_basics": [
        {"q": "0.5 + 0.5 = ?", "a": "1.0"},
        {"q": "1.2 + 0.3 = ?", "a": "1.5"},
        {"q": "0.9 - 0.4 = ?", "a": "0.5"},
        {"q": "Convert 1/2 to decimal.", "a": "0.5"},
        {"q": "Write 0.05 in words.", "a": "zero point zero five"},
        {"q": "Which is larger: 0.1 or 0.09?", "a": "0.1"},
        {"q": "2.5 + 2.5 = ?", "a": "5.0"},
        {"q": "1.0 - 0.1 = ?", "a": "0.9"},
        {"q": "Convert 3/4 to decimal.", "a": "0.75"},
        {"q": "0.2 x 10 = ?", "a": "2"},
        {"q": "Write 'zero point eight' in figures.", "a": "0.8"},
        {"q": "4.5 - 2.0 = ?", "a": "2.5"},
        {"q": "0.15 + 0.05 = ?", "a": "0.2"},
        {"q": "Convert 1/10 to decimal.", "a": "0.1"},
        {"q": "Which is smaller: 0.5 or 0.25?", "a": "0.25"},
        {"q": "0.6 + 0.4 = ?", "a": "1.0"},
        {"q": "3.3 - 1.1 = ?", "a": "2.2"},
        {"q": "0.5 x 2 = ?", "a": "1.0"},
        {"q": "Convert 5/10 to decimal.", "a": "0.5"},
        {"q": "Write 1.25 in words.", "a": "one point two five"},
        {"q": "0.01 + 0.09 = ?", "a": "0.1"},
        {"q": "5.0 - 0.5 = ?", "a": "4.5"},
        {"q": "0.7 + 0.3 = ?", "a": "1.0"},
        {"q": "Convert 1/5 to decimal.", "a": "0.2"},
        {"q": "0.8 - 0.8 = ?", "a": "0"},
        {"q": "Which is larger: 0.75 or 0.8?", "a": "0.8"},
        {"q": "2.0 + 0.55 = ?", "a": "2.55"},
        {"q": "10.0 / 10 = ?", "a": "1.0"},
        {"q": "Convert 9/10 to decimal.", "a": "0.9"},
        {"q": "0.1 + 0.1 + 0.1 = ?", "a": "0.3"},
        {"q": "1.5 x 2 = ?", "a": "3.0"},
        {"q": "0.45 - 0.05 = ?", "a": "0.4"},
        {"q": "Write 'two point zero one' in figures.", "a": "2.01"},
        {"q": "Convert 25/100 to decimal.", "a": "0.25"},
        {"q": "0.2 + 0.8 = ?", "a": "1.0"},
        {"q": "5.5 - 5.4 = ?", "a": "0.1"},
        {"q": "Which is smaller: 0.12 or 0.21?", "a": "0.12"},
        {"q": "0.3 x 3 = ?", "a": "0.9"},
        {"q": "Convert 7/100 to decimal.", "a": "0.07"},
        {"q": "0.99 + 0.01 = ?", "a": "1.0"},
        {"q": "4.2 - 0.2 = ?", "a": "4.0"},
        {"q": "0.25 + 0.75 = ?", "a": "1.0"},
        {"q": "Convert 0.5 to percentage.", "a": "50%"},
        {"q": "Write 0.123 in words.", "a": "zero point one two three"},
        {"q": "1.1 + 1.1 = ?", "a": "2.2"},
        {"q": "0.8 - 0.2 = ?", "a": "0.6"},
        {"q": "0.05 + 0.05 = ?", "a": "0.1"},
        {"q": "Convert 1/8 to decimal.", "a": "0.125"},
        {"q": "3.0 - 1.5 = ?", "a": "1.5"},
        {"q": "Does 0.1 equal 0.10?", "a": "yes"}
    ],
"percentage_fun": [
        {"q": "What is 50% of 100?", "a": "50"},
        {"q": "What is 10% of 80?", "a": "8"},
        {"q": "Convert 1/4 to percentage.", "a": "25%"},
        {"q": "What is 100% of 55?", "a": "55"},
        {"q": "What is 25% of 20?", "a": "5"},
        {"q": "Convert 0.5 to percentage.", "a": "50%"},
        {"q": "What is 20% of 50?", "a": "10"},
        {"q": "What is 75% of 100?", "a": "75"},
        {"q": "Convert 1/10 to percentage.", "a": "10%"},
        {"q": "What is 50% of 10?", "a": "5"},
        {"q": "What is 10% of 200?", "a": "20"},
        {"q": "Convert 1/2 to percentage.", "a": "50%"},
        {"q": "What is 5% of 100?", "a": "5"},
        {"q": "What is 200% of 10?", "a": "20"},
        {"q": "Convert 0.15 to percentage.", "a": "15%"},
        {"q": "What is 50% of 44?", "a": "22"},
        {"q": "What is 10% of 1,000?", "a": "100"},
        {"q": "Convert 3/4 to percentage.", "a": "75%"},
        {"q": "What is 25% of 40?", "a": "10"},
        {"q": "What is 30% of 100?", "a": "30"},
        {"q": "Convert 1/5 to percentage.", "a": "20%"},
        {"q": "What is 50% of 250?", "a": "125"},
        {"q": "What is 10% of 5?", "a": "0.5"},
        {"q": "Convert 0.01 to percentage.", "a": "1%"},
        {"q": "What is 40% of 50?", "a": "20"},
        {"q": "What is 100% of 1,000?", "a": "1000"},
        {"q": "Convert 2/5 to percentage.", "a": "40%"},
        {"q": "What is 50% of 1?", "a": "0.5"},
        {"q": "What is 15% of 100?", "a": "15"},
        {"q": "Convert 1/1 to percentage.", "a": "100%"},
        {"q": "What is 25% of 100?", "a": "25"},
        {"q": "What is 10% of 90?", "a": "9"},
        {"q": "Convert 0.8 to percentage.", "a": "80%"},
        {"q": "What is 50% of 80?", "a": "40"},
        {"q": "What is 20% of 20?", "a": "4"},
        {"q": "Convert 4/5 to percentage.", "a": "80%"},
        {"q": "What is 5% of 20?", "a": "1"},
        {"q": "What is 10% of 150?", "a": "15"},
        {"q": "Convert 0.25 to percentage.", "a": "25%"},
        {"q": "What is 50% of 16?", "a": "8"},
        {"q": "What is 30% of 200?", "a": "60"},
        {"q": "Convert 0.7 to percentage.", "a": "70%"},
        {"q": "What is 25% of 8?", "a": "2"},
        {"q": "What is 10% of 120?", "a": "12"},
        {"q": "Convert 1/20 to percentage.", "a": "5%"},
        {"q": "What is 50% of 300?", "a": "150"},
        {"q": "What is 60% of 100?", "a": "60"},
        {"q": "Convert 0.99 to percentage.", "a": "99%"},
        {"q": "What is 50% of 1,000?", "a": "500"},
        {"q": "Is 50% equal to 0.5?", "a": "yes"}
    ],
    "money_matters": [
        {"q": "RM5 + RM2 = ?", "a": "RM7"},
        {"q": "RM10 - RM4 = ?", "a": "RM6"},
        {"q": "How many 50 sen coins in RM1?", "a": "2"},
        {"q": "RM1.50 + 50 sen = ?", "a": "RM2.00"},
        {"q": "RM20 / 4 = ?", "a": "RM5"},
        {"q": "RM3 x 5 = ?", "a": "RM15"},
        {"q": "How many 20 sen coins in RM1?", "a": "5"},
        {"q": "RM50 - RM15 = ?", "a": "RM35"},
        {"q": "10 sen + 20 sen + 50 sen = ?", "a": "80 sen"},
        {"q": "RM100 - RM1 = ?", "a": "RM99"},
        {"q": "RM2.50 + RM2.50 = ?", "a": "RM5.00"},
        {"q": "How many RM5 notes in RM50?", "a": "10"},
        {"q": "RM0.80 - RM0.30 = ?", "a": "RM0.50"},
        {"q": "RM10 / 2 = ?", "a": "RM5"},
        {"q": "RM12 + RM8 = ?", "a": "RM20"},
        {"q": "How many 10 sen coins in RM1?", "a": "10"},
        {"q": "RM4.00 x 2 = ?", "a": "RM8.00"},
        {"q": "RM5.50 - 50 sen = ?", "a": "RM5.00"},
        {"q": "RM100 / 10 = ?", "a": "RM10"},
        {"q": "RM7 + RM3 + RM5 = ?", "a": "RM15"},
        {"q": "How many RM10 notes in RM100?", "a": "10"},
        {"q": "RM0.45 + RM0.05 = ?", "a": "RM0.50"},
        {"q": "RM25 - RM5 = ?", "a": "RM20"},
        {"q": "RM2.00 / 4 = ?", "a": "50 sen"},
        {"q": "RM15 x 2 = ?", "a": "RM30"},
        {"q": "How many RM1 notes in RM50?", "a": "50"},
        {"q": "RM60 + RM40 = ?", "a": "RM100"},
        {"q": "RM1.20 - 40 sen = ?", "a": "80 sen"},
        {"q": "RM10 x 10 = ?", "a": "RM100"},
        {"q": "RM5.00 / 10 = ?", "a": "50 sen"},
        {"q": "How many 5 sen coins in 50 sen?", "a": "10"},
        {"q": "RM3.50 + RM1.50 = ?", "a": "RM5.00"},
        {"q": "RM80 - RM20 - RM10 = ?", "a": "RM50"},
        {"q": "RM0.90 x 2 = ?", "a": "RM1.80"},
        {"q": "RM1,000 / 2 = ?", "a": "RM500"},
        {"q": "How many RM2 notes in RM20?", "a": "10"},
        {"q": "RM45 + RM5 = ?", "a": "RM50"},
        {"q": "RM10 - 20 sen = ?", "a": "RM9.80"},
        {"q": "RM0.05 + RM0.05 = ?", "a": "RM0.10"},
        {"q": "RM6 x 3 = ?", "a": "RM18"},
        {"q": "How many RM50 notes in RM200?", "a": "4"},
        {"q": "RM1.10 + 90 sen = ?", "a": "RM2.00"},
        {"q": "RM50 - RM49.50 = ?", "a": "50 sen"},
        {"q": "RM100 / 4 = ?", "a": "RM25"},
        {"q": "RM2.20 x 2 = ?", "a": "RM4.40"},
        {"q": "How many 20 sen coins in RM2?", "a": "10"},
        {"q": "RM12 + RM12 = ?", "a": "RM24"},
        {"q": "RM5 - RM2.20 = ?", "a": "RM2.80"},
        {"q": "RM0.25 x 4 = ?", "a": "RM1.00"},
        {"q": "Is RM1 equal to 100 sen?", "a": "yes"}
    ],
    "time_and_clock": [
        {"q": "How many minutes in 1 hour?", "a": "60"},
        {"q": "How many seconds in 1 minute?", "a": "60"},
        {"q": "How many hours in 1 day?", "a": "24"},
        {"q": "How many days in 1 week?", "a": "7"},
        {"q": "How many months in 1 year?", "a": "12"},
        {"q": "Half an hour = ___ minutes?", "a": "30"},
        {"q": "Quarter of an hour = ___ minutes?", "a": "15"},
        {"q": "What is 12:00 in the afternoon called?", "a": "noon"},
        {"q": "What is 12:00 at night called?", "a": "midnight"},
        {"q": "How many days in January?", "a": "31"},
        {"q": "How many weeks in 1 year?", "a": "52"},
        {"q": "Convert 2 hours to minutes.", "a": "120"},
        {"q": "What comes after Monday?", "a": "Tuesday"},
        {"q": "What comes before June?", "a": "May"},
        {"q": "How many days in February (Normal Year)?", "a": "28"},
        {"q": "1:30 PM in 24-hour format?", "a": "13:30"},
        {"q": "How many hours from 9 AM to 11 AM?", "a": "2"},
        {"q": "How many minutes in 2 hours?", "a": "120"},
        {"q": "How many seconds in 2 minutes?", "a": "120"},
        {"q": "How many hours in 2 days?", "a": "48"},
        {"q": "Which is longer: 65 minutes or 1 hour?", "a": "65 minutes"},
        {"q": "How many days in a Leap Year?", "a": "366"},
        {"q": "How many months in 2 years?", "a": "24"},
        {"q": "3:00 PM in 24-hour format?", "a": "15:00"},
        {"q": "How many minutes from 1:15 to 1:45?", "a": "30"},
        {"q": "How many days in December?", "a": "31"},
        {"q": "What is the 5th month of the year?", "a": "May"},
        {"q": "Convert 3 minutes to seconds.", "a": "180"},
        {"q": "10:00 PM in 24-hour format?", "a": "22:00"},
        {"q": "How many minutes in 3 hours?", "a": "180"},
        {"q": "What day is 2 days after Friday?", "a": "Sunday"},
        {"q": "How many hours in half a day?", "a": "12"},
        {"q": "How many minutes in a quarter hour?", "a": "15"},
        {"q": "Convert 1 hour 10 minutes to minutes.", "a": "70"},
        {"q": "What is the last month of the year?", "a": "December"},
        {"q": "How many days in April?", "a": "30"},
        {"q": "How many months have 31 days?", "a": "7"},
        {"q": "Convert 120 seconds to minutes.", "a": "2"},
        {"q": "What time is 1 hour after 11:30 PM?", "a": "12:30 AM"},
        {"q": "How many years in a decade?", "a": "10"},
        {"q": "How many years in a century?", "a": "100"},
        {"q": "Convert 48 hours to days.", "a": "2"},
        {"q": "What month comes after August?", "a": "September"},
        {"q": "How many days in a fortnight?", "a": "14"},
        {"q": "How many minutes between 8:00 and 8:15?", "a": "15"},
        {"q": "Convert 300 seconds to minutes.", "a": "5"},
        {"q": "What is 00:00 in 12-hour format?", "a": "12:00 AM"},
        {"q": "How many seasons are there (Standard)?", "a": "4"},
        {"q": "Is 1 hour equal to 3,600 seconds?", "a": "yes"},
        {"q": "How many hours from midnight to noon?", "a": "12"}
    ],
    "length_and_mass": [
        {"q": "1 kg = ___ g?", "a": "1000"},
        {"q": "1 m = ___ cm?", "a": "100"},
        {"q": "1 km = ___ m?", "a": "1000"},
        {"q": "1 cm = ___ mm?", "a": "10"},
        {"q": "How many grams in 2 kg?", "a": "2000"},
        {"q": "How many centimeters in 5 m?", "a": "500"},
        {"q": "Convert 1,000 m to km.", "a": "1"},
        {"q": "Which is heavier: 1 kg or 500 g?", "a": "1 kg"},
        {"q": "Which is longer: 1 m or 120 cm?", "a": "120 cm"},
        {"q": "Half a kilogram = ___ g?", "a": "500"},
        {"q": "Convert 30 mm to cm.", "a": "3"},
        {"q": "How many meters in 3 km?", "a": "3000"},
        {"q": "250 g + 250 g = ?", "a": "500 g"},
        {"q": "1 m - 20 cm = ?", "a": "80 cm"},
        {"q": "How many grams in 1/4 kg?", "a": "250"},
        {"q": "Convert 500 cm to m.", "a": "5"},
        {"q": "Convert 2,500 g to kg.", "a": "2.5"},
        {"q": "Add: 1.5 kg + 0.5 kg = ?", "a": "2 kg"},
        {"q": "10 cm x 5 = ?", "a": "50 cm"},
        {"q": "Convert 7 km to m.", "a": "7000"},
        {"q": "Which is shorter: 10 mm or 2 cm?", "a": "10 mm"},
        {"q": "1 kg - 300 g = ?", "a": "700 g"},
        {"q": "How many mm in 5 cm?", "a": "50"},
        {"q": "Convert 0.5 m to cm.", "a": "50"},
        {"q": "How many grams in 10 kg?", "a": "10000"},
        {"q": "2 m + 3 m = ?", "a": "5 m"},
        {"q": "Convert 450 cm to m.", "a": "4.5"},
        {"q": "1 kg / 2 = ?", "a": "500 g"},
        {"q": "100 m x 10 = ?", "a": "1 km"},
        {"q": "Convert 8,000 g to kg.", "a": "8"},
        {"q": "Which is lighter: 2 kg or 2,500 g?", "a": "2 kg"},
        {"q": "How many centimeters in 0.1 m?", "a": "10"},
        {"q": "1.2 kg = ___ g?", "a": "1200"},
        {"q": "300 m + 700 m = ?", "a": "1 km"},
        {"q": "Convert 15 cm to mm.", "a": "150"},
        {"q": "How many kg in 5,000 g?", "a": "5"},
        {"q": "2.5 m = ___ cm?", "a": "250"},
        {"q": "1 kg - 1 g = ?", "a": "999 g"},
        {"q": "How many meters in 0.5 km?", "a": "500"},
        {"q": "Convert 20 mm to cm.", "a": "2"},
        {"q": "500 g x 4 = ?", "a": "2 kg"},
        {"q": "How many cm in 10 m?", "a": "1000"},
        {"q": "Convert 1.5 km to m.", "a": "1500"},
        {"q": "10 kg - 5.5 kg = ?", "a": "4.5 kg"},
        {"q": "How many mm in 1 m?", "a": "1000"},
        {"q": "Convert 0.75 kg to g.", "a": "750"},
        {"q": "5 m / 2 = ?", "a": "2.5 m"},
        {"q": "1 km - 500 m = ?", "a": "500 m"},
        {"q": "Is 100 cm equal to 1,000 mm?", "a": "yes"},
        {"q": "How many g in 0.1 kg?", "a": "100"}
    ],
    "volume_of_liquid": [
        {"q": "1 L = ___ mL?", "a": "1000"},
        {"q": "How many mL in 2 L?", "a": "2000"},
        {"q": "Convert 5,000 mL to L.", "a": "5"},
        {"q": "Half a liter = ___ mL?", "a": "500"},
        {"q": "500 mL + 500 mL = ?", "a": "1 L"},
        {"q": "1 L - 200 mL = ?", "a": "800 mL"},
        {"q": "Convert 2.5 L to mL.", "a": "2500"},
        {"q": "How many mL in 1/4 L?", "a": "250"},
        {"q": "Which is more: 1 L or 900 mL?", "a": "1 L"},
        {"q": "Convert 750 mL to L.", "a": "0.75"},
        {"q": "10 L / 2 = ?", "a": "5 L"},
        {"q": "250 mL x 4 = ?", "a": "1 L"},
        {"q": "Convert 10,000 mL to L.", "a": "10"},
        {"q": "How many L in 3,000 mL?", "a": "3"},
        {"q": "1.5 L = ___ mL?", "a": "1500"},
        {"q": "200 mL + 300 mL = ?", "a": "500 mL"},
        {"q": "Convert 0.5 L to mL.", "a": "500"},
        {"q": "Which is less: 2 L or 2,500 mL?", "a": "2 L"},
        {"q": "How many mL in 0.1 L?", "a": "100"},
        {"q": "1 L - 1 mL = ?", "a": "999 mL"},
        {"q": "3 L + 4 L = ?", "a": "7 L"},
        {"q": "Convert 1,200 mL to L.", "a": "1.2"},
        {"q": "How many 250 mL cups in 1 L?", "a": "4"},
        {"q": "10 L - 3.5 L = ?", "a": "6.5 L"},
        {"q": "Convert 0.25 L to mL.", "a": "250"},
        {"q": "How many L in 500 mL?", "a": "0.5"},
        {"q": "5 L x 3 = ?", "a": "15 L"},
        {"q": "Convert 4,500 mL to L.", "a": "4.5"},
        {"q": "100 mL x 10 = ?", "a": "1 L"},
        {"q": "Convert 0.7 L to mL.", "a": "700"},
        {"q": "How many mL in 0.05 L?", "a": "50"},
        {"q": "2.5 L + 2.5 L = ?", "a": "5 L"},
        {"q": "Convert 6,000 mL to L.", "a": "6"},
        {"q": "Which is more: 500 mL or 0.4 L?", "a": "500 mL"},
        {"q": "1 L / 4 = ?", "a": "250 mL"},
        {"q": "Convert 1.1 L to mL.", "a": "1100"},
        {"q": "10 L - 1 L = ?", "a": "9 L"},
        {"q": "How many mL in 10 L?", "a": "10000"},
        {"q": "Convert 800 mL to L.", "a": "0.8"},
        {"q": "300 mL x 2 = ?", "a": "600 mL"},
        {"q": "Convert 0.2 L to mL.", "a": "200"},
        {"q": "How many L in 250 mL?", "a": "0.25"},
        {"q": "1.8 L = ___ mL?", "a": "1800"},
        {"q": "500 mL / 2 = ?", "a": "250 mL"},
        {"q": "Convert 20,000 mL to L.", "a": "20"},
        {"q": "1 L + 2 L + 3 L = ?", "a": "6 L"},
        {"q": "How many mL in 0.001 L?", "a": "1"},
        {"q": "Convert 350 mL to L.", "a": "0.35"},
        {"q": "Is 1,000 mL equal to 1 L?", "a": "yes"},
        {"q": "How many mL in 0.45 L?", "a": "450"}
    ],
    "area_and_perimeter": [
        {"q": "Perimeter of a square with side 5cm?", "a": "20cm"},
        {"q": "Area of a square with side 4cm?", "a": "16cm2"},
        {"q": "Perimeter of a rectangle (5cm x 2cm)?", "a": "14cm"},
        {"q": "Area of a rectangle (6cm x 3cm)?", "a": "18cm2"},
        {"q": "Perimeter of a triangle with sides 3, 4, 5cm?", "a": "12cm"},
        {"q": "Area of a square with side 10cm?", "a": "100cm2"},
        {"q": "Perimeter of a square with side 2cm?", "a": "8cm"},
        {"q": "Area of a rectangle (10cm x 5cm)?", "a": "50cm2"},
        {"q": "Perimeter of a rectangle (10cm x 1cm)?", "a": "22cm"},
        {"q": "Area of a square with side 1cm?", "a": "1cm2"},
        {"q": "Perimeter of a square with side 6cm?", "a": "24cm"},
        {"q": "Area of a square with side 5cm?", "a": "25cm2"},
        {"q": "Perimeter of a rectangle (4cm x 4cm)?", "a": "16cm"},
        {"q": "Area of a rectangle (2cm x 8cm)?", "a": "16cm2"},
        {"q": "Perimeter of an equilateral triangle with side 10cm?", "a": "30cm"},
        {"q": "Area of a square with side 3cm?", "a": "9cm2"},
        {"q": "Perimeter of a square with side 1cm?", "a": "4cm"},
        {"q": "Area of a rectangle (7cm x 2cm)?", "a": "14cm2"},
        {"q": "Perimeter of a rectangle (8cm x 3cm)?", "a": "22cm"},
        {"q": "Area of a square with side 2cm?", "a": "4cm2"},
        {"q": "Perimeter of a square with side 8cm?", "a": "32cm"},
        {"q": "Area of a rectangle (12cm x 2cm)?", "a": "24cm2"},
        {"q": "Perimeter of a rectangle (20cm x 5cm)?", "a": "50cm"},
        {"q": "Area of a square with side 9cm?", "a": "81cm2"},
        {"q": "Perimeter of a square with side 100cm?", "a": "400cm"},
        {"q": "Area of a square with side 8cm?", "a": "64cm2"},
        {"q": "Perimeter of a rectangle (15cm x 10cm)?", "a": "50cm"},
        {"q": "Area of a rectangle (1cm x 100cm)?", "a": "100cm2"},
        {"q": "Perimeter of a square with side 3cm?", "a": "12cm"},
        {"q": "Area of a square with side 7cm?", "a": "49cm2"},
        {"q": "Perimeter of a rectangle (12cm x 3cm)?", "a": "30cm"},
        {"q": "Area of a rectangle (5cm x 4cm)?", "a": "20cm2"},
        {"q": "Perimeter of a square with side 4cm?", "a": "16cm"},
        {"q": "Area of a square with side 6cm?", "a": "36cm2"},
        {"q": "Perimeter of a rectangle (100cm x 1cm)?", "a": "202cm"},
        {"q": "Area of a rectangle (11cm x 3cm)?", "a": "33cm2"},
        {"q": "Perimeter of a square with side 7cm?", "a": "28cm"},
        {"q": "Area of a square with side 11cm?", "a": "121cm2"},
        {"q": "Perimeter of a rectangle (2cm x 2cm)?", "a": "8cm"},
        {"q": "Area of a rectangle (9cm x 2cm)?", "a": "18cm2"},
        {"q": "Perimeter of a square with side 12cm?", "a": "48cm"},
        {"q": "Area of a square with side 12cm?", "a": "144cm2"},
        {"q": "Perimeter of a rectangle (6cm x 6cm)?", "a": "24cm"},
        {"q": "Area of a rectangle (3cm x 4cm)?", "a": "12cm2"},
        {"q": "Perimeter of a square with side 9cm?", "a": "36cm"},
        {"q": "Area of a square with side 20cm?", "a": "400cm2"},
        {"q": "Perimeter of a rectangle (7cm x 3cm)?", "a": "20cm"},
        {"q": "Area of a rectangle (10cm x 10cm)?", "a": "100cm2"},
        {"q": "Perimeter of an equilateral triangle with side 5cm?", "a": "15cm"},
        {"q": "If perimeter of a square is 20cm, what is the side?", "a": "5cm"}
    ],
    "data_handling": [
        {"q": "If 1 picture represents 2 people, how many people in 3 pictures?", "a": "6"},
        {"q": "What is the mode of: 2, 3, 3, 4?", "a": "3"},
        {"q": "What is the range of 10 and 2?", "a": "8"},
        {"q": "Find the average of 4 and 6.", "a": "5"},
        {"q": "If 5 like apples and 3 like oranges, how many total people?", "a": "8"},
        {"q": "What is the median of 1, 3, 5?", "a": "3"},
        {"q": "If 1 star = 10 marks, 5 stars = ___ marks?", "a": "50"},
        {"q": "Mode of 1, 1, 2, 2, 2, 3?", "a": "2"},
        {"q": "Range of 15, 20, 25?", "a": "10"},
        {"q": "Average of 10, 20, 30?", "a": "20"},
        {"q": "If 1 circle = 5 balls, 10 circles = ___ balls?", "a": "50"},
        {"q": "What is the maximum value in: 4, 8, 2, 10?", "a": "10"},
        {"q": "What is the minimum value in: 15, 3, 7, 20?", "a": "3"},
        {"q": "Mode of 5, 6, 5, 7, 5?", "a": "5"},
        {"q": "Average of 1, 2, 3?", "a": "2"},
        {"q": "If 1 icon = 100 people, 4 icons = ___ people?", "a": "400"},
        {"q": "Range of 50 and 100?", "a": "50"},
        {"q": "Find the average of 5 and 15.", "a": "10"},
        {"q": "Mode of Red, Blue, Red, Green?", "a": "Red"},
        {"q": "If 1 book icon = 2 books, how many icons for 10 books?", "a": "5"},
        {"q": "Median of 2, 4, 6, 8, 10?", "a": "6"},
        {"q": "What is the difference between 90 and 40?", "a": "50"},
        {"q": "Total of 12, 13, and 5?", "a": "30"},
        {"q": "Average of 100 and 200?", "a": "150"},
        {"q": "If 1 sun = 1 day, 7 suns = ___ days?", "a": "7"},
        {"q": "Mode of 10, 20, 10, 30, 10?", "a": "10"},
        {"q": "Range of 1 and 10?", "a": "9"},
        {"q": "Minimum of 44, 22, 33?", "a": "22"},
        {"q": "Maximum of 100, 500, 200?", "a": "500"},
        {"q": "If 1 stick = 5 points, 6 sticks = ___ points?", "a": "30"},
        {"q": "Average of 4, 4, 4?", "a": "4"},
        {"q": "Mode of 0, 1, 0, 2, 0?", "a": "0"},
        {"q": "Range of 12 and 18?", "a": "6"},
        {"q": "Median of 7, 8, 9?", "a": "8"},
        {"q": "Total of 25, 25, 25, 25?", "a": "100"},
        {"q": "If 1 face = 10 kids, 2.5 faces = ___ kids?", "a": "25"},
        {"q": "Average of 50 and 60?", "a": "55"},
        {"q": "Mode of 9, 8, 9, 7?", "a": "9"},
        {"q": "Maximum of 1, 2, 3, 4, 5?", "a": "5"},
        {"q": "Difference between Max (10) and Min (1)?", "a": "9"},
        {"q": "If 10 people voted A and 15 voted B, how many more for B?", "a": "5"},
        {"q": "Average of 0 and 10?", "a": "5"},
        {"q": "Mode of 100, 100, 200?", "a": "100"},
        {"q": "Range of 30, 35, 40?", "a": "10"},
        {"q": "If 1 box = 12 eggs, 2 boxes = ___ eggs?", "a": "24"},
        {"q": "Median of 10, 20, 30?", "a": "20"},
        {"q": "Total of 1, 2, 3, 4?", "a": "10"},
        {"q": "If 50 people like cat, 30 like dog, total?", "a": "80"},
        {"q": "Average of 2, 4, 6, 8?", "a": "5"},
        {"q": "Is 'Average' the same as 'Mean'?", "a": "yes"}
    ],
    "math_logic": [
        {"q": "If today is Monday, what is the day after tomorrow?", "a": "Wednesday"},
        {"q": "Next number in pattern: 2, 4, 6, 8, ___?", "a": "10"},
        {"q": "Next number in pattern: 10, 20, 30, ___?", "a": "40"},
        {"q": "Abu has 5 apples, gives 2 to Siti, how many left?", "a": "3"},
        {"q": "A car has 4 wheels, how many wheels on 3 cars?", "a": "12"},
        {"q": "If you have 2 pairs of shoes, how many shoes in total?", "a": "4"},
        {"q": "Pattern: 1, 3, 5, 7, ___?", "a": "9"},
        {"q": "Next number: 5, 10, 15, 20, ___?", "a": "25"},
        {"q": "If 1 cat has 4 legs, how many legs do 5 cats have?", "a": "20"},
        {"q": "What is half of 50?", "a": "25"},
        {"q": "What is double of 15?", "a": "30"},
        {"q": "Pattern: 100, 90, 80, ___?", "a": "70"},
        {"q": "If tomorrow is Sunday, what day is today?", "a": "Saturday"},
        {"q": "A bird has 2 legs, how many legs on 10 birds?", "a": "20"},
        {"q": "If you have RM10 and spend RM3, how much left?", "a": "RM7"},
        {"q": "Pattern: 2, 4, 8, 16, ___?", "a": "32"},
        {"q": "What is 10 more than 85?", "a": "95"},
        {"q": "What is 5 less than 100?", "a": "95"},
        {"q": "If 1 week has 7 days, how many days in 2 weeks?", "a": "14"},
        {"q": "Next number: 1, 4, 7, 10, ___?", "a": "13"},
        {"q": "If you are 10 years old, how old were you 3 years ago?", "a": "7"},
        {"q": "A triangle has 3 sides, how many sides in 4 triangles?", "a": "12"},
        {"q": "What is the sum of the first three numbers (1, 2, 3)?", "a": "6"},
        {"q": "If you have 3 pockets and 2 coins in each, total coins?", "a": "6"},
        {"q": "Pattern: 11, 22, 33, ___?", "a": "44"},
        {"q": "How many fingers on 4 hands?", "a": "20"},
        {"q": "If you double 50, you get?", "a": "100"},
        {"q": "What is the difference between 50 and 15?", "a": "35"},
        {"q": "Next number: 90, 80, 70, 60, ___?", "a": "50"},
        {"q": "If 1 hand has 5 fingers, how many fingers on 10 hands?", "a": "50"},
        {"q": "What is 1,000 minus 1?", "a": "999"},
        {"q": "If you share 12 sweets between 2 kids, each gets?", "a": "6"},
        {"q": "How many months in half a year?", "a": "6"},
        {"q": "Pattern: 5, 15, 25, ___?", "a": "35"},
        {"q": "If today is Friday, what was yesterday?", "a": "Thursday"},
        {"q": "What is the smallest 2-digit number?", "a": "10"},
        {"q": "What is the largest 2-digit number?", "a": "99"},
        {"q": "If a dozen is 12, how many is half a dozen?", "a": "6"},
        {"q": "Next number: 3, 6, 9, 12, ___?", "a": "15"},
        {"q": "How many hours in 1 hour and 30 minutes?", "a": "1.5"},
        {"q": "If you have 4 groups of 5 students, total students?", "a": "20"},
        {"q": "What is 100 divided by 2?", "a": "50"},
        {"q": "Pattern: 2, 5, 8, 11, ___?", "a": "14"},
        {"q": "If 3 people have 2 legs each, total legs?", "a": "6"},
        {"q": "What is 7 times 3 plus 1?", "a": "22"},
        {"q": "How many days in 3 weeks?", "a": "21"},
        {"q": "If you are the 3rd person in a line of 10, how many behind you?", "a": "7"},
        {"q": "What is 1/2 of 1/2?", "a": "1/4"},
        {"q": "Next number: 1, 2, 4, 7, 11, ___?", "a": "16"},
        {"q": "Is 0 an even number?", "a": "yes"}
    ]
};