// ==========================================
// 1. SCIENCE QUESTION DATA (16 Categories)
// ==========================================
const scienceData = {
    "scientific_skills": [
        {"q": "Using senses to gather information about objects or phenomena?", "a": "observing"},
        {"q": "The tool used to measure the length of a book?", "a": "ruler"},
        {"q": "The sense used to smell a flower?", "a": "smell"},
        {"q": "The sense used to taste an orange?", "a": "taste"},
        {"q": "The sense used to hear a bell?", "a": "hearing"},
        {"q": "The sense used to see the color of a leaf?", "a": "sight"},
        {"q": "The sense used to feel if an object is hot?", "a": "touch"},
        {"q": "Giving an early explanation for an observation?", "a": "inference"},
        {"q": "Making an expectation about what will happen next?", "a": "predicting"},
        {"q": "Grouping objects based on similar characteristics?", "a": "classifying"},
        {"q": "The standard unit for measuring temperature?", "a": "degree celsius"},
        {"q": "A tool used to measure temperature?", "a": "thermometer"},
        {"q": "A tool used to measure time accurately in a race?", "a": "stopwatch"},
        {"q": "The standard unit for a short duration of time?", "a": "second"},
        {"q": "A tool used to measure the mass of an object?", "a": "weighing scale"},
        {"q": "The standard unit for heavy mass?", "a": "kilogram"},
        {"q": "A tool used to measure the volume of a liquid?", "a": "measuring cylinder"},
        {"q": "The standard unit for liquid volume?", "a": "millilitre"},
        {"q": "The variable that is changed in an experiment?", "a": "manipulated variable"},
        {"q": "The variable that is observed or measured?", "a": "responding variable"},
        {"q": "The variable that is kept the same?", "a": "constant variable"},
        {"q": "A testable statement about the relationship between variables?", "a": "hypothesis"},
        {"q": "Tool used to see very tiny objects like bacteria?", "a": "microscope"},
        {"q": "Tool used to see very distant objects in space?", "a": "telescope"},
        {"q": "Recording and sharing data in tables or charts?", "a": "communicating"},
        {"q": "One way to communicate scientific data visually?", "a": "graph"},
        {"q": "Tool used to clean a test tube?", "a": "test tube brush"},
        {"q": "Where should liquid chemical waste be disposed?", "a": "sink"},
        {"q": "Where should solid waste be disposed in the lab?", "a": "dustbin"},
        {"q": "What should students do before entering the science room?", "a": "line up"},
        {"q": "What activity is strictly forbidden in the science room?", "a": "eating"},
        {"q": "Who should you report an accident to immediately?", "a": "teacher"},
        {"q": "A tool used to put out small fires?", "a": "fire extinguisher"},
        {"q": "Representing a specimen accurately through a drawing?", "a": "scientific drawing"},
        {"q": "The unit for measuring area?", "a": "square centimetre"},
        {"q": "The correct eye level when reading a liquid scale?", "a": "meniscus level"},
        {"q": "Using a hand lens makes a specimen look?", "a": "bigger"},
        {"q": "Live specimens should be returned to their?", "a": "original habitat"},
        {"q": "The skill of handling science equipment correctly?", "a": "manipulative skills"},
        {"q": "Arranging data from the smallest value to the largest?", "a": "ascending order"},
        {"q": "The main purpose of an experiment is to test a?", "a": "hypothesis"},
        {"q": "A summary of the results is called a?", "a": "conclusion"},
        {"q": "Tool used to measure the girth of a tree?", "a": "measuring tape"},
        {"q": "Unit for measuring a very short length?", "a": "millimetre"},
        {"q": "Anything that can be measured and changed in an experiment?", "a": "variable"},
        {"q": "Measuring the change in litmus paper color is a skill of?", "a": "observing"},
        {"q": "The trait of a scientist who always wants to find out more?", "a": "curiosity"},
        {"q": "A science room must have good airflow or?", "a": "ventilation"},
        {"q": "The first step in a scientific investigation?", "a": "identifying the problem"},
        {"q": "An ancient tool used to measure time?", "a": "hourglass"}
    ],
"human_life_processes": [
        {"q": "The main organ used for breathing is?", "a": "lungs"},
        {"q": "The gas we inhale during breathing is?", "a": "oxygen"},
        {"q": "The gas we exhale during breathing is?", "a": "carbon dioxide"},
        {"q": "The path of air during inhalation?", "a": "nose, trachea, lungs"},
        {"q": "The path of air during exhalation?", "a": "lungs, trachea, nose"},
        {"q": "Small air sacs in the lungs for gas exchange?", "a": "alveoli"},
        {"q": "Chest movement during inhalation?", "a": "upwards and outwards"},
        {"q": "Chest movement during exhalation?", "a": "downwards and inwards"},
        {"q": "The breathing rate when we are sleeping is?", "a": "low"},
        {"q": "The breathing rate when we are running is?", "a": "high"},
        {"q": "The process of removing waste from the body?", "a": "excretion"},
        {"q": "The process of removing undigested food?", "a": "defecation"},
        {"q": "The organ that excretes urine?", "a": "kidneys"},
        {"q": "The organ that excretes sweat?", "a": "skin"},
        {"q": "The organ that excretes carbon dioxide?", "a": "lungs"},
        {"q": "The liquid waste product of the kidneys?", "a": "urine"},
        {"q": "The waste product released through the skin?", "a": "sweat"},
        {"q": "Waste products released by the lungs?", "a": "carbon dioxide and water vapor"},
        {"q": "Why is excretion important to humans?", "a": "to stay healthy"},
        {"q": "The body's reaction to a change in surroundings?", "a": "response to stimuli"},
        {"q": "Closing eyes when bright light shines is a response to?", "a": "light"},
        {"q": "Shivering when it is very cold is a response to?", "a": "temperature"},
        {"q": "Pulling your hand away from a hot stove is a response to?", "a": "heat"},
        {"q": "The sense organ used for hearing sound stimuli?", "a": "ears"},
        {"q": "The sense organ used for tasting food?", "a": "tongue"},
        {"q": "The sense organ used for smelling?", "a": "nose"},
        {"q": "The sense organ used for touch and temperature?", "a": "skin"},
        {"q": "Humans reproduce by which method?", "a": "giving birth"},
        {"q": "Passing characteristics from parents to offspring?", "a": "inheritance"},
        {"q": "An example of a physical trait inherited from parents?", "a": "hair type"},
        {"q": "Another example of an inherited characteristic?", "a": "skin color"},
        {"q": "Inherited color of the eye is called?", "a": "iris color"},
        {"q": "Harmful substance found in cigarettes?", "a": "nicotine"},
        {"q": "A habit that seriously damages the lungs?", "a": "smoking"},
        {"q": "A substance that slows down response to stimuli?", "a": "alcohol"},
        {"q": "Substances that cause hallucinations and loss of coordination?", "a": "drugs"},
        {"q": "The muscle that helps in the breathing process?", "a": "diaphragm"},
        {"q": "The bones that protect the heart and lungs?", "a": "rib cage"},
        {"q": "Difficulty in passing out feces is called?", "a": "constipation"},
        {"q": "To prevent constipation, we must eat enough?", "a": "fiber"},
        {"q": "The gas required by body cells to stay alive?", "a": "oxygen"},
        {"q": "The temporary storage for urine in the body?", "a": "urinary bladder"},
        {"q": "Undigested food waste is known as?", "a": "feces"},
        {"q": "Is height an inherited characteristic?", "a": "yes"},
        {"q": "Can a scar from an injury be inherited?", "a": "no"},
        {"q": "The human life cycle begins from a?", "a": "baby"},
        {"q": "Jumping when hearing a loud thunder is a response to?", "a": "sound"},
        {"q": "Breathing rate is measured as breaths per?", "a": "minute"},
        {"q": "The windpipe that connects the nose to the lungs?", "a": "trachea"},
        {"q": "The process of making new individuals?", "a": "reproduction"}
    ],
"animal_classification": [
        {"q": "Animals with a backbone are called?", "a": "vertebrates"},
        {"q": "Animals without a backbone are called?", "a": "invertebrates"},
        {"q": "The breathing organ of a fish is?", "a": "gills"},
        {"q": "The breathing organ of a grasshopper is?", "a": "spiracles"},
        {"q": "The breathing organ of a worm is?", "a": "moist skin"},
        {"q": "The breathing organ of a cat is?", "a": "lungs"},
        {"q": "Animals that live both on land and in water are?", "a": "amphibians"},
        {"q": "The breathing organ of a frog in water is?", "a": "moist skin"},
        {"q": "The breathing organ of a frog on land is?", "a": "lungs"},
        {"q": "Animals that eat only plants are called?", "a": "herbivores"},
        {"q": "Animals that eat only other animals are called?", "a": "carnivores"},
        {"q": "Animals that eat both plants and animals are called?", "a": "omnivores"},
        {"q": "Is a cow a herbivore, carnivore, or omnivore?", "a": "herbivore"},
        {"q": "Is a tiger a herbivore, carnivore, or omnivore?", "a": "carnivore"},
        {"q": "Is a chicken a herbivore, carnivore, or omnivore?", "a": "omnivore"},
        {"q": "Animals that give birth to their young are?", "a": "mammals"},
        {"q": "Animals that lay eggs and have feathers are?", "a": "birds"},
        {"q": "Animals with dry scales that lay eggs are?", "a": "reptiles"},
        {"q": "A whale breathes through its?", "a": "lungs"},
        {"q": "A dolphin is classified as a?", "a": "mammal"},
        {"q": "A platypus is a unique mammal because it?", "a": "lays eggs"},
        {"q": "Insects have how many legs?", "a": "six"},
        {"q": "A spider is an invertebrate because it has no?", "a": "backbone"},
        {"q": "Which group of vertebrates are warm-blooded and have fur?", "a": "mammals"},
        {"q": "The breathing organ of a shrimp is?", "a": "gills"},
        {"q": "A butterfly breathes through?", "a": "spiracles"},
        {"q": "An example of a reptile that lives in water is a?", "a": "turtle"},
        {"q": "Birds breathe using their?", "a": "lungs"},
        {"q": "Is a crocodile a vertebrate or invertebrate?", "a": "vertebrate"},
        {"q": "A penguin is classified as a?", "a": "bird"},
        {"q": "The hard outer covering of an insect is an?", "a": "exoskeleton"},
        {"q": "An animal that produces milk for its young is a?", "a": "mammal"},
        {"q": "Salamanders and newts are examples of?", "a": "amphibians"},
        {"q": "A snail is an example of an?", "a": "invertebrate"},
        {"q": "Does a snake have a backbone?", "a": "yes"},
        {"q": "Animals that hunt other animals for food are?", "a": "predators"},
        {"q": "Animals that are hunted and eaten are?", "a": "prey"},
        {"q": "A bat is the only mammal that can?", "a": "fly"},
        {"q": "Is an eagle a carnivore?", "a": "yes"},
        {"q": "Do all mammals live on land?", "a": "no"},
        {"q": "Is a shark a mammal or a fish?", "a": "fish"},
        {"q": "Invertebrates like crabs have a hard?", "a": "shell"},
        {"q": "Which organ do tadpoles use to breathe?", "a": "gills"},
        {"q": "A lizard is classified as a?", "a": "reptile"},
        {"q": "The group of animals that feed their young with milk?", "a": "mammals"},
        {"q": "Are most insects vertebrates or invertebrates?", "a": "invertebrates"},
        {"q": "A dragonfly is an example of an?", "a": "insect"},
        {"q": "The breathing organ of a caterpillar is?", "a": "spiracles"},
        {"q": "Is a bear an omnivore?", "a": "yes"},
        {"q": "An animal with a streamlined body for swimming is a?", "a": "fish"}
    ],
"plant_processes": [
        {"q": "The process by which plants make their own food?", "a": "photosynthesis"},
        {"q": "The green pigment found in leaves is called?", "a": "chlorophyll"},
        {"q": "The gas absorbed by plants for photosynthesis?", "a": "carbon dioxide"},
        {"q": "The gas released by plants during photosynthesis?", "a": "oxygen"},
        {"q": "The main source of energy for photosynthesis?", "a": "sunlight"},
        {"q": "What do plants absorb from the soil for photosynthesis?", "a": "water"},
        {"q": "The food produced by photosynthesis is stored as?", "a": "starch"},
        {"q": "Which part of the plant usually carries out photosynthesis?", "a": "leaves"},
        {"q": "Plant shoots grow towards which stimulus?", "a": "light"},
        {"q": "Plant roots grow towards which stimulus?", "a": "water"},
        {"q": "Plant roots also respond to the downward pull of?", "a": "gravity"},
        {"q": "Mimosa pudica (touch-me-not) leaves fold inward when?", "a": "touched"},
        {"q": "Venus flytrap leaves snap shut in response to?", "a": "touch"},
        {"q": "Where is starch usually stored in a potato plant?", "a": "underground stem"},
        {"q": "Tiny pores on the surface of leaves are called?", "a": "stomata"},
        {"q": "How do non-flowering plants like ferns reproduce?", "a": "spores"},
        {"q": "How do banana plants reproduce?", "a": "suckers"},
        {"q": "How do hibiscus plants usually reproduce?", "a": "stem cutting"},
        {"q": "How do mushrooms reproduce?", "a": "spores"},
        {"q": "How do onions reproduce?", "a": "underground stems"},
        {"q": "The process of scattering seeds away from the parent plant?", "a": "seed dispersal"},
        {"q": "Seeds dispersed by wind are usually light and have?", "a": "wings"},
        {"q": "An example of a seed dispersed by wind?", "a": "dandelion"},
        {"q": "Seeds dispersed by water have a husk that is?", "a": "spongy"},
        {"q": "An example of a fruit dispersed by water?", "a": "coconut"},
        {"q": "Fruits dispersed by animals are usually brightly colored and?", "a": "fleshy"},
        {"q": "Seeds dispersed by an explosive mechanism will?", "a": "burst"},
        {"q": "An example of a seed dispersed by an explosive mechanism?", "a": "rubber seed"},
        {"q": "Why must seeds be dispersed far away?", "a": "to reduce competition"},
        {"q": "What characteristic helps a cactus store water in the desert?", "a": "fleshy stem"},
        {"q": "Why do some plants shed their leaves in the dry season?", "a": "to reduce water loss"},
        {"q": "An example of a plant that sheds its leaves during dry seasons?", "a": "rubber tree"},
        {"q": "Needle-like leaves help pine trees reduce?", "a": "water loss"},
        {"q": "What protects a rose plant from enemies?", "a": "thorns"},
        {"q": "What protects a papaya tree from insects?", "a": "latex"},
        {"q": "What protects bamboo from enemies?", "a": "fine hairs"},
        {"q": "Fine hairs on bamboo stems can cause?", "a": "itchiness"},
        {"q": "What protects a rafflesia flower from being eaten by herbivores?", "a": "bad smell"},
        {"q": "Some plants like the pong-pong tree protect themselves by being?", "a": "poisonous"},
        {"q": "Does a mushroom make its own food?", "a": "no"},
        {"q": "Do all plants produce flowers?", "a": "no"},
        {"q": "What part of the plant holds it firmly in the ground?", "a": "roots"},
        {"q": "The tube that transports water from roots to leaves?", "a": "xylem"},
        {"q": "The tube that transports food from leaves to other parts?", "a": "phloem"},
        {"q": "What characteristic helps a lotus float on water?", "a": "air spaces in stem"},
        {"q": "How do morning glory plants get enough sunlight?", "a": "climbing stems"},
        {"q": "What protects a pineapple plant from being eaten?", "a": "sharp leaves"},
        {"q": "Plants are known as what in a food chain?", "a": "producers"},
        {"q": "Does a plant need oxygen to survive?", "a": "yes"},
        {"q": "What do seeds need to germinate? Water, air, and?", "a": "warmth"}
    ],
"energy_forms": [
        {"q": "What is the primary source of energy on Earth?", "a": "Sun"},
        {"q": "Energy possessed by a moving object is called?", "a": "kinetic energy"},
        {"q": "Energy stored in food, wood, or batteries is called?", "a": "chemical energy"},
        {"q": "Energy that we can see is called?", "a": "light energy"},
        {"q": "Energy produced by vibrating objects is called?", "a": "sound energy"},
        {"q": "Energy that makes us feel warm is called?", "a": "heat energy"},
        {"q": "Energy stored in a stretched rubber band or lifted object?", "a": "potential energy"},
        {"q": "Energy flowing through electrical wires is called?", "a": "electrical energy"},
        {"q": "Energy generated from the splitting of atoms?", "a": "nuclear energy"},
        {"q": "Is energy from the Sun renewable or non-renewable?", "a": "renewable"},
        {"q": "Are fossil fuels renewable or non-renewable?", "a": "non-renewable"},
        {"q": "An example of a fossil fuel extracted from the ground?", "a": "petroleum"},
        {"q": "Energy source from plant and animal waste is called?", "a": "biomass"},
        {"q": "Electricity generated from moving water is called?", "a": "hydroelectric"},
        {"q": "Principle: Energy cannot be created or?", "a": "destroyed"},
        {"q": "In a battery, chemical energy changes to?", "a": "electrical energy"},
        {"q": "In a light bulb, electrical energy changes to light and?", "a": "heat energy"},
        {"q": "In a radio, electrical energy changes to?", "a": "sound energy"},
        {"q": "A solar panel changes solar energy to?", "a": "electrical energy"},
        {"q": "When you rub your hands together, kinetic energy changes to?", "a": "heat energy"},
        {"q": "A television converts electrical energy into sound and?", "a": "light energy"},
        {"q": "An electric iron converts electrical energy into?", "a": "heat energy"},
        {"q": "A falling apple changes potential energy into?", "a": "kinetic energy"},
        {"q": "During photosynthesis, solar energy changes into?", "a": "chemical energy"},
        {"q": "Energy that can be replenished constantly is called?", "a": "renewable energy"},
        {"q": "Energy that will run out and cannot be replaced quickly?", "a": "non-renewable energy"},
        {"q": "Wind turbines use what type of energy source?", "a": "wind"},
        {"q": "Is coal a renewable energy source?", "a": "no"},
        {"q": "Is ocean wave a renewable energy source?", "a": "yes"},
        {"q": "Energy obtained from hot rocks deep underground is?", "a": "geothermal energy"},
        {"q": "Switching off lights when leaving a room helps to?", "a": "save energy"},
        {"q": "Carpooling helps to save which energy source?", "a": "fossil fuels"},
        {"q": "Food provides humans with what type of energy?", "a": "chemical energy"},
        {"q": "When a bow is pulled back, it gains?", "a": "potential energy"},
        {"q": "The faster a car moves, the more ___ it has.", "a": "kinetic energy"},
        {"q": "A ringing school bell produces what type of energy?", "a": "sound energy"},
        {"q": "A lit candle converts chemical energy into light and?", "a": "heat energy"},
        {"q": "A moving bicycle has what type of energy?", "a": "kinetic energy"},
        {"q": "A laptop runs on what type of energy?", "a": "electrical energy"},
        {"q": "The energy stored in fossil fuels originally came from the?", "a": "Sun"},
        {"q": "Riding a bicycle instead of driving helps save?", "a": "fuel"},
        {"q": "Solar panels are usually placed on the?", "a": "roof"},
        {"q": "Do plants use kinetic energy to make food?", "a": "no"},
        {"q": "The main form of energy you get from sitting near a campfire?", "a": "heat energy"},
        {"q": "A book resting high up on a shelf has?", "a": "potential energy"},
        {"q": "A washing machine converts electrical energy mainly into?", "a": "kinetic energy"},
        {"q": "An electric toaster converts electrical energy into?", "a": "heat energy"},
        {"q": "Are natural gas reserves limitless?", "a": "no"},
        {"q": "Using energy wisely ensures we have enough for the?", "a": "future"},
        {"q": "Batteries store energy in what form?", "a": "chemical energy"}
    ],
"light_properties": [
        {"q": "How does light travel?", "a": "straight line"},
        {"q": "The bouncing of light off a surface is called?", "a": "reflection"},
        {"q": "The bending of light as it moves between different materials?", "a": "refraction"},
        {"q": "An object that allows all light to pass through it?", "a": "transparent"},
        {"q": "An object that allows only some light to pass through it?", "a": "translucent"},
        {"q": "An object that does not allow any light to pass through it?", "a": "opaque"},
        {"q": "Is clear glass transparent, translucent, or opaque?", "a": "transparent"},
        {"q": "Is wood transparent, translucent, or opaque?", "a": "opaque"},
        {"q": "Is frosted glass transparent, translucent, or opaque?", "a": "translucent"},
        {"q": "A dark area formed when light is blocked by an object?", "a": "shadow"},
        {"q": "If an object is moved closer to the light source, the shadow becomes?", "a": "bigger"},
        {"q": "If the screen is moved further from the object, the shadow becomes?", "a": "bigger"},
        {"q": "Shadows are formed because light travels in a?", "a": "straight line"},
        {"q": "A tool that uses reflection to see behind or around corners?", "a": "periscope"},
        {"q": "A surface that reflects light well is usually smooth and?", "a": "shiny"},
        {"q": "An example of an object that reflects light is a?", "a": "mirror"},
        {"q": "A pencil looks bent in a glass of water due to?", "a": "refraction"},
        {"q": "The size of a pool looks shallower than it is due to?", "a": "refraction"},
        {"q": "A tool used to see tiny objects by refracting light?", "a": "microscope"},
        {"q": "A tool used to see distant stars through refraction or reflection?", "a": "telescope"},
        {"q": "A glass object that separates white light into seven colors?", "a": "prism"},
        {"q": "The seven colors of light are seen in a?", "a": "rainbow"},
        {"q": "The first color in a rainbow is?", "a": "red"},
        {"q": "A mirror with a flat surface is called a?", "a": "plane mirror"},
        {"q": "A mirror that curves outwards is a?", "a": "convex mirror"},
        {"q": "A mirror that curves inwards is a?", "a": "concave mirror"},
        {"q": "Side mirrors of a car are usually?", "a": "convex mirrors"},
        {"q": "Security mirrors in shops are usually?", "a": "convex mirrors"},
        {"q": "Dentists use this type of mirror to see teeth clearly?", "a": "concave mirror"},
        {"q": "Does a shadow have colors?", "a": "no"},
        {"q": "When light hits a mirror, it is?", "a": "reflected"},
        {"q": "What happens to light when it enters a prism?", "a": "refraction"},
        {"q": "Can light pass through a brick wall?", "a": "no"},
        {"q": "Is water a transparent material?", "a": "yes"},
        {"q": "Is a shadow always the same shape as the object?", "a": "yes"},
        {"q": "What is the natural source of light for Earth?", "a": "sun"},
        {"q": "Lenses in spectacles work based on light?", "a": "refraction"},
        {"q": "A magnifying glass uses which property of light?", "a": "refraction"},
        {"q": "Light travels faster in air than in?", "a": "water"},
        {"q": "A periscope contains two?", "a": "mirrors"},
        {"q": "Can we see objects in a completely dark room?", "a": "no"},
        {"q": "To see an object, light must be ___ into our eyes.", "a": "reflected"},
        {"q": "Does air allow light to pass through?", "a": "yes"},
        {"q": "A shadow is shortest when the sun is?", "a": "overhead"},
        {"q": "Shadows are longest during sunrise and?", "a": "sunset"},
        {"q": "The image in a plane mirror is always the same ___ as the object.", "a": "size"},
        {"q": "Is clear plastic a transparent material?", "a": "yes"},
        {"q": "Refraction happens because the ___ of light changes.", "a": "speed"},
        {"q": "A rainbow is formed when sunlight is refracted by?", "a": "raindrops"},
        {"q": "Can a shadow be formed by a transparent object?", "a": "no"}
    ],
"electricity_basics": [
        {"q": "What provides electrical energy in a simple circuit?", "a": "dry cell"},
        {"q": "What converts electrical energy into light energy in a circuit?", "a": "bulb"},
        {"q": "The component used to connect all parts of a circuit?", "a": "connecting wires"},
        {"q": "The component used to complete or break a circuit?", "a": "switch"},
        {"q": "A circuit where electricity can flow through is called a?", "a": "complete circuit"},
        {"q": "A circuit where the path of electricity is broken?", "a": "incomplete circuit"},
        {"q": "If the switch is open, will the bulb light up?", "a": "no"},
        {"q": "If the switch is closed, will the bulb light up?", "a": "yes"},
        {"q": "A circuit with only one path for electricity to flow?", "a": "series circuit"},
        {"q": "A circuit with more than one path for electricity to flow?", "a": "parallel circuit"},
        {"q": "In which circuit do bulbs share the same path?", "a": "series circuit"},
        {"q": "In which circuit is each bulb on a different branch?", "a": "parallel circuit"},
        {"q": "Adding more dry cells in a series circuit makes the bulb?", "a": "brighter"},
        {"q": "Adding more bulbs in a series circuit makes the bulbs?", "a": "dimmer"},
        {"q": "Which type of circuit is used in most houses?", "a": "parallel circuit"},
        {"q": "If one bulb blows in a series circuit, do others stay lit?", "a": "no"},
        {"q": "If one bulb blows in a parallel circuit, do others stay lit?", "a": "yes"},
        {"q": "The positive and negative symbols on a dry cell represent?", "a": "terminals"},
        {"q": "Materials that allow electricity to flow through them?", "a": "conductors"},
        {"q": "Materials that do not allow electricity to flow through them?", "a": "insulators"},
        {"q": "Is a metal spoon a conductor or an insulator?", "a": "conductor"},
        {"q": "Is a plastic ruler a conductor or an insulator?", "a": "insulator"},
        {"q": "Is copper wire an insulator?", "a": "no"},
        {"q": "Is rubber an insulator?", "a": "yes"},
        {"q": "Why are wires covered with plastic?", "a": "insulation"},
        {"q": "What happens if you touch a switch with wet hands?", "a": "electric shock"},
        {"q": "Is water a conductor of electricity?", "a": "yes"},
        {"q": "A safety device that breaks the circuit when current is too high?", "a": "fuse"},
        {"q": "Which component is represented by a long and short line in a diagram?", "a": "dry cell"},
        {"q": "The flow of electricity is also known as electrical?", "a": "current"},
        {"q": "Do bulbs in a parallel circuit have the same brightness?", "a": "yes"},
        {"q": "Can a dry cell store energy forever?", "a": "no"},
        {"q": "What energy is stored inside a dry cell?", "a": "chemical energy"},
        {"q": "Using many appliances on one socket can cause a?", "a": "short circuit"},
        {"q": "Objects that use electricity to work are called?", "a": "appliances"},
        {"q": "Is an eraser a conductor?", "a": "no"},
        {"q": "Is a safety pin a conductor?", "a": "yes"},
        {"q": "A drawing that uses symbols to show a circuit?", "a": "circuit diagram"},
        {"q": "If the wires are not connected to the terminals, will the bulb light?", "a": "no"},
        {"q": "What happens to the brightness of bulbs in parallel if one is removed?", "a": "stays the same"},
        {"q": "Which is brighter: 2 cells with 1 bulb or 1 cell with 1 bulb?", "a": "2 cells with 1 bulb"},
        {"q": "Is a glass rod a conductor?", "a": "no"},
        {"q": "Does a bulb light up if it is 'blown'?", "a": "no"},
        {"q": "The thin wire inside a bulb that glows is called the?", "a": "filament"},
        {"q": "When electricity flows through a bulb, it produces light and?", "a": "heat"},
        {"q": "Should we put metal objects into a socket?", "a": "no"},
        {"q": "Should we repair electrical items while they are plugged in?", "a": "no"},
        {"q": "A car battery is also known as an?", "a": "accumulator"},
        {"q": "Electricity from a wall socket comes from a?", "a": "power station"},
        {"q": "To save electricity, we should use energy-efficient?", "a": "appliances"}
    ],
"heat_and_temperature": [
        {"q": "A form of energy that flows from hot to cold?", "a": "heat"},
        {"q": "The degree of hotness or coldness of an object?", "a": "temperature"},
        {"q": "The standard unit for temperature?", "a": "degree celsius"},
        {"q": "A tool used to measure temperature?", "a": "thermometer"},
        {"q": "What happens to the temperature of water when it is heated?", "a": "increases"},
        {"q": "What happens to the temperature of water when it is cooled?", "a": "decreases"},
        {"q": "The temperature of boiling water?", "a": "100 degree celsius"},
        {"q": "The temperature of melting ice?", "a": "0 degree celsius"},
        {"q": "When an object gains heat, it will?", "a": "expand"},
        {"q": "When an object loses heat, it will?", "a": "contract"},
        {"q": "Gaps are left between railway tracks to allow for?", "a": "expansion"},
        {"q": "Electric wires are hung loosely to prevent snapping during?", "a": "contraction"},
        {"q": "What happens to the liquid in a thermometer when it gets hot?", "a": "rises"},
        {"q": "What happens to the liquid in a thermometer when it gets cold?", "a": "drops"},
        {"q": "The liquid used in a traditional thermometer is usually?", "a": "mercury"},
        {"q": "Why does a balloon expand when placed in hot water?", "a": "air expands"},
        {"q": "A metal ball cannot pass through a ring after heating because it?", "a": "expanded"},
        {"q": "To open a tight metal bottle cap, we should soak it in?", "a": "hot water"},
        {"q": "The main source of heat for the Earth is?", "a": "sun"},
        {"q": "When we rub our palms, they feel warm because of?", "a": "friction"},
        {"q": "Does a large bucket of water have more heat than a cup at the same temperature?", "a": "yes"},
        {"q": "Is 'Heat' and 'Temperature' the same thing?", "a": "no"},
        {"q": "Water changes into steam at what temperature?", "a": "100 degree celsius"},
        {"q": "Materials that allow heat to flow through easily?", "a": "heat conductors"},
        {"q": "Materials that do not allow heat to flow through easily?", "a": "heat insulators"},
        {"q": "Is aluminum a good heat conductor?", "a": "yes"},
        {"q": "Is wood a good heat insulator?", "a": "yes"},
        {"q": "Why are cooking pot handles usually made of plastic?", "a": "heat insulator"},
        {"q": "What happens to the mass of a metal bar after it expands?", "a": "remains the same"},
        {"q": "Expansion means an increase in?", "a": "size"},
        {"q": "Contraction means a decrease in?", "a": "size"},
        {"q": "The normal temperature of a healthy human body is around?", "a": "37 degree celsius"},
        {"q": "Can heat travel through a vacuum?", "a": "yes"},
        {"q": "Heat travels from a place of higher temperature to?", "a": "lower temperature"},
        {"q": "A thermometer should be read at the level of the?", "a": "meniscus"},
        {"q": "What happens to water vapor when it loses heat?", "a": "condenses"},
        {"q": "What happens to liquid water when it loses a lot of heat?", "a": "freezes"},
        {"q": "A clinical thermometer is used to measure?", "a": "body temperature"},
        {"q": "What protects us from the cold by trapping heat?", "a": "blanket"},
        {"q": "Does ice gain or lose heat to melt?", "a": "gain heat"},
        {"q": "Concrete bridges have expansion joints to prevent?", "a": "cracking"},
        {"q": "If we put an inflated balloon in the freezer, it will?", "a": "shrink"},
        {"q": "The process of a solid changing to a liquid is?", "a": "melting"},
        {"q": "The process of a liquid changing to a gas is?", "a": "evaporation"},
        {"q": "Is air a good conductor of heat?", "a": "no"},
        {"q": "Which is hotter: 40°C or 80°C?", "a": "80°C"},
        {"q": "When steam touches a cold surface, it turns into?", "a": "water"},
        {"q": "The transfer of heat through a liquid or gas is called?", "a": "convection"},
        {"q": "The transfer of heat through a solid is called?", "a": "conduction"},
        {"q": "The transfer of heat through waves is called?", "a": "radiation"}
    ],
"states_of_matter": [
        {"q": "Anything that has mass and occupies space is called?", "a": "matter"},
        {"q": "The three states of matter are solid, liquid, and?", "a": "gas"},
        {"q": "Does a solid have a fixed shape?", "a": "yes"},
        {"q": "Does a solid have a fixed volume?", "a": "yes"},
        {"q": "Does a liquid have a fixed shape?", "a": "no"},
        {"q": "Does a liquid have a fixed volume?", "a": "yes"},
        {"q": "Does a gas have a fixed shape?", "a": "no"},
        {"q": "Does a gas have a fixed volume?", "a": "no"},
        {"q": "Which state of matter can be compressed easily?", "a": "gas"},
        {"q": "The process of a liquid turning into a solid?", "a": "freezing"},
        {"q": "The process of a solid turning into a liquid?", "a": "melting"},
        {"q": "The process of a liquid turning into a gas at boiling point?", "a": "boiling"},
        {"q": "The process of a liquid turning into a gas below boiling point?", "a": "evaporation"},
        {"q": "The process of a gas turning into a liquid?", "a": "condensation"},
        {"q": "At what temperature does water freeze?", "a": "0 degree celsius"},
        {"q": "At what temperature does water boil?", "a": "100 degree celsius"},
        {"q": "Cloud formation is a result of which process?", "a": "condensation"},
        {"q": "Rain is part of the natural ___ cycle?", "a": "water"},
        {"q": "Small droplets of water on the outside of a cold glass are caused by?", "a": "condensation"},
        {"q": "Drying clothes under the sun involves the process of?", "a": "evaporation"},
        {"q": "Is a stone a solid, liquid, or gas?", "a": "solid"},
        {"q": "Is oxygen a solid, liquid, or gas?", "a": "gas"},
        {"q": "Is cooking oil a solid, liquid, or gas?", "a": "liquid"},
        {"q": "What happens to the arrangement of particles when ice melts?", "a": "becomes less orderly"},
        {"q": "In which state are particles packed very closely together?", "a": "solid"},
        {"q": "In which state can particles move freely and far apart?", "a": "gas"},
        {"q": "The constant movement of water between Earth and sky?", "a": "water cycle"},
        {"q": "What provides energy for the water cycle?", "a": "sun"},
        {"q": "Does air have mass?", "a": "yes"},
        {"q": "Does air occupy space?", "a": "yes"},
        {"q": "Ice is the ___ state of water?", "a": "solid"},
        {"q": "Steam is the ___ state of water?", "a": "gas"},
        {"q": "When water evaporates, it turns into?", "a": "water vapor"},
        {"q": "The process that happens when we see morning dew on leaves?", "a": "condensation"},
        {"q": "Why does a liquid take the shape of its container?", "a": "no fixed shape"},
        {"q": "Can a solid flow like a liquid?", "a": "no"},
        {"q": "What happens to the volume of gas if it is put in a larger container?", "a": "increases"},
        {"q": "Is smoke an example of a gas?", "a": "yes"},
        {"q": "Is honey a liquid?", "a": "yes"},
        {"q": "Particles in a liquid can ___ over each other.", "a": "slide"},
        {"q": "To change a liquid to a gas, must it gain or lose heat?", "a": "gain heat"},
        {"q": "To change a liquid to a solid, must it gain or lose heat?", "a": "lose heat"},
        {"q": "Is a sponge a solid?", "a": "yes"},
        {"q": "What is inside the bubbles in boiling water?", "a": "water vapor"},
        {"q": "Does evaporation only happen at 100°C?", "a": "no"},
        {"q": "A state of matter that has no fixed shape and no fixed volume?", "a": "gas"},
        {"q": "What is the result of water vapor losing heat in the sky?", "a": "clouds"},
        {"q": "Can we see water vapor?", "a": "no"},
        {"q": "Is fine sand a solid or liquid?", "a": "solid"},
        {"q": "Water is the only substance found naturally in all three ___?", "a": "states"}
    ],
"food_chains": [
        {"q": "An organism that makes its own food using sunlight?", "a": "producer"},
        {"q": "Animals that eat plants or other animals are called?", "a": "consumers"},
        {"q": "A diagram showing 'who eats whom' is a?", "a": "food chain"},
        {"q": "The main source of energy for all food chains?", "a": "sun"},
        {"q": "An animal that hunts and eats other animals?", "a": "predator"},
        {"q": "An animal that is hunted and eaten by another animal?", "a": "prey"},
        {"q": "In a food chain, what do the arrows represent?", "a": "flow of energy"},
        {"q": "Plants are producers because they perform?", "a": "photosynthesis"},
        {"q": "An animal that eats only producers (plants)?", "a": "herbivore"},
        {"q": "An animal that eats only other consumers (meat)?", "a": "carnivore"},
        {"q": "An animal that eats both plants and animals?", "a": "omnivore"},
        {"q": "Several food chains linked together form a?", "a": "food web"},
        {"q": "A consumer that eats only plants is a ___ consumer.", "a": "primary"},
        {"q": "An animal that eats a primary consumer is a ___ consumer.", "a": "secondary"},
        {"q": "An animal at the top of a food chain is an ___ predator.", "a": "apex"},
        {"q": "What happens to the number of prey if predators increase?", "a": "decreases"},
        {"q": "What happens to the number of predators if prey disappears?", "a": "decreases"},
        {"q": "Organisms that break down dead plants and animals?", "a": "decomposers"},
        {"q": "An example of a producer in a pond?", "a": "algae"},
        {"q": "An example of a producer on land?", "a": "grass"},
        {"q": "A hawk eating a snake is an example of a?", "a": "predator"},
        {"q": "In the chain: Grass -> Grasshopper -> Bird, the bird is a?", "a": "secondary consumer"},
        {"q": "In the chain: Leaf -> Caterpillar -> Bird, the leaf is a?", "a": "producer"},
        {"q": "Can a food chain start with an animal?", "a": "no"},
        {"q": "Energy ___ as it moves up the food chain.", "a": "decreases"},
        {"q": "A habitat with many linked food chains is very?", "a": "stable"},
        {"q": "If all plants in a habitat die, what happens to the animals?", "a": "die"},
        {"q": "Is a mushroom a producer?", "a": "no"},
        {"q": "Is a tiger a primary consumer?", "a": "no"},
        {"q": "A cow eating grass is a ___ consumer.", "a": "primary"},
        {"q": "Does a food web show more realistic eating habits than a chain?", "a": "yes"},
        {"q": "Which organism has the most energy in a food chain?", "a": "producer"},
        {"q": "Which organism has the least energy in a food chain?", "a": "apex predator"},
        {"q": "An eagle is a predator, its prey could be a?", "a": "snake"},
        {"q": "Small animals in the sea that eat algae are?", "a": "primary consumers"},
        {"q": "Can an animal be both a predator and a prey?", "a": "yes"},
        {"q": "Humans are usually classified as ___ in a food web.", "a": "omnivores"},
        {"q": "If frogs are removed, what happens to the insect population?", "a": "increases"},
        {"q": "Paddy plant -> Rat -> Snake. Who is the secondary consumer?", "a": "snake"},
        {"q": "Is a cat a predator to a mouse?", "a": "yes"},
        {"q": "Plankton -> Small fish -> Big fish. Who is the producer?", "a": "plankton"},
        {"q": "Most food chains have no more than ___ steps.", "a": "five"},
        {"q": "Energy is lost in the form of ___ at each level.", "a": "heat"},
        {"q": "A scavenger eats ___ animals.", "a": "dead"},
        {"q": "Is a vulture a scavenger?", "a": "yes"},
        {"q": "Is a spider a predator?", "a": "yes"},
        {"q": "A caterpillar is a ___ to a bird.", "a": "prey"},
        {"q": "Fungi and bacteria are examples of?", "a": "decomposers"},
        {"q": "Does a food chain work without sunlight?", "a": "no"},
        {"q": "The position of an organism in a food chain is its ___ level.", "a": "trophic"}
    ],
"materials_properties": [
        {"q": "Materials like wood and cotton come from?", "a": "plants"},
        {"q": "Materials like silk and wool come from?", "a": "animals"},
        {"q": "Materials like metal and glass come from?", "a": "rocks"},
        {"q": "Materials like plastic and synthetic cloth come from?", "a": "petroleum"},
        {"q": "A material that can be stretched and returns to its original shape?", "a": "elastic"},
        {"q": "Is a rubber band elastic or non-elastic?", "a": "elastic"},
        {"q": "Materials that allow water to pass through or be soaked up?", "a": "absorbent"},
        {"q": "Materials that do not soak up water are called?", "a": "waterproof"},
        {"q": "Is a raincoat made of absorbent or waterproof material?", "a": "waterproof"},
        {"q": "A material that allows light to pass through clearly?", "a": "transparent"},
        {"q": "Is a metal spoon transparent?", "a": "no"},
        {"q": "Materials that allow electricity to flow through are?", "a": "electrical conductors"},
        {"q": "Most objects made of ___ are good electrical conductors.", "a": "metal"},
        {"q": "Materials that do not allow heat to flow through easily?", "a": "heat insulators"},
        {"q": "Why is a cooking pot made of metal?", "a": "heat conductor"},
        {"q": "Why is a towel made of cotton?", "a": "absorbs water"},
        {"q": "An object that stays on the surface of water is said to?", "a": "float"},
        {"q": "An object that goes to the bottom of water is said to?", "a": "sink"},
        {"q": "Is a coin likely to float or sink?", "a": "sink"},
        {"q": "Is a dry leaf likely to float or sink?", "a": "float"},
        {"q": "Leather comes from the skin of?", "a": "animals"},
        {"q": "What is the basic source of a plastic bottle?", "a": "petroleum"},
        {"q": "Is glass a natural or man-made material from rocks?", "a": "man-made"},
        {"q": "The ability of a material to support a heavy load without breaking?", "a": "strength"},
        {"q": "Is a paper bag stronger than a plastic bag when wet?", "a": "no"},
        {"q": "Objects made of iron will ___ when exposed to water and air.", "a": "rust"},
        {"q": "To prevent rusting, we can ___ the metal surface.", "a": "paint"},
        {"q": "Is gold a metal that trusts easily?", "a": "no"},
        {"q": "A magnet can attract objects made of?", "a": "iron"},
        {"q": "Is aluminum attracted to a magnet?", "a": "no"},
        {"q": "Which material is used to make car tires?", "a": "rubber"},
        {"q": "Ceramics are made from?", "a": "clay"},
        {"q": "Is a ceramic vase waterproof?", "a": "yes"},
        {"q": "Is a sponge an absorbent material?", "a": "yes"},
        {"q": "Are most plastics heat insulators?", "a": "yes"},
        {"q": "Why are electrical wires covered in plastic?", "a": "electrical insulator"},
        {"q": "Which material is best for making a mirror?", "a": "glass"},
        {"q": "Is cotton a natural fiber?", "a": "yes"},
        {"q": "Is nylon a synthetic fiber?", "a": "yes"},
        {"q": "Synthetic materials are mostly made from?", "a": "petroleum"},
        {"q": "A window pane is made of glass because it is?", "a": "transparent"},
        {"q": "Is a wooden bridge a good electrical conductor?", "a": "no"},
        {"q": "Wool is used to make sweaters because it traps?", "a": "heat"},
        {"q": "Which is more elastic: a steel wire or a rubber string?", "a": "rubber string"},
        {"q": "An umbrella must be made of ___ material.", "a": "waterproof"},
        {"q": "Do all metals sink in water?", "a": "no"},
        {"q": "Copper is used in wires because it is a good?", "a": "conductor"},
        {"q": "Can a material be both waterproof and transparent?", "a": "yes"},
        {"q": "Is paper made from animals?", "a": "no"},
        {"q": "What material is best for a swimming cap?", "a": "latex"}
    ],
"solar_system": [
        {"q": "The center of the solar system is the?", "a": "sun"},
        {"q": "How many planets are there in our solar system?", "a": "eight"},
        {"q": "The closest planet to the Sun is?", "a": "mercury"},
        {"q": "The largest planet in the solar system is?", "a": "jupiter"},
        {"q": "The 'Red Planet' is known as?", "a": "mars"},
        {"q": "The planet famous for its beautiful rings is?", "a": "saturn"},
        {"q": "The coldest and furthest planet from the Sun is?", "a": "neptune"},
        {"q": "The third planet from the Sun is?", "a": "earth"},
        {"q": "The hottest planet in the solar system is?", "a": "venus"},
        {"q": "Small rocky objects that orbit the Sun, mostly between Mars and Jupiter?", "a": "asteroids"},
        {"q": "A 'dirty snowball' made of ice and dust that orbits the Sun?", "a": "comet"},
        {"q": "Natural satellites that orbit planets are called?", "a": "moons"},
        {"q": "A path followed by a planet around the Sun is an?", "a": "orbit"},
        {"q": "The spinning of the Earth on its axis is called?", "a": "rotation"},
        {"q": "The movement of the Earth around the Sun is called?", "a": "revolution"},
        {"q": "How long does it take for Earth to complete one rotation?", "a": "24 hours"},
        {"q": "How long does it take for Earth to complete one revolution?", "a": "365.25 days"},
        {"q": "The Earth rotates from ___ to ___.", "a": "west to east"},
        {"q": "The Sun appears to rise in the?", "a": "east"},
        {"q": "The Sun appears to set in the?", "a": "west"},
        {"q": "The rotation of the Earth causes day and?", "a": "night"},
        {"q": "The imaginary line through the center of the Earth is the?", "a": "axis"},
        {"q": "Does the Sun move around the Earth?", "a": "no"},
        {"q": "The moon reflects light from the?", "a": "sun"},
        {"q": "How long does it take for the Moon to orbit the Earth?", "a": "27.3 days"},
        {"q": "The different shapes of the Moon seen from Earth are called?", "a": "phases of the moon"},
        {"q": "The phase when the Moon is not visible at all is the?", "a": "new moon"},
        {"q": "The phase when the Moon looks like a complete circle?", "a": "full moon"},
        {"q": "Which planet is known as Earth's twin?", "a": "venus"},
        {"q": "Is Pluto still classified as a major planet?", "a": "no"},
        {"q": "What is Pluto classified as now?", "a": "dwarf planet"},
        {"q": "Gravity on the Moon is ___ than on Earth.", "a": "weaker"},
        {"q": "Does the Moon have its own light?", "a": "no"},
        {"q": "The force that keeps planets in their orbits is?", "a": "gravity"},
        {"q": "Which planet rotates on its side?", "a": "uranus"},
        {"q": "The belt between Mars and Jupiter is the ___ belt.", "a": "asteroid"},
        {"q": "A meteor that hits the Earth's surface is a?", "a": "meteorite"},
        {"q": "A 'shooting star' is actually a?", "a": "meteor"},
        {"q": "Which planet has the most visible rings?", "a": "saturn"},
        {"q": "Is the Sun a planet or a star?", "a": "star"},
        {"q": "The shape of a planet's orbit is an?", "a": "ellipse"},
        {"q": "Does Venus have any moons?", "a": "no"},
        {"q": "Does Mercury have an atmosphere?", "a": "no"},
        {"q": "Which planet is known for the Great Red Spot?", "a": "jupiter"},
        {"q": "The only planet known to support life is?", "a": "earth"},
        {"q": "Why is Mars red? Because of iron ___ in the soil.", "a": "oxide"},
        {"q": "A collection of billions of stars and solar systems is a?", "a": "galaxy"},
        {"q": "What is the name of our galaxy?", "a": "milky way"},
        {"q": "Is the Earth's axis straight or tilted?", "a": "tilted"},
        {"q": "Tides on Earth are caused by the pull of the?", "a": "moon"}
    ],
"machines_simple": [
        {"q": "A tool that makes work easier and faster is a?", "a": "machine"},
        {"q": "A simple machine with a slanted surface to move loads up?", "a": "inclined plane"},
        {"q": "A simple machine with a grooved wheel and a rope?", "a": "pulley"},
        {"q": "A simple machine consisting of a rigid bar that turns on a fixed point?", "a": "lever"},
        {"q": "The fixed point on which a lever turns is called the?", "a": "fulcrum"},
        {"q": "The force applied to a lever to move a load is called?", "a": "effort"},
        {"q": "The object being moved by a lever is called the?", "a": "load"},
        {"q": "A simple machine made of two circular objects of different sizes?", "a": "wheel and axle"},
        {"q": "A simple machine that is thick at one end and tapers to a thin edge?", "a": "wedge"},
        {"q": "An inclined plane wrapped around a cylinder or cone?", "a": "screw"},
        {"q": "A wheel with teeth around its rim?", "a": "gear"},
        {"q": "A pair of scissors is an example of which simple machine?", "a": "lever"},
        {"q": "A staircase is an example of which simple machine?", "a": "inclined plane"},
        {"q": "An axe is an example of which simple machine?", "a": "wedge"},
        {"q": "A flagpole uses which simple machine to raise the flag?", "a": "pulley"},
        {"q": "A doorknob is an example of which simple machine?", "a": "wheel and axle"},
        {"q": "A bottle cap is an example of which simple machine?", "a": "screw"},
        {"q": "What type of simple machine is a slide in a playground?", "a": "inclined plane"},
        {"q": "Which simple machine is used to cut or split objects?", "a": "wedge"},
        {"q": "Which simple machine is used to hold objects together?", "a": "screw"},
        {"q": "A see-saw is an example of a first-class?", "a": "lever"},
        {"q": "A wheelbarrow is an example of a second-class?", "a": "lever"},
        {"q": "A fishing rod is an example of a third-class?", "a": "lever"},
        {"q": "Two gears working together can change the ___ of motion.", "a": "direction"},
        {"q": "A combination of two or more simple machines is a ___ machine.", "a": "complex"},
        {"q": "A bicycle is an example of a?", "a": "complex machine"},
        {"q": "Simple machines help us by reducing the ___ needed.", "a": "effort"},
        {"q": "Is a knife a wedge?", "a": "yes"},
        {"q": "Is a ramp an inclined plane?", "a": "yes"},
        {"q": "A crane uses a system of ___ to lift heavy loads.", "a": "pulleys"},
        {"q": "In a wheel and axle, the larger circle is the?", "a": "wheel"},
        {"q": "The rod that goes through the center of a wheel is the?", "a": "axle"},
        {"q": "Which machine uses a spiral thread?", "a": "screw"},
        {"q": "When two gears mesh, they turn in ___ directions.", "a": "opposite"},
        {"q": "A nutcracker is an example of a?", "a": "lever"},
        {"q": "The longer the inclined plane, the ___ effort is needed.", "a": "less"},
        {"q": "Is a pencil sharpener a complex machine?", "a": "yes"},
        {"q": "What do we call a machine that is durable and sustainable?", "a": "sustainable machine"},
        {"q": "Maintenance like ___ prevents machines from rusting.", "a": "oiling"},
        {"q": "A broom is a type of?", "a": "lever"},
        {"q": "Tweezers are a type of?", "a": "lever"},
        {"q": "The part of a screw that winds around is the?", "a": "thread"},
        {"q": "Can a pulley change the direction of a force?", "a": "yes"},
        {"q": "Is a hammer a simple machine?", "a": "yes"},
        {"q": "What type of machine is a manual hand drill?", "a": "complex machine"},
        {"q": "The point where the effort is applied is the?", "a": "effort point"},
        {"q": "Does a simple machine create energy?", "a": "no"},
        {"q": "Which is easier: lifting a load straight up or using a ramp?", "a": "using a ramp"},
        {"q": "A ladder is an example of an?", "a": "inclined plane"},
        {"q": "Keeping machines clean helps them to last?", "a": "longer"}
    ],
"microorganisms": [
        {"q": "Very tiny living things that cannot be seen with the naked eye?", "a": "microorganisms"},
        {"q": "The tool used to see microorganisms clearly?", "a": "microscope"},
        {"q": "A type of microorganism used to make bread rise?", "a": "yeast"},
        {"q": "Microorganisms that can be seen without a microscope in a group?", "a": "fungi"},
        {"q": "A type of microorganism often found in yogurt?", "a": "bacteria"},
        {"q": "The smallest type of microorganism?", "a": "virus"},
        {"q": "Microorganisms breathe, move and ___?", "a": "grow"},
        {"q": "Dough rising is proof that yeast is ___?", "a": "breathing"},
        {"q": "What do fungi produce to reproduce?", "a": "spores"},
        {"q": "Food turns moldy because of the growth of?", "a": "fungi"},
        {"q": "Diseases caused by microorganisms are called ___ diseases.", "a": "infectious"},
        {"q": "Is a mushroom a type of fungi?", "a": "yes"},
        {"q": "Can some bacteria be useful to humans?", "a": "yes"},
        {"q": "Tooth decay is caused by?", "a": "bacteria"},
        {"q": "A medicine used to kill bacteria?", "a": "antibiotic"},
        {"q": "What prevents the spread of viruses through coughing?", "a": "face mask"},
        {"q": "Washing hands with soap helps to remove?", "a": "microorganisms"},
        {"q": "Which microorganism causes the common flu?", "a": "virus"},
        {"q": "An example of a microorganism found in pond water?", "a": "protozoa"},
        {"q": "Microorganisms need air, food, and ___ to grow.", "a": "water"},
        {"q": "What is the best temperature for microorganism growth?", "a": "room temperature"},
        {"q": "Can microorganisms live in very cold places?", "a": "yes"},
        {"q": "Is Amoeba a type of protozoa?", "a": "yes"},
        {"q": "The green spots on old bread are usually?", "a": "fungi"},
        {"q": "Does heat kill most microorganisms?", "a": "yes"},
        {"q": "Vaccinations help our body fight against?", "a": "viruses"},
        {"q": "Are all microorganisms harmful?", "a": "no"},
        {"q": "What do we call harmful microorganisms that cause illness?", "a": "germs"},
        {"q": "Which process is used to make tap water safe from germs?", "a": "chlorination"},
        {"q": "Is Penicillium a type of useful fungi?", "a": "yes"},
        {"q": "Microorganisms that can make their own food?", "a": "algae"},
        {"q": "The study of microorganisms is called?", "a": "microbiology"},
        {"q": "Can we see a single bacterium with our eyes?", "a": "no"},
        {"q": "Does freezing kill all microorganisms?", "a": "no"},
        {"q": "Microorganisms grow faster in ___ conditions.", "a": "damp"},
        {"q": "Which gas is released by yeast during fermentation?", "a": "carbon dioxide"},
        {"q": "Is COVID-19 caused by a bacteria or virus?", "a": "virus"},
        {"q": "Are microorganisms used in making compost?", "a": "yes"},
        {"q": "Spoiled food usually has a bad?", "a": "smell"},
        {"q": "The process where microorganisms break down food is?", "a": "decomposition"},
        {"q": "Does stomach acid help kill some germs?", "a": "yes"},
        {"q": "Microorganisms breathe to produce?", "a": "energy"},
        {"q": "A type of algae often found in aquariums?", "a": "phytoplankton"},
        {"q": "Can viruses survive outside a host for long?", "a": "no"},
        {"q": "Using a separate cutting board for meat helps prevent?", "a": "cross contamination"},
        {"q": "Is yeast a multicellular or unicellular organism?", "a": "unicellular"},
        {"q": "Is Paramecium a protozoa?", "a": "yes"},
        {"q": "Which sense helps you identify rotten food?", "a": "smell"},
        {"q": "Microorganisms are found?", "a": "everywhere"},
        {"q": "A group of bacteria is called a?", "a": "colony"}
    ],

    "food_preservation": [
        {"q": "The process of treating food to stop it from spoiling?", "a": "food preservation"},
        {"q": "Boiling food at high temperatures to kill germs?", "a": "boiling"},
        {"q": "Preserving food by removing all its water?", "a": "drying"},
        {"q": "Using salt to preserve food like fish?", "a": "salting"},
        {"q": "Preserving food in a vinegar or sugar solution?", "a": "pickling"},
        {"q": "The process of heating liquid then cooling it quickly?", "a": "pasteurization"},
        {"q": "Storing food in airtight containers or cans?", "a": "canning"},
        {"q": "Storing food in air-tight plastic bags?", "a": "vacuum packing"},
        {"q": "Keeping food at very low temperatures (below 0°C)?", "a": "freezing"},
        {"q": "Keeping food in the refrigerator (above 0°C)?", "a": "cooling"},
        {"q": "Coating food with melted wax to prevent air contact?", "a": "waxing"},
        {"q": "Exposing food to wood smoke for preservation?", "a": "smoking"},
        {"q": "Salt and sugar act as ___ in food preservation.", "a": "preservatives"},
        {"q": "Which method is best for preserving milk?", "a": "pasteurization"},
        {"q": "Which method is best for making salted fish?", "a": "salting"},
        {"q": "Drying food can be done using the oven or?", "a": "sunlight"},
        {"q": "What is the main cause of food spoilage?", "a": "microorganisms"},
        {"q": "Spoiled food often changes in color, smell, and?", "a": "taste"},
        {"q": "Why does vacuum packing prevent spoilage?", "a": "no air"},
        {"q": "Canned food can last for a long?", "a": "time"},
        {"q": "Pasteurization is named after which scientist?", "a": "Louis Pasteur"},
        {"q": "Honey is a natural preservative because it has low?", "a": "water content"},
        {"q": "Does freezing kill microorganisms or just stop them growing?", "a": "stop them growing"},
        {"q": "Which method is used for making jams?", "a": "boiling with sugar"},
        {"q": "The acid in vinegar helps to prevent ___ growth.", "a": "bacteria"},
        {"q": "Is canned food safe to eat if the can is dented?", "a": "no"},
        {"q": "Preserved food is easier to ___ to other places.", "a": "transport"},
        {"q": "Food preservation helps to avoid food ___?", "a": "wastage"},
        {"q": "Which method is commonly used for chili or dried shrimp?", "a": "drying"},
        {"q": "Waxing is usually done on which type of food?", "a": "fruits"},
        {"q": "High acidity in pickling prevents the growth of?", "a": "microorganisms"},
        {"q": "What happens to the taste of food after pickling?", "a": "becomes sour"},
        {"q": "Smoking food removes water and adds?", "a": "flavor"},
        {"q": "Should we check the 'Expiry Date' before buying food?", "a": "yes"},
        {"q": "Does boiling kill all microorganisms?", "a": "yes"},
        {"q": "Which preservation method uses high pressure?", "a": "canning"},
        {"q": "Why is salt used to preserve eggs?", "a": "draws out water"},
        {"q": "Keeping food in a cool place slows down?", "a": "spoilage"},
        {"q": "What is used to coat some apples to keep them fresh?", "a": "wax"},
        {"q": "Preserved food can be eaten out of ___?", "a": "season"},
        {"q": "Is pickling a modern or traditional method?", "a": "traditional"},
        {"q": "Does drying change the texture of food?", "a": "yes"},
        {"q": "Pasteurization is mainly used for milk and?", "a": "fruit juice"},
        {"q": "Can vacuum packing be used for nuts?", "a": "yes"},
        {"q": "Microorganisms cannot grow without ___?", "a": "moisture"},
        {"q": "A bulging can is a sign that the food is ___?", "a": "spoiled"},
        {"q": "Is refrigeration a permanent preservation method?", "a": "no"},
        {"q": "Ultra-High Temperature (UHT) is a type of?", "a": "pasteurization"},
        {"q": "Why do we preserve food for emergencies?", "a": "long shelf life"},
        {"q": "The main goal of preservation is to create an ___ environment for germs.", "a": "unsuitable"}
    ],

    "preservation_conservation": [
        {"q": "Protecting the environment and living things from being destroyed?", "a": "preservation"},
        {"q": "Using natural resources wisely to avoid wastage?", "a": "conservation"},
        {"q": "Animals that no longer exist on Earth are?", "a": "extinct"},
        {"q": "An example of an extinct animal?", "a": "dinosaur"},
        {"q": "Another example of an extinct bird?", "a": "dodo"},
        {"q": "Animals or plants facing the threat of extinction?", "a": "endangered"},
        {"q": "An example of an endangered animal in Malaysia?", "a": "orangutan"},
        {"q": "Is the Malayan Tiger endangered?", "a": "yes"},
        {"q": "The main cause of animal extinction today?", "a": "human activities"},
        {"q": "Illegal hunting of animals is called?", "a": "poaching"},
        {"q": "Cutting down forests on a large scale is called?", "a": "deforestation"},
        {"q": "The place where an animal or plant naturally lives?", "a": "habitat"},
        {"q": "Reforestation means ___ trees.", "a": "replanting"},
        {"q": "Setting up a 'Taman Negara' is an effort for?", "a": "preservation"},
        {"q": "Reducing, reusing, and recycling are part of?", "a": "conservation"},
        {"q": "Is the Rafflesia flower endangered?", "a": "yes"},
        {"q": "Is the leatherback turtle endangered?", "a": "yes"},
        {"q": "Poachers hunt elephants for their?", "a": "tusks"},
        {"q": "Poachers hunt tigers for their?", "a": "skin"},
        {"q": "Poachers hunt rhinoceros for their?", "a": "horns"},
        {"q": "What happens to animals when their habitat is destroyed?", "a": "lose their home"},
        {"q": "Water pollution can kill ___ life.", "a": "aquatic"},
        {"q": "Is the Mammoth an extinct animal?", "a": "yes"},
        {"q": "Creating a forest reserve is a way to protect?", "a": "biodiversity"},
        {"q": "The law that protects wildlife in Malaysia?", "a": "wildlife protection act"},
        {"q": "Education helps people understand the ___ of nature.", "a": "importance"},
        {"q": "Is the Panda still an endangered species?", "a": "yes"},
        {"q": "An area protected to save turtles is a turtle ___?", "a": "sanctuary"},
        {"q": "Oil spills in the ocean cause?", "a": "pollution"},
        {"q": "Global warming is caused by too much ___ gas.", "a": "carbon dioxide"},
        {"q": "Can extinction be reversed?", "a": "no"},
        {"q": "Sustainable logging helps to maintain?", "a": "forests"},
        {"q": "The removal of the top layer of soil is?", "a": "soil erosion"},
        {"q": "Mangrove forests protect the coastline from?", "a": "erosion"},
        {"q": "Recycling paper helps to save ___?", "a": "trees"},
        {"q": "What is the status of the Javan Rhino?", "a": "endangered"},
        {"q": "Is hunting for fun allowed in protected areas?", "a": "no"},
        {"q": "A place where animals are bred to increase their population?", "a": "breeding center"},
        {"q": "Is the Quagga an extinct animal?", "a": "yes"},
        {"q": "Using solar energy is a way of ___ energy.", "a": "conserving"},
        {"q": "Is air pollution a threat to living things?", "a": "yes"},
        {"q": "Can we buy products made from endangered animals?", "a": "no"},
        {"q": "The balance of nature is called the?", "a": "ecosystem"},
        {"q": "Which organization works to protect nature globally?", "a": "WWF"},
        {"q": "Is the Dugong an endangered animal?", "a": "yes"},
        {"q": "Planting trees in urban areas is called?", "a": "urban forestry"},
        {"q": "Saving water is an act of?", "a": "conservation"},
        {"q": "The main reason for the extinction of the Dodo?", "a": "overhunting"},
        {"q": "Is the Tasmanian Tiger extinct?", "a": "yes"},
        {"q": "We must protect nature for our ___ generations.", "a": "future"}
    ]
};