// ==========================================
// DATA SOALAN REKA BENTUK DAN TEKNOLOGI (4 Kategori Pertama)
// ==========================================
const rbtData = {
    "keselamatan_bengkel": [
        {"q": "Tempat kita melakukan kerja amali kemahiran dipanggil ___?", "a": "bengkel"},
        {"q": "Baju perlu dimasukkan ke dalam seluar supaya kelihatan ___?", "a": "kemas"},
        {"q": "Rambut yang panjang perlulah di___ semasa di bengkel?", "a": "ikat"},
        {"q": "Kasut yang dipakai ke bengkel mestilah jenis ___?", "a": "bertutup"},
        {"q": "Pakaian yang kotor dapat dihalang dengan memakai ___?", "a": "apron"},
        {"q": "Tingkap dan pintu perlu dibuka untuk pengaliran ___?", "a": "udara"},
        {"q": "Cahaya yang cukup diperlukan supaya bengkel menjadi ___?", "a": "terang"},
        {"q": "Alatan tangan yang tajam boleh menyebabkan luka atau ___?", "a": "kecederaan"},
        {"q": "Jika berlaku kemalangan, laporkan dengan segera kepada ___?", "a": "guru"},
        {"q": "Sisa kayu yang tidak digunakan perlu dibuang ke dalam tong ___?", "a": "sampah"},
        {"q": "Bahan mudah terbakar perlu sentiasa dijauhkan daripada ___?", "a": "api"},
        {"q": "Tanda kawasan larangan bermaksud kita sama sekali tidak boleh ___?", "a": "masuk"},
        {"q": "Alatan tangan yang telah digunakan perlu di___ semula?", "a": "simpan"},
        {"q": "Minyak yang tumpah di lantai perlu di___ supaya tidak licin?", "a": "bersih"},
        {"q": "Bermain dan berlari di dalam bengkel adalah dilarang ___?", "a": "keras"},
        {"q": "Alatan elektrik mesti dimatikan suisnya selepas di___?", "a": "guna"},
        {"q": "Peti yang mengandungi ubat luka dipanggil peti pertolongan ___?", "a": "cemas"},
        {"q": "Alat pemadam api silinder digunakan untuk memadam kebakaran ___?", "a": "kecil"},
        {"q": "Langkah pertama: Tarik ___ picu pemadam api.", "a": "pin"},
        {"q": "Langkah kedua: Hala muncung hos ke arah pangkal ___.", "a": "api"},
        {"q": "Langkah ketiga: Tekan ___ pemicit pemadam perlahan-lahan.", "a": "tuil"},
        {"q": "Plaster luka plaster luka boleh didapati di dalam peti ___?", "a": "cemas"},
        {"q": "Jangan lupa matikan suis utama elektrik selepas selesai ___?", "a": "guna"},
        {"q": "Alatan tajam mestilah dipegang dengan postur tangan yang ___?", "a": "betul"},
        {"q": "Alatan siap guna perlu dibersihkan sebelum di___ ke dalam almari?", "a": "simpan"},
        {"q": "Meja kerja kayu perlu di___ habuknya selepas tamat amali?", "a": "bersih"},
        {"q": "Tangan yang basah dilarang keras memegang plug atau ___?", "a": "suis"},
        {"q": "Memakai sarung tangan fabrik adalah untuk pelindung ___?", "a": "tangan"},
        {"q": "Topeng muka menghalang kita daripada menghidu habuk ___?", "a": "kayu"},
        {"q": "Dilarang bergurau senda terutamanya ketika membawa alatan ___?", "a": "tajam"},
        {"q": "Sentiasa patuh pada peraturan semasa berada di dalam ___?", "a": "bengkel"},
        {"q": "Pintu bilik mesti sentiasa ditutup rapat bila kita ___?", "a": "keluar"},
        {"q": "Sisa kayu di lantai boleh menyebabkan kawan kita ___?", "a": "tersadung"},
        {"q": "Pastikan alatan mesin elektrik tidak cacat atau ___?", "a": "rosak"},
        {"q": "Wayar terdedah mengundang bahaya renjatan maut ___?", "a": "elektrik"},
        {"q": "Laporkan alatan rosak kepada guru kelas dengan ___?", "a": "segera"},
        {"q": "Kain buruk kotor perlu di___ sebelum disidai semula?", "a": "basuh"},
        {"q": "Pelitup mata plastik bertindak pelindung mata dari debu ___?", "a": "habuk"},
        {"q": "Serbuk gergaji kayu di lantai perlu disapu guna ___?", "a": "penyapu"},
        {"q": "Murid perempuan bertudung, tudung wajib di___ ke dalam apron.", "a": "selit"},
        {"q": "Lengan baju sekolah yang panjang perlu dilipat ___?", "a": "pendek"},
        {"q": "Alatan bengkel tidak boleh sesuka hati dibawa ke ___?", "a": "luar"},
        {"q": "Susun bangku kerusi di bawah meja sebelum ___?", "a": "pulang"},
        {"q": "Matikan semua suis peralatan elektrik kipas dan ___?", "a": "lampu"},
        {"q": "Masuk kelas kemahiran bengkel perlulah dengan kebenaran ___?", "a": "guru"},
        {"q": "Jika luka kecil tercucuk paku halus balut guna ___?", "a": "plaster"},
        {"q": "Jangan sengaja tekan main alat pemadam ___?", "a": "api"},
        {"q": "Papan tanda amaran di bengkel lazimnya berwarna ___?", "a": "merah"},
        {"q": "Pematuhan etika di bengkel amat menjamin tahap ___?", "a": "keselamatan"},
        {"q": "Udara segar jadikan suasana bengkel aman dan ___?", "a": "selesa"}
    ],

    "pengenalan_reka_bentuk": [
        {"q": "Penghasilan idea produk objek baru dipanggil reka ___?", "a": "bentuk"},
        {"q": "Fungsi utama reka bentuk adalah untuk selesaikan masalah ___?", "a": "manusia"},
        {"q": "Elemen garisan terawal sebenarnya bermula daripada titik ___?", "a": "titik"},
        {"q": "Pertemuan hujung garisan yang bercantum akan membentuk ___?", "a": "rupa"},
        {"q": "Rupa lukisan datar rata tiada isipadu dikenali ciri dua ___?", "a": "dimensi"},
        {"q": "Bentuk tiga dimensi yang fizikal boleh dipegang ialah bentuk ___?", "a": "konkrit"},
        {"q": "Bentuk nipis di dalam lukisan gambar foto ialah bentuk ___?", "a": "ilusi"},
        {"q": "Kesan sifat rasa permukaan luaran objek ialah ___?", "a": "jalinan"},
        {"q": "Jalinan cengkaman tayar yang kasar dipanggil jalinan ___?", "a": "sentuh"},
        {"q": "Jalinan corak langsir yang rata dipanggil jalinan ___?", "a": "tampak"},
        {"q": "Kawasan lapang jarak kosong antara objek dipanggil ___?", "a": "ruang"},
        {"q": "Merah, biru dan juga hijau tergolong dalam elemen ___?", "a": "warna"},
        {"q": "Warna api merah dan jingga ialah kategori warna ___?", "a": "panas"},
        {"q": "Warna laut biru dan hijau ialah kategori warna ___?", "a": "sejuk"},
        {"q": "Campuran asas merah digabung kuning menghasilkan rona ___?", "a": "jingga"},
        {"q": "Campuran asas biru digabung kuning menghasilkan rona ___?", "a": "hijau"},
        {"q": "Campuran asas biru digabung merah menghasilkan rona ___?", "a": "ungu"},
        {"q": "Aplikasi reka bentuk teknologi menjadikan aktiviti hidup ___?", "a": "mudah"},
        {"q": "Produk teknologi moden ciptaan saintis memajukan sosioekonomi ___?", "a": "negara"},
        {"q": "Lakaran garisan beralun melengkung menunjukkan pergerakan yang ___?", "a": "lembut"},
        {"q": "Lakaran garisan putus-putus putus menunjukkan keadaan yang ___?", "a": "tersembunyi"},
        {"q": "Rupa geometri stabil bersudut bucu seperti kotak segi ___?", "a": "empat"},
        {"q": "Rupa organik adalah bebas dan tidak bersudut seperti rupa ___?", "a": "daun"},
        {"q": "Saiz objek jauh dan besar di hadapan mewujudkan kesan ___?", "a": "ruang"},
        {"q": "Pengulangan susunan rupa bercorak akan membentuk prinsip yang ___?", "a": "harmoni"},
        {"q": "Ton warna pastel terang perlu dicampur banyak warna ___?", "a": "putih"},
        {"q": "Ton warna seram gelap perlu dicampur pewarna cecair ___?", "a": "hitam"},
        {"q": "Rupa bentuk objek yang nyata di dalam lukisan ialah rupa ___?", "a": "positif"},
        {"q": "Kawasan latar belakang di luar lukisan imej ialah rupa ___?", "a": "negatif"},
        {"q": "Penggunaan pengetahuan sains dalam inovasi penciptaan dipanggil ___?", "a": "teknologi"},
        {"q": "Reka bentuk saiz kasut bergantung rapat kepada ukuran ___?", "a": "kaki"},
        {"q": "Ciptaan pengangkutan darat kereta memudahkan proses urusan ___?", "a": "perjalanan"},
        {"q": "Rekaan atap payung tebal melindungi pemakai dari hujan dan ___?", "a": "panas"},
        {"q": "Garisan tiang lurus menegak nampak kuat, stabil dan ___?", "a": "teguh"},
        {"q": "Garisan arus beralun kelihatan cantik mendamaikan macam ___?", "a": "ombak"},
        {"q": "Elemen bentuk mesti mempunyai ukuran panjang, lebar dan ___?", "a": "tinggi"},
        {"q": "Reka bentuk empat kaki meja makan amat mementingkan ___?", "a": "kestabilan"},
        {"q": "Kerusi empuk di kelas direka khas bentuknya untuk kita ___?", "a": "duduk"},
        {"q": "Sifat jalinan kulit durian tajam sangat menyakitkan dan ___?", "a": "kasar"},
        {"q": "Jalinan cermin tingkap kaca amat licin dan sangat ___?", "a": "licin"},
        {"q": "Penghasilan produk karya baharu atau penambahbaikan dipanggil ___?", "a": "inovasi"},
        {"q": "Lakaran percambahan idea melakar guna alat pensel atas ___?", "a": "kertas"},
        {"q": "Lakaran lakaran idea asas lakaran awal selalunya tidak perlu guna ___?", "a": "pembaris"},
        {"q": "Pilihan corak lakaran terbaik akan dipilih sebagai idea ___?", "a": "akhir"},
        {"q": "Gandingan warna hitam serta putih diiktiraf sebagai warna ___?", "a": "neutral"},
        {"q": "Garisan senget condong menampakkan keadaan binaan yang tidak ___?", "a": "stabil"},
        {"q": "Elemen corak penting untuk memikat pelanggan ialah semestinya ___?", "a": "cantik"},
        {"q": "Secara ilusi objek nun jauh perlulah dilukis bersaiz ___?", "a": "kecil"},
        {"q": "Secara ilusi objek amat dekat perlulah dilukis bersaiz ___?", "a": "besar"},
        {"q": "Proses pencarian ilham mereka bentuk perlukan minda daya ___?", "a": "kreatif"}
    ],

    "reka_bentuk_pembungkusan": [
        {"q": "Benda bekas membalut melindungi produk di dalamnya ialah ___?", "a": "pembungkusan"},
        {"q": "Fungsi keselamatan utama pembungkusan adalah untuk melindungi ___?", "a": "produk"},
        {"q": "Pembungkusan vakum udara elak makanan ringan agar tidak cepat ___?", "a": "rosak"},
        {"q": "Kertas stiker label pada pembungkus bertugas berikan pentingnya ___?", "a": "maklumat"},
        {"q": "Maklumat jangka hayat produk amat penting ialah tarikh ___?", "a": "luput"},
        {"q": "Warna pembungkusan wajib menarik perhatian pandangan pelanggan atau ___?", "a": "pembeli"},
        {"q": "Bekas material silika kaca berkilat sangat mudah jatuh ___?", "a": "pecah"},
        {"q": "Pembungkus kotak dari kertas nipis sangat tidak kalis air dan ___?", "a": "koyak"},
        {"q": "Bahan mesra alam biodegradasi bermaksud sisanya boleh di ___?", "a": "kitar"},
        {"q": "Pensijilan logo hijau Jakim tanda makanan halal untuk penganut ___?", "a": "islam"},
        {"q": "Info jisim berat bahan cecair produk ditulis dalam sukatan ___?", "a": "mililiter"},
        {"q": "Botol penutup air mineral di kantin lazimnya dibungkus guna ___?", "a": "plastik"},
        {"q": "Kotak kasut direka empat segi menggunakan kertas bahan keras ___?", "a": "kadbod"},
        {"q": "Tutup botol bekas cecair ubat mestilah rapat ketat agar tidak ___?", "a": "bocor"},
        {"q": "Bungkusan pek cip makanan ringan mesti kedap dan dipam ___?", "a": "udara"},
        {"q": "Suntikan udara gelembung dalam pek jajan halang cip dari ___?", "a": "hancur"},
        {"q": "Tanda nama asal hak cipta kilang pembuat dipanggil jenama ___?", "a": "jenama"},
        {"q": "Reka bentuk maskot kartun unik buat produk snek lebih ___?", "a": "laku"},
        {"q": "Material bekas botol kaca adalah stabil berat dan permukaannya ___?", "a": "tebal"},
        {"q": "Susu lembu segar dari ladang sangat popular dibungkus di dalam ___?", "a": "kotak"},
        {"q": "Tutup khas ubat batuk moden dibina ciri kunci pusing keselamatan ___?", "a": "kanak-kanak"},
        {"q": "Tin minuman tin milo banyak memproses logam besi jenis ___?", "a": "aluminium"},
        {"q": "Benda kaca dibalut kepingan bubble plastik gelembung elak hentakan ___?", "a": "retak"},
        {"q": "Teks ramuan senarai bahan diguna kilang ditulis pada pelekat ___?", "a": "label"},
        {"q": "Garisan hitam putih kod jalur barcode diimbas untuk mengira ___?", "a": "harga"},
        {"q": "Beg kraf reka bentuk pek di pasaraya perlu ringan senang di ___?", "a": "bawa"},
        {"q": "Pembalutan hadiah hari jadi hari lahir banyak gunakan corak pembalut ___?", "a": "hadiah"},
        {"q": "Reka corak anyaman daun pisang ialah kraf pembungkusan bahan ___?", "a": "semulajadi"},
        {"q": "Nasi lemak dibungkus dengan daun pisang keluarkan bau aroma ___?", "a": "wangi"},
        {"q": "Kelonsong pulut ketupat dianyam segi tiga guna lilitan daun ___?", "a": "palas"},
        {"q": "Plastik pembungkus mesra alam membantu bumi mengurangkan lambakan ___?", "a": "sampah"},
        {"q": "Tapak beg kertas hadiah mudah bocor basah rabak jika ia ___?", "a": "basah"},
        {"q": "Tin makanan seperti sardin diawet kedap tahan haba dan tahan ___?", "a": "lama"},
        {"q": "Pemilihan plastik lutsinar pek ais krim sejuk mestilah kalis ___?", "a": "air"},
        {"q": "Pembungkus sarang telur direka bersekat pelindung cengkerang yang nipis ___?", "a": "nipis"},
        {"q": "Reka sekat pembahagi kotak berpetak buah epal elak epal rosak ___?", "a": "berlanggar"},
        {"q": "Tarikh dikilang tanda tarikh pembuatan hari dan bulan kilang ___?", "a": "dibuat"},
        {"q": "Reka tiub plastik untuk bekas ubat gigi mudahkan ubat di ___?", "a": "picit"},
        {"q": "Pembalut perak foil kertas kerajang aluminium kawal serap suhu ___?", "a": "panas"},
        {"q": "Bekas tingkap plastik jernih nampakkan kek sedap di kawasan ___?", "a": "dalam"},
        {"q": "Reka corak susunan grafik kotak pembungkusan mesti sentiasa kreatif ___?", "a": "inovatif"},
        {"q": "Warna anyaman tradisional kraf kelarai klasik mengkuang dibungkus kelarai ___?", "a": "mengkuang"},
        {"q": "Pengilang sangat sukakan plastik nipis kerana modal belinya amat ___?", "a": "murah"},
        {"q": "Cincin perhiasan kecil barang kemas perlukan kotak pelindung baldu ___?", "a": "eksklusif"},
        {"q": "Bekas bertebing tinggi bentuk silinder sesuai untuk reka botol ___?", "a": "air"},
        {"q": "Teks teks penerangan label panduan cara guna untuk pembeli pengguna ___?", "a": "baru"},
        {"q": "Logo tengkorak amaran pada pek asid penting untuk cegah bahaya ___?", "a": "keselamatan"},
        {"q": "Produk kaca diletak logo amaran gelas retak cawan tanda amaran ___?", "a": "pecah"},
        {"q": "Sisa pembalut mesti dibuang cermat, simbol amaran sampah tong ___?", "a": "tong"},
        {"q": "Setiap produk Malaysia diwajibkan kualiti sirim tanda buatan negara ___?", "a": "malaysia"}
    ],

    "reka_bentuk_makanan": [
        {"q": "Gaya gaya kreatif susunan sajian makanan dalam pinggan dipanggil reka ___?", "a": "bentuk"},
        {"q": "Daya tarikan visual makanan menarik naikkan selera nafsu air ___?", "a": "liur"},
        {"q": "Gaya hiasan cantik bahan sampingan pada keliling makanan dipanggil ___?", "a": "gubahan"},
        {"q": "Ukiran seni buah tembikai ukir halus menggunakan pisau ukir ___?", "a": "tajam"},
        {"q": "Syarat utama dulang bekas pinggan hidangan perlu dijamin sentiasa ___?", "a": "bersih"},
        {"q": "Bentuk sayur segar lobak merah banyak diukir menjadi kelopak ___?", "a": "bunga"},
        {"q": "Rona warna warni kontras makanan menyerlahkan tambah nilai deria ___?", "a": "estetika"},
        {"q": "Makan dibalut dengan pembungkusan bento cantik di kedai nampak ___?", "a": "mahal"},
        {"q": "Roti keras alatan memotong kek roti dipotong lancar guna pisau ___?", "a": "gerigi"},
        {"q": "Muncung nozel isian aising coklat krim picit dari kelongsong beg ___?", "a": "paip"},
        {"q": "Acuan cawan mangkuk jernih serlahkan lapisan lapisan warna agar-agar ___?", "a": "puding"},
        {"q": "Perhiasan salad selalunya tambah biji tomato ceri bulat saiz ___?", "a": "kecil"},
        {"q": "Tekan penekap pemotong loyang cutter doh bentukkan rupa pastri ___?", "a": "biskut"},
        {"q": "Puncak gubahan puding diletak pucuk pudina atau daun selasih ___?", "a": "wangi"},
        {"q": "Hirisan roti keping buat hidangan sandwich dipotong melintang segi ___?", "a": "tiga"},
        {"q": "Rebusan nasi himpit pulut dihiris dadu menjadi kiub segi empat ___?", "a": "sama"},
        {"q": "Elemen kebersihan kuman tangan patut diutamakan semasa sentuh sedia ___?", "a": "makanan"},
        {"q": "Sarung perlindungan elak jangkitan balut tangan plastik nipis agar ___?", "a": "bersih"},
        {"q": "Sisa kupasan lebihan makanan kotor hiasan dibuang pantas dalam ___?", "a": "tong"},
        {"q": "Ketulan rangka ayam pisau chef pemotong bilah lebar potong bahan ___?", "a": "tebal"},
        {"q": "Peraturan dapur papan pemotong perlu kotor asingkan memotong daging mentah ___?", "a": "sayur"},
        {"q": "Konsep bekal jepun bento disusun rapat padat asingkan lauk ikut ___?", "a": "petak"},
        {"q": "Nasi goreng kampung lazat dihias jalur dadar telur kuali potong ___?", "a": "nipis"},
        {"q": "Cucuk koktail guna lidi pancing panjang sambung stabilkan bahagian hirisan ___?", "a": "buah"},
        {"q": "Bentuk acuan scoop pengorek tekan pusing tembikai cedok buah menjadi ___?", "a": "bulat"},
        {"q": "Gubahan cantik susunan kuih muih kenduri sedulang diatur seragam secara ___?", "a": "kemas"},
        {"q": "Sos pekat tiram dicorak hias simetri dilukis di kawasan birai ___?", "a": "pinggan"},
        {"q": "Sapuan lepa leper pisau palet roti bakar disapu jem strawberry ___?", "a": "manis"},
        {"q": "Tekstur sayur kobis buah epal dihiris disagat rapi guna alat ___?", "a": "parut"},
        {"q": "Bentuk kraf lipatan pau dimuncung tepi dicubit berlipat bentuk kelopak ___?", "a": "bunga"},
        {"q": "Label kod warna botol cecair pewarna makanan disahkan lulus selamat ___?", "a": "makan"},
        {"q": "Titisan ekstrak pewarna biru air hidangan nasi kerabu bunga telang ___?", "a": "asli"},
        {"q": "Warna kuih ondeh-ondeh hijau diperah ekstrak wangi dari daun pokok ___?", "a": "pandan"},
        {"q": "Deretan buah-buahan cucuk gilir lidi panjang manis panggang dipanggil hidangan ___?", "a": "kebab"},
        {"q": "Keliling lipatan kelim karipap beralun-alun pusing tepi jadi rupa ___?", "a": "ombak"},
        {"q": "Hiasan tabur aiskrim vanilla sundae manis ditabur taburan warna manik ___?", "a": "gula"},
        {"q": "Fokus pinggan reka bentuk makanan bekal bento sentiasa perlu padat ___?", "a": "sihat"},
        {"q": "Pirak makanan tertinggi kumpulan kecil harus dikurang ambil minyak gula ___?", "a": "manis"},
        {"q": "Pinggan bulat kosong putih rata pamir serlah warna susunan dengan ___?", "a": "jelas"},
        {"q": "Getah lentur lembut acuan mangkuk silikon sangat mudah terbalik keluarkan ___?", "a": "mulut"},
        {"q": "Fokus makanan hilang hiasan sampingan tidak patut berlebihan berserabut sangat ___?", "a": "sarat"},
        {"q": "Kekacang keras tekstur rasa garing rangup biskut tambah gigitan rasa ___?", "a": "sedap"},
        {"q": "Perancangan kerja draf lakaran idea kasar susunan pinggan wajar di ___?", "a": "lukis"},
        {"q": "Kewangan berniaga draf pengiraan jumlah kos modal makanan perlu agar ___?", "a": "rugi"},
        {"q": "Bakteria jahat bahaya pencemaran kebersihan alatan kotor elak merebak dari ___?", "a": "kuman"},
        {"q": "Sisa racun tani buah dan sayuran mesti wajib dibilas basuh ___?", "a": "air"},
        {"q": "Bahan daun salad layu kuning jadikan selera pemandangan pinggan tidak ___?", "a": "segar"},
        {"q": "Kanak hidangan guna corak sudu garfu rekaan tembikai comel saiz ___?", "a": "mini"},
        {"q": "Tema watak animasi bekal kotak hidangan murid kanak-kanak potong rupa ___?", "a": "kartun"},
        {"q": "Ilham seni masak kemahiran membentuk hidangan gubahan perlukan idea peribadi ___?", "a": "kreatif"}
    ],

    "pengaturcaraan_t4": [
        {"q": "Aktiviti menulis menyusun arahan kod jujukan mesin komputer dipanggil sistem ___?", "a": "pengaturcaraan"},
        {"q": "Siri senarai langkah turutan sistematik selesaikan masalah kod dipanggil arahan ___?", "a": "algoritma"},
        {"q": "Ciri algoritma yang baik ada urutan langkah satu persatu secara ___?", "a": "tertib"},
        {"q": "Cara penulisan algoritma ditaip guna teks ayat ringkas nota dipanggil ___?", "a": "pseudokod"},
        {"q": "Rajah panduan lukisan simbol bergambar grafik proses pengaturcaraan ialah carta ___?", "a": "alir"},
        {"q": "Bentuk simbol grafik lonjong bujur di carta alir menandakan fungsi ___?", "a": "mula"},
        {"q": "Kotak condong bentuk segi empat garis selari diguna menyatakan masuk ___?", "a": "input"},
        {"q": "Kotak lurus kotak segi empat biasa tepat diguna mencatat proses ___?", "a": "tindakan"},
        {"q": "Simbol serong bentuk layang-layang rombus bersoal untuk cabang proses ___?", "a": "pilihan"},
        {"q": "Garisan bersambung anak panah carta hala tunjuk sambung gerak arah ___?", "a": "aliran"},
        {"q": "Syarat tulis skrip draf pseudokod paling atas mesti bermula mula ___?", "a": "mula"},
        {"q": "Syarat nota bawah draf kod pseudokod paling bawah habis dengan ___?", "a": "tamat"},
        {"q": "Perisian ikon haiwan koding aturcara blok asas sekolah rendah iaitu ___?", "a": "scratch"},
        {"q": "Benda ikon gambar watak pelakon dalam aplikasi pentas scratch dipanggil ___?", "a": "sprite"},
        {"q": "Haiwan comel kucing meow oren ialah ikon watak asas sistem ___?", "a": "scratch"},
        {"q": "Gambar ruang belakang pentas latar belakang lakonan scratch stage dipanggil ___?", "a": "backdrop"},
        {"q": "Format menaip koding skrip baris kod cantum sambung seakan blok ___?", "a": "lego"},
        {"q": "Label skrip blok kategori pergerakan berwarna biru bahasa inggeris motion ___?", "a": "motion"},
        {"q": "Warna ungu kod rupa blok tab arahan untuk tukar muka ___?", "a": "looks"},
        {"q": "Merekod suara meow pop klik dari blok arahan tab ungu ___?", "a": "sound"},
        {"q": "Mula gerak ikon hijau kibar bendera flag diklik tanda arahan ___?", "a": "mula"},
        {"q": "Papan tanda ikon butang heksagon warna merah klik tanda kod ___?", "a": "berhenti"},
        {"q": "Arahan kawal atur skrip kod event blok events warna asas ___?", "a": "kuning"},
        {"q": "Angka taip arahan motion 'move 10 steps' jadikan kucing jalan ___?", "a": "depan"},
        {"q": "Ubah pusing arah darjah 'turn 15 degrees' jadikan badan kucing ___?", "a": "pusing"},
        {"q": "Ruang kosong luas tengah aplikasi letak kawasan susun dipanggil script ___?", "a": "area"},
        {"q": "Istilah kerosakan sangkut ralat baris arahan sistem koding rosak dipanggil ___?", "a": "bug"},
        {"q": "Baiki betulkan uji semak ralat masalah ralat komputer dipanggil nyah ___?", "a": "pepijat"},
        {"q": "Alat peranti cip memori digital elektronik mesin basuh faham bahasa ___?", "a": "mesin"},
        {"q": "Skrip set ayat sistem pengaturcaraan memberi bahasa langkah arahan kepada ___?", "a": "komputer"},
        {"q": "Peranti cip otak kawal alat elektrik rumah pintu automatik mikropemproses ___?", "a": "mikropengawal"},
        {"q": "Alat pintar sistem pintar telefon rumah tv pintar dikawal oleh ___?", "a": "kod"},
        {"q": "Blok ayat logik tanya 'if then' ialah cabang struktur laluan ___?", "a": "pilihan"},
        {"q": "Blok urutan 'repeat 10' pusing memusing buat benda sama dipanggil ___?", "a": "gelung"},
        {"q": "Flow turun laju turun blok lurus set langkah sebaris ialah ___?", "a": "jujukan"},
        {"q": "Lokasi paksi kordinat pergerakan garis lintang paksi titik koordinat paksi ___?", "a": "x"},
        {"q": "Lokasi graf kordinat gerak lurus naik atas atau pacak tegak ___?", "a": "y"},
        {"q": "Skrip baca blok kata bubble dialog 'say hello' cetak kotak ___?", "a": "teks"},
        {"q": "Menjaga memelihara simpan muat turun projek koding kerja ke menu ___?", "a": "fail"},
        {"q": "Arahan langgar sempadan sempadan bingkai skrin kucing lantun tab 'bounce' ___?", "a": "edge"},
        {"q": "Tetap tempoh lengah jeda masa tunggu 'wait 1 sec' sekat ___?", "a": "tunggu"},
        {"q": "Kod kawal 'forever' pusing pusing pusing terus tanpa rehat arahan ___?", "a": "gelung"},
        {"q": "Logik contoh pseudokod seduh teh, langkah awal sediakan gula dan ___?", "a": "air"},
        {"q": "Logik carta alir soal jawab 'adakah susu manis' letak kotak ___?", "a": "rombus"},
        {"q": "Proses selesai akhir output carta alir letak kotak condong segi ___?", "a": "selari"},
        {"q": "Tunjuk baca carta dari kotak atas susur turun bawah ikut garisan ___?", "a": "panah"},
        {"q": "Skrip blok utama events klik arahan mulakan gerak ikon bendera warna ___?", "a": "hijau"},
        {"q": "Kemahiran bijak koding sains komputer bantu minda pantas fikir secara ___?", "a": "logik"},
        {"q": "Berlatih tulis kod uji baiki susun blok latih kemahiran selesaikan ___?", "a": "masalah"},
        {"q": "Peluang pekerjaan bidang IT bina aplikasi aturcara program digital dipanggil ___?", "a": "pengaturcara"}
    ],

"teknologi_rumah_tangga": [
        {"q": "Kerja mencantum dua keping kain menggunakan benang dipanggil seni ___?", "a": "jahitan"},
        {"q": "Alatan tajam berlubang untuk memasukkan benang ialah ___?", "a": "jarum"},
        {"q": "Alatan memotong fabrik kain dengan lurus ialah ___?", "a": "gunting"},
        {"q": "Mengukur panjang fabrik sebelum dipotong memerlukan pita ___?", "a": "ukur"},
        {"q": "Mata jahitan sementara untuk menetapkan kedudukan kain ialah jelujur ___?", "a": "kasar"},
        {"q": "Jahitan kekal yang kukuh menyerupai jahitan mesin ialah jahitan ___?", "a": "kia"},
        {"q": "Jahitan mengemaskan tepi kain agar tidak berbulu ialah lilit ___?", "a": "ubi"},
        {"q": "Jahitan hiasan corak silang pangkah di tepi kain dipanggil silang ___?", "a": "pangkah"},
        {"q": "Roda bergeri tajam untuk memindahkan tanda pola ialah roda ___?", "a": "surih"},
        {"q": "Kertas karbon warna digunakan bersama roda surih untuk membuat ___?", "a": "tanda"},
        {"q": "Kapur tukang jahit diguna melukis garisan pola atas ___?", "a": "kain"},
        {"q": "Menanggalkan mata jahitan yang tersilap memerlukan alat peretas ___?", "a": "jahitan"},
        {"q": "Menyemat kepingan fabrik agar tidak lari guna jarum ___?", "a": "peniti"},
        {"q": "Benang perlu dimasukkan ke dalam lubang jarum yang dipanggil ___?", "a": "mata"},
        {"q": "Bekas simpanan jarum yang selamat dipanggil kusyen ___?", "a": "pin"},
        {"q": "Sisa kain lebihan digunting panggil perca ___?", "a": "kain"},
        {"q": "Contoh artikel jahitan mudah ialah sarung ___?", "a": "bantal"},
        {"q": "Jahitan menyambung dua fabrik secara tetap ialah jelujur ___?", "a": "halus"},
        {"q": "Jahit kia sangat rapat dan amat ___?", "a": "kukuh"},
        {"q": "Bahan utama membuat artikel jahitan semestinya ialah ___?", "a": "fabrik"},
        {"q": "Tali halus untuk mencantumkan fabrik dipanggil ___?", "a": "benang"},
        {"q": "Sarung logam pelindung jari elak tercucuk jarum dipanggil ___?", "a": "didal"},
        {"q": "Kertas draf lukisan ukuran baju dipanggil kertas ___?", "a": "pola"},
        {"q": "Tanda kapur pada kain mudah hilang apabila di___?", "a": "basuh"},
        {"q": "Gunting fabrik dilarang guna potong kertas agar bilahnya kekal ___?", "a": "tajam"},
        {"q": "Pembaris sesiku L pastikan sudut ukuran kain sentiasa ___?", "a": "tepat"},
        {"q": "Fabrik kapas serap peluh amat sesuai dijadikan baju ___?", "a": "tidur"},
        {"q": "Jenis kain licin berkilat mahal harganya ialah kain ___?", "a": "sutera"},
        {"q": "Fabrik tebal berbulu sesuai buat selimut ialah ___?", "a": "flanel"},
        {"q": "Benang sulam tebal jadikan hiasan bunga lebih ___?", "a": "timbul"},
        {"q": "Kapas fiber poliester diguna jadi bahan ___ bantal?", "a": "isi"},
        {"q": "Hiasan butang berlubang dua dijahit guna teknik jahitan ___?", "a": "silang"},
        {"q": "Tampalan corak hiasan kain atas fabrik dipanggil seni ___?", "a": "aplike"},
        {"q": "Hiasan reben diikat bentuk rama-rama pada sarung tangan ___?", "a": "ketuhar"},
        {"q": "Hasil ciptaan kain siap dijahit panggil artikel ___?", "a": "jahitan"},
        {"q": "Benang dijahit simpul mati di hujung supaya kain tidak ___?", "a": "terbuka"},
        {"q": "Gunting kecil tajam memotong lebihan benang ialah gunting ___?", "a": "snipper"},
        {"q": "Kain felt mudah dibentuk kerana sisinya tidak ___?", "a": "berbulu"},
        {"q": "Jahitan insang pari kemaskan tepi dan nampak sangat ___?", "a": "cantik"},
        {"q": "Peniti dicabut satu persatu ketika kerja jahitan sedang ___?", "a": "berjalan"},
        {"q": "Roda surih ditekan atas garisan pola untuk memindah ___?", "a": "tanda"},
        {"q": "Fabrik jeans biru sangat lasak dan ___?", "a": "tebal"},
        {"q": "Benang polyester kuat tahan lasak dan sukar ___?", "a": "putus"},
        {"q": "Jarum mesin jahit tidak boleh diguna untuk jahit ___?", "a": "tangan"},
        {"q": "Pembaris lurus kayu ukur fabrik ukuran panjang dalam ___?", "a": "meter"},
        {"q": "Kotak plastik susun atur alatan jahit panggil kotak ___?", "a": "jahitan"},
        {"q": "Kain tuala serap air sesuai dibuat alas ___?", "a": "meja"},
        {"q": "Manik kilat kecil dijahit rapat jadi hiasan ___?", "a": "baju"},
        {"q": "Kain renda berlubang tambah seri cantik pada ___ kain?", "a": "tepi"},
        {"q": "Ilmu kemahiran menjahit boleh jana sumber wang ___?", "a": "pendapatan"}
    ],

    "kejuruteraan": [
        {"q": "Sumber tenaga alam yang tidak akan habis dipanggil tenaga boleh ___?", "a": "baharu"},
        {"q": "Tenaga dari cahaya pancaran matahari panggil tenaga ___?", "a": "suria"},
        {"q": "Panel kaca serap haba cahaya matahari panggil panel ___?", "a": "solar"},
        {"q": "Kipas gergasi pusing tiupan angin panggil kincir ___?", "a": "angin"},
        {"q": "Aliran air sungai deras hasilkan empangan tenaga ___?", "a": "hidro"},
        {"q": "Bahan sisa reput tumbuhan dan haiwan hasilkan tenaga ___?", "a": "biomas"},
        {"q": "Tenaga haba bumi bawah tanah panggil tenaga ___?", "a": "geoterma"},
        {"q": "Ombak laut beralun besar jana tenaga stesen ___?", "a": "ombak"},
        {"q": "Penggunaan tenaga suria dapat jimatkan bil elektrik ___?", "a": "rumah"},
        {"q": "Asap kilang bakar arang batu cemar udara dan ___?", "a": "alam"},
        {"q": "Tenaga fosil petrol dan diesel lambat laun akan ___?", "a": "habis"},
        {"q": "Solar panel ubah cahaya matahari jadi arus ___?", "a": "elektrik"},
        {"q": "Kereta hibrid moden guna enjin petrol dan motor ___?", "a": "bateri"},
        {"q": "Bateri simpan kuasa elektrik bahan kimia untuk guna waktu ___?", "a": "malam"},
        {"q": "Motor DC tukar arus elektrik kepada pergerakan ___?", "a": "mekanikal"},
        {"q": "Gear roda bergigi pindah kuasa putaran kelajuan ___?", "a": "enjin"},
        {"q": "Suis tekan buka dan tutup aliran litar ___?", "a": "elektrik"},
        {"q": "Mentol LED jimat kuasa keluar cahaya sangat ___?", "a": "terang"},
        {"q": "Wayar kuprum bersalut getah merah bawa arus elektrik ___?", "a": "positif"},
        {"q": "Wayar kuprum bersalut getah hitam bawa arus elektrik ___?", "a": "negatif"},
        {"q": "Pemegang bateri tempat simpan dan sambung sel ___?", "a": "kering"},
        {"q": "Dinamo basikal geser tayar hidupkan lampu masa ___?", "a": "kayuh"},
        {"q": "Kincir angin guna kuasa tiupan untuk pusingkan ___?", "a": "bilah"},
        {"q": "Tenaga boleh baharu sangat mesra dan selamatkan ___?", "a": "bumi"},
        {"q": "Panel solar bumbung rumah serap haba waktu ___?", "a": "siang"},
        {"q": "Penjana generator tukar gerak mekanikal kepada ___?", "a": "elektrik"},
        {"q": "Model kereta solar cilik lumba laju waktu tengah ___?", "a": "hari"},
        {"q": "Bahan kitar semula botol plastik boleh buat badan ___?", "a": "kereta"},
        {"q": "Lidi sate kayu panjang boleh jadi gandar ___?", "a": "tayar"},
        {"q": "Penutup botol tebuk lubang letak lidi jadikan roda ___?", "a": "bulat"},
        {"q": "Pita pelekat ikat motor DC kukuh pada tapak ___?", "a": "casis"},
        {"q": "Bod lekap ringan kuat buat bingkai badan ___?", "a": "model"},
        {"q": "Pembaris besi ukur saiz bod lekap agar potong ___?", "a": "tepat"},
        {"q": "Pisau tajam keratan bod lekap potong atas alas ___?", "a": "pemotong"},
        {"q": "Gam pistol panas cantum kuat sisa bahan ___?", "a": "projek"},
        {"q": "Ujian model kereta solar jalan lurus trek waktu ___?", "a": "panas"},
        {"q": "Jika kereta undur belakang, wayar sambungan motor perlu di___?", "a": "tukar"},
        {"q": "Model kereta elektrik bergerak perlahan, mungkin kuasa bateri ___?", "a": "lemah"},
        {"q": "Tenaga hidro elektrik Malaysia empangan sungai ___?", "a": "bakun"},
        {"q": "Penggunaan kereta elektrik kurangkan pelepasan gas ___?", "a": "karbon"},
        {"q": "Reka bentuk kereta aerodinamik angin laju potong ___?", "a": "rintangan"},
        {"q": "Bumbung stesen bas moden pasang panel jana lampu ___?", "a": "led"},
        {"q": "Ciptaan kejuruteraan mudahkan manusia jalan kerja ___?", "a": "harian"},
        {"q": "Geoterma haba wap air tanah pancut air ___?", "a": "panas"},
        {"q": "Tenaga suria kalkulator guna sel panel sangat ___?", "a": "kecil"},
        {"q": "Pengguna tenaga hijau bantu alam sekitar sentiasa ___?", "a": "bersih"},
        {"q": "Bekalan arang batu wujudkan fenomena rumah ___?", "a": "hijau"},
        {"q": "Inovasi kincir angin laut jana kuasa elektrik ___?", "a": "besar"},
        {"q": "Projek model berjaya gerak cemerlang catat markah ___?", "a": "tinggi"},
        {"q": "Pelajar reka bentuk kejuruteraan cemerlang aset masa ___?", "a": "depan"}
    ],

    "pengaturcaraan_t5": [
        {"q": "Otak komputer kecil kawal mesin dipanggil papan ___?", "a": "mikropengawal"},
        {"q": "Peranti kawal lampu isyarat jalan guna sistem ___?", "a": "automatik"},
        {"q": "Papan mikropengawal popular di sekolah dipanggil micro ___?", "a": "bit"},
        {"q": "Butang abjad huruf A dan B pada papan panggil butang ___?", "a": "tekan"},
        {"q": "Skrin kecil merah papan bit ada 25 biji lampu ___?", "a": "led"},
        {"q": "Palam penyambung wayar buaya jepit panggil klip ___?", "a": "buaya"},
        {"q": "Papan reka bit disambung ke komputer guna kabel ___?", "a": "usb"},
        {"q": "Aplikasi web kod susun tarik blok arahan panggil make ___?", "a": "code"},
        {"q": "Blok arahan teks tulis angka nombor panggil blok ___?", "a": "nombor"},
        {"q": "Blok arahan keluar mesej huruf skrin panggil blok ___?", "a": "rentetan"},
        {"q": "Gelung arahan loop ulang benda sama berkali ___?", "a": "kali"},
        {"q": "Syarat if then else masuk cabang pilihan arahan ___?", "a": "logik"},
        {"q": "Kotak arahan on start mula laksana kod dari ___?", "a": "awal"},
        {"q": "Kotak arahan forever ulang kod sampai bila ___?", "a": "bila"},
        {"q": "Peranti input kesan panas sejuk bilik panggil penderia ___?", "a": "suhu"},
        {"q": "Peranti masuk kesan gelap terang panggil penderia ___?", "a": "cahaya"},
        {"q": "Main melodi lagu bunyi audio dari arahan blok ___?", "a": "muzik"},
        {"q": "Gambar jantung kelip kelip pilih ikon led rupa ___?", "a": "hati"},
        {"q": "Bateri pek AAA bagi kuasa pada papan ___?", "a": "microbit"},
        {"q": "Ralat kerosakan kod tidak jalan panggil bug ___?", "a": "pepijat"},
        {"q": "Baiki kod salah komputer rosak panggil nyah ___?", "a": "pepijat"},
        {"q": "Papan bit boleh gegar kesan pergerakan guna fungsi ___?", "a": "pecutan"},
        {"q": "Guna pin bumi ground negatif pada papan label ___?", "a": "gnd"},
        {"q": "Tulis aturcara susun blok arahan dipanggil kerja ___?", "a": "pengekodan"},
        {"q": "Format muat turun fail kod hex khas untuk papan ___?", "a": "bit"},
        {"q": "Buka perisian pelayar web taip alamat url di ___?", "a": "internet"},
        {"q": "Blok muzik play tone keluar nada bunyi ___?", "a": "bunyi"},
        {"q": "Kipas pintar automatik pusing laju bila penderia kesan ___?", "a": "panas"},
        {"q": "Pintu pasaraya buka sendiri kesan laluan orang guna penderia ___?", "a": "gerakan"},
        {"q": "Palam buzzer sambung klip buaya keluar bunyi ___?", "a": "bip"},
        {"q": "Wayar klip buaya merah kepit pin kuasa tiga ___?", "a": "volt"},
        {"q": "Input suis butang loceng rumah tekan untuk ___?", "a": "bunyi"},
        {"q": "Pemboleh ubah variable simpan rekod nilai data ___?", "a": "markah"},
        {"q": "Blok input butang abjad A ditekan skrin tunjuk ___?", "a": "huruf"},
        {"q": "Goncang papan bit on shake keluar ikon dadu ___?", "a": "rawak"},
        {"q": "Lampun isyarat lalu lintas kereta ada tiga ___?", "a": "warna"},
        {"q": "Komponen output nyala amaran merah panggil lampu ___?", "a": "led"},
        {"q": "Cip mikropengawal otak utama elektronik kawal operasi ___?", "a": "sistem"},
        {"q": "Kereta robot elak langgar dinding guna penderia jarak ___?", "a": "ultrasonik"},
        {"q": "Sistem palang tol angkat naik guna putaran motor ___?", "a": "servo"},
        {"q": "Arahan pause henti rehat masa sekejap dalam kiraan ___?", "a": "saat"},
        {"q": "Blok logik matematik operasi campur tolak darab ___?", "a": "bahagi"},
        {"q": "Penderia terbina dalam bit baca tahap darjah ___?", "a": "suhu"},
        {"q": "Cipta koding mesin automatik basuh baju pusing ___?", "a": "motor"},
        {"q": "Periuk nasi moden masak nasi bila ditekan satu ___?", "a": "butang"},
        {"q": "Murid pengaturcara bijak susun kod tiada sebarang ___?", "a": "ralat"},
        {"q": "Simpan muat turun save projek siap ke dalam ___ komputer?", "a": "folder"},
        {"q": "Robot gerak depan jika bacaan penderia halangan jalan ___?", "a": "jelas"},
        {"q": "Kongsi kod ciptaan pautan web internet rakan kawan ___?", "a": "lihat"},
        {"q": "Pelajar mahir asah kemahiran IT hadapi cabaran masa ___?", "a": "depan"}
    ],

    "teknologi_pertanian": [
        {"q": "Kaedah tanam sayur bandar jimat ruang panggil pertanian ___?", "a": "bandar"},
        {"q": "Tanam sayur dalam bekas air takung bernutrisi panggil sistem ___?", "a": "takungan"},
        {"q": "Tanam sayur pasu di balkoni simen flat apartmen ___?", "a": "tinggi"},
        {"q": "Botol plastik terbuang dikitar semula jadikan bekas ___?", "a": "tanaman"},
        {"q": "Sistem hidroponik guna air baja cair tanpa tanah ___?", "a": "hitam"},
        {"q": "Bekas palung paip pvc tebuk lubang tanam ___ pokok?", "a": "sayur"},
        {"q": "Span potong dadu serap air basah tempat semai ___?", "a": "biji"},
        {"q": "Benih kangkung bayam sangat sesuai tanam hidroponik daun ___?", "a": "hijau"},
        {"q": "Rockwool bulu mineral gentian simpan air pegang semaian ___?", "a": "benih"},
        {"q": "Benang mop kapilari berfungsi serap hisap naik air ___?", "a": "baja"},
        {"q": "Pam pusing air paip oksigen gabung pelihara ikan panggil ___?", "a": "akuaponik"},
        {"q": "Baja cecair kimia campur nutrisi tanaman baja ___?", "a": "ab"},
        {"q": "Leca tanah liat bulat bakar sokong cengkam akar ___?", "a": "pokok"},
        {"q": "Pasir kasar batu kelikir takung air bebas kotoran ___?", "a": "bersih"},
        {"q": "Bakul netpot bekas raga lubang letak span juntaikan ___?", "a": "akar"},
        {"q": "Gunting botol belah dua masuk benang sumbu dari ___?", "a": "bawah"},
        {"q": "Nyamuk denggi membiak air takung halang dengan serbuk ___?", "a": "abate"},
        {"q": "Cahaya mentari kena daun buat proses buat makanan ___?", "a": "fotosintesis"},
        {"q": "Kawalan jaring kelambu serangga elak belalang ulat ___?", "a": "makan"},
        {"q": "Sukatan baja penutup bekas botol ukur dalam unit ___?", "a": "mililiter"},
        {"q": "Tanam pokok sedut gas berbahaya gas karbon ___?", "a": "dioksida"},
        {"q": "Tuai potong sayur segar masak terus sedap di___?", "a": "makan"},
        {"q": "Sayur organik hidroponik bebas racun kimia badan ___?", "a": "sihat"},
        {"q": "Susun rak pvc menegak bertingkat jimatkan ruang kawasan ___?", "a": "sempit"},
        {"q": "Tanam daun pandan pudina wangi hidroponik hiasan tepi ___?", "a": "dapur"},
        {"q": "Botol cat dibalut warna gelap halang tumbesaran lumut ___?", "a": "hijau"},
        {"q": "Lumut curi baja oksigen air jadikan pokok sakit ___?", "a": "bantut"},
        {"q": "Benih kacang hijau rendam air malam bagi biji ___?", "a": "cambah"},
        {"q": "Span basah tebuk celah tengah masuk benih guna ___?", "a": "lidi"},
        {"q": "Akar pokok tumbuh panjang wajib menjuntai sentuh air ___?", "a": "baja"},
        {"q": "Periksa paras air takung kering cepat tambah air ___?", "a": "paip"},
        {"q": "Baja A dan B asing botol elak tindakbalas ___?", "a": "beku"},
        {"q": "Ikan keli tilapia berak air kumbahan jadi baja ___?", "a": "najis"},
        {"q": "Akar lebat serap kotoran tapis air bersih kolam ___?", "a": "ikan"},
        {"q": "Kerja berkebun tanam sayur aktiviti riadah musim ___?", "a": "cuti"},
        {"q": "Tanaman kebun tepi rumah jimat duit beli di ___?", "a": "pasar"},
        {"q": "Sabut kelapa hancur cocopeat ringan pegang kelembapan ___?", "a": "air"},
        {"q": "Baja sisa sayur dapur reput campur jadi kompos ___?", "a": "organik"},
        {"q": "Pasu dinding tegak vertical garden gantung tak guna ___?", "a": "lantai"},
        {"q": "Sistem titis paip mikro halus jimat guna air ___?", "a": "titisan"},
        {"q": "Tali dawai gantung paip pvc kukuh tak putus jatuh ___?", "a": "bawah"},
        {"q": "Pisau pemotong tebuk lubang botol tajam elak tangan ___?", "a": "luka"},
        {"q": "Uji jalan pam air bocor tampal letak gam ___?", "a": "tampal"},
        {"q": "Alat ec meter celup ukur kepekatan baja litar ___?", "a": "elektrik"},
        {"q": "Sayur salad daun lebat subur petik makan buat ulam ___?", "a": "mentah"},
        {"q": "Sembur cecair cuka kayu halau ulat serangga perosak ___?", "a": "perosak"},
        {"q": "Akar hitam lembik luruh mati tanda takung air tak ___?", "a": "bersih"},
        {"q": "Pokok cili hidroponik buah masak warna merah amat ___?", "a": "pedas"},
        {"q": "Tuai kangkung potong batang akar tumbuh pucuk muda ___?", "a": "baru"},
        {"q": "Ilmu tani moden bantu sekuriti makanan penduduk negara ___?", "a": "makanan"}
    ],

"elektromekanikal": [
        {"q": "Gabungan elemen elektrik dan fungsi mekanikal dipanggil ___?", "a": "elektromekanikal"},
        {"q": "Litar yang membekalkan arus kuasa dipanggil sistem ___?", "a": "elektrik"},
        {"q": "Bahagian litar kawalan cip mikropengawal dipanggil sistem ___?", "a": "elektronik"},
        {"q": "Sistem yang melibatkan roda dan putaran dipanggil sistem ___?", "a": "mekanikal"},
        {"q": "Roda bergigi yang memindahkan kelajuan rantai dipanggil ___?", "a": "gear"},
        {"q": "Roda beralur bulat yang memegang tali getah dipanggil ___?", "a": "takal"},
        {"q": "Tali getah penghubung memusingkan dua takal panggil tali ___?", "a": "sawat"},
        {"q": "Motor DC menukar elektrik kepada tenaga pusingan ___?", "a": "mekanikal"},
        {"q": "Komponen pemutus dan penyambung litar elektrik dipanggil ___?", "a": "suis"},
        {"q": "Bateri bertindak sebagai sumber bekalan tenaga litar ___?", "a": "elektrik"},
        {"q": "Bekas untuk memegang sel kering bateri dipanggil ___?", "a": "pemegang"},
        {"q": "Rantai besi basikal menghubungkan putaran antara dua ___?", "a": "gear"},
        {"q": "Wayar kuprum disalut getah berwarna merah untuk kutub ___?", "a": "positif"},
        {"q": "Wayar kuprum disalut getah berwarna hitam untuk kutub ___?", "a": "negatif"},
        {"q": "Mesin basuh moden menggunakan sistem putaran secara ___?", "a": "elektromekanikal"},
        {"q": "Pemutar skru silang hujungnya berbentuk alur ___?", "a": "pangkah"},
        {"q": "Pemutar skru alur rata hujungnya berbentuk garis ___?", "a": "lurus"},
        {"q": "Bod impra plastik berongga sangat ringan untuk buat badan ___?", "a": "projek"},
        {"q": "Alat memotong bod impra paling tajam ialah pisau ___?", "a": "kraf"},
        {"q": "Alas bergrid elak meja tercalar semasa potong panggil alas ___?", "a": "pemotong"},
        {"q": "Alat muncung tirus untuk membengkok dawai dipanggil ___?", "a": "playar"},
        {"q": "Tukul kuku kambing digunakan untuk mengetuk dan mencabut ___?", "a": "paku"},
        {"q": "Memotong lebihan kepingan zink memerlukan alat gunting ___?", "a": "logam"},
        {"q": "Gergaji puting memotong batang kayu secara garis ___?", "a": "lurus"},
        {"q": "Jika tali sawat putus, pusingan motor tidak dapat ___?", "a": "bergerak"},
        {"q": "Gear rak dan pinan biasa dijumpai pada sistem pintu pagar ___?", "a": "automatik"},
        {"q": "Mesin pengisar jus di dapur memutar bilah guna kuasa ___?", "a": "motor"},
        {"q": "Pita pelekat kuat mencantum sisi kotak projek supaya ___?", "a": "kukuh"},
        {"q": "Bila suis ditekan tutup, litar bersambung dan arus ___?", "a": "mengalir"},
        {"q": "Bila suis ditekan buka, litar terputus dan lampu akan ___?", "a": "padam"},
        {"q": "Mentol LED sangat jimat elektrik dan menyala amat ___?", "a": "terang"},
        {"q": "Kerja mencantum sambungan wayar litar guna besi ___?", "a": "pemateri"},
        {"q": "Timah pateri cair yang panas melekatkan wayar dengan ___?", "a": "kuat"},
        {"q": "Papan litar elektronik hijau cetakan pateri dipanggil papan ___?", "a": "pcb"},
        {"q": "Bateri telefon pintar jenis lithium boleh dicas berkali ___?", "a": "kali"},
        {"q": "Kereta mainan kawalan jauh bergerak gabung elektrik dan ___?", "a": "mekanikal"},
        {"q": "Jika gear motor saiz besar, roda tayar pusing amat ___?", "a": "laju"},
        {"q": "Lakaran rancangan idea projek dilukis dengan pensel di atas ___?", "a": "kertas"},
        {"q": "Projek palang tol guna motor berputar sudut panggil motor ___?", "a": "servo"},
        {"q": "Takal tali sawat kren sangat kuat memanjat angkat beban ___?", "a": "berat"},
        {"q": "Guna kotak botol terpakai menjimatkan perbelanjaan kos ___?", "a": "modal"},
        {"q": "Bumbung badan kereta ditutup rapat elak air hujan ___?", "a": "masuk"},
        {"q": "Cat semburan warna warni menjadikan hasil projek tampak ___?", "a": "cantik"},
        {"q": "Setiap projek siap mestilah dipasang suis untuk di___?", "a": "uji"},
        {"q": "Litar pintas kerosakan ralat berlaku jika wayar positif sentuh ___?", "a": "negatif"},
        {"q": "Bateri buang litar terbakar asap bau sangat ___?", "a": "hangit"},
        {"q": "Kabel litar bersepah perlu diikat balut supaya nampak ___?", "a": "kemas"},
        {"q": "Lakaran susun atur dalam manual pengguna sebagai panduan ___?", "a": "pemasangan"},
        {"q": "Robot elektromekanikal bantu kurangkan beban tugas otot ___?", "a": "manusia"},
        {"q": "Hasil seni inovasi mekanikal wajar dikagumi dan di___?", "a": "hargai"}
    ],

    "pengaturcaraan_t6": [
        {"q": "Robot pintar bergerak dikawal oleh papan otak ___?", "a": "mikropengawal"},
        {"q": "Tulisan set arahan kod blok komputer dipanggil sistem ___?", "a": "pengaturcaraan"},
        {"q": "Binaan robot beroda berjalan guna kuasa motor arus ___?", "a": "terus"},
        {"q": "Robot kereta elak langgar dinding guna penderia kesan ___?", "a": "ultrasonik"},
        {"q": "Robot menjejak ikut garisan lantai guna penderia cahaya ___?", "a": "inframerah"},
        {"q": "Komponen output mengeluarkan bunyi amaran bip dipanggil ___?", "a": "buzer"},
        {"q": "Komponen output lampu dioda berkelip kelip ialah mentol ___?", "a": "led"},
        {"q": "Papan kuasa robot dihidupkan dengan sel bateri boleh ___?", "a": "cas"},
        {"q": "Blok gelung loop arahan pusing kod tak henti panggil ___?", "a": "selamanya"},
        {"q": "Blok logik jika maka uji keputusan syarat panggil ___?", "a": "logik"},
        {"q": "Arahan kod hentikan putaran tayar robot panggil fungsi ___?", "a": "berhenti"},
        {"q": "Arahan tayar pusing depan lurus panggil fungsi jalan ___?", "a": "maju"},
        {"q": "Arahan tayar pusing terbalik jalan belakang panggil fungsi ___?", "a": "undur"},
        {"q": "Kod tayar pusing belok mengubah laluan arah panggil ___?", "a": "belok"},
        {"q": "Pemindahan fail hex masuk ke papan cip melalui kabel ___?", "a": "usb"},
        {"q": "Kesilapan kecacatan litar rosak ralat skrip dipanggil ___?", "a": "pepijat"},
        {"q": "Kerja menguji membaiki ralat kod program panggil nyah ___?", "a": "pepijat"},
        {"q": "Cip pemacu motor kawal kelajuan tayar dipanggil litar ___?", "a": "pemacu"},
        {"q": "Dua tayar robot pusing depan serentak, robot pergi ke ___?", "a": "depan"},
        {"q": "Tayar kiri pusing, tayar kanan henti, robot pusing ke ___?", "a": "kanan"},
        {"q": "Sensor ultrasonik membaca jarak halangan dalam unit ukuran ___?", "a": "sentimeter"},
        {"q": "Gelombang bunyi ultrasonik melantun balik gema bila kena ___?", "a": "objek"},
        {"q": "Sensor ldr amat peka dengan darjah kecerahan sumber ___?", "a": "cahaya"},
        {"q": "Carta alir dilukis simbol kotak oval bermula dan ___?", "a": "tamat"},
        {"q": "Pseudokod tulis langkah draf kod dalam format struktur ___? ", "a": "teks"},
        {"q": "Nama laci blok tempat simpan rekod kira data dipanggil pemboleh ___?", "a": "ubah"},
        {"q": "Aplikasi mblock grafik skrin paparkan kucing comel dipanggil ___?", "a": "sprite"},
        {"q": "Wayar pelompat jumper sambung pin cucuk lubang papan ___?", "a": "litar"},
        {"q": "Laluan luar bawa masuk bacaan deria sensor panggil port ___?", "a": "input"},
        {"q": "Laluan keluar arah operasi jalan tayar panggil port ___?", "a": "output"},
        {"q": "Program tarik lepas tetikus mouse panggil tarik dan ___?", "a": "lepas"},
        {"q": "Pintu cermin pasaraya buka tutup sendiri guna sensor kesan ___?", "a": "gerakan"},
        {"q": "Lampu jalan waktu malam nyala sendiri kesan cahaya ___?", "a": "gelap"},
        {"q": "Sistem siram pokok auto kesan tahap kelembapan siram ___?", "a": "tanah"},
        {"q": "Tekan on sistem litar bateri kuasa akan mula ___?", "a": "hidup"},
        {"q": "Jalan uji robot lumba di atas lantai atau papan ___?", "a": "trek"},
        {"q": "Lengan mekanikal pasang tayar di kilang buat kereta ___?", "a": "robot"},
        {"q": "Robot moden kerja laju berat hari malam tanpa rasa ___?", "a": "penat"},
        {"q": "Jujukan lurus satu garisan alir ikut turutan nombor ___?", "a": "langkah"},
        {"q": "Wayar klip klip besi salah pasang terbakar papan akan ___?", "a": "rosak"},
        {"q": "Mesin pembersih hampagas bulat sedut buang sisa kotor ___?", "a": "habuk"},
        {"q": "Pertandingan cabaran robotik sekolah uji kelajuan lawan ___?", "a": "kawan"},
        {"q": "Pelayan memori awan kongsi projek kod hantar pautan ___?", "a": "web"},
        {"q": "Profesional reka tulis kod perisian robot panggil jurutera ___?", "a": "komputer"},
        {"q": "Minda logik asah fikiran murid bijak urus selesaikan ___?", "a": "masalah"},
        {"q": "Kod atur arahan gelung ulang proses jimatkan penulisan ___?", "a": "blok"},
        {"q": "Simbol segi empat selari senget baca aliran data ___?", "a": "masuk"},
        {"q": "Komputer tablet wifi skrin sentuh taip kod sentuh ___?", "a": "skrin"},
        {"q": "Robotika perindustrian negara maju gerak ekonomi era digital ___?", "a": "automatik"},
        {"q": "Murid bijak it masa depan negara kuasai ilmu ___?", "a": "teknologi"}
    ],

    "pembangunan_produk": [
        {"q": "Proses penciptaan barang ciptaan guna semua tajuk rbt panggil ___?", "a": "produk"},
        {"q": "Penghasilan barangan binaan baharu untuk keperluan awam panggil ___?", "a": "pembangunan"},
        {"q": "Gabung dua tajuk pertanian jahitan hasil ciptaan moden ___?", "a": "inovasi"},
        {"q": "Idea draf grafik awal dilukis atas kertas pensel panggil ___?", "a": "lakaran"},
        {"q": "Pilih nilai satu lukisan paling baik jadi lakaran ___?", "a": "akhir"},
        {"q": "Ubah suai bentuk lama agar nampak lebih fungsi panggil ___?", "a": "penambahbaikan"},
        {"q": "Langkah ukur dimensi panjang tinggi guna alat kayu ___?", "a": "pembaris"},
        {"q": "Senarai senarai peralatan perkakasan projek panggil bahan dan ___?", "a": "alatan"},
        {"q": "Jumlah belanja modal wang wang ringgit dibayar panggil ___?", "a": "kos"},
        {"q": "Harga kos bayaran tenaga titik peluh pekerja manusia panggil ___?", "a": "upah"},
        {"q": "Kos bil sewa elektrik air kilang pengurusan panggil ___?", "a": "overhed"},
        {"q": "Campur kos bahan upah overhed akan dapat jumlah kos ___?", "a": "pengeluaran"},
        {"q": "Bila jual di pasar niaga harga mestilah dinaikkan demi ___?", "a": "untung"},
        {"q": "Langkah cantum bina potong kraf bina bentuk model ___?", "a": "sebenar"},
        {"q": "Kerja buat cantikkan produk balut kotak pek bekas ___?", "a": "pembungkusan"},
        {"q": "Kaedah sebar maklumat kelebihan barang promosi pada pembeli ___?", "a": "iklan"},
        {"q": "Promosi barang tular tekan like share di aplikasi platform ___?", "a": "sosial"},
        {"q": "Kertas helai cetak gambar edar di jalanan iklan promosi ___?", "a": "risalah"},
        {"q": "Lisan berdiri di hadapan kelas cerita jual produk panggil ___?", "a": "pembentangan"},
        {"q": "Cakap promosi lantang jelas tarik hati orang jadi ___?", "a": "yakin"},
        {"q": "Pusing suis enjin on tengok kipas uji pastikan tidak ___?", "a": "rosak"},
        {"q": "Pecah kayu longgar lekatkan sambung semula guna pistol gam ___?", "a": "panas"},
        {"q": "Pemasaran perniagaan jual beli e-dagang kedai runcit di ___?", "a": "internet"},
        {"q": "Fungsi keselamatan alat tajam tidak potong kulit jari tidak ___?", "a": "luka"},
        {"q": "Kualiti kraf produk ketahanan tidak mudah patah sangat ___?", "a": "kukuh"},
        {"q": "Teks label grafik kotak mesti ada harga nama kilang ___?", "a": "jenama"},
        {"q": "Buku rekod baki duit untung perniagaan wang tunai wang ___?", "a": "masuk"},
        {"q": "Kumpulan rakan usaha projek sama muafakat berkat tolong saling ___?", "a": "bekerjasama"},
        {"q": "Sisa barang guna semula surat khabar botol dipanggil sisa ___?", "a": "kitar"},
        {"q": "Carta garis draf jadual kerja mingguan tempoh masa siap ___?", "a": "gantt"},
        {"q": "Kemasan akhir spray varnis cat sembur produk kilat sangat ___?", "a": "cantik"},
        {"q": "Peniaga senang hati habis barang laku cepat laku ___?", "a": "laris"},
        {"q": "Barang kualiti tinggi harga murah buat hati pembeli amat ___?", "a": "berbaloi"},
        {"q": "Letak lekat tag hias corak sulam labuci riben benda ___?", "a": "hiasan"},
        {"q": "Buku buku lipat kotak ajar butang on tekan cara ___?", "a": "guna"},
        {"q": "Slip cetak bukti pelanggan beli bayar kedai bil ___?", "a": "jualan"},
        {"q": "Daftar hak cipta terpelihara tiru ciplak logo panggil cap ___?", "a": "paten"},
        {"q": "Kemahiran otak meniaga berniaga pasaran saham wang asah bakat ___?", "a": "usahawan"},
        {"q": "Niat niaga lurus jujur adil timbangan dacing sikap jujur ___?", "a": "amanah"},
        {"q": "Pertuturan suara vokal jelas pidato depan orang asah sifat ___?", "a": "keyakinan"},
        {"q": "Beg balut ganti beg plastik buang alam sekitar tanpa ___?", "a": "plastik"},
        {"q": "Agih untung saksama dengan semua kawan ahli kongsi dalam ___?", "a": "kumpulan"},
        {"q": "Langkah ujian jatuh produk tengok struktur jatuh kuat tidak ___?", "a": "pecah"},
        {"q": "Ilmu kemahiran wang kaya niaga duit jana wang ekonomi ___?", "a": "depan"},
        {"q": "Acara bertanding cipta robot pintar dewan tunjuk luar daya ___?", "a": "bakat"},
        {"q": "Komen kritik tegur kelemahan pensyarah cikgu guna ulasan idea ___?", "a": "baik"},
        {"q": "Tugasan lengkap siap hujung hantar sekolah lulus subjek akhir ___?", "a": "rbt"},
        {"q": "Kaji kaji isu kesan masalah orang jadikan titik penyelesaian ___?", "a": "baru"},
        {"q": "Sopan tutur rapi layan soal pelanggan ikhlas riang ukir ___?", "a": "senyum"},
        {"q": "Puas senyum tawan rasa jaya tengok hasil berkat hasil ___?", "a": "gigih"}
    ]
};
